### PR TITLE
Enhance Model Wizards: Finalize Generation, Finish Steps & Inline Notifications

### LINKED ISSUE #13974: [UI] Create Model, Import Model: Remember user input form post-submission
### Current Behavior
Users click the final submit button on the Create Model and the Import Model wizards.

1. Users are not shown any confirmation of the operation in progress. It's not until moments later, when the server responds, that users are aware that their request is even being processed.

2. If their Create or Import Model request fails. Users have to start from scratch, filling in the complete set of forms in the wizard again. 

### Desired Behavior
1. Show the user notification that their request is being processed.
2. Input remembered post-submission of a multi-step form of the Create Model and the Import Model wizards.

### Implementation

Given that this state is only useful for the form and that we don’t have a large child hierarchy, simply using React State is the Ideal approach to store form data as the user progresses through the steps.

React State makes it simple to go back and forward with steps while retaining the data. Lift the state to the parent  and then pass  it into the steps components directly. 

```

ModelImportFlowComponent ( holds the state and setters )
        <Step 1 data={formData} />
         <Step 2  data = {formData} />
```

### Acceptance Tests
1. Users can revisit the form post-submission and have all of their text and file-based input remembered as input values.
2. Users can also choose to Reset the multi-step form.
3. This behavior is available for both the Create Model and Import Model forms.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by FaheemOnHub**
**This PR introduces  and fixes #13974**
- Added two new steps: "Finalize Generation" & "Finish" to the Create Model wizard.
- Added a Notification step in the Import Model wizard, which displays success or error notifications inside the modal.

**Images**
Screenshot 2025-03-22 at 12 29 25 AM
Screenshot 2025-03-22 at 10 41 02 PM
Screenshot 2025-03-22 at 10 41 08 PM
Screenshot 2025-03-22 at 11 10 10 PM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Two failing tests here.... related?

File: ui/components/MeshModelRegistry/Stepper/UrlStepper.js [hunk 1]
```diff
@@ -520,6 +653,140 @@ const UrlStepper = React.memo(({ handleGenerateModal, handleClose }) => {
...
+                Model Generation
+              </a>
+              .
+            </p>
+          </>
+        ),
+      },
+      {
+        component: (
+          <FinishDeploymentStep perform_deployment={handleFinish} deployment_type="register" />
```
Comment (amitamrutiya) [inline ui/components/MeshModelRegistry/Stepper/UrlStepper.js:785]: use camelCase naming

File: ui/components/MeshModelRegistry/Stepper/UrlStepper.js [hunk 2]
```diff
@@ -545,9 +812,21 @@ const UrlStepper = React.memo(({ handleGenerateModal, handleClose }) => {
       nextAction: () => urlStepper.handleNext(),
     },
     4: {
+      canGoNext: () => true,
+      nextButtonText: 'Next',
+      nextAction: () => {
+        urlStepper.handleNext();
+      },
```
Comment (amitamrutiya) [inline ui/components/MeshModelRegistry/Stepper/UrlStepper.js:819]: use arrow function

**Review by amitamrutiya — CHANGES_REQUESTED** [review]

**Comment by amitamrutiya** [comment]
in dark mode background color is weird use same that are present for the stepper background.  In the final generation still I feel you added lot of spaces(look at in light mode). please reduce little bit if you can.

**Comment by FaheemOnHub** [comment]
@amitamrutiya its ready!!

**Comment by amitamrutiya** [comment]
@FaheemOnHub small conflicts.

**Comment by amitamrutiya** [comment]
@FaheemOnHub small conflicts.

File: ui/components/MeshModelRegistry/MeshModelComponent.js [hunk 3]
```diff
@@ -648,34 +665,96 @@ const ImportModal = React.memo((props) => {
...
+  const [isDeploying, setIsDeploying] = useState(false);
+  const [deployEvent, setDeployEvent] = useState();
+
+  useEffect(() => {
+    try {
+      setIsDeploying(true);
+    } catch (error) {
+      setIsDeploying(false);
+    }
+  }, []);
```
Comment (amitamrutiya) [inline ui/components/MeshModelRegistry/MeshModelComponent.js:712]: I don't get it why we need this useEffect

File: ui/components/MeshModelRegistry/Stepper/UrlStepper.js [hunk 4]
```diff
@@ -111,28 +120,117 @@ const UrlStepper = React.memo(({ handleGenerateModal, handleClose }) => {
...
-        isAnnotation: isAnnotation,
-        publishToRegistry: true,
-      },
-    });
+  const FinishDeploymentStep = ({ performDeployment, deploymentType }) => {
+    const { operationsCenterActorRef } = useContext(NotificationCenterContext);
+    const [isDeploying, setIsDeploying] = useState(false);
+    const [deployEvent, setDeployEvent] = useState();
+    const [deployError, setDeployError] = useState(null);
+    // const router = useRouter();
```
Comment (amitamrutiya) [inline ui/components/MeshModelRegistry/Stepper/UrlStepper.js:128]:
```suggestion
    // const router = useRouter();
```

File: ui/components/MeshModelRegistry/Stepper/style.js [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+  backgroundColor: theme.palette.background.blur?.heavy || '#f8f9fa',
+  padding: '1rem',
+  borderRadius: '8px',
+  marginBottom: '1rem',
+}));
+
+export const StyledSummaryItem = styled(Box)(({ theme }) => ({
+  borderRadius: '0.5rem',
+  padding: '0.7rem',
+  backgroundColor: theme.palette.background.paper || '#ffffff',
```
Comment (amitamrutiya) [inline ui/components/MeshModelRegistry/Stepper/style.js:12]: sistent color and why we need fallback color

File: ui/components/MeshModelRegistry/Stepper/style.js [hunk 6]
```diff
@@ -0,0 +1,30 @@
+import { styled, Box, Typography } from '@layer5/sistent';
+export const StyledSummaryBox = styled(Box)(({ theme }) => ({
+  backgroundColor: theme.palette.background.blur?.heavy || '#f8f9fa',
```
Comment (amitamrutiya) [inline ui/components/MeshModelRegistry/Stepper/style.js:3]: sistent color and why we need fallback color

**Review by amitamrutiya — CHANGES_REQUESTED** [review]

File: ui/components/MeshModelRegistry/Stepper/style.js (hunk 5 above)
Comment (amitamrutiya) [inline ui/components/MeshModelRegistry/Stepper/style.js:12]:
```suggestion
  backgroundColor: theme.palette.background.hover,
```

File: ui/components/MeshModelRegistry/Stepper/style.js (hunk 6 above)
Comment (amitamrutiya) [inline ui/components/MeshModelRegistry/Stepper/style.js:3]:
```suggestion
  backgroundColor: theme.palette.background.blur?.heavy,
```
