### PR TITLE
proper error logs and event w/singoff

### LINKED ISSUE #11352: [UI] Settings --> Registry: Model Import and Model Export
Related to https://github.com/meshery/meshery/issues/9775

### Current Behavior
Meshery supports importing and exporting of individual models into an out of the registry in a few different formats, however, this functionality is only exposed in `mesheryctl model`, currently.

### Desired Behavior
The ability to import and export models using Meshery UI **- using the OCI format only.**

### Implementation
1. Add Import button in Settings --> Registry page to upload a model in OCI format.
1. Add Export button in Settings --> Registry page to export a model in OCI format.
---
Bonus:
3. Bulk export of more than one model at a time.

### Acceptance Tests
1. User can click "Import" to open a file browser and upload a model in OCI format to Meshery Server, which upon import, validates all of the models contained entities, registers valid entities, notifies the user with a toasted event  and one filed in the Notification Center that includes a summary of the number of entities successfully imported or details as to why the import failed and what to do about it (with MeshKit error reference)
2. User can select (checkmark) a single model name (that might contain one or more versions of the model). Click Export and have an OCI-formatted model file pushed to their client (web browser).

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Jougan-0**
**Notes for Reviewers**

This PR fixes #11352
Support for models and UI event whenever handler logs.
Needs minor updates Do not merge.
Meshkit PR [#589](https://github.com/meshery/meshkit/pull/589)
Meshery Schemas PR [#174
](https://github.com/meshery/schemas/pull/174)

- [x] UI for import URL
- [x] Export needs a revisits slightly (very slightly) in approach.
Future implementation Separate PR
- [x] Case when user imports models that are already generated. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/internal/cli/root/model/import.go [hunk 1]
```diff
@@ -84,6 +84,7 @@ var importModelCmd = &cobra.Command{
 				}
 				err = sendToAPI(fileData, path, "file")
 				if err != nil {
+					utils.Log.Info("Error while sending file to API")
```
Comment (leecalcote) [inline mesheryctl/internal/cli/root/model/import.go:87]: to "Meshery Server", yeah? 

Or "Meshery Server API" or even better "Meshery Server API at https:///.........."

File: server/handlers/component_handler.go [hunk 2]
```diff
@@ -1387,11 +1387,24 @@ func prettifyCompDefSchema(entities []entity.Entity) []v1beta1.ComponentDefiniti
...
+	eventBuilder := events.NewEvent().ActedUpon(userID).FromUser(userID).FromSystem(*h.SystemID).WithAction("register")
+	infoeventBuilder := events.NewEvent().ActedUpon(userID).FromUser(userID).FromSystem(*h.SystemID).WithAction("register")
+
+	var message strings.Builder
 	dirPath := r.FormValue("dir")
 	if dirPath != "" {
 		tempFile, err := os.CreateTemp("", "upload-*.tar.gz")
 		if err != nil {
 			err = meshkitutils.ErrCreateFile(err, "/tmp/upload-*.tar.gz")
+			eventBuilder.WithSeverity(events.Error).WithDescription("Failed to create temp Directory ").WithMetadata(map[string]interface{}{
```
Comment (leecalcote) [inline server/handlers/component_handler.go:1402]: Why is "Directory" capitalized?

File: server/handlers/component_handler.go [hunk 3]
```diff
@@ -1432,47 +1481,75 @@ func (h *Handler) RegisterMeshmodels(rw http.ResponseWriter, r *http.Request, _
 	fileContent, err := io.ReadAll(file)
 	if err != nil {
 		err = meshkitutils.ErrReadFile(err, string(fileContent))
+		eventBuilder.WithSeverity(events.Error).WithDescription("Failed to read the file data ").WithMetadata(map[string]interface{}{
```
Comment (leecalcote) [inline server/handlers/component_handler.go:1484]: which file? name or URI?

File: server/handlers/component_handler.go [hunk 4]
```diff
@@ -1432,47 +1481,75 @@ func (h *Handler) RegisterMeshmodels(rw http.ResponseWriter, r *http.Request, _
...
+		_event := eventBuilder.Build()
+		_ = provider.PersistEvent(_event)
+		go h.config.EventBroadcaster.Publish(userID, _event)
 		http.Error(rw, err.Error(), http.StatusInternalServerError)
 		return
 	}
 
 	entityType, err := meshkitutils.FindEntityType(fileContent)
 	if err != nil {
+		eventBuilder.WithSeverity(events.Error).WithDescription("Failed to validate schemaversion").WithMetadata(map[string]interface{}{
```
Comment (leecalcote) [inline server/handlers/component_handler.go:1496]: schemaVersion

or 

schema version

File: server/handlers/component_handler.go [hunk 5]
```diff
@@ -1432,47 +1481,75 @@ func (h *Handler) RegisterMeshmodels(rw http.ResponseWriter, r *http.Request, _
...
+		_ = provider.PersistEvent(_event)
+		go h.config.EventBroadcaster.Publish(userID, _event)
 		h.log.Error(err)
 		http.Error(rw, err.Error(), http.StatusInternalServerError)
 		return
 	}
 
 	err = RegisterEntity(fileContent, entityType, h)
 	if err != nil {
+		eventBuilder.WithSeverity(events.Error).WithDescription("Failed to register the entity").WithMetadata(map[string]interface{}{
```
Comment (leecalcote) [inline server/handlers/component_handler.go:1523]: which entity in which model?

**Review by leecalcote — CHANGES_REQUESTED** [review]

File: server/handlers/component_handler.go [hunk 6]
```diff
@@ -1401,29 +1414,65 @@ func (h *Handler) RegisterMeshmodels(rw http.ResponseWriter, r *http.Request, _
...
 		}
-		rw.WriteHeader(http.StatusOK)
-		_, _ = rw.Write([]byte(message.String()))
 		return
 	}
 
 	file, _, err := r.FormFile("file")
 	if err != nil {
 		err = ErrRetrieveData(err)
+		eventBuilder.WithSeverity(events.Error).WithDescription("Failed to retrieve data ").WithMetadata(map[string]interface{}{
```
Comment (leecalcote) [inline server/handlers/component_handler.go:1469]: what data?

File: server/handlers/component_handler.go [hunk 7]
```diff
@@ -1401,29 +1414,65 @@ func (h *Handler) RegisterMeshmodels(rw http.ResponseWriter, r *http.Request, _
...
+			_event := eventBuilder.Build()
+			errMsg = msg
+			_ = provider.PersistEvent(_event)
+			go h.config.EventBroadcaster.Publish(userID, _event)
+		}
+
+		message = writeMessageString(compCount, relCount)
 		if message.Len() > 0 {
 			h.log.Info(message.String())
+			infoeventBuilder.WithSeverity(events.Informational).WithDescription("Succesfully Registered Model(s)").WithMetadata(map[string]interface{}{
```
Comment (leecalcote) [inline server/handlers/component_handler.go:1453]: Don't say "successfully".

File: server/handlers/component_handler.go [hunk 8]
```diff
@@ -1432,47 +1481,75 @@ func (h *Handler) RegisterMeshmodels(rw http.ResponseWriter, r *http.Request, _
...
+		go h.config.EventBroadcaster.Publish(userID, _event)
 		h.log.Error(err)
 		http.Error(rw, err.Error(), http.StatusInternalServerError)
 		return
 	}
 	if entityType == "" {
+
 		err = meshkitutils.ErrInvalidSchemaVersion
+
+		eventBuilder.WithSeverity(events.Error).WithDescription("Failed to validate schemaversion").WithMetadata(map[string]interface{}{
```
Comment (leecalcote) [inline server/handlers/component_handler.go:1510]: same as above

File: mesheryctl/internal/cli/root/model/import.go [hunk 9]
```diff
@@ -96,6 +97,7 @@ var importModelCmd = &cobra.Command{
 				}
 				err = sendToAPI(fileData, path, "dir")
 				if err != nil {
+					utils.Log.Info("Error while sending file to API")
```
Comment (leecalcote) [inline mesheryctl/internal/cli/root/model/import.go:100]: same as above

File: server/handlers/component_handler.go [hunk 10]
```diff
@@ -1401,29 +1414,65 @@ func (h *Handler) RegisterMeshmodels(rw http.ResponseWriter, r *http.Request, _
...
 		if err != nil {
 			h.log.Error(err)
-			http.Error(rw, err.Error(), http.StatusBadRequest)
-			return
 		}
-		message := writeMessageString(compCount, relCount)
+		if totalErrCount > 0 {
+			msg := fmt.Sprintf("Failed to register a total of %d entities:", totalErrCount)
+			if errCompCount > 0 && errRelCount > 0 {
+				msg = fmt.Sprintf("%s %d Components and %d Relationships", msg, errCompCount, errRelCount)
```
Comment (leecalcote) [inline server/handlers/component_handler.go:1435]: Across how many models? This is a nice-to-know, but shouldn't hold up this PR.

File: server/handlers/component_handler.go [hunk 11]
```diff
@@ -1432,47 +1481,75 @@ func (h *Handler) RegisterMeshmodels(rw http.ResponseWriter, r *http.Request, _
...
 		return
 	}
-	message := ""
+
 	if entityType == entity.ComponentDefinition {
-		message = "Successfully registered Component"
+		message.WriteString("Successfully registered Component")
 	} else {
-		message = "Successfully registered Relationship"
+		message.WriteString("Successfully registered Relationship")
```
Comment (leecalcote) [inline server/handlers/component_handler.go:1537]: Which relationship? Remove "successfully".

File: server/handlers/component_handler.go [hunk 12]
```diff
@@ -1432,47 +1481,75 @@ func (h *Handler) RegisterMeshmodels(rw http.ResponseWriter, r *http.Request, _
...
+		go h.config.EventBroadcaster.Publish(userID, _event)
 		h.log.Error(err)
 		http.Error(rw, err.Error(), http.StatusInternalServerError)
 		return
 	}
-	message := ""
+
 	if entityType == entity.ComponentDefinition {
-		message = "Successfully registered Component"
+		message.WriteString("Successfully registered Component")
```
Comment (leecalcote) [inline server/handlers/component_handler.go:1535]: Which component? Remove "successfully".

File: server/handlers/component_handler.go [hunk 13]
```diff
@@ -1481,7 +1558,7 @@ func writeMessageString(compCount int, relCount int) strings.Builder {
 	}
 	return message
 }
-func processUploadedFile(filePath string, h *Handler, compCount *int, relCount *int) error {
+func processUploadedFile(filePath string, h *Handler, compCount *int, relCount *int, errCompCount *int, errRelCount *int, totalErrCount *int) error {
```
Comment (leecalcote) [inline server/handlers/component_handler.go:1561]: no model count?

File: server/handlers/component_handler.go [hunk 14]
```diff
@@ -1554,6 +1640,11 @@ func RegisterEntity(content []byte, entityType entity.EntityType, h *Handler) er
 		helpers.HandleError(v1beta1.Host{
 			Hostname: r.Model.Registrant.Hostname,
 		}, &r, err, isModelError, isRegistrantError)
+		return err
+	case entity.Model:
+		//handler oci return here
+		return nil
+	case entity.PolicyDefinition:
```
Comment (leecalcote) [inline server/handlers/component_handler.go:1647]: Is this a placeholder for future support? Add a comment indicating this, if so.

If not, it's out of place and not something that we currently have and should be removed or replaced with Relationship, if that is what is meant.

**Review by leecalcote — CHANGES_REQUESTED** [review]

**Comment by Ashparshp** [comment]
@Jougan-0 Could we discuss this issue during the Meshery dev meeting call? Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

File: ui/components/NotificationCenter/metadata.js [hunk 15]
```diff
@@ -42,6 +57,57 @@ const TitleLink = ({ href, children, ...props }) => {
...
+    <Typography variant="body1">
+      {Kind} {Subtype} {Model.displayName}
+    </Typography>
+  );
+};
+
+const ModelDetail = ({ model }) => {
+  const { Subtype } = model;
+  if (Subtype !== undefined) {
+    console.log(Subtype);
```
Comment (leecalcote) [inline ui/components/NotificationCenter/metadata.js:106]: Remove...?

File: server/models/meshery_meshmodels_api_response.go [hunk 16]
```diff
@@ -44,6 +44,27 @@ type MeshmodelRelationshipsAPIResponse struct {
 	Count         int64           `json:"total_count"`
 	Relationships []entity.Entity `json:"relationships"`
 }
+type EntityCount struct {
```
Comment (leecalcote) [inline server/models/meshery_meshmodels_api_response.go:47]: Created from which schema?

File: server/handlers/componetgenratorhelper.go [hunk 17]
```diff
@@ -0,0 +1,391 @@
...
+		WithMetadata(metadata).
+		Build()
+	_ = provider.PersistEvent(event)
+	go h.config.EventBroadcaster.Publish(userID, event)
+}
+
+func RegisterEntity(content []byte, entityType entity.EntityType, h *Handler, response *models.RegisterMeshmodelAPIResponse, mu *sync.Mutex) (string, error) {
+	switch entityType {
+	case entity.ComponentDefinition:
+		var c v1beta1.ComponentDefinition
```
Comment (leecalcote) [inline server/handlers/componetgenratorhelper.go:281]: v1beta1 ✅

File: ui/components/NotificationCenter/metadata.js (hunk 15 above)
Comment (Jougan-0) [reply ui/components/NotificationCenter/metadata.js:106]: Yes.

File: server/handlers/componetgenratorhelper.go [hunk 18]
```diff
@@ -0,0 +1,391 @@
...
+
+func (h *Handler) sendErrorEvent(userID uuid.UUID, provider models.Provider, description string, err error) {
+	event := events.NewEvent().ActedUpon(userID).FromUser(userID).FromSystem(*h.SystemID).WithAction("register").WithSeverity(events.Error).WithDescription(description).WithMetadata(map[string]interface{}{
+		"error": err,
+	}).Build()
+	_ = provider.PersistEvent(event)
+	go h.config.EventBroadcaster.Publish(userID, event)
+}
+
+func ModelNames(response *models.RegisterMeshmodelAPIResponse) string {
```
Comment (leecalcote) [inline server/handlers/componetgenratorhelper.go:238]: Please move away from "meshmodel" and use "registry" instead.

File: server/handlers/componetgenratorhelper.go [hunk 19]
```diff
@@ -0,0 +1,391 @@
...
+				"Model":   r.Model,
+				"Kind":    r.Kind,
+				"Subtype": r.SubType,
+				// "RelationshipType": r.RelationshipType, //future when we support type
+			}
+			response.EntityTypeSummary.SuccessfulRelationships = append(response.EntityTypeSummary.SuccessfulRelationships, entry)
+			response.ModelName = append(response.ModelName, r.Model.DisplayName)
+		}
+	case entity.Model:
+		var m v1beta1.Model
```
Comment (leecalcote) [inline server/handlers/componetgenratorhelper.go:172]: v1beta1 ✅

File: mesheryctl/internal/cli/root/model/import.go [hunk 20]
```diff
@@ -208,9 +171,138 @@ func sendToAPI(data []byte, name string, dataType string) error {
...
+	}
+	return b
+}
+
+func centerText(text string, width int) string {
+	if len(text) >= width {
+		return text
+	}
+	padding := (width - len(text)) / 2
+	return fmt.Sprintf("%*s%*s", padding+len(text), text, width-len(text)-padding, "")
```
Comment (leecalcote) [inline mesheryctl/internal/cli/root/model/import.go:307]: Why is CSS not used here?

**Comment by leecalcote** [comment]
@Jougan-0 revisit, please. Address each unresolved comment.

File: mesheryctl/internal/cli/root/model/import.go [hunk 21]
```diff
@@ -208,9 +201,271 @@ func sendToAPI(data []byte, name string, dataType string) error {
...
+	if len(response.ModelName) != 0 && response.EntityCount.CompCount == 0 && response.EntityCount.RelCount == 0 {
+		if response.EntityCount.TotalErrCount == 0 {
+			return false
+		}
+	}
+	return true
+}
+
+// TO check the case if we were never able to read the file at first palce
+func hasExtension(name string) bool {
```
Comment (humblenginr) [inline mesheryctl/internal/cli/root/model/import.go:232]: Let's avoid using file extensions. They are fragile. We can sequentially try to parse them and figure out if they are of any valid format.

Comment (Jougan-0) [reply mesheryctl/internal/cli/root/model/import.go:232]: Those are the scenarios where the file is corrupted and then we check for the extension. It is when the whole file had an issue and in that case the data returned is the filename as model so yes that is why we are doing this.

**Review by humblenginr — APPROVED** [review]
TODO: Make use of the centralised logic in meshkit for registration of entities (also update if required).

File: server/handlers/component_handler.go [hunk 22]
```diff
@@ -1191,147 +1195,215 @@ func prettifyCompDefSchema(entities []entity.Entity) []component.ComponentDefini
...
+	}
+	// 3. Send response
+	byt, _ := os.ReadFile(tarfileName)
+	rw.Header().Add("Content-Type", "application/x-tar")
+	rw.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"%s.tar\"", model.Name))
+	rw.Header().Set("Content-Length", fmt.Sprintf("%d", len(byt))) // Correctly format the Content-Length header
+	_, err = rw.Write(byt)
 	if err != nil {
-		return err
+		h.log.Error(ErrGetMeshModels(err)) // TODO: Add appropriate meshkit error
```
Comment (leecalcote) [inline server/handlers/component_handler.go:1404]:
```suggestion
		h.log.Error(ErrGetMeshModels(err)) 
```

**Review by leecalcote — APPROVED** [review]

File: server/handlers/componetgenratorhelper.go [hunk 23]
```diff
@@ -0,0 +1,647 @@
...
+		return nil, ErrCreateFile(err, "/tmp/upload-*.tar.gz")
+	}
+
+	if _, err = tempFile.Write([]byte(dirPath)); err != nil {
+		return nil, meshkitutils.ErrWriteFile(err, tempFile.Name())
+	}
+	return tempFile, nil
+}
+
+func processUploadedFile(filePath string, tempDir string, h *Handler, response *models.RegistryAPIResponse, provider models.Provider, checkOCI bool) error {
```
Comment (MUzairS15) [inline server/handlers/componetgenratorhelper.go:63]: Why is this being re-defined?
Try to use the `meshkit` functionality. There's already a logic for importing models when packaged as a directory.

File: server/handlers/componetgenratorhelper.go [hunk 24]
```diff
@@ -0,0 +1,647 @@
...
+		} else {
+			if path != "" {
+				incrementCountersOnSuccess(mu, entityType, &response.EntityCount.CompCount, &response.EntityCount.RelCount, &response.EntityCount.ModelCount)
+				addSuccessfulEntry(content, entityType, response)
+			}
+
+		}
+	}
+}
+func addSuccessfulEntry(content []byte, entityType entity.EntityType, response *models.RegistryAPIResponse) {
```
Comment (MUzairS15) [inline server/handlers/componetgenratorhelper.go:150]: Similar logic for logging and eventing for registration is present, let's try to use that.

File: server/handlers/componetgenratorhelper.go [hunk 25]
```diff
@@ -0,0 +1,647 @@
...
+	isDisplayNamePresent := func(displayName string) bool {
+		for _, name := range response.ModelName {
+			if name == displayName {
+				return true
+			}
+		}
+		return false
+	}
+
+	switch entityType {
```
Comment (MUzairS15) [inline server/handlers/componetgenratorhelper.go:161]: @Jougan-0 Recently, an `encoding` package was added in Meshkit, to have consistent error handling (returning Meshkit error) and the same logic for marshalling/unmarshalling and also supporting yaml and json data.

The existing Umarshal in Meshkit is deprecated, wherever we use utils.UnMarshal and Marshal we need to replace with encoding package.

File: server/helpers/utils/utils.go [hunk 26]
```diff
@@ -419,10 +421,81 @@ func FormatToTitleCase(s string) string {
...
 func ExtractFile(filePath string, destDir string) error {
+
 	if utils.IsTarGz(filePath) {
 		return utils.ExtractTarGz(destDir, filePath)
 	} else if utils.IsZip(filePath) {
 		return utils.ExtractZip(destDir, filePath)
 	}
 	return utils.ErrExtractType
 }
+func ConvertToJSONCompatible(data interface{}) interface{} {
```
Comment (MUzairS15) [inline server/helpers/utils/utils.go:432]: @Jougan-0 **In this same file look a few lines above, you will find a function which is meant to do the same thing.**

Before adding logic, check if it already exists.

**Review by MUzairS15 — CHANGES_REQUESTED** [review]
@Jougan-0 Look at the lint check deprecation warnings, please don't ignore these.

https://github.com/meshery/meshery/pull/11354#discussion_r1724443218

File: mesheryctl/internal/cli/root/model/export.go [hunk 27]
```diff
@@ -21,26 +22,6 @@ mesheryctl model export [model-name] -o [oci/json/yaml] (default is oci)
 mesheryctl model export [model-name] -l /home/meshery/
 mesheryctl model export [model-name] --discard-components --discard-relationships
     `,
-	PreRunE: func(cmd *cobra.Command, args []string) error {
```
[the remark this answers is not in the document]
Comment (MUzairS15) [reply mesheryctl/internal/cli/root/model/export.go:24]: I see the PreRun exist for the model (parent) command.

[the remark this answers is not in the document]
Comment (MUzairS15) [reply mesheryctl/internal/cli/root/model/export.go:24]: I see the PreRun exist for the model (parent) command.

File: server/handlers/component_handler.go [hunk 28]
```diff
@@ -1191,147 +1195,215 @@ func prettifyCompDefSchema(entities []entity.Entity) []component.ComponentDefini
...
+		UploadType string `json:"uploadType"`
+	}
+
+	err := json.NewDecoder(r.Body).Decode(&importRequest)
+	if err != nil {
+		h.log.Info("Error in unmarshalling request body")
+		http.Error(rw, "Invalid request format", http.StatusBadRequest)
+		return
+	}
+	base64Data, err := json.Marshal(importRequest.ImportBody.ModelFile)
```
[the remark this answers is not in the document]
Comment (Jougan-0) [reply server/handlers/component_handler.go:1223]: Yes

File: server/handlers/componetgenratorhelper.go (hunk 24 above)
Comment (Jougan-0) [reply server/handlers/componetgenratorhelper.go:150]: No this is different.

File: ui/components/MeshModelRegistry/MeshModelComponent.js [hunk 29]
```diff
@@ -367,10 +436,33 @@ const MeshModelComponent_ = ({
   useEffect(() => {
     fetchData();
   }, [view, page, rowsPerPage, checked, searchText, modelFilters, registrantFilters]);
+  useEffect(() => {
+    const fetchData = async () => {
+      try {
+        const response = await fetch('/api/schema/resource/model', {
```
Comment (MUzairS15) [inline ui/components/MeshModelRegistry/MeshModelComponent.js:442]: Please don't use fetch API.
We are trying to move away from fetch API and use rtk query. // @captain-Akshay May be you can help @Jougan-0 here.

File: ui/components/MeshModelRegistry/MeshModelComponent.js [hunk 30]
```diff
@@ -367,10 +436,33 @@ const MeshModelComponent_ = ({
...
+          method: 'GET',
+          credentials: 'include',
+        });
+        const result = await response.json();
+        setImportSchema(result);
+      } catch (error) {
+        console.error('Error fetching data:', error);
```
Comment (MUzairS15) [inline ui/components/MeshModelRegistry/MeshModelComponent.js:449]: Notify the user in the form of event/snackbar as well.

File: ui/components/MeshModelRegistry/MeshModelComponent.js [hunk 31]
```diff
@@ -451,24 +543,48 @@ const MeshModelComponent_ = ({
     </div>
   );
 };
+const ImportModal = React.memo((props) => {
+  const { importFormSchema, handleClose, handleImportModel } = props;
+
+  return (
+    <>
```
Comment (MUzairS15) [inline ui/components/MeshModelRegistry/MeshModelComponent.js:550]:
```suggestion
```

File: ui/components/MeshModelRegistry/MeshModelComponent.js [hunk 32]
```diff
@@ -451,24 +543,48 @@ const MeshModelComponent_ = ({
...
+          <RJSFModalWrapper
+            schema={importFormSchema.rjsfSchema}
+            uiSchema={importFormSchema.uiSchema}
+            handleSubmit={handleImportModel}
+            submitBtnText="Import"
+            handleClose={handleClose}
+          />
+        </SistentModal>
+      </UsesSistent>
+    </>
```
Comment (MUzairS15) [inline ui/components/MeshModelRegistry/MeshModelComponent.js:562]:
```suggestion
```

File: ui/components/MeshModelRegistry/MeshModelDetails.js [hunk 33]
```diff
@@ -152,15 +155,34 @@ const ModelContents = withSuppressedErrorBoundary(({ modelDef }) => {
     duplicates: modelDef?.duplicates?.toString(),
     relationships: getCompRelValue().relationships.toString(),
   };
-
+  const handleExport = () => {
+    const a = document.createElement('a');
```
Comment (MUzairS15) [inline ui/components/MeshModelRegistry/MeshModelDetails.js:159]: @Jougan-0 Instead UI can simply make a GET call, and the server is already responding with a Content-Disposition header, so no need to to this I believe.

File: ui/components/NotificationCenter/metadata.js [hunk 34]
```diff
@@ -42,6 +55,166 @@ const TitleLink = ({ href, children, ...props }) => {
...
+    <>
+      <Typography variant="body1">{message}</Typography>
+      <ErrorMetadataFormatter metadata={error.error} event={{}} />
+    </>
+  );
+};
+
+const imageCache = {};
+
+const checkImageExists = async (url) => {
```
Comment (MUzairS15) [inline ui/components/NotificationCenter/metadata.js:93]: @captain-Akshay Don't we have a logic already to check if the image link is valid otherwise fallback to default logo?

File: server/handlers/component_handler.go (hunk 28 above)
[the remark this answers is not in the document]
Comment (MUzairS15) [reply server/handlers/component_handler.go:1223]: The Unmarshal function decodes the base64 data by itself. Use the correct type if it is not happening.

File: ui/components/MeshModelRegistry/MeshModelComponent.js (hunk 29 above)
Comment (Jougan-0) [reply ui/components/MeshModelRegistry/MeshModelComponent.js:442]: This was used for pattern import I just copied the functions and updated it.

Comment (MUzairS15) [reply ui/components/MeshModelRegistry/MeshModelComponent.js:442]: I see, the migration to rtk isn't complete, but as we are defining/calling APIs let's try to no use fetch.

Comment (MUzairS15) [reply ui/components/MeshModelRegistry/MeshModelComponent.js:442]: @captain-Akshay

**Comment by Jougan-0** [comment]
https://github.com/meshery/meshkit/pull/589

File: mesheryctl/internal/cli/root/model/model.go [hunk 35]
```diff
@@ -276,35 +282,129 @@ func exportModel(modelName string, cmd *cobra.Command, url string, displayCountO
...
 		utils.Log.Error(err)
-		return err
+		return nil
 	}
 	if len(modelsResponse.Models) < 1 {
-		return ErrExportModel(fmt.Errorf("Model with the given name could not be found in the registry"), modelName)
+		return ErrExportModel(fmt.Errorf("model with the given name could not be found in the registry"), modelName)
 	}
 	model := modelsResponse.Models[0]
+	_ = model.ReplaceSVGData("../")
```
Comment (MUzairS15) [inline mesheryctl/internal/cli/root/model/model.go:298]: Will you add a comment explaining this?

Are we writing to "../" or reading files from "../"?

File: mesheryctl/internal/cli/root/model/model.go [hunk 36]
```diff
@@ -276,35 +282,129 @@ func exportModel(modelName string, cmd *cobra.Command, url string, displayCountO
...
+
+	var rels []relationship.RelationshipDefinition
+	var components []component.ComponentDefinition
+	if model.Components != nil {
+		slice, ok := model.Components.([]interface{})
+		if !ok {
+			err = meshkitutils.ErrUnmarshal(meshkitutils.ErrInvalidSchemaVersion)
```
Comment (MUzairS15) [inline mesheryctl/internal/cli/root/model/model.go:305]: Incorrect error used.

**Review by MUzairS15 — COMMENTED** [review]
@Jougan-0 I assume this is still in WIP, let us know when ready.

File: mesheryctl/internal/cli/root/model/model.go (hunk 35 above)
Comment (Jougan-0) [reply mesheryctl/internal/cli/root/model/model.go:298]: Sure.

File: mesheryctl/internal/cli/root/model/model.go (hunk 36 above)
Comment (Jougan-0) [reply mesheryctl/internal/cli/root/model/model.go:305]: Yes this is one my list captain.

**Comment by l5io** [comment]
🚀 Preview for commit 6c849b6d8097ce931c563c959efcb38f16cbb439 at: https://66ed7f82ca1d51807f6eab58--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ecde1c3965eb99609548514f5e1499ec33e98900 at: https://66ed886eb962d582618f8ad7--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6ab160cb39725b4c2f4a7addd9c31a39d8edce9e at: https://66ed8afe857b098efb02c2be--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit cc5ca37bbf4ea3a59733d951f2b91093fd55ca7d at: https://66ed8f63de4e9a04bdd7364a--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3f9a78f6a77565fe31f15d63997d9b12cbb983cc at: https://66ef02d23e2f9295db948e1f--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 76aa7a8737e907e9dac37b5cd00dc805f9290856 at: https://66ef04d99ba64ea1ec94659d--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a7a0dffb5c5d512eea2bf52f6916c542fea6af18 at: https://66ef07467b8506a2ebf1b62e--meshery-docs-preview.netlify.app
