### PR TITLE
[mesheryctl] Make `stop` wait for namespace to be deleted 

### LINKED ISSUE #4951: [mesheryctl] `system restart` colliding with helm delete operation
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Meshery CLI users that execute `mesheryctl system restart` while using in-cluster deployments find that `system restart` fails to start Meshery due to a helm uninstall operation ongoing (initiated by the `system stop` included in `system restart`).

#### Desired Behavior
Mesheryctl to wait for `stop` to complete, then proceed with `start`.

#### Screenshot
```
 mesheryctl system restart
Restarting Meshery...
Meshery deployments will be deleted from your cluster. Are you sure you want to continue [y/n]? y
Stopping Meshery...
Deleting Meshery Namespace...
Meshery is stopped.
Starting Meshery...
⡿ Deploying Meshery on Kubernetes Error: cannot start Meshery: create: failed to create: secrets "sh.helm.release.v1.meshery.v1" is forbidden: unable to create new content in namespace meshery because it is being terminated
Usage:
  mesheryctl system restart [flags]

Flags:
  -h, --help          help for restart
      --skip-update   (optional) skip checking for new Meshery's container images.

Global Flags:
      --config string    path to config file (default "/Users/lee/.meshery/config.yaml")
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.
```

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by gr455**
**Description**
With stop operation, mesheryctl now polls kubernetes client waiting for meshery namespace to be deleted (times out at 300s with a message). This also fixes `restart` operation conflicting with namespace delete operation.

This PR fixes #4951

**Notes for Reviewers**
To test the changes
1. Run `make` inside `mesheryctl/` directory to generate the binary
2. Run `./mesheryctl system start` from within `mesheryctl/` directory and let the deployment complete
3. Now run `./mesheryctl system stop` and wait for the cli to exit
4. Verify that `kubectl get namespace` does not show the meshery namespace
5. Run `./mesheryctl system restart` also to make sure the restart happens without any errors.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by gr455** [comment]
It was suggested in the last development meeting that we cancel the `restart` operation if the `stop` operation times out without the deployments stopping.

**Comment by gr455** [comment]
Hey @piyushsingariya @leecalcote, mind having a look at this? Thanks :D

File: mesheryctl/internal/cli/root/system/stop.go [hunk 1]
```diff
@@ -168,8 +168,17 @@ func stop() error {
...
-
-	log.Info("Meshery is stopped.")
+	// Wait for meshery to stop
+	done, err := mesheryStopCheck()
+	if err != nil {
+		log.Info(err)
+	}
+	// If stop is not done until timeout, display info
+	if !done {
+		log.Info("Meshery has not stopped yet.\nPlease check the status of the pods by executing “mesheryctl system status” and Meshery-UI endpoint with “mesheryctl system dashboard”.")
```
Comment (hexxdump) [inline mesheryctl/internal/cli/root/system/stop.go:178]: whats the use of checking the Meshery-UI endpoint in this stop workflow?
I feel, the below log would be sufficient:

"Meshery has not stopped yet.\nPlease check the status of the pods by executing “mesheryctl system status”".
Why I am not in favor of asking users to run "mesheryctl system dashboard" is - this command might fail as some resources might have got deleted already.
// @piyushsingariya

File: mesheryctl/pkg/utils/healthcheck.go [hunk 2]
```diff
@@ -251,3 +251,32 @@ func WaitForPodRunning(c *meshkitkube.Client, desiredPod, namespace string, time
 
 	return pollForPodRunning(c, namespace, desiredPodName, time.Duration(timeout)*time.Second)
 }
+
```
Comment (hexxdump) [inline mesheryctl/pkg/utils/healthcheck.go:254]: looks good

File: mesheryctl/internal/cli/root/system/stop.go (hunk 1 above)
Comment (gr455) [reply mesheryctl/internal/cli/root/system/stop.go:178]: Ah yes. I copied this message from the start workflow.

**Comment by gr455** [comment]
> It was suggested in the last development meeting that we cancel the `restart` operation if the `stop` operation times out without the deployments stopping.

@piyushsingariya @hexxdump. I would love to know your thoughts on this

**Review by piyushsingariya — COMMENTED** [review]
I like this strategy but I'm not sure if this is a solid one.
waiting for the namespace to get deleted isn't a good option, rn in `restart` we are deleting namespace and we create it again, although that should not be the case, `restart` should only delete resources and restart the resources.

I would like you to push in a direction where we could poll till the resources are deleted.

**Comment by gr455** [comment]
> I like this strategy but I'm not sure if this is a solid one. waiting for the namespace to get deleted isn't a good option, rn in `restart` we are deleting namespace and we create it again, although that should not be the case, `restart` should only delete resources and restart the resources.
> 
> I would like you to push in a direction where we could poll till the resources are deleted.

This could use the `AreMesheryComponentsRunning` from https://github.com/meshery/meshery/commit/8b8d110283743ccd8b025ae5f51c50c2cddfbc02 right?

**Comment by piyushsingariya** [comment]
@gr455 I think that would work here better!

**Comment by gr455** [comment]
> @gr455 I think that would work here better!

Unfortunately, this does not work because AreMesheryComponentsRunning only checks if the deployments are deleted. When deployments are deleted, the pods might still exist in `terminating` state. So this still fails.

**Comment by piyushsingariya** [comment]
> > @gr455 I think that would work here better!
> 
> Unfortunately, this does not work because AreMesheryComponentsRunning only checks if the deployments are deleted. When deployments are deleted, the pods might still exist in `terminating` state. So this still fails.

Ohh I see, can you check the `--force` flag in the `stop` command, I think you can come up with a function that would be `WaitForMesheryResourceDeleted` which would be a better and best option for doing this.

**Comment by gr455** [comment]
Sorry for bugging you @piyushsingariya, can you give me an idea of what all resources to poll for. Should it be the same as those that are deleted in the `ForceCleanupCluster` function? If so then I am confused why we are deleting replicaSets explicitly, aren't replicasets a part of deployments?

**Comment by piyushsingariya** [comment]
> Sorry for bugging you @piyushsingariya, can you give me an idea of what all resources to poll for. Should it be the same as those that are deleted in the `ForceCleanupCluster` function? If so then I am confused why we are deleting replicaSets explicitly, aren't replicasets a part of deployments?

Yeah, deployment is a higher-level concept that manages replicaSets, I was in flow while writing that code, I forgot and added that piece of code, deleting deployments would delete replicaSets because of the delete policy. You can remove that particular part of code(do test it though).

In an ideal world, we should poll for all kinds of resources Meshery uses in clusters.

**Comment by navendu-pottekkat** [comment]
@gr455 Quick question: Does this handle `system restart` failing to start Meshery as it is being stopped?

**Comment by gr455** [comment]
> @gr455 Quick question: Does this handle `system restart` failing to start Meshery as it is being stopped?

Yes this should handle that. I'm actually changing this PR a bit to poll for components instead of the namespace, but either way it should handle that

**Comment by gr455** [comment]
Seems like another linting problem which was not caught locally :(.
Anyway, this time we poll resources and if namespace is set to be deleted, then we poll namespace too (without this, the restart error persists)

File: mesheryctl/pkg/utils/healthcheck.go [hunk 3]
```diff
@@ -290,3 +290,138 @@ func WaitForPodRunning(c *meshkitkube.Client, desiredPod, namespace string, time
...
+				services, err := c.KubeClient.CoreV1().Services(namespace).List(context.TODO(), metav1.ListOptions{})
+				if err != nil {
+					return false, err
+				}
+				return len(services.Items) == 0, nil
+			}
+		}
+
+		return true, nil
+	}
```
Comment (piyushsingariya) [inline mesheryctl/pkg/utils/healthcheck.go:355]: Let's not do this with switch case and do it for all resources in one-go.

also not pods/replicasets exactly we should be checking for higher level concepts such as deployments/services/roles.

File: mesheryctl/pkg/utils/healthcheck.go [hunk 4]
```diff
@@ -290,3 +290,138 @@ func WaitForPodRunning(c *meshkitkube.Client, desiredPod, namespace string, time
...
+	err = wait.PollImmediate(time.Second, timeout, areMesheryComponentsDeleted(c, namespace, "statefulset"))
+	if err != nil {
+		return err
+	}
+	// Wait for services to delete
+	err = wait.PollImmediate(time.Second, timeout, areMesheryComponentsDeleted(c, namespace, "service"))
+	if err != nil {
+		return err
+	}
+
```
Comment (piyushsingariya) [inline mesheryctl/pkg/utils/healthcheck.go:409]: We shouldn't run multiple poll methods like this, it's bad practice.

**Review by piyushsingariya — CHANGES_REQUESTED** [review]

File: mesheryctl/pkg/utils/healthcheck.go (hunk 3 above)
Comment (gr455) [reply mesheryctl/pkg/utils/healthcheck.go:355]: The problem is, even when the deployment is deleted, the pods are still in terminating state and are not actually yet deleted. So if we are waiting for the resources to be deleted, then we might not want to return before everything is actually deleted

File: mesheryctl/pkg/utils/healthcheck.go (hunk 4 above)
Comment (gr455) [reply mesheryctl/pkg/utils/healthcheck.go:409]: Oh, I did this so that it doesn't poll for everything everytime. For example if all pods are deleted and and some service is yet to be deleted, I would not want the pods to be polled again since we know they're deleted.

File: mesheryctl/pkg/utils/healthcheck.go (hunk 3 above)
Comment (piyushsingariya) [reply mesheryctl/pkg/utils/healthcheck.go:355]: Nice point! Understood we can keep it this way then.

Comment (gr455) [reply mesheryctl/pkg/utils/healthcheck.go:355]: Piyush can you check the comment on the original issue by Lee, We can also not add the polling behaviour for resources at all if we don't need to (it doesn't break anything)

File: mesheryctl/pkg/utils/healthcheck.go (hunk 4 above)
Comment (piyushsingariya) [reply mesheryctl/pkg/utils/healthcheck.go:409]: See, what we should do is if any of the resources are present, we poll again. That's how it should work.

And this polling shouldn't call the boolean function each second on each failure instead, as we know stopping a system is a time taking process from the user's perspective and that's why we can take a lease here and call the function after an interval, maybe 7 Seconds.

makes sense??

Comment (piyushsingariya) [reply mesheryctl/pkg/utils/healthcheck.go:409]: about the linter, it never works locally, at least for me. You can check your lint errors by clicking on 'Files Changed' in the top navigation.

Comment (gr455) [reply mesheryctl/pkg/utils/healthcheck.go:409]: Yep got it, thanks! (also nudging you to check the comment I made under the issue :sweat_smile:)

Comment (piyushsingariya) [reply mesheryctl/pkg/utils/healthcheck.go:409]: Yeah, I just checked it, that makes sense, You're right on that. I forgot the original issue and over-complexed it in my head and misdirected you.

I apologies! you can revoke these unnecessary changes. Let's get this wrapped up.

Comment (gr455) [reply mesheryctl/pkg/utils/healthcheck.go:409]: That's completely fine! Thanks for sticking around for this for so long. Let's get this done with :rocket:

File: mesheryctl/pkg/utils/healthcheck.go [hunk 5]
```diff
@@ -290,3 +290,32 @@ func WaitForPodRunning(c *meshkitkube.Client, desiredPod, namespace string, time
...
+			}
+		}
+
+		return true, nil
+	}
+}
+
+// Poll up to timeout seconds every 5 seconds until the namespace no more exists.
+func pollForNamespaceDeleted(c *meshkitkube.Client, namespace string, timeout time.Duration) error {
+	return wait.PollImmediate(5*time.Second, timeout, isNamespaceDeleted(c, namespace))
```
Comment (piyushsingariya) [inline mesheryctl/pkg/utils/healthcheck.go:315]: We don't want to PollImmediate here, we should do it interval-based, we discussed right? Deleting namespace takes a good time, we can take a lease here and do it at intervals.

File: mesheryctl/internal/cli/root/system/check.go [hunk 6]
```diff
@@ -581,6 +581,20 @@ func mesheryReadinessHealthCheck() (bool, error) {
...
+		return false, err
+	}
+
+	if err := utils.WaitForNamespaceDeleted(kubeClient, utils.MesheryNamespace, 300); err != nil {
+		return false, err
+	}
+
+	return true, nil
+}
+
```
Comment (piyushsingariya) [inline mesheryctl/internal/cli/root/system/check.go:597]: shift this to healthcheck.go in utils, this function doesn't align with other functions in check.go

File: mesheryctl/internal/cli/root/system/stop.go [hunk 7]
```diff
@@ -177,11 +178,20 @@ func stop() error {
 			if err = deleteNs(utils.MesheryNamespace, client.KubeClient); err != nil {
 				return err
 			}
+			// Wait for the namespace to be deleted
+			done, err := mesheryNsDeleteCheck()
+			if err != nil {
+				log.Info(err)
+			} else if !done {
+				log.Info("Meshery is taking too long to stop.\nPlease check the status of the pods by executing “mesheryctl system status”.")
```
Comment (piyushsingariya) [inline mesheryctl/internal/cli/root/system/stop.go:186]: These two conditions can be merged! The error will normally be thrown by `wait` once the timeout is expired.

File: mesheryctl/internal/cli/root/system/stop.go [hunk 8]
```diff
@@ -177,11 +178,20 @@ func stop() error {
...
+			}
+		} else {
+			log.Info("Meshery is stopped.")
 		}
 	}
 
-	log.Info("Meshery is stopped.")
-
 	// Reset Meshery config file to default settings
 	if utils.ResetFlag {
```
Comment (piyushsingariya) [inline mesheryctl/internal/cli/root/system/stop.go:196]: Let's shift this part of the code above because I feel this should be executed before the wait, the wait might return an error in some condition and then this won't be executed.

Let me know your thoughts!!

**Review by piyushsingariya — CHANGES_REQUESTED** [review]

File: mesheryctl/pkg/utils/healthcheck.go (hunk 5 above)
Comment (gr455) [reply mesheryctl/pkg/utils/healthcheck.go:315]: This does poll every 5 seconds, it only starts with a poll. I can replace it with `Poll` which starts with a wait which makes more sense because it's not very useful to poll in the start since it'll definitely take more time to stop :+1:

File: mesheryctl/internal/cli/root/system/check.go (hunk 6 above)
Comment (gr455) [reply mesheryctl/internal/cli/root/system/check.go:597]: Got it

File: mesheryctl/internal/cli/root/system/stop.go (hunk 8 above)
Comment (gr455) [reply mesheryctl/internal/cli/root/system/stop.go:196]: We are not returning the error from `wait` any further, so it will still get executed (correct me if I'm wrong). If we move it above, we will have to move it before the deleting happens because this bit is common for docker and kubernetes setup.

File: mesheryctl/internal/cli/root/system/stop.go (hunk 7 above)
Comment (gr455) [reply mesheryctl/internal/cli/root/system/stop.go:186]: Ah okay. Will do

File: mesheryctl/internal/cli/root/system/stop.go (hunk 8 above)
Comment (piyushsingariya) [reply mesheryctl/internal/cli/root/system/stop.go:196]: ahh, it will be okay now that we'll be logging in both cases above.

Comment (gr455) [reply mesheryctl/internal/cli/root/system/stop.go:196]: So you reckon it's okay to move the config reset code above the delete code for both (k8s and docker)?

Comment (piyushsingariya) [reply mesheryctl/internal/cli/root/system/stop.go:196]: let's leave it where it is. it would always execute because of logging. I'm already ending up introducing more and more bugs these days :laughing:

File: mesheryctl/internal/cli/root/system/stop.go [hunk 9]
```diff
@@ -177,11 +178,18 @@ func stop() error {
 			if err = deleteNs(utils.MesheryNamespace, client.KubeClient); err != nil {
 				return err
 			}
+			// Wait for the namespace to be deleted
+			_, err := utils.CheckMesheryNsDelete()
+			if err != nil {
```
Comment (piyushsingariya) [inline mesheryctl/internal/cli/root/system/stop.go:183]:
```suggestion
			if err != nil || !bool {
```

**Review by piyushsingariya — CHANGES_REQUESTED** [review]
Looks good!

File: mesheryctl/pkg/utils/healthcheck.go [hunk 10]
```diff
@@ -241,6 +241,20 @@ func AreAllPodsRunning() (bool, error) {
 	return true, nil
 }
 
+// CheckMesheryNsDelete waits for Meshery namespace to be deleted, returns (done, error)
+func CheckMesheryNsDelete() (bool, error) {
+	kubeClient, err := meshkitkube.New([]byte(""))
```
Comment (piyushsingariya) [inline mesheryctl/pkg/utils/healthcheck.go:246]:
```suggestion
	client, err := meshkitkube.New([]byte(""))
```
Minor edit for consistency across files. 

This is ready to merge.

Comment (gr455) [reply mesheryctl/pkg/utils/healthcheck.go]: Done!

**Review by piyushsingariya — APPROVED** [review]
LGTM! Amazing work @gr455 :partying_face: :balloon:

**Comment by piyushsingariya** [comment]
Let's go @gr455 !
image

**Comment by gr455** [comment]
> LGTM! Amazing work @gr455 partying_face balloon

Finally got this done! :tada: Thank you for sticking around
