### PR TITLE
[mesheryctl] fixed meshery start command bug with adapter components

### LINKED ISSUE #9149: [mesheryctl] `system start` not recognizing Meshery Adapters as components
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by zakisk**
**Notes for Reviewers**

This PR fixes #9149

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
There are a couple of these that you might be able to tackle at the same time, @zakisk - SA1019: cliflags.NewCommonOptions is deprecated

**Comment by leecalcote** [comment]
What other commands other than `start` will now need to be updated to use this new Compose manifest reference?

**Review by leecalcote — CHANGES_REQUESTED** [review]
@zakisk please fix the two failing lint checks.

**Review by leecalcote — APPROVED** [review]
@zakisk let's move forward prematurely (before lint checks are fixed) in order to include this bug fix in today's release.

File: mesheryctl/internal/cli/root/system/start.go [hunk 1]
```diff
@@ -204,40 +204,39 @@ func start() error {
 		}
 
 		//changing the port mapping in docker compose
```
Comment (hexxdump) [inline mesheryctl/internal/cli/root/system/start.go:206]: This comment becomes obsolete now, isnt it ?
We are programmatically reading the port mapping from helpers.go rather than the docker compose file.
