### PR TITLE
[UI] Fixed the applications page modal bug

### LINKED ISSUE #6803: [UI] Application Page Modal Bug
#### Current Behavior
The modal appearing on the click of deploy and undeploy is not in sync.

https://user-images.githubusercontent.com/99184676/209844879-b0d932a6-7486-40fe-85b5-673055ca3f47.mp4

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by partik03**
**Notes for Reviewers**

This PR fixes #6803 

**Before**

https://user-images.githubusercontent.com/99184676/209846987-cdc94f00-d0c8-459b-9ad0-39c7ed42d816.mp4

**After**

https://user-images.githubusercontent.com/99184676/211164235-3f989f32-a23d-4231-bd2d-935b3d94e901.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by partik03** [comment]
@Chadha93 @leecalcote Please review the pr.

**Comment by leecalcote** [comment]
@hs05june would you like to offer review on this PR?

**Review by hs05june — DISMISSED** [review]
Thank you @partik03 for PR. The changes appear good 👍

**Comment by Chadha93** [comment]
@partik03 Seems the After video was not uploaded. Will you reupload it?

**Comment by partik03** [comment]
@Chadha93 please review it again

**Comment by partik03** [comment]
@leecalcote @Chadha93 please review it again.

File: ui/components/ConfirmationModal.js [hunk 1]
```diff
@@ -185,6 +185,7 @@ function ConfirmationMsg(props) {
   },[selectedK8sContexts]);
 
   const handleTabValChange = (event, newVal) => {
+    console.log(newVal);
```
Comment (Chadha93) [inline ui/components/ConfirmationModal.js:188]:
```suggestion

```

File: ui/components/ConfirmationModal.js [hunk 2]
```diff
@@ -284,18 +284,24 @@ function ConfirmationMsg(props) {
             <Tab
               data-cy="validate-btn-modal"
               className={classes.tab}
-              label={<div style={{ display : "flex" }}> <DoneIcon style={{ margin : "2px" }}  fontSize="small"/><span className={classes.tabLabel}>Validate</span> </div>
+              label={<div style={{ display : "flex" }}
+                onClick={(e) => handleTabValChange(e,0)}
```
Comment (Chadha93) [inline ui/components/ConfirmationModal.js:288]: @partik03 Don't use onClick under the label, this will create an intuitive click issue. As I tested this PR, I'm only able to change the table when exactly clicked on the text(label) not on the tab.

File: ui/components/ConfirmationModal.js [hunk 3]
```diff
@@ -284,18 +284,24 @@ function ConfirmationMsg(props) {
...
+              > <DoneIcon style={{ margin : "2px" }}  fontSize="small"/><span className={classes.tabLabel}>Validate</span> </div>
               }
             />}
             <Tab
               data-cy="Undeploy-btn-modal"
               className={classes.tab}
-              label={<div style={{ display : "flex" }}> <div style={{ margin : "2px" }}> <UndeployIcon fill="rgba(0, 0, 0, 0.54)" width="20" height="20"/> </div> <span className={classes.tabLabel}>Undeploy</span> </div>}
+              label={<div style={{ display : "flex" }}
+                onClick={(e) => handleTabValChange(e,1)}
```
Comment (Chadha93) [inline ui/components/ConfirmationModal.js:296]: Use event instead of `e` or another relevant term.

Comment (partik03) [reply ui/components/ConfirmationModal.js]: Done

File: ui/components/ConfirmationModal.js (hunk 2 above)
Comment (partik03) [reply ui/components/ConfirmationModal.js]: Done

**Review by Chadha93 — APPROVED** [review]
Thank you @partik03
