### PR TITLE
fix: route based details on MeshModelsDetails Component

### LINKED ISSUE #11471: [Server] Registry Enhancements
### Current Behavior
- [x] 1. Update the API endpoints to retrieve only the count of components and relationships for each model, rather than returning all data.
    - [x] Fix the bug where both the component count and relationship count are showing zero,
- [ ] 2. Remove duplicated data that's currently being returned from the endpoint.
- [ ] 3. Add query parameters for the `meshmodel/models`, `meshmodels/components`, `meshmodels/relationships`, and `meshmodels/registrants` endpoints.
    - [ ] Add a query parameter like `duplication-data=true` to fetch information about duplicated entities. This will allow the UI to filter and highlight duplicate entities.
- [ ] 4. Remove the aggregation of models in the registrants tab once the data duplication is resolved from the endpoint.
- [ ] 5. Add ID-based `GET` endpoints for all Registry requests to simplify the selection of entities. #12361
    - Currently, selection is based on a combination of name and version.
    - Possibly related PR: https://github.com/meshery/meshkit/pull/538.
- [ ] 6. [UI] Ensure the `meshmodel` details component respects the current level of navigation in the tree structure. (depends on 1st issue of this list)
    - [ ] At the top level of a model, display the aggregate count of components across all versions of that model.

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

### To Reproduce
1. Go to [https://playground.meshery.io/settings?settingsCategory=Registry](https://playground.meshery.io/settings?settingsCategory=Registry)

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by amitamrutiya**
**Notes for Reviewers**

This PR fixes #11471

Able to retrieve the content of the `MeshModelsDetails` component from the URL.
[Screencast from 2024-08-21 23-19-17.webm](https://github.com/user-attachments/assets/f3d866b8-83f9-4bdb-bb5b-c17f5d28618f)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/MeshModelRegistry/MesheryTreeView.js [hunk 1]
```diff
@@ -43,6 +44,27 @@ const VersionedModelComponentTree = ({
     model: versionedModelDef.name,
     params: { version: versionedModelDef.model.version },
   });
+  const { selectedItemUUID } = useRegistryRouter();
+
+  useEffect(() => {
```
Comment (leecalcote) [inline ui/components/MeshModelRegistry/MesheryTreeView.js:49]: An opportunity for use of RTK?

Comment (amitamrutiya) [reply ui/components/MeshModelRegistry/MesheryTreeView.js:49]: This is not an RTK query, This is a custom hook that encapsulates the logic for managing routing and query parameters.

**Review by leecalcote — APPROVED** [review]
