### PR TITLE
[mesheryctl] Fix error logs for non importable files

### LINKED ISSUE #13143: [Server] Model import attempts to import invalid files
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
`mesheryctl model import` fails to import a Model (whether presented as a directory of files or as an OCI image - a .tar) in the event any file fail YAML validation.

In the same way, attempting to import models in Meshery UI under the Settings-->Registry page will result in the same error.

- Sample model (working): [meshery-core.tar.zip](https://github.com/user-attachments/files/18303471/meshery-core.tar.zip)
- Sample model (not working): [meshery-core-original.tar.zip](https://github.com/user-attachments/files/18303476/meshery-core-original.tar.zip)

### Desired Behavior

The behavior of Meshery during import of model packages should be to fail forward, which is to say that any file included in the model directory or model OCI image that fails to import, should not cause the import to fail, but that file should be listed as not being importable.

### Implementation
The fix for this issue will likely need to be made in https://github.com/meshery/meshkit and https://github.com/meshery/meshery/server

### Screenshots/Logs
In the example below, .DS_Store should be ignored during model import.

```
$ mesheryctl model import -f meshery-core
SUMMARY: Imported model meshery-core, .DS_Store (17 components), encountered error for 1 entity (1 unknown entity)

MODEL: meshery-core

  COMPONENT                 CATEGORY  VERSION
  AnchorNode                          v1.0.0
  BoundingBox                         v1.0.0
  Comment                             v1.0.0
  Connection                          v1.0.0
  Container                           v1.0.0
  Credential                          v1.0.0
  GenericNode                         v1.0.0
  ImageNode                           v1.0.0
  NodeGroupInventoryWallet            v1.0.0
  Pen                                 v1.0.0
  PenConnectorNode                    v1.0.0
  PenTerminal                         v1.0.0
  Pencil                              v1.0.0
  Picture                             v1.0.0
  Section                             v1.0.0
  TextBox                             v1.0.0
  WASMFilter                          v1.0.0

MODEL: .DS_Store

ERROR: Import process for file .DS_Store encountered error:
    yaml: control characters are not allowed
```

**Other examples from Meshery UI**

Screenshot 2025-01-03 at 2 17 52 PM
Screenshot 2025-01-03 at 2 17 44 PM

### Environment

- Host OS: Mac
- Meshery Server Version: stable-v0.8.3
- Meshery Client Version: stable-v0.8.3
- Platform: Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by riyaa14**
**Notes for Reviewers**

- This PR fixes #13143 

Changes in `meshery/mesheryctl` covers:
1. Fixed error logs for non-importable files (eg: .rego, .DS_Store)
2. Extensive logging with causes and suggestions
3. Replaced hardcoded error messages. The error messages are fetched from server directly.

Changes in `meshery/server` covers:
New error messages that are more detailed and specific to file types.

### Before - 
image

### After -
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: server/handlers/componetgenratorhelper.go [hunk 1]
```diff
@@ -147,11 +148,31 @@ func addUnsuccessfulEntry(path string, response *models.RegistryAPIResponse, err
...
+	if isEntityJsonFile {
+		errMsg = meshkitFileUtils.ErrInvalidJson(filename, err)
+	} else if isEntityYamlFile {
+		errMsg = meshkitFileUtils.ErrInvalidYaml(filename, err)
+	} else if isEntityModel {
+		errMsg = meshkitFileUtils.ErrFailedToExtractArchive(filename, err)
+	} else {
+		supportedExtensions := []string{".json", ".yaml", ".yml", ".tar", ".tgz", ".tar.gz", ".zip"}
+		errMsg = meshkitFileUtils.ErrUnsupportedExtensionForOperation("import", filename, fileExt, supportedExtensions)
+	}
```
Comment (lekaf974) [inline server/handlers/componetgenratorhelper.go:169]: Ccould this be moved in function in meshkit ?

Comment (riyaa14) [reply server/handlers/componetgenratorhelper.go:169]: yes, makes sense. I have done this. Please check this PR in Meshkit - [Meshkit #671](https://github.com/meshery/meshkit/pull/671)

To see these changes, we'll need a new meshkit release I think?

Comment (lekaf974) [reply server/handlers/componetgenratorhelper.go]: yep, we will need new release available

Comment (riyaa14) [reply server/handlers/componetgenratorhelper.go]: @lekaf974 after a discussion with @aabidsofi19 , I got to know that this new function in meshkit isn't needed. Since model import isn't updated currently based on [Meshkit v0.8.9](https://github.com/meshery/meshkit/releases/tag/v0.8.9)  (which includes file type identification), we'll need to check these file extensions currently.

Once it is refactored just like `design import` - #13445 
We won't need this check for file extensions

and so, to improve `model import` error logs for now, can we merge it as it is? and in the next PR I'll refactor model import.

**Comment by lekaf974** [comment]
I am okay with this approach but IMO the cli should also validated extension before  to avoid to send non valid request to the serve.

**Comment by lekaf974** [comment]
can you fix lint iisue

**Comment by riyaa14** [comment]
> I am okay with this approach but IMO the cli should also validated extension before to avoid to send non valid request to the serve.

Okay, got your point, makes total sense. I did that here in the [3rd commit ](https://github.com/meshery/meshery/pull/13420/commits/4080e85dcb5cf604ddb5749614627f6c7e627b33)
Is this what you are saying? I'll make changes accordingly then.

For all other errors like InvalidJson, InvalidYaml, etc, they go through some file sanitization and so I think it would be best to keep that logic to server side. We can check for invalid extensions on cli side.
