### PR TITLE
fix-rows-per-page-in-mesh-model-summary

### LINKED ISSUE #7971: [UI] Rows per page is not working in meshmodel tabs in settings
#### Current Behavior
In tabs `Models`, `Components` Rows per page is not working

https://github.com/meshery/meshery/assets/71271069/7143b00d-e2d4-4409-b111-ffc1eb6a9050

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by HarshDobariya79**
**Notes for Reviewers**

This PR fixes #7971 

**Changes**
- Before **rows per page** wasn't working (25 rows per page irrespective of selected value)
- Add options **10**, **25**, **50**, **100** rows per page options
- Fix rows per page in **Models**, **Components**, and **Relationships** tabs.
- create API calling functions with custom page size.

https://github.com/meshery/meshery/assets/29772969/efb6fddd-61d1-423e-8711-94b27dcf552b

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
is selecting 100 working?

**Comment by HarshDobariya79** [comment]
> is selecting 100 works?

Yes, It is working fine.

[100RowsPerPageDemo.webm](https://github.com/meshery/meshery/assets/29772969/80cbb622-2836-4d6b-a89c-84744bb29d6f)

File: ui/api/meshmodel.js [hunk 1]
```diff
@@ -55,6 +55,12 @@ export async function getVersionedComponentFromModel(
   );
 }
 
+export async function getComponentsDetailWithPageSize(page=1, pageSize="all") {
+  return await promisifiedDataFetch(
+    `api/meshmodels/components?page=${page}&pagesize=${pageSize}`
+  );
+}
```
Comment (Yashsharma1911) [inline ui/api/meshmodel.js:62]: I think we don't need to create separate function, we can use getComponentDetails by passing pageSize param with default value.

Comment (HarshDobariya79) [reply ui/api/meshmodel.js:62]: Yes, that will be great. But since there were separate functions already present for **Mesh Models**, I followed the same convention.

https://github.com/meshery/meshery/blob/master/ui/api/meshmodel.js#L37

https://github.com/meshery/meshery/blob/master/ui/api/meshmodel.js#L64

Comment (HarshDobariya79) [reply ui/api/meshmodel.js:62]: I think it is because the default page size is mentioned in **backend**. Let's say we modify the function with the **default page size**, then if the default page size is updated in the **backend**, the changes won't be reflected in the **front-end** unless we change it in front-end also.

Comment (Yashsharma1911) [reply ui/api/meshmodel.js:62]: I think then we are good, @Chadha93 thoughts? ^^

Comment (leecalcote) [reply ui/api/meshmodel.js:62]: @duckling69?

**Review by leecalcote — APPROVED** [review]
Thanks, @HarshDobariya79. 

@nebula-aac thoughts on establishing a convention in this regard?
