### PR TITLE
fix(mesheryctl): use meshkit error properly and remove logrus in syst…

### LINKED ISSUE #18332: [mesheryctl] system stop uses meshkit error properly + remove logrus
## Parent Issue
#17709

## Current Behavior
In `stop.go`:
- Logrus used directly: log.Info, log.Debug

## Desired Behavior
- Replace logrus references with `utils.Log`

### PR DESCRIPTION
**Pull request by Vydeh07**
…em stop

This replaces direct logrus usage with utils.Log and standard errors with Meshkit errors.

Fixes #18332

**Notes for Reviewers**

- This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/internal/cli/root/system/stop.go [hunk 1]
```diff
@@ -290,7 +289,7 @@ func invokeDeleteCRDs() error {
 			return err
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/stop.go:289]: is this error a meshkit error ?

Comment (Vydeh07) [reply mesheryctl/internal/cli/root/system/stop.go:289]: Yep, it is. It's currently defined in mesheryctl/internal/cli/root/system/error.go

**Comment by lekaf974** [comment]
@Vydeh07 could you resynv with master and resolve conflicts

**Review by lekaf974 — APPROVED** [review]
