### PR TITLE
[mesheryctl] Improve `mesheryctl registry generate` command by applying argument check

### LINKED ISSUE #13001: [mesheryctl] Improve `mesheryctl registry generate` command
Regeneration:
```Bash
$ mesheryctl registry generate
unexpected end of JSON input
```
so for better output this should output something like the help of this command which can be generated using `mesheryctl registry generate --help` if not describing the exact error happening instead of just outputting `unexpected end of JSON input
` which is a bit off.

**see exmaple of output when running `mesheryctl model import`

## Update

- Update the output for the following `mesheryctl registry` subcommands
  - generate
  - publish

### PR DESCRIPTION
**Pull request by riyaa14**
**Notes for Reviewers**

- This PR fixes #13001 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/internal/cli/root/registry/generate.go [hunk 1]
```diff
@@ -67,6 +67,9 @@ mesheryctl registry generate --directory <DIRECTORY_PATH>
 	},
 
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if len(args) == 0 {
+			return cmd.Help()
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/registry/generate.go:71]: We need to be explicit and tell the user what he is doing wrong not just display the `--help`  see my comment in #13001

**Review by lekaf974 — CHANGES_REQUESTED** [review]

**Comment by vishalvivekm** [comment]
@riyaa14 
Thank you for your contributions! Let's discuss this today, during Meshery Development call at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1&tab=t.0#) || [meeting link.](https://meet.layer5.io/meshery)

**Comment by riyaa14** [comment]
@lekaf974 , I have made the changes you suggested. Kindly review my new commits. Thanks!

**Review by lekaf974 — APPROVED** [review]
LGTM

**Comment by lekaf974** [comment]
@alphaX86 could you have a second review please

File: mesheryctl/internal/cli/root/registry/generate.go [hunk 2]
```diff
@@ -63,10 +64,32 @@ mesheryctl registry generate --directory <DIRECTORY_PATH>
 		// Prerequisite check is needed - https://github.com/meshery/meshery/issues/10369
 		// TODO: Include a prerequisite check to confirm that this command IS being the executED from within a fork of the Meshery repo, and is being executed at the root of that fork.
 
+		spreadsheetIdFlag, _ := cmd.Flags().GetString("spreadsheet-id")
+		registrantDefFlag, _ := cmd.Flags().GetString("registrant-def")
+		directory, _ := cmd.Flags().GetString("directory")
+
+		if spreadsheetIdFlag == "" && registrantDefFlag == "" && directory == "" {
+			return errors.New(utils.RegistryError("[ Spreadsheet ID | Registrant Connection Definition Path | Local Directory ] isn't specified", "generate"))
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/registry/generate.go:72]:
```suggestion
			 const errorMsg = "[ Spreadsheet ID | Registrant Connection Definition Path | Local Directory ] isn't specified\n\nUsage: mesheryctl registry generate --spreadsheet-id [Spreadsheet ID] --spreadsheet-cred $CRED\nmesheryctl registry generate --spreadsheet-id [Spreadsheet ID] --spreadsheet-cred $CRED --model \"[model-name]\"\nRun 'mesheryctl registry generate --help' to see detailed help message"
			return errors.New(utils.RegistryError(errorMsg, "generate"))
```

example in model import
```bash
/mesheryctl model import
Error: [ file | filepath | URL ] isn't specified

Usage: mesheryctl model import [ file | filePath | URL ]
Run 'mesheryctl model import --help' to see detailed help message
```

File: mesheryctl/internal/cli/root/registry/generate.go [hunk 3]
```diff
@@ -63,10 +64,32 @@ mesheryctl registry generate --directory <DIRECTORY_PATH>
...
+		}
+
+		spreadsheetCredFlag, _ := cmd.Flags().GetString("spreadsheet-cred")
+		registrantCredFlag, _ := cmd.Flags().GetString("registrant-cred")
+
+		if spreadsheetIdFlag != "" && spreadsheetCredFlag == "" {
+			return errors.New(utils.RegistryError("Spreadsheet Credentials is required\nUsage: \nmesheryctl registry generate --spreadsheet-id [Spreadsheet ID] --spreadsheet-cred $CRED\nmesheryctl registry generate --spreadsheet-id [Spreadsheet ID] --spreadsheet-cred $CRED --model \"[model-name]\"", "generate"))
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/registry/generate.go:79]:
```suggestion
			return errors.New(utils.RegistryError("Spreadsheet Credentials is required\n\nUsage: \nmesheryctl registry generate --spreadsheet-id [Spreadsheet ID] --spreadsheet-cred $CRED\nmesheryctl registry generate --spreadsheet-id [Spreadsheet ID] --spreadsheet-cred $CRED --model \"[model-name]\"\nRun 'mesheryctl registry generate --help'", "generate"))
```

File: mesheryctl/internal/cli/root/registry/generate.go [hunk 4]
```diff
@@ -63,10 +64,32 @@ mesheryctl registry generate --directory <DIRECTORY_PATH>
...
+		}
+
+		if registrantDefFlag != "" && registrantCredFlag == "" {
+			return errors.New(utils.RegistryError("Registrant Credentials is required\nUsage: mesheryctl registry generate --registrant-def [path to connection definition] --registrant-cred [path to credential definition]", "generate"))
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/registry/generate.go:83]:
```suggestion
			return errors.New(utils.RegistryError("Registrant Credentials is required\n\nUsage: mesheryctl registry generate --registrant-def [path to connection definition] --registrant-cred [path to credential definition]\nRun 'mesheryctl registry generate --help'", "generate"))
```

File: mesheryctl/internal/cli/root/registry/publish.go [hunk 5]
```diff
@@ -80,11 +80,16 @@ mesheryctl registry publish website $CRED 1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwiz
 // Publishing to any website
 mesheryctl registry publish website $CRED 1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw path/to/models path/to/icons -o mdx
 	`,
-	RunE: func(cmd *cobra.Command, args []string) error {
+	PreRunE: func(cmd *cobra.Command, args []string) error {
+
 		if len(args) != 5 {
-			return cmd.Help()
+			return errors.New(utils.RegistryError("Missing Arguments - [ system, google sheet credential, sheet-id, models output path, imgs output path] are required\nUsage: \nmesheryctl registry publish [system] [google-sheet-credential] [sheet-id] [models-output-path] [imgs-output-path]\nmesheryctl registry publish [system] [google-sheet-credential] [sheet-id] [models-output-path] [imgs-output-path] -o [output-format]", "publish"))
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/registry/publish.go:86]:
```suggestion
			return errors.New(utils.RegistryError("[ system, google sheet credential, sheet-id, models output path, imgs output path] are required\nUsage: \nmesheryctl registry publish [system] [google-sheet-credential] [sheet-id] [models-output-path] [imgs-output-path]\nmesheryctl registry publish [system] [google-sheet-credential] [sheet-id] [models-output-path] [imgs-output-path] -o [output-format]\nRun 'mesheryctl registry publish --help'", "publish"))
```

**Review by lekaf974 — CHANGES_REQUESTED** [review]
@riyaa14 last comment should be OK after update

File: mesheryctl/internal/cli/root/registry/generate.go (hunk 1 above)
Comment (riyaa14) [reply mesheryctl/internal/cli/root/registry/generate.go:91]: > could you move it in PreRunE and updated message

Oh I forgot to resolve the conversation, this change is already done ✅

Comment (riyaa14) [reply mesheryctl/internal/cli/root/registry/generate.go:91]: > could you move it in PreRunE and updated message

Since we are already checking for flags, rather than moving this to PreRun, shall we completely remove the argument length check? This case is automatically handled because of flag check.

Comment (lekaf974) [reply mesheryctl/internal/cli/root/registry/generate.go:91]: exact arguments checks should be covered in PreRunE so in RunE we don't need to revalidate

Comment (riyaa14) [reply mesheryctl/internal/cli/root/registry/generate.go]: @lekaf974 changes done. Thanks for the suggestions!

**Review by lekaf974 — APPROVED** [review]
LGTM

**Comment by lekaf974** [comment]
@riyaa14 can you sync master in your branch ?

**Comment by riyaa14** [comment]
> @riyaa14 can you sync master in your branch ?

done ✅

**Comment by riyaa14** [comment]
@lekaf974 the command isn't working now because we are checking if argument length is 0. This command has no arguments, it only has flags and so we need to remove this condition.
argument length will always be 0 in this command.

Before making changes, wanted your views on this

**Comment by pratikgitss** [comment]
I am also facing the same issue!!

**Comment by lekaf974** [comment]
Ok, let's remove it

**Comment by lekaf974** [comment]
@riyaa14 I push a fix in #13338
