### PR TITLE
[Server] Fix None provider blank login by routing through /user/login

### LINKED ISSUE #17321: Provider=None redirects to blank login screen instead of dashboard
### Current Behavior
When selecting the "None" provider (or when PROVIDER=None is set), the server redirects to /user/login, which renders a blank page. The local provider's InitiateLogin doesn't perform any redirect, resulting in an empty response. On a subsequent page refresh, the dashboard loads because the session cookie is already set.

### Expected Behavior
Selecting the "None" provider should redirect users directly to the dashboard (/) without passing through the blank login screen.

#### Current Behavior:

https://github.com/user-attachments/assets/c3ffebe6-5702-44b1-b7df-e77f2f4f676d

#### Expected Behavior:

https://github.com/user-attachments/assets/014161f4-ffd1-4c2c-b76d-bca7f81d889b

### Environment
  - Host OS: Linux
  - Platform: Kubernetes
  - Meshery Server Version: v0.8.202

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
- 📺 [Self-paced Contributor Trainings](https://meshery.io/talks-and-trainings#trainings)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by leecalcote**
## Description

Fixes #17321 – When `Provider=None` is selected (or enforced via `PROVIDER` env var), users are redirected to a blank login page because `DefaultLocalProvider.InitiateLogin` was a no-op (the method body was commented out). This PR fixes the root cause by making `InitiateLogin` complete the login flow with a redirect.

### Root Cause

`DefaultLocalProvider.InitiateLogin` (in `server/models/default_local_provider.go`) had its body commented out (`// l.issueSession(w, r, fromMiddleWare)`). When `LoginHandler` called `provider.InitiateLogin(w, r, false)`, no HTTP response was written, resulting in a blank page.

### Fix

**`server/models/default_local_provider.go`**
- `InitiateLogin` now redirects to `/` (or to the deep-link target from the `ref` query param) when called from the `/user/login` route (`fromMiddleWare=false`)
- When called from `AuthMiddleware` (`fromMiddleWare=true`), it remains a no-op to avoid sending 302 responses to REST API clients
- Uses `core.DecodeRefURL()` for centralized base64 ref decoding
- Adds `isSafeRedirect()` validation to prevent open redirect attacks via the `ref` parameter (rejects absolute URLs, protocol-relative URLs, and non-empty scheme/host)

**`server/handlers/provider_handler.go`**
- Removed the `provider == "None"` special-case bypass from `ProviderHandler` — the None provider now flows through `/user/login` like all other providers
- Fixed `ProviderUIHandler` to avoid appending a trailing `?` when `RawQuery` is empty

**`server/handlers/common_handlers.go`**
- Fixed swagger annotation from `/api/user/login` to `/user/login` to match the actual route

### Login Flow (After Fix)

1. User selects "None" provider → `ProviderHandler` sets cookie → redirects to `/user/login?provider=None`
2. `/user/login` → `ProviderMiddleware` resolves provider → `LoginHandler` → `DefaultLocalProvider.InitiateLogin` → **302 to `/`** (dashboard)

When `PROVIDER=None` env var is set:
1. User visits `/provider` → `ProviderUIHandler` sets cookie → redirects to `/user/login`
2. Same flow as above → dashboard

### Tests

Added `server/handlers/provider_handler_test.go` with 7 tests:
- `TestProviderHandler_NoneRedirectsThroughLogin` — verifies cookie + redirect to `/user/login`
- `TestProviderUIHandler_NoneEnvVarRedirectsThroughLogin` — verifies env var flow (no trailing `?`)
- `TestLoginHandler_NoneProviderRedirectsHome` — verifies redirect to `/`
- `TestLoginHandler_NoneProviderDeepLink` — verifies `ref` param deep-link support
- `TestLoginHandler_NoneProviderRejectsOpenRedirect` — table-driven test for absolute URL, protocol-relative, and javascript scheme
- `TestLoginHandler_NoneProviderFromMiddleware` — verifies no redirect when `fromMiddleWare=true`

### Approach Comparison with #17322

Both PRs fix `InitiateLogin` to redirect. This PR differs by:
- **Removing** the `ProviderHandler` bypass instead of adding more bypasses
- Preserving the standard login flow (`/user/login` route) for all providers
- Adding open redirect protection for the `ref` parameter
- Using centralized `core.DecodeRefURL()` instead of inline base64 decoding
- Adding comprehensive test coverage

### CODE REVIEW

File: server/models/default_local_provider.go [hunk 1]
```diff
@@ -140,9 +140,17 @@ func (l *DefaultLocalProvider) GetProviderCapabilities(w http.ResponseWriter, _
...
+// there instead of / so that deep-links survive provider selection.
+func (l *DefaultLocalProvider) InitiateLogin(w http.ResponseWriter, r *http.Request, _ bool) {
+	redirectURL := "/"
+	if ref := r.URL.Query().Get("ref"); ref != "" {
+		if decoded, err := base64.RawURLEncoding.DecodeString(ref); err == nil && len(decoded) > 0 {
+			redirectURL = string(decoded)
+		}
+	}
+	http.Redirect(w, r, redirectURL, http.StatusFound)
 }
```
[the remark this answers is not in the document]
Comment (PragalvaXFREZ) [reply server/models/default_local_provider.go]: This is a valid concern. I've checked it locally the ref param is vulnerable to open redirects. 

Image

File: server/handlers/provider_handler_test.go [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+
+func TestLoginHandler_NoneProviderDeepLink(t *testing.T) {
+	local := &models.DefaultLocalProvider{}
+	local.Initialize()
+
+	providers := map[string]models.Provider{local.Name(): local}
+	h := newTestHandler(t, providers, "")
+
+	// ref is base64-raw-url-encoded "/extension/meshmap"
+	req := httptest.NewRequest(http.MethodGet, "/user/login?provider=None&ref=L2V4dGVuc2lvbi9tZXNobWFw", nil)
```
Comment (PragalvaXFREZ) [inline server/handlers/provider_handler_test.go:125]: Could we add a case here to verify that an external URL passed as ref doesn't result in an off-site redirect?

File: server/handlers/provider_handler.go
Comment (PragalvaXFREZ) [inline server/handlers/provider_handler.go]: Is there a reason we're not including h.Provider in the redirect query string here? I noticed an infinite redirect loop between /provider and /user/login? when testing without cookies (e.g., curl without a cookie jar). It works fine in browsers since cookies are sent automatically, but appending the provider (e.g., /user/login?provider=None) would make the flow less dependent on cookie state.

**Comment by leecalcote** [comment]
@copilot open a new pull request to apply changes based on the comments in [this thread](https://github.com/meshery/meshery/pull/17342#pullrequestreview-3768890668)

File: server/models/default_local_provider.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (leecalcote) [reply server/models/default_local_provider.go]: Thanks for this, @PragalvaXFREZ. This feedback is being addressed in #17350

File: server/handlers/provider_handler.go
Comment (leecalcote) [reply server/handlers/provider_handler.go]: Thanks for bringing this up... 🤔

File: server/handlers/provider_handler_test.go (hunk 2 above)
Comment (leecalcote) [reply server/handlers/provider_handler_test.go:125]: Yes, I'll let you add.

Comment (leecalcote) [reply server/handlers/provider_handler_test.go:125]: Implemented.

File: server/handlers/provider_handler_test.go [hunk 3]
```diff
@@ -0,0 +1,137 @@
...
+	t.Helper()
+	log, _ := logger.New("test", logger.Options{Format: logger.SyslogLogFormat})
+	return &Handler{
+		config: &models.HandlerConfig{
+			Providers:          providers,
+			ProviderCookieName: "meshery-provider",
+		},
+		Provider: providerOverride,
+		log:      log,
+	}
```
[the remark this answers is not in the document]
Comment (leecalcote) [reply server/handlers/provider_handler_test.go:27]: Incorporated.

File: server/handlers/provider_handler_test.go [hunk 4]
```diff
@@ -0,0 +1,137 @@
...
+	defer resp.Body.Close()
+
+	if resp.StatusCode != http.StatusFound {
+		t.Fatalf("expected 302 Found, got %d", resp.StatusCode)
+	}
+
+	loc := resp.Header.Get("Location")
+	if loc != "/user/login?" {
+		t.Errorf("expected redirect to /user/login?, got %s", loc)
+	}
```
[the remark this answers is not in the document]
Comment (leecalcote) [reply server/handlers/provider_handler_test.go:89]: Incorporated.

File: docs/pages/extensibility/providers.md
Comment (hortison) [inline docs/pages/extensibility/providers.md:73]:
```suggestion

#### Example remote provider

Name: **"Acme"** (default)

- Enforces user authentication.
- Long-term term persistence.
- Save environment setup.
- Retrieve performance test results.
- Events are stored locally and can be published to remote provider. [Read more about server events](https://docs.meshery.io/project/contributing/contributing-server-events)
- Free to use.
```
