### PR TITLE
[UI] Dark mode toggle switch text fix in user preferences section

### LINKED ISSUE #7931: [UI] User preferences dark mode toggle button text
#### Current Behavior

- In the user **preferences** section, when **dark mode** is active text is changed to **"Light Mode"**.
user-preferences-dark-mode-issue

#### Desired Behavior

- **"Dark Mode"** should be displayed irrespective of the current mode.
user-preferences-dark-mode-desired-behaviour

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by HarshDobariya79**
**Notes for Reviewers**

This PR fixes #7931 

**Changes**
- Before the dark-mode toggle switch text was "**Dark Mode**" when **light-mode** was active and "**Light Mode**" when **dark-mode** was active.
- Text is changed to "**Dark Mode**" irrespective of the current mode.
 
Before:
before-preview

After:
after-preview

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/UserPreferences.js [hunk 1]
```diff
@@ -152,7 +152,7 @@ function ThemeToggler({ theme, themeSetter, enqueueSnackbar, classes }) {
         checked={themeToggle}
         onChange={themeToggler}
       />{" "}
-      {themeToggle ? "Light Mode" : "Dark Mode"}
+      Dark Mode
```
Comment (samyakshah3008) [inline ui/components/UserPreferences.js:155]: Can we keep a behavior: 
If it is light theme, then we can show the text: "Light Mode" 
And if it is dark theme, then we can show the text: "Dark Mode" 

What are your views? 🤔

Comment (HarshDobariya79) [reply ui/components/UserPreferences.js:155]: If it was a **button** only, then it would be better. But since it is a **toggle switch**, "**Dark Mode**" will be a better approach I guess. Refer to this thread for more insights https://layer5io.slack.com/archives/CFGG6U10E/p1687449363485659

Comment (samyakshah3008) [reply ui/components/UserPreferences.js:155]: Cool, I agree with the vote of majority 👌

**Comment by vishalvivekm** [comment]
@HarshDobariya79 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Review by sudhanshutech — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]
