### PR TITLE
[mesheryctl] fix context support for all commands, clean-up

### LINKED ISSUE #2393: [mesheryctl] Respect current-context, fetch correct docker-compose.yaml
#### Description

Whenever `mesheryctl` cannot find `docker-compose.yaml` it downloads it from Github, but all it does not take into account the `correct-context` and always download the latest file from the master branch.
[Several instances](https://github.com/layer5io/meshery/search?q=fileURL) of this behaviour needs to be corrected.

`mesheryctl system reset` has been updated to fetch correct `docker-compose.yaml`  file from GitHub corresponding to the `channel` and `version` specified in the `current-context`. 

The logic inside `resetMesheryConfig` can be extracted to create a separate helper function that fetches correct file.
https://github.com/layer5io/meshery/blob/1a91051afe17d82a668c7429c735bf7ed94970c7/mesheryctl/internal/cli/root/system/reset.go#L80-L90

 

#### Expected Behavior

`mesheryctl` should fetch correct `docker-compose.yaml` based on `current-context`

#### Child Issues

Issue #2394 [mesheryctl] Feature: Add current-context support to `system update`
Issue #2395 [mesheryctl] Feature: Add current-context support to `system log`
Issye #2396 [mesheryctl] Feature: Add current-context support to `system start`

### LINKED ISSUE #2394: [mesheryctl] Feature: Add current-context support to `system update`
#### Description

See Epic #2393 for more context

#### Current Behavior

https://github.com/layer5io/meshery/blob/1a91051afe17d82a668c7429c735bf7ed94970c7/mesheryctl/internal/cli/root/system/update.go#L44-L48

#### Expected Behavior

`mesheryctl system update` should fetch correct `docker-compose.yaml` as per `version` and `channel` specified in `current-context`

### LINKED ISSUE #2395: [mesheryctl] Feature: Add current-context support to `system log`
#### Description

See Epic #2393 for more context

#### Current Behavior

https://github.com/layer5io/meshery/blob/f8227b1978de965ecad238529a60fae35af61a99/mesheryctl/internal/cli/root/system/logs.go#L45-L49

#### Expected Behavior

`mesheryctl system log` should fetch correct `docker-compose.yaml` as per `version` and `channel` specified in `current-context`

### PR DESCRIPTION
**Pull request by aneeshnema**
**Description**

This PR fixes #2393, fixes #2394 , fixes #2395 

**Notes for Reviewers**

1.  ~Added `skipConfirmation` flag to `resetMesheryConfig`~
2.  Added user confirmation ⚠ to update command 
3.  ~`GetCurrentContext` now also sets the correct `Version` instead of leaving it empty~ 
    ❌function removed, use newly added setter `SetCurrentContext` for similar functionality
4.  Renamed ~`GetContextContent`~ `GetCurrentContext`✔ (getter)
5.  Removed `ValidateComposeFileForRecreation` from start.go because it is not needed now as we are always downloading the correct docker-compose file at every start.
6.  Updated all files based on the above changes.

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/internal/cli/root/system/update.go [hunk 1]
```diff
@@ -41,11 +38,6 @@ var updateCmd = &cobra.Command{
 	},
 	RunE: func(cmd *cobra.Command, args []string) error {
 
-		if _, err := os.Stat(utils.DockerComposeFile); os.IsNotExist(err) {
-			if err := utils.DownloadFile(utils.DockerComposeFile, fileURL); err != nil {
-				return errors.Wrapf(err, utils.SystemError(fmt.Sprintf("failed to download %s file from %s", utils.DockerComposeFile, fileURL)))
-			}
-		}
 		err := resetMesheryConfig()
 		if err != nil {
```
Comment (aneeshnema) [inline mesheryctl/internal/cli/root/system/update.go:42]: `resetMesheryConfig` already handles downloading the docker-compose file
removed redundant code

TODO: fixing the update command to abort update when reset is aborted. Currently `resetMesheryConfig` does not return anything that can signal reset aborted.

File: mesheryctl/internal/cli/root/system/logs.go [hunk 2]
```diff
@@ -42,10 +41,10 @@ var logsCmd = &cobra.Command{
 
 		log.Info("Starting Meshery logging...")
 
-		if _, err := os.Stat(utils.DockerComposeFile); os.IsNotExist(err) {
-			if err := utils.DownloadFile(utils.DockerComposeFile, fileURL); err != nil {
-				return errors.Wrapf(err, utils.SystemError(fmt.Sprintf("failed to download %s file from %s", utils.DockerComposeFile, fileURL)))
-			}
+		// download(don't force) the docker-compose.yaml file corresponding to the current version
+		_, currCtx, err := utils.GetCurrentContext(tempContext)
+		if _, err := utils.DownloadDockerComposeFile(currCtx, false); err != nil {
```
Comment (aneeshnema) [inline mesheryctl/internal/cli/root/system/logs.go:46]: skip the download of docker-compose file if it already exists (since meshery must be already running, the file should be correct?)

Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/logs.go:49]: It should be correct. @anirudhjain75 @leecalcote This can be done right?

File: mesheryctl/internal/cli/root/system/update.go (hunk 1 above)
Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/update.go:42]: When running reset() from the update command, we can maybe pass in an argument that would suppress the confirmation question. If we still need to confirm with the user, we can have a confirmation question in the update command.

**Review by navendu-pottekkat — COMMENTED** [review]
Looks good. I have left some suggestions for handling reset() in the update command. Please check if that would work.

File: mesheryctl/internal/cli/root/system/update.go (hunk 1 above)
Comment (leecalcote) [reply mesheryctl/internal/cli/root/system/update.go:42]: Let's take note of this in consideration for a future, global `--silent` flag.

Comment (leecalcote) [reply mesheryctl/internal/cli/root/system/update.go:42]: Note that the `system update` command sets precedent with `--skip` flag. Different, but somewhat related in concept.

File: mesheryctl/internal/cli/root/system/logs.go (hunk 2 above)
Comment (leecalcote) [reply mesheryctl/internal/cli/root/system/logs.go:49]: Right. If the user wants to see Meshery logs and there is no docker-compose file, then we should invoke a central function that does something like:

1. Inform the user of the missing deployment file.
2. Ask if they would like mesheryctl to retrieve a new deployment file (or...)
3. Ask if they would like mesheryctl to generate a new deployment file (assuming that mesheryctl has this ability at some point).

File: mesheryctl/internal/cli/root/system/update.go (hunk 1 above)
Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/update.go:42]: Got it. @leecalcote but how should we handle it now? When the user runs `system update`, it will call the `reset()` function which will ask for confirmation from the user. If the user responds "no", the `system update` command would not consider it and still continue with the update process. This should be changed.

Comment (leecalcote) [reply mesheryctl/internal/cli/root/system/update.go:42]: Currently, (in the released versions), `mesheryctl system update` does not call `reset()`. I haven't read through this whole issue. Is there a need to change this behavior?

Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/update.go:42]: It resets first and then proceeds to update doesn't it. We do not need to change this... The issue is that since we added a user confirmation in the reset function, we need to also add handling for it in the update command.

File: mesheryctl/internal/cli/root/system/start.go [hunk 3]
```diff
@@ -194,11 +194,9 @@ func start() error {
...
 	case "docker":
 
-		if _, err := os.Stat(utils.MesheryFolder); os.IsNotExist(err) {
-			// download the docker-compose.yaml file corresponding to the current version
-			if _, err := utils.DownloadDockerComposeFile(currCtx, true); err != nil {
-				return errors.Wrapf(err, utils.SystemError(fmt.Sprintf("failed to download %s file", utils.DockerComposeFile)))
-			}
+		// download the docker-compose.yaml file corresponding to the current version
+		if _, err := utils.DownloadDockerComposeFile(currCtx, true); err != nil {
+			return errors.Wrapf(err, utils.SystemError(fmt.Sprintf("failed to download %s file", utils.DockerComposeFile)))
```
Comment (aneeshnema) [inline mesheryctl/internal/cli/root/system/start.go:199]: This update was done to ensure the correct version of the docker-compose file is downloaded based on context.
For example:
suppose I already have a file `meshery.yaml` that was downloaded when my context used `channel: edge`,
now I change my context such that it uses `channel: stable` . 
There is no indicator in `meshery.yaml`  that can identify the version of the file.

If this is acceptable, then we can also remove `ValidateComposeFileForRecreation` function as it becomes redundant.

@anirudhjain75 @navendu-pottekkat

Comment (anirudhjain75) [reply mesheryctl/internal/cli/root/system/start.go:199]: So the meshery.yaml is to be fetched only when there is a change in version. The reasonable way would be to compare the latest releasr version and see it there is a change... The compose is to be built using context, a function can be created so as to update the meshery.yaml based off on context

**Comment by leecalcote** [comment]
@aneeshnema is this PR ready for review? It is currently marked as Draft.

File: mesheryctl/internal/cli/root/system/start.go (hunk 3 above)
Comment (leecalcote) [reply mesheryctl/internal/cli/root/system/start.go:199]: Is this an optimization that can be addressed later?

**Comment by navendu-pottekkat** [comment]
@leecalcote 

@aneeshnema and I will discuss with @anirudhjain75 on this on a call tomorrow and we would hopefully be able to clear things up and @aneeshnema will probably be able to get it done tomorrow itself. There is just some confusion about refactoring things.

**Comment by aneeshnema** [comment]
@leecalcote no, there are few more changes requires as per suggestions above. I was busy travelling/shifting back to my college campus so couldn't work on the PR. Will update tomorrow.

**Comment by leecalcote** [comment]
What?! In-person schooling? So fancy. What a refreshing change, I'm sure.

**Review by navendu-pottekkat — APPROVED** [review]
@aneeshnema Looks good to me! 

Great work with the refactoring. It may be best if we test it a bit more since we have made a few changes and make sure that nothing is breaking.

So `mesheryctl` is fully context supported?

**Comment by aneeshnema** [comment]
@navendu-pottekkat yes, mesheryctl is fully context supported now (for docker platform). I have tried all the commands on my local machine, everything seems to work fine.  Still, do test out yourself, just in case.

File: mesheryctl/internal/cli/root/system/reset.go [hunk 4]
```diff
@@ -30,35 +30,37 @@ var resetCmd = &cobra.Command{
...
+		if !userResponse {
+			log.Info("Reset aborted.")
+			return nil
 		}
+	}
 
-		log.Printf("Current Context: %s", currCtxName)
-		log.Printf("Channel: %s", currCtx.Channel)
-		log.Printf("Version: %s\n", currVersion)
+	currCtxName, currCtx, err := utils.GetCurrentContext(tempContext)
```
Comment (anirudhjain75) [inline mesheryctl/internal/cli/root/system/reset.go:48]: Why are you still using a seperate function for getting current context ?... You should create / modify new function in config.go

File: mesheryctl/internal/cli/root/system/start.go [hunk 5]
```diff
@@ -175,30 +150,22 @@ func start() error {
...
-	// Get viper instance used for context
-	mctlCfg, err := config.GetMesheryCtl(viper.GetViper())
-	if err != nil {
-		return errors.Wrap(err, "error processing config")
-	}
-
 	// get the platform, channel and the version of the current context
 	// if a temp context is set using the -c flag, use it as the current context
-	currCtxName, currCtx, err := utils.GetCurrentContext(tempContext)
+	_, currCtx, err := utils.GetCurrentContext(tempContext)
```
Comment (anirudhjain75) [inline mesheryctl/internal/cli/root/system/start.go:155]: same here

File: mesheryctl/internal/cli/root/system/start.go [hunk 6]
```diff
@@ -175,30 +150,22 @@ func start() error {
...
 	switch currPlatform {
 	case "docker":
 
-		if _, err := os.Stat(utils.MesheryFolder); os.IsNotExist(err) {
-			// download the docker-compose.yaml file corresponding to the current version
-			if _, err := utils.DownloadDockerComposeFile(currCtx, true); err != nil {
-				return errors.Wrapf(err, utils.SystemError(fmt.Sprintf("failed to download %s file", utils.DockerComposeFile)))
-			}
+		// download the docker-compose.yaml file corresponding to the current version
+		if err := utils.DownloadDockerComposeFile(currCtx, true); err != nil {
```
Comment (anirudhjain75) [inline mesheryctl/internal/cli/root/system/start.go:167]: here too

File: mesheryctl/pkg/utils/helpers.go [hunk 7]
```diff
@@ -715,33 +715,41 @@ func GetCurrentContext(tempCtxName string) (string, config.Context, error) {
...
 		return "", config.Context{}, errors.New("context does not exist")
 	}
+	if currCtx.Version == "" {
+		// if no version is specified, pick latest imgaes based on channel
+		if currCtx.Channel == "edge" {
+			// if channel is edge, pick the edge-latest images
+			currCtx.Version = "latest"
+		} else if currCtx.Channel == "stable" {
+			// if the channel is stable, pick the version of the latest stable release
+			currCtx.Version, err = GetLatestStableReleaseTag()
```
Comment (anirudhjain75) [inline mesheryctl/pkg/utils/helpers.go:725]: this can be put inside compose.go as a function of struct

**Review by anirudhjain75 — CHANGES_REQUESTED** [review]
Here are the comments I can make after looking into the changes... Do address these, @navendu-pottekkat @leecalcote do let me know if these suggestions are wrong. I'm trying to keep functionality of compose and context in their respective class objects.

**Comment by anirudhjain75** [comment]
Thanks for refractoring @aneeshnema :).

**Comment by navendu-pottekkat** [comment]
@anirudhjain75 I agree.

Maybe moving the `GetCurrentContext()` function inside `config.go` file and replacing the existing `GetContextContent()` function would work. Or we can make this a separate function in config.go

File: mesheryctl/internal/cli/root/system/reset.go (hunk 4 above)
Comment (aneeshnema) [reply mesheryctl/internal/cli/root/system/reset.go]: moved `GetCurrentContext` to config.go

**Review by navendu-pottekkat — APPROVED** [review]
This looks good. We are fully "context" supported!

File: mesheryctl/internal/cli/root/config/config.go [hunk 8]
```diff
@@ -88,3 +96,69 @@ func (v *Version) GetBuild() string {
...
+			}
+		} else {
+			return errors.Errorf("unknown channel %s", ctx.Channel)
+		}
+	}
+	return nil
+}
+
+// GetLatestStableReleaseTag fetches and returns the latest release tag from GitHub
+func GetLatestStableReleaseTag() (string, error) {
```
Comment (anirudhjain75) [inline mesheryctl/internal/cli/root/config/config.go:122]: This should probably be a part of compose.go and part of the docker compose struct

File: mesheryctl/internal/cli/root/config/config.go [hunk 9]
```diff
@@ -88,3 +96,69 @@ func (v *Version) GetBuild() string {
...
+	if err := json.Unmarshal(body, &dat); err != nil {
+		return "", errors.Wrap(err, "failed to unmarshal json into object")
+	}
+
+	return dat["tag_name"].(string), nil
+}
+
+// GetCurrentContext returns the current context name and context struct.
+// If the user mentions a temporary context(tempCtxName) with -c flag, change the current-context and proceed to temporary-context
+func GetCurrentContext(tempCtxName string) (string, Context, error) {
```
Comment (anirudhjain75) [inline mesheryctl/internal/cli/root/config/config.go:144]: This should be a part of context struct

Comment (aneeshnema) [reply mesheryctl/internal/cli/root/config/config.go:144]: It cannot be part of the context struct because that would be a paradox. The function is there to return context(i.e. the user using it does not have access to context)
it can be part of `MesheryCtlConfig`, but then we will have to create `mctlCfg` everywhere and handle its error. Then we will also have to call the member function and handle its error too. All this will be added everywhere where the only purpose is to get context.

File: mesheryctl/internal/cli/root/config/config.go (hunk 8 above)
Comment (aneeshnema) [reply mesheryctl/internal/cli/root/config/config.go:122]: `GetLatestStableReleaseTag` is used to get the latest release tag of meshery, which is used in creating the docker-compose file. This tag is not directly linked with docker-compose. In future, it will also be used for Kubernetes platform to fetch correct manifest files based on version.

Moving only `GetLatestStableReleaseTag` to `helpers.go` will create cyclic dependency.

**Review by anirudhjain75 — APPROVED** [review]

**Comment by anirudhjain75** [comment]
LGTM

File: mesheryctl/internal/cli/root/system/update.go [hunk 10]
```diff
@@ -40,13 +37,12 @@ var updateCmd = &cobra.Command{
 		return utils.PreReqCheck(cmd.Use, "")
 	},
 	RunE: func(cmd *cobra.Command, args []string) error {
-
-		if _, err := os.Stat(utils.DockerComposeFile); os.IsNotExist(err) {
-			if err := utils.DownloadFile(utils.DockerComposeFile, fileURL); err != nil {
-				return errors.Wrapf(err, utils.SystemError(fmt.Sprintf("failed to download %s file from %s", utils.DockerComposeFile, fileURL)))
-			}
+		userResponse := utils.AskForConfirmation("Meshery container images are going to be updated. Are you sure you want to continue")
```
Comment (leecalcote) [inline mesheryctl/internal/cli/root/system/update.go:40]: This is desired behavior only if users are also notified that they are running an old version and asked to update. Otherwise, we have intentionally set the behavior here to autoupdate to ensure that users are always using the latest and greatest.

A subscription to a release channel is .... just that - a _subscription_. If they are on `stable-latest`, then they should receive _latest_. Unless the user has pinned their version in their meshconfig, autoupdates should be happening under their subscription.

**Review by leecalcote — CHANGES_REQUESTED** [review]

File: mesheryctl/internal/cli/root/system/update.go (hunk 10 above)
Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/update.go:40]: i.e for implementing this, 

if the user is on the stable-latest channel, if they run `mesheryctl system update`, it should just go and update without asking the user for confirmation.

If the user is on a specific version, then we should ask for confirmation.

Is that the case?

Comment (leecalcote) [reply mesheryctl/internal/cli/root/system/update.go:40]: Perfect, yes.

Comment (leecalcote) [reply mesheryctl/internal/cli/root/system/update.go:40]: We may get feedback in the future that asking the user to update when they have intentionally pinned to a specific version is not ideal. Let's wait for people to give that feedback, though.

Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/update.go:40]: Yep. @aneeshnema could you please check this out?

Comment (aneeshnema) [reply mesheryctl/internal/cli/root/system/update.go]: fixed ✔

**Review by leecalcote — APPROVED** [review]
Good work!
