### PR TITLE
Fix Console error in Meshery cloud 

### LINKED ISSUE #9030: Fix: The console log error
### Current Behavior
For every request in meshery cloud prints the `prevProps.k8sConfig ` object

### Screenshots/Logs
image

### Environment
- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by coder12git**
**Notes for Reviewers**

This PR fixes #9030

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by coder12git** [comment]
cc @aabidsofi19

File: ui/pages/_app.js [hunk 1]
```diff
@@ -219,7 +219,7 @@ class MesheryApp extends App {
     if (isMesheryUiRestrictedAndThePageIsNotPlayground(capabilitiesRegistry)) {
       Router.push(mesheryExtensionRoute);
     }
-    console.log('prevProps.k8sConfig', prevProps.k8sConfig, 'k8sConfig', k8sConfig);
+    // console.log('prevProps.k8sConfig', prevProps.k8sConfig, 'k8sConfig', k8sConfig);
```
Comment (aabidsofi19) [inline ui/pages/_app.js:222]:
```suggestion
    /
```

**Comment by leecalcote** [comment]
@aabidsofi19 I placed a `pr/hold` label on this pull request, because hiding these logs is not necessarily desirous. These logs, while unwanted, serve as indicator of an underlying issue that needs to be addressed at source in Meshery Server.

If the underlying issue hasn't been addressed, I'm hesitant to have this indicator muted.
