### PR TITLE
[mesheryctl]Attempt to start docker daemon during mesheryctl installation

### LINKED ISSUE #1677: [mesheryctl] installation throws an exception if docker daemon is not running
**Description**
`mesheryctl system start` needs to be re-attempted if docker-compose fails for any reason.

**Expected Behavior**
if `mesheryctl system start` fails to start due to docker not running on the system,
throw an informational message to the users to start docker and then re-attempt 
`mesheryctl system start`

**Screenshots**

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**
1. Stop docker daemon
2. Run curl -L https://git.io/meshery | bash -

[Optional] **Additional Context**

### PR DESCRIPTION
**Pull request by hexxdump**
Attempt to start docker daemon during mesheryctl installation

`mesheryctl system start` throws an exception, if docker daemon is not running
try to start docker and if it fails, throw appropriate informational message

Signed-off-by: Hussaina Begum Nandyala <hexxdump@gmail.com>

**Description**
Attempt to start docker daemon during mesheryctl installation

This PR fixes #1677 

**Notes for Reviewers**
Also for MacOS, I used a default path to start the Docker daemon and introduced a wait timer.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by hexxdump** [comment]
@Nikhil-Ladha @NupurThakur27 pls review
I tried to add the code to read user input, but its failing:

    var resp string 
    fmt.Printf("Do you want to start docker daemon?(y/n): ")
    _, err := fmt.Scan(&resp)
    fmt.Printf("Response read:%s, err: %v\n", resp, err)
    if err != nil {
       log.Info("Run `masheryctl system start` once docker is started.")
       return nil
    }
    resp = strings.TrimSpace(resp)
    resp = strings.ToLower(resp)
    if resp == "n" || resp == "no" {
		log.Info("Run `masheryctl system start` once docker is started.")
		return nil
   }

File: mesheryctl/pkg/utils/helpers.go [hunk 1]
```diff
@@ -158,18 +158,55 @@ func SetFileLocation() error {
 
 //PreReqCheck prerequisites check
 func PreReqCheck() error {
+	//Check whether docker daemon is running or not
+	if err := exec.Command("docker", "ps").Run(); err != nil {
+		log.Info("Docker daemon is not running")
+		//No auto installation of docker for windows
+		if runtime.GOOS == "windows" {
+			return errors.Wrap(err, "please start docker daemon. Run `masheryctl system start` once docker is started.")
```
Comment (Nikhil-Ladha) [inline mesheryctl/pkg/utils/helpers.go:166]: Capitalisation should be taken care of. Also it's `mesheryctl`.
Please make the changes in othe areas too.

File: mesheryctl/pkg/utils/helpers.go [hunk 2]
```diff
@@ -158,18 +158,55 @@ func SetFileLocation() error {
...
 		if err != nil {
-			return errors.Wrap(err, "failed to install prerequisites")
+			return errors.Wrap(err, "failed to install prerequisites. Run `masheryctl system start` once docker-compose is installed.")
+		}
+	}
+	return nil
+}
+
+func startdockerdaemon() error {
+	log.Info("Attempting to start docker daemon")
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/helpers.go:189]:
```suggestion
	log.Info("Attempting to start Docker daemon")
```

File: mesheryctl/pkg/utils/helpers.go [hunk 3]
```diff
@@ -158,18 +158,55 @@ func SetFileLocation() error {
...
+	// TODO: read user input on whether to start docker or not.
+	// once user gaves permission, start docker daemon on linux/macOS
+	if runtime.GOOS == "linux" {
+		if err := exec.Command("service", "docker", "start").Run(); err != nil {
+			return errors.Wrap(err, "Please start docker then run the command `mesheryctl system start` to start mesheryctl")
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/helpers.go:194]:
```suggestion
			return errors.Wrap(err, "Please start Docker, then run the command `mesheryctl system start` to start Meshery.")
```

File: mesheryctl/pkg/utils/helpers.go [hunk 4]
```diff
@@ -158,18 +158,55 @@ func SetFileLocation() error {
...
+			return errors.Wrap(err, "failed to start docker daemon. Run `masheryctl system start` once docker is started.")
+		}
+	}
 	//Check for installed docker-compose on client system
 	if err := exec.Command("docker-compose", "-v").Run(); err != nil {
 		log.Info("Docker-Compose is not installed")
 		//No auto installation of Docker-compose for windows
 		if runtime.GOOS == "windows" {
-			return errors.Wrap(err, "please install docker-compose")
+			return errors.Wrap(err, "please install docker-compose. Run `masheryctl system start` once docker-compose is installed.")
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/helpers.go:178]:
```suggestion
			return errors.Wrap(err, "Please install docker-compose. Run `mesheryctl system start` after docker-compose is installed.")
```

File: mesheryctl/pkg/utils/helpers.go [hunk 5]
```diff
@@ -158,18 +158,55 @@ func SetFileLocation() error {
...
 		}
 		err = installprereq()
 		if err != nil {
-			return errors.Wrap(err, "failed to install prerequisites")
+			return errors.Wrap(err, "failed to install prerequisites. Run `masheryctl system start` once docker-compose is installed.")
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/helpers.go:182]:
```suggestion
			return errors.Wrap(err, "Failed to install prerequisites. Run `mesheryctl system start` after docker-compose is installed.")
```

File: mesheryctl/pkg/utils/helpers.go [hunk 6]
```diff
@@ -158,18 +158,55 @@ func SetFileLocation() error {
...
+	if runtime.GOOS == "linux" {
+		if err := exec.Command("service", "docker", "start").Run(); err != nil {
+			return errors.Wrap(err, "Please start docker then run the command `mesheryctl system start` to start mesheryctl")
+		}
+	} else {
+		// Assuming we are on macOS, try to start Docker from default path
+		cmd := exec.Command("/Applications/Docker.app/Contents/MacOS/Docker")
+		err := cmd.Start()
+		if err != nil {
+			return errors.Wrap(err, "Please start docker then run the command `mesheryctl system start` to start mesheryctl")
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/helpers.go:201]:
```suggestion
			return errors.Wrap(err, "Please start Docker, then run the command `mesheryctl system start` to start Meshery.")
```

File: mesheryctl/pkg/utils/helpers.go [hunk 7]
```diff
@@ -158,18 +158,55 @@ func SetFileLocation() error {
...
+		}
+		// wait for few seconds for docker to start
+		err = exec.Command("sleep", "20").Run()
+		if err != nil {
+			return errors.Wrap(err, "Please start docker then run the command `mesheryctl system start` to start mesheryctl")
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/helpers.go:206]:
```suggestion
			return errors.Wrap(err, "Please start Docker, then run the command `mesheryctl system start` to start Meshery.")
```

File: mesheryctl/pkg/utils/helpers.go (hunk 1 above)
Comment (leecalcote) [inline mesheryctl/pkg/utils/helpers.go:166]:
```suggestion
			return errors.Wrap(err, "Please start Docker daemon. Run `mesheryctl system start` after Docker is started.")
```

File: mesheryctl/pkg/utils/helpers.go [hunk 8]
```diff
@@ -158,18 +158,55 @@ func SetFileLocation() error {
...
+	//Check whether docker daemon is running or not
+	if err := exec.Command("docker", "ps").Run(); err != nil {
+		log.Info("Docker daemon is not running")
+		//No auto installation of docker for windows
+		if runtime.GOOS == "windows" {
+			return errors.Wrap(err, "please start docker daemon. Run `masheryctl system start` once docker is started.")
+		}
+		err = startdockerdaemon()
+		if err != nil {
+			return errors.Wrap(err, "failed to start docker daemon. Run `masheryctl system start` once docker is started.")
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/helpers.go:170]:
```suggestion
			return errors.Wrap(err, "Failed to start Docker daemon. Run `mesheryctl system start` after Docker is started.")
```

File: mesheryctl/pkg/utils/helpers.go [hunk 9]
```diff
@@ -158,18 +158,55 @@ func SetFileLocation() error {
...
+		}
+	} else {
+		// Assuming we are on macOS, try to start Docker from default path
+		cmd := exec.Command("/Applications/Docker.app/Contents/MacOS/Docker")
+		err := cmd.Start()
+		if err != nil {
+			return errors.Wrap(err, "Please start docker then run the command `mesheryctl system start` to start mesheryctl")
+		}
+		// wait for few seconds for docker to start
+		err = exec.Command("sleep", "20").Run()
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/helpers.go:204]: I'm not sure if there's a more clever way to detect if the Docker daemon is running other than sleeping. If there is and it's easy to implement, that might be nice. If not, no problem.

**Review by leecalcote — COMMENTED** [review]
Thank you, @hexxdump. Good stuff in here. 👍

**Comment by hexxdump** [comment]
Hi @leecalcote @Nikhil-Ladha 

I tried to capitalize some errors, however i got a lint error as below:
  Error: error strings should not be capitalized or end with punctuation or a newline (golint)

File: mesheryctl/pkg/utils/helpers.go (hunk 9 above)
Comment (NupurThakur27) [reply mesheryctl/pkg/utils/helpers.go:204]: `systemctl is-active docker` this command works in Linux, @hexxdump You can use this in macOS and if the status is active you can proceed. Again I am not sure if it is efficient., Feel free to choose which way is more efficient according to you.

Comment (hexxdump) [reply mesheryctl/pkg/utils/helpers.go:204]: @NupurThakur27 I already checked, If i could use "systemctl start docker" for both linux and MacOS. However, systemctl is not available on MacOS. Hence I had to write different logic for each OS. 
I did not like the idea of the sleep command myself, but since its the install flow, I thought the sleep statement(delay) could be justifiable.

Comment (NupurThakur27) [reply mesheryctl/pkg/utils/helpers.go:204]: Okay @hexxdump, Then it makes sense.

**Comment by leecalcote** [comment]
> Hi @leecalcote @Nikhil-Ladha
> 
> I tried to capitalize some errors, however i got a lint error as below:
> Error: error strings should not be capitalized or end with punctuation or a newline (golint)

Ugh. I don't like that lint rule. The rule encourages poor English. :/ 

@kushthedude is this a rule that we can change or ignore?

**Comment by kushthedude** [comment]
Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation, since they are usually printed following other context. That is, use fmt.Errorf("something bad") not fmt.Errorf("Something bad"), so that log.Printf("Reading %s: %v", filename, err) formats without a spurious capital letter mid-message. This does not apply to logging, which is implicitly line-oriented and not combined inside other messages.

@leecalcote

File: mesheryctl/pkg/utils/helpers.go [hunk 10]
```diff
@@ -158,18 +158,55 @@ func SetFileLocation() error {
...
+	}
+	return nil
+}
+
+func startdockerdaemon() error {
+	log.Info("Attempting to start Docker daemon")
+	// TODO: read user input on whether to start docker or not.
+	// once user gaves permission, start docker daemon on linux/macOS
+	if runtime.GOOS == "linux" {
+		if err := exec.Command("service", "docker", "start").Run(); err != nil {
```
Comment (sladyn98) [inline mesheryctl/pkg/utils/helpers.go:193]: Minor Question: What if the user is not added to the sudoers group or the docker group

File: mesheryctl/pkg/utils/helpers.go [hunk 11]
```diff
@@ -158,18 +158,55 @@ func SetFileLocation() error {
...
-			return errors.Wrap(err, "failed to install prerequisites")
+			return errors.Wrap(err, "failed to install prerequisites. Run `mesheryctl system start` after docker-compose is installed.")
+		}
+	}
+	return nil
+}
+
+func startdockerdaemon() error {
+	log.Info("Attempting to start Docker daemon")
+	// TODO: read user input on whether to start docker or not.
```
Comment (sladyn98) [inline mesheryctl/pkg/utils/helpers.go:190]: We might want to consider running it as sudo

File: mesheryctl/pkg/utils/helpers.go [hunk 12]
```diff
@@ -158,18 +158,55 @@ func SetFileLocation() error {
...
+	// once user gaves permission, start docker daemon on linux/macOS
+	if runtime.GOOS == "linux" {
+		if err := exec.Command("service", "docker", "start").Run(); err != nil {
+			return errors.Wrap(err, "please start Docker then run the command `mesheryctl system start` to start Meshery")
+		}
+	} else {
+		// Assuming we are on macOS, try to start Docker from default path
+		cmd := exec.Command("/Applications/Docker.app/Contents/MacOS/Docker")
```
Comment (sladyn98) [inline mesheryctl/pkg/utils/helpers.go:198]: Minor Question: If docker is not in this path could we get the path from the user ? or run a sort of which to find it

File: mesheryctl/pkg/utils/helpers.go (hunk 9 above)
Comment (sladyn98) [reply mesheryctl/pkg/utils/helpers.go:204]: Looks good to me. Question: Could we increase the timeout if it fails to start within this time? And then fail hard if it does not start with the increased timeout ?

**Review by sladyn98 — COMMENTED** [review]
Just some minor suggestions

**Comment by leecalcote** [comment]
> > Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation, since they are usually printed following other context. That is, use fmt.Errorf("something bad") not fmt.Errorf("Something bad"), so that log.Printf("Reading %s: %v", filename, err) formats without a spurious capital letter mid-message. This does not apply to logging, which is implicitly line-oriented and not combined inside other messages.
> 
> @leecalcote

Thank you for this explanation, @kushthedude. I wasn't aware of this reasoning. This logic makes sense now and so does the lint check given this context. ✅

**Comment by leecalcote** [comment]
> Hi @leecalcote @Nikhil-Ladha
> 
> I tried to capitalize some errors, however i got a lint error as below:
> Error: error strings should not be capitalized or end with punctuation or a newline (golint)

Thanks for attempting this, @hexxdump. I understand better now why the linter enforces lowercase to start these error messages. I have resolved these comments. Please continue. 😄

File: mesheryctl/pkg/utils/helpers.go (hunk 11 above)
Comment (hexxdump) [reply mesheryctl/pkg/utils/helpers.go:190]: done

File: mesheryctl/pkg/utils/helpers.go (hunk 10 above)
Comment (hexxdump) [reply mesheryctl/pkg/utils/helpers.go]: This is best effort attempt, if the command fails to start docker, user will see the informational message to reattempt "mesheryctl system start" once docker is started.

File: mesheryctl/pkg/utils/helpers.go (hunk 12 above)
Comment (hexxdump) [reply mesheryctl/pkg/utils/helpers.go:198]: This is best effort attempt, if the command fails to find Docker application in the given path, user will see the informational message to reattempt "mesheryctl system start" once docker is started. I have also added a check to see if docker daemon gets started after the sleep time, if not, an info message is displayed to user.

**Comment by leecalcote** [comment]
@hexxdump you're ears were burning on today's Meshery Development call (we were talking about your good work here).

**Review by leecalcote — APPROVED** [review]
Good work, @hexxdump!! 😄

**Comment by leecalcote** [comment]
@hexxdump part of today's discussion was a suggestion that in the event that Docker isn't running in the user's system, that instead of attempting to automatically start Docker, that `mesheryctl` first prompt the user with a message like:

```
Unable to start Meshery. Docker not available. Would you like to start Docker now? [y/n]
```

What do you think? Is this a better user experience? If so, should an issue be created to follow up here?

**Comment by hexxdump** [comment]
> @hexxdump part of today's discussion was a suggestion that in the event that Docker isn't running in the user's system, that instead of attempting to automatically start Docker, that `mesheryctl` first prompt the user with a message like:
> 
> ```
> Unable to start Meshery. Docker not available. Would you like to start Docker now? [y/n]
> ```
> 
> What do you think? Is this a better user experience? If so, should an issue be created to follow up here?

Yes @leecalcote. Myself and @Nikhil-Ladha discussed this already. I tried to add the below code snippet as well:
var resp string 
fmt.Printf("Do you want to start docker daemon?(y/n): ")
_, err := fmt.Scan(&resp)
fmt.Printf("Response read:%s, err: %v\n", resp, err)
if err != nil {
   log.Info("Run `masheryctl system start` once docker is started.")
   return nil
}
resp = strings.TrimSpace(resp)
resp = strings.ToLower(resp)
if resp == "n" || resp == "no" {
	log.Info("Run `masheryctl system start` once docker is started.")
	return nil
}
For some reason the script is not waiting for the user input. I might need to try a different input functions to read the user consent before attempting to start docker daemon.
I have left a TODO comment in the code, need to handle it eventually.

**Comment by hexxdump** [comment]
> @hexxdump your ears were burning on today's Meshery Development call (we were talking about your good work here).

I could not join yesterday's meeting due to a conflict. Thanks to the team for being so helping and forthcoming. I am happy to be learning about Meshery and contributing to it.
