### PR TITLE
fix: go-releaser for mesheryctl & model rename

### LINKED ISSUE #915: mesheryctl: Build & Release process failing

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #915
/cc @leecalcote

### CODE REVIEW

File: models/handlers.go [hunk 1]
```diff
@@ -5,7 +5,7 @@ import (
 
 	"time"
 
-	"github.com/vmihailenco/taskq"
+	"github.com/vmihailenco/taskq/v3"
```
Comment (leecalcote) [inline models/handlers.go:8]: Fingers crossed.

**Comment by leecalcote** [comment]
I almost hope that the issue doesn't get fixed for a few more attempts. I'm getting a good chuckle out of @kushthedude's commit messages.

**Comment by kushthedude** [comment]
> I almost hope that the issue doesn't get fixed for a few more attempts. I'm getting a good chuckle out of @kushthedude's commit messages.

I will squash this commit 😆

File: models/handlers.go (hunk 1 above)
Comment (kushthedude) [reply models/handlers.go:8]: Not working! But this could be due to the deprecations as we have been using a much older version of taskq and we have jumped with over 3 major version with this commit.

Comment (nveenjain) [reply models/handlers.go:8]: @kushthedude , try `go get -u github.com/vmihailenco/taskq/v3@master` since this issue was fixed recently only....

File: go.mod [hunk 2]
```diff
@@ -29,11 +29,11 @@ require (
 	github.com/spf13/cobra v0.0.7
 	github.com/spf13/viper v1.6.3
 	github.com/vmihailenco/taskq v0.0.0-20190605141845-97870321dc66
+	github.com/vmihailenco/taskq/v3 v3.0.0-beta.8
```
Comment (nveenjain) [inline go.mod:32]: This should be 	github.com/vmihailenco/taskq/v3 v3.0.0-beta.8.0.20200427064301-df0ef147bc92

File: go.sum [hunk 3]
```diff
@@ -284,14 +318,27 @@ github.com/valyala/gozstd v1.5.0 h1:OI7Z2e+GkvmmdRFiJeyuByhT/WMTLuRLa43Z2Tjzenw=
...
 github.com/vmihailenco/msgpack v4.0.4+incompatible h1:dSLoQfGFAo3F6OoNhwUmLwVgaUXK79GlxNBwueZn0xI=
 github.com/vmihailenco/msgpack v4.0.4+incompatible/go.mod h1:fy3FlTQTDXWkZ7Bh6AcGMlsjHatGryHQYUTf1ShIgkk=
+github.com/vmihailenco/msgpack/v4 v4.3.11/go.mod h1:gborTTJjAo/GWTqqRjrLCn9pgNN+NXzzngzBKDPIqw4=
+github.com/vmihailenco/msgpack/v5 v5.0.0-alpha.2 h1:0jVpYJSRJzGY7m21n9V5uIkl7Zre64W8DR1dxEKX2g4=
+github.com/vmihailenco/msgpack/v5 v5.0.0-alpha.2/go.mod h1:LDfrk4wJpSFwkzNOJxrCWiSm8c7Iqw/hXNPT2fzQfE8=
+github.com/vmihailenco/tagparser v0.1.1 h1:quXMXlA39OCbd2wAdTsGDlK9RkOk6Wuw+x37wVyIuWY=
+github.com/vmihailenco/tagparser v0.1.1/go.mod h1:OeAg3pn3UbLjkWt+rN9oFYB6u/cQgqMEUPoW2WPyhdI=
 github.com/vmihailenco/taskq v0.0.0-20190605141845-97870321dc66 h1:Uv192emHCMz+O0efMuFzde+Dge20xgHc08q284sS60w=
 github.com/vmihailenco/taskq v0.0.0-20190605141845-97870321dc66/go.mod h1:PjbIiqJ7OY4C2p1QJ8/wVZpgvyYT4M8t9cU2CT1583s=
+github.com/vmihailenco/taskq/v3 v3.0.0-beta.8 h1:t8VOLOmQqOEwWyFwoEz1mHHHYdlFLQU550UK44tat7I=
```
Comment (nveenjain) [inline go.sum:328]: This should be
```
github.com/vmihailenco/taskq/v3 v3.0.0-beta.8.0.20200427064301-df0ef147bc92 h1:Tny1Sf97Rz4UFEFzer9Lp2opp87K9M6irGcwdAJMxiY=
github.com/vmihailenco/taskq/v3 v3.0.0-beta.8.0.20200427064301-df0ef147bc92/go.mod h1:g6lXPgzn6WehOtLeYkPZjWizPu9g8m4r87yVeONWJdE=
```

**Comment by nveenjain** [comment]
Also you can test the changes locally by executing 
```bash
goreleaser --snapshot --skip-publish --rm-dist
```

File: models/handlers.go (hunk 1 above)
Comment (nveenjain) [reply models/handlers.go:8]: > this could be due to the deprecations as we have been using a much older version of taskq and we have jumped with over 3 major version with this commit.

That is the reason why static lint is failing.

File: go.mod (hunk 2 above)
Comment (kushthedude) [reply go.mod:32]: This change is already present in beta.8 .

File: models/handlers.go (hunk 1 above)
Comment (kushthedude) [reply models/handlers.go:8]: > @kushthedude , try `go get -u github.com/vmihailenco/taskq/v3@master` since this issue was fixed recently only....

0.8 was released 21 days ago & this was fixed on 27 march.

File: handlers/handler_instance.go [hunk 4]
```diff
@@ -20,7 +20,7 @@ func NewHandlerInstance(
 		config: handlerConfig,
 	}
 
-	h.task = handlerConfig.Queue.NewTask(&taskq.TaskOptions{
+	h.task = handlerConfig.Queue.RegisterTask(&taskq.TaskOptions{
```
Comment (kushthedude) [inline handlers/handler_instance.go:23]: @nveenjain Any help here? I updated it according to new methods, but it seems docs are quite less descriptive.

Comment (nveenjain) [reply handlers/handler_instance.go:23]: looking into it!

Comment (nveenjain) [reply handlers/handler_instance.go:23]: Actually the architecture has changed in v3 @kushthedude, Now what RegisterTask method is present in the `taskq` module itself.
These tasks should be added separately to the queue. (A separate package for this is recommended)
and the queue can be started there... (In worker package/process is recommended)
As mentioned in https://github.com/vmihailenco/taskq#quickstart
detailed example in :- https://github.com/vmihailenco/taskq/tree/master/examples/api_worker

**Comment by kushthedude** [comment]
Finally, Green Ticks are really soothing to my eyes ❤️ . 
Got the bug, now will restore the workflow 🚀

**Comment by leecalcote** [comment]
@kushthedude there is one or more conflict(s) in go.sum. You're in a better position to resolve than I am.

**Comment by leecalcote** [comment]
There's something about green that feels so good here. 
meshery-logo

**Comment by kushthedude** [comment]
> @kushthedude there is one or more conflict(s) in go.sum. You're in a better position to resolve than I am.

Oh don't worry, I will fix it! Also, there are still some pending things over here. Precisely all this work was to check the small bug & change the way we were using taskq & grafana-sdk.


> There's something about green that feels so good here.
> 
> 

When you're green, your growing.

**Comment by kushthedude** [comment]
@leecalcote Welcome back, `Mesheryctl Build & Release` 🎉 🎉 🎉 .
Please review & merge!
