### PR TITLE
[mesheryctl] Validating versions and gracefully handling invalid versions

### LINKED ISSUE #2954: [mesheryctl] `system start` and other commands fail when the version in the meshconfig is not available in GitHub
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Running `mesheryctl system start` with an invalid version(version that was not released or versions that are not yet released) in the `meshconfig` file will fail as these are not available on GitHub.

Screenshot from 2021-05-16 22-37-10

#### Desired Behavior

If the specified version is invalid, `mesheryctl` should convey that to the user and handle the error gracefully.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by metonymic-smokey**
**Description**
This PR uses a Github API call to check for invalid versions when setting the current context from the `meshconfig`.  It gracefully handles the error by displaying that the version is not part of the current release list.

This PR fixes #2954 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by metonymic-smokey** [comment]
Extra commit here since the lint check was failing for 2 separate, unrelated files.  
The file containing the version validation is only `config.go`.

**Comment by leecalcote** [comment]
Ready for review?

**Comment by metonymic-smokey** [comment]
> Ready for review? No pressure. I ask, because people tend to forget to remove "draft" labels and "wip" titles.

yes @leecalcote !

File: mesheryctl/internal/cli/root/config/config.go [hunk 1]
```diff
@@ -81,16 +81,24 @@ func (ctx *Context) ValidateVersion() error {
 		return nil
 	}
 
-	matched, err := regexp.MatchString(`v[0-9]+.[0-9]+.[0-9]+[-a-z0-9]*`, ctx.Version)
-	if err != nil || !matched {
-		return errors.New("invalid version " + ctx.Version + " specified")
+	url := "https://api.github.com/repos/layer5io/meshery/git/trees/" + ctx.Version + "?recursive=1"
```
Comment (leecalcote) [inline mesheryctl/internal/cli/root/config/config.go:84]: We'll want to refer to these constants - https://github.com/layer5io/meshery/blob/57f4e901d19acdc9c2586e04b57001ace67929f2/mesheryctl/pkg/utils/helpers.go#L60-L62

Speaking of these constants, having them in a utils file called "helpers" doesn't seem the most befitting.

File: mesheryctl/internal/cli/root/config/config.go [hunk 2]
```diff
@@ -81,16 +81,24 @@ func (ctx *Context) ValidateVersion() error {
...
+	resp, err := http.Get(url)
+
+	defer func() {
+		if cerr := resp.Body.Close(); cerr != nil {
+			log.Error(cerr)
+		}
+	}()
+
+	if resp.StatusCode == 404 {
+		log.Fatal("version " + ctx.Version + " not in list of releases")
```
Comment (leecalcote) [inline mesheryctl/internal/cli/root/config/config.go:94]:
```suggestion
		log.Fatal("version " + ctx.Version + " is not a valid Meshery release")
```

File: mesheryctl/internal/cli/root/config/config.go (hunk 1 above)
Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/config/config.go:84]: Agreed @leecalcote 
But I'm not sure how to use these constants in `config.go` since that's imported in `pkg/utils` and hence using these(via the getter functions) leads to circular imports.    

I have used these constants in a URL in another function in `platform.go` though.

**Comment by leecalcote** [comment]
Yikes. Now is a great time to create a model, a struct, a something to centralize these constants globally for mesheryctl. Where and how do you suggest we do this?

**Comment by metonymic-smokey** [comment]
> Yikes. Now is a great time to create a model, a struct, a something to centralize these constants globally for mesheryctl. Where and how do you suggest we do this?

I'm not too sure where we could add those constants AND then access them in `config.go`. Do you have any ideas?
// @navendu-pottekkat

**Comment by navendu-pottekkat** [comment]
@leecalcote @metonymic-smokey all such constants are defined in `helpers.go` so let's just stick with that?

**Comment by metonymic-smokey** [comment]
Yes, but I'm not sure how to use them. I'm going wrong somewhere when I try
to import them into config.go using the getter methods :( Do you know any
other way to do this?

**Comment by leecalcote** [comment]
Graceful, schmaceful.

File: mesheryctl/pkg/utils/platform.go [hunk 3]
```diff
@@ -215,7 +215,7 @@ func FetchManifests(version string) ([]Manifest, error) {
 
 // GetLatestStableReleaseTag fetches and returns the latest release tag from GitHub
 func GetLatestStableReleaseTag() (string, error) {
-	url := "https://api.github.com/repos/layer5io/meshery/releases/latest"
+	url := "https://api.github.com/repos/" + mesheryGitHubOrg + "/" + mesheryGitHubRepo + "/releases/latest"
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/platform.go:218]: Very nice.

Comment (metonymic-smokey) [reply mesheryctl/pkg/utils/platform.go:218]: thank you @leecalcote !

**Comment by metonymic-smokey** [comment]
I don't understand why the DCO is failing though I sign my commits locally(and the same is display here when I push too).

**Comment by utkarsh-pro** [comment]
@metonymic-smokey, I think commit: 8299d31 is failing the DCO. Can you try:
`git commit --ammend -s -c  8299d31`
and then force push it.

It should fix the issue.

**Comment by metonymic-smokey** [comment]
Thanks @utkarsh-pro ! This worked for that commit.

**Review by leecalcote — APPROVED** [review]
Quality work, @metonymic-smokey 💪
