### PR TITLE
Generate meshery config dir at mesheryctl init

### LINKED ISSUE #1779: [mesheryctl] mesheryctl fails to run if default meshery config directory is missing
**Description**
`mesheryctl` initialization fails if `~/.meshery` default config directory is not found with error 

```
open /Users/nitish_malhotra/.meshery/mesheryctlConfig.yaml: no such file or directory
Creating and Using defaults config for mesheryctl
open /Users/nitish_malhotra/.meshery/mesheryctlConfig.yaml: no such file or directory
```

**Expected Behavior**
`mesheryctl` initialization should create the default config folder `~/.meshery` if it doesn't exist similar to how this is done when running the `meshery` server for the first time.

**Screenshots**
meshery_installation_issue

**Environment:**
- Host OS: MacOS/Linux/...
- Meshery Version: using both branch/master and https://raw.githubusercontent.com/layer5io/meshery/master/meshery
- Kubernetes Version: N/A
- Browser: N/A

---
[Optional] **To Reproduce**
1. `rm ~/.meshery`
2.  `curl -L https://git.io/meshery | bash -`
or
2. `git clone https://github.com/layer5io/meshery.git`
    `cd meshery`
    `make mesheryctl`
    `./mesheryctl/mesheryctl system start`
[Optional] **Additional Context**
N/A

### PR DESCRIPTION
**Pull request by nitishm**
Signed-off-by: Nitish Malhotra <nitish.malhotra@gmail.com>

**Description**

Generate default meshery config folder at `mesheryctl` invocation, if not exist.
This PR fixes #1779

**Notes for Reviewers**

```
cd mesheryctl
make
./mesheryctl system start
```

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/internal/cli/root/root.go [hunk 1]
```diff
@@ -125,6 +126,12 @@ func initConfig() {
 		viper.SetConfigFile(cfgFile)
 	} else {
 		// Use default ".meshery" folder location.
+		if _, err := os.Stat(utils.MesheryFolder); err != nil {
+			if os.IsNotExist(err) {
+				os.MkdirAll(utils.MesheryFolder, 0775)
+			}
```
Comment (leecalcote) [inline mesheryctl/internal/cli/root/root.go:132]: Looks right. There’s a small lint check item that you might give consideration to.

**Review by leecalcote — APPROVED** [review]

File: mesheryctl/internal/cli/root/root.go (hunk 1 above)
Comment (nitishm) [reply mesheryctl/internal/cli/root/root.go:135]: pushed the lint fix

**Review by leecalcote — APPROVED** [review]
Works well on MacOS. 👍
