### PR TITLE
[UI] Fix unselect all issue for active context

### LINKED ISSUE #11639: [UI] Unable to unselect all in the Kubernetes context menu.
### Current Behavior
In the Meshery Playground, on the Kubernetes context menu, the "Select All" button works perfectly, but the "Unselect" functionality is not working.

### Desired Behavior
Clicking "Select All" should also unselect all items.

### Screenshots/Logs
image

### Environment

- Browser:  Firefox
- Host OS:  Linux
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by amitamrutiya**
**Notes for Reviewers**

This PR fixes #11639

[Screencast from 2024-08-19 10-54-00.webm](https://github.com/user-attachments/assets/b93fe7f9-96a0-444c-8740-50db375aec96)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ashparshp** [comment]
@amitamrutiya, let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

File: ui/pages/_app.js [hunk 1]
```diff
@@ -429,6 +429,14 @@ class MesheryApp extends App {
         return;
       }
 
+      // if id is an empty array, clear all active contexts
```
Comment (leecalcote) [inline ui/pages/_app.js:432]: Thank you for including this comment, @amitamrutiya

**Review by leecalcote — APPROVED** [review]
LGTM
