### PR TITLE
fixed the filter-dropdown component

### LINKED ISSUE #9019: [UI] Data Table: Misbehaving filter option
### Current Behavior
[Screencast from 2023-10-04 20-08-02.webm](https://github.com/meshery/meshery/assets/59491379/bc902d50-f736-4e1b-979b-15c9ef7271d1)

### Desired Behavior
All filter options should be able to be clicked at all time 

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by captain-Akshay**
**Notes for Reviewers**

This PR fixes #9019
this fix is a simple fix make the dropdown component index to be higher the header component of the table
as the header component z-index is 110 i used 150 to be on the top.
This fixed both the issue :-
- the white band over the dropdown menu
- making the check button unclickable 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by captain-Akshay** [comment]
@saurabh100ni would love to hear some feedback!

**Comment by sudhanshutech** [comment]
@captain-Akshay can you provide any recording or screenshot

**Comment by captain-Akshay** [comment]
Sure! here:-

[Screencast from 2023-10-04 22-28-00.webm](https://github.com/meshery/meshery/assets/59491379/e312df35-3f43-4e84-8f17-79cb8379512e)

**Comment by sudhanshutech** [comment]
@captain-Akshay there is small issue here, you made the drop-down above to toolbar, it need to slided behind the toolbar

**Comment by captain-Akshay** [comment]
oh right i will get back to you!

**Comment by captain-Akshay** [comment]
@sudhanshutech 
i think it's fixed now!

[Screencast from 2023-10-05 00-28-19.webm](https://github.com/meshery/meshery/assets/59491379/e38b55a5-c84d-4cb0-bf23-f74a573a677e)

**Comment by leecalcote** [comment]
The behavior in the video looks great.

That Designs icon needs help.

**Review by leecalcote — DISMISSED** [review]

File: ui/components/MesheryPatterns.js [hunk 1]
```diff
@@ -1478,7 +1478,7 @@ function MesheryPatterns({
             pattern={selectedPattern.pattern}
           />
         )}
-        <div className={StyleClass.toolWrapper}>
+        <div className={StyleClass.toolWrapper} style={{ zIndex: 125 }}>
```
Comment (sudhanshutech) [inline ui/components/MesheryPatterns.js:1481]: @captain-Akshay you need to pass this style to root component of toolWrapper where its defined because this change will have effect on only pattern section not others

**Review by sudhanshutech — CHANGES_REQUESTED** [review]

**Comment by sudhanshutech** [comment]
> The behavior in the video looks great.
> 
> That Designs icon needs help.

That was fixed
