### PR TITLE
fix(docs): update file paths in tests to use temporary directories

### LINKED ISSUE #18439: [mesheryctl] Stop generating docs/content/en/reference/mesheryctl/test.md
### Description

Stop generating `docs/content/en/reference/mesheryctl/test.md` and `mesheryctl/doc/cmds.yml`

I keep getting these two files generated and included in my PRs.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- ⌨️ [Meshkit errors Guide](https://docs.meshery.io/project/contributing/contributing-error)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)
- 📺 [Self-paced Contributor Trainings](https://meshery.io/talks-and-trainings#trainings)

### PR DESCRIPTION
**Pull request by lekaf974**
Signed-off-by: lekaf974 <matthieu.evrin@gmail.com>

**Notes for Reviewers**

- This PR fixes #18439

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/doc/doc.go [hunk 1]
```diff
@@ -386,6 +386,13 @@ func GenYamlTreeCustom(cmd *cobra.Command, dir string, filePrepender, linkHandle
 	basename := "cmds.yml"
 	filename := filepath.Join(dir, basename)
 	f, err := os.OpenFile(filename, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
+	defer func() {
```
Comment (arjunmehta-git) [inline mesheryctl/doc/doc.go:389]: 👍

**Comment by alexquincy** [comment]
this is nice. 😄

**Comment by Omkar-Ugal** [comment]
LGTM! 🚀

**Comment by alexquincy** [comment]
What about the auto-generation of the rest of the files that are created when `make docs-mesheryctl` is run?

**Comment by alexquincy** [comment]
When are those files automatically created?

**Comment by alexquincy** [comment]
Which workflow, I mean.

**Comment by lekaf974** [comment]
> Which workflow, I mean.

Just updated the workflow to ensure doc site preview is triggered when modifying `mesheryctl/docs`
