### PR TITLE
mesheryctl: improved error reporting and handling

### LINKED ISSUE #1049: mesheryctl: Improve error reporting and add robust error handling
**Current Behavior**
mesheryctl currently does not report errors but instead just prints the usage/help command to the screen. This can make it difficult for the user of mesheryctl to identify what they did wrong or even report new issues as they encounters problems.
NOTE: This applies only to `mesheryctl` cobra command error handling, and not to the meshery server runs.

**Desired Behavior**
Add more error logging and have the command executions return errors. Errors from upstream functions must be propagated back to top level `Run` or `RunE` functions (provided by cobra).

---
**Resources**
see `RunE` https://pkg.go.dev/github.com/spf13/cobra@v1.0.0?tab=doc#Command
Errors should be handled and returned here.
Example:
https://github.com/docker/cli/blob/master/cli/cobra.go#L177-L192

**Alternatives / Additional Context**
N/A

### PR DESCRIPTION
**Pull request by nitishm**
Error handling and reporting is very primitive with a lot of errors
not caught which can cause unexpected failures for the user.
Added better error reporting and handling in mesheryctl commands.

Fixes #1049

Signed-off-by: nitish.malhotra@gmail.com <nitish.malhotra@gmail.com>

**Description**

This PR fixes # 

**Notes to reviewers**

#### Checklist

- [] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).
- [] PR title includes `[<name of area>]:<description>`

### CODE REVIEW

File: mesheryctl/internal/cli/root/perf/perf.go [hunk 1]
```diff
@@ -221,49 +189,43 @@ var PerfCmd = &cobra.Command{
...
 		req.URL.RawQuery = q.Encode()
 
 		client := &http.Client{}
 		resp, err := client.Do(req)
-
 		if err != nil {
-			log.Print("\nFailed to make request to URL:", testURL)
-			log.Fatal("Error Message:\n", err)
-			return
+			log.Info("\nFailed to make request to URL:", testURL)
```
Comment (kushthedude) [inline mesheryctl/internal/cli/root/perf/perf.go:210]: Since we are reporting the error, I think the following log statement is not needed.

File: mesheryctl/internal/cli/root/perf/perf.go [hunk 2]
```diff
@@ -180,39 +151,36 @@ var PerfCmd = &cobra.Command{
...
 			postData = postData + "\nendpoint_url: " + testURL
 		} else {
-			log.Fatal("Error: Please enter a test URL")
-			return
+			return errors.New("please enter a test URL")
 		}
 
 		// Method to check if the entered Test URL is valid or not
-		var validURL bool = govalidator.IsURL(testURL)
+		var validURL = govalidator.IsURL(testURL)
```
Comment (kushthedude) [inline mesheryctl/internal/cli/root/perf/perf.go:180]: Don't we need to specify the bool type here ?

File: mesheryctl/internal/cli/root/perf/perf.go [hunk 3]
```diff
@@ -51,31 +53,6 @@ var (
 	tokenPath          = ""
 )
 
-var perfDetails = `
```
Comment (kushthedude) [inline mesheryctl/internal/cli/root/perf/perf.go:54]: What will be the behaviour now if I run the command without any argument? Because @leecalcote asked to output the command description if user runs any sub-command without passing arguments.

File: mesheryctl/internal/cli/root/perf/perf.go (hunk 1 above)
Comment (nitishm) [reply mesheryctl/internal/cli/root/perf/perf.go]: Removed

File: mesheryctl/internal/cli/root/perf/perf.go (hunk 3 above)
Comment (kushthedude) [reply mesheryctl/internal/cli/root/perf/perf.go:54]: Displaying command definition after the error may seem bad UX, so either we should display a more informative message like
` No arguments passed, please see --help flag for details on the command`  or we should display the command details. Let's leave the final decision to @leecalcote .

File: mesheryctl/internal/cli/root/perf/perf.go (hunk 2 above)
Comment (kushthedude) [reply mesheryctl/internal/cli/root/perf/perf.go:180]: > The linters flag the type declaration as redundant and can trigger warnings.

Thanks!

File: mesheryctl/internal/cli/root/perf/perf.go (hunk 3 above)
Comment (nitishm) [reply mesheryctl/internal/cli/root/perf/perf.go:54]: it's not customizable through cobra but let's see maybe we can create an error reporter for it.

**Comment by leecalcote** [comment]
Informing the user of the specific thing they are missing and then giving them the command-specific help is almost as good as it gets.

Here's an ideal example:
```
"mesheryctl perf" requires an endpoint to test. Identify an endpoint using the "--url" or "--file" arguments.

Performance Testing & Benchmarking using Meshery CLI.

Usage:
  mesheryctl perf --[flags]

Available Flags for Performance Command:
  name[string]                  (optional) A short descriptor to serve as reference for this test. If not provided, a random name will be generate.
  url[string]                   (required) URL endpoint to send requests.
  duration[string]              (required) Length of time to perform test (e.g 30s, 15m, 1hr). See standard notation https://golang.org/pkg/time/#ParseDuration
  load-generator[string]        (optional) Name of load generator to be used to perform test (default: "fortio")
  mesh[string]              	(optional) Name of the service mesh to be tested (default: "None")
  provider[string]            	(required) Choice of Provider (default: "Meshery")
  concurrent-requests[string]   (optional) Number of parallel requests to be sent (default: "1")
  qps[string]                   (required) Queries per second (default: "0")
  file[string]			        (optional) file containing SMPS-compatible test configuration. See https://github.com/layer5io/service-mesh-performance-specification
  help                          Help for perf subcommand

url, duration, concurrent-requests, and qps can be considered optional flags if specified through an SMPS compatible yaml file using --file

Example usage of perf subcommand :

 mesheryctl perf --name "a quick stress test" --url http://192.168.1.15/productpage --qps 300 --concurrent-requests 2 --duration 30s --token "provider=Meshery"
```

A way to improve from here is to include a URL to the `mesheryctl perf` command guide, containing examples and documentation on its behavior. We don't have this, but need a set of these.

**Comment by nitishm** [comment]
@leecalcote @kushthedude 
Maybe a formatted error using a helper function as below 
```go
const (
	// Usage URLs
	perfUsageURL   = "https://meshery.layer5.io/docs/guides/mesheryctl#performance-management"
	systemUsageURL = "https://meshery.layer5.io/docs/guides/mesheryctl#meshery-lifecycle-management"
	meshUsageURL   = "https://meshery.layer5.io/docs/guides/mesheryctl#service-mesh-lifecycle-management"
)

// FormatErrors returns a formatted error message with a link to the meshery command URL
func FormatErrors(msg string, cmd string) string {
	switch cmd {
	case "perf":
		return fmt.Sprintf("Error: %s. See %s for usage details\n", msg, perfUsageURL)
	case "mesh":
		return fmt.Sprintf("Error: %s. See %s for usage details\n", msg, meshUsageURL)
	case "system":
		return fmt.Sprintf("Error: %s. See %s for usage details\n", msg, systemUsageURL)
	}
	return fmt.Sprintf("Error: %s\n", msg)
}
```

**Comment by nitishm** [comment]
Sample error output :
`mesheryctl perf`
```
Error: please enter a test URL
See https://meshery.layer5.io/docs/guides/mesheryctl#performance-management for usage details

Usage:
  mesheryctl perf [flags]

Examples:
mesheryctl perf --name "a quick stress test" --url http://192.168.1.15/productpage --qps 300 --concurrent-requests 2 --duration 30s --token "provider=Meshery"

Flags:
      --concurrent-requests string   (optional) Number of Parallel Requests (default "1")
      --duration string              (optional) Length of test (e.g. 10s, 5m, 2h). For more, see https://golang.org/pkg/time/#ParseDuration (default "30s")
      --file string                  (optional) file containing SMPS-compatible test configuration. For more, see https://github.com/layer5io/service-mesh-performance-specification
  -h, --help                         help for perf
      --load-generator string        (optional) Load-Generator to be used (fortio/wrk2) (default "fortio")
      --mesh string                  (optional) Name of the Service Mesh
      --name string                  (optional) Name of the Test
      --qps string                   (optional) Queries per second (default "0")
      --token string                 (optional) Path to meshery auth config (default "auth.json")
      --url string                   (required) Endpoint URL to test

Global Flags:
      --config string   config file (default location is: /Users/nitish_malhotra/.meshery/meshery.yaml)

```

**Comment by nitishm** [comment]
@kushthedude 
```
# mesheryctl system foobar
Error: invalid command: "foobar"
See https://meshery.layer5.io/docs/guides/mesheryctl#performance-management for usage details

Usage:
  mesheryctl system [flags]
  mesheryctl system [command]

Available Commands:
  logs        Print logs
  reset       Reset Meshery's configuration
  start       Start Meshery
  status      Check Meshery status
  stop        Stop Meshery
  update      Pull new Meshery images from Docker Hub.

Flags:
  -h, --help   help for system

Global Flags:
      --config string              config file (default location is: /Users/nitish_malhotra/.meshery/meshery.yaml)
      --mesheryctl-config string   mesheryctl config file to override defaults (default file: <unset>

Use "mesheryctl system [command] --help" for more information about a command.
```

&

```
# mesheryctl foobar
Error: invalid command: "foobar"
See https://meshery.layer5.io/docs/guides/mesheryctl#global-commands-and-flags for usage details

Usage:
  mesheryctl [flags]
  mesheryctl [command]

Available Commands:
  help        Help about any command
  perf        Performance Testing
  system      Meshery Lifecycle Management
  version     Version of mesheryctl

Flags:
      --config string              config file (default location is: /Users/nitish_malhotra/.meshery/meshery.yaml)
  -d, --debug                      Debug flag
  -h, --help                       help for mesheryctl
      --mesheryctl-config string   mesheryctl config file to override defaults (default file: <unset>
  -v, --version                    Version flag

Use "mesheryctl [command] --help" for more information about a command.
```

**Comment by nitishm** [comment]
@leecalcote Is this ready to be merged ?

**Comment by leecalcote** [comment]
@nitishm these sample error outputs really help / save some time. Thank you.

**Comment by leecalcote** [comment]
> @leecalcote @kushthedude
> Maybe a formatted error using a helper function as below
> 
> ```go
> const (
> 	// Usage URLs
> 	perfUsageURL   = "https://meshery.layer5.io/docs/guides/mesheryctl#performance-management"
> 	systemUsageURL = "https://meshery.layer5.io/docs/guides/mesheryctl#meshery-lifecycle-management"
> 	meshUsageURL   = "https://meshery.layer5.io/docs/guides/mesheryctl#service-mesh-lifecycle-management"
> )
> 
> // FormatErrors returns a formatted error message with a link to the meshery command URL
> func FormatErrors(msg string, cmd string) string {
> 	switch cmd {
> 	case "perf":
> 		return fmt.Sprintf("Error: %s. See %s for usage details\n", msg, perfUsageURL)
> 	case "mesh":
> 		return fmt.Sprintf("Error: %s. See %s for usage details\n", msg, meshUsageURL)
> 	case "system":
> 		return fmt.Sprintf("Error: %s. See %s for usage details\n", msg, systemUsageURL)
> 	}
> 	return fmt.Sprintf("Error: %s\n", msg)
> }
> ```

This is really good stuff. 👍
