### PR TITLE
[mesheryctl] perculate the silentFlag to PreReqChecks as well.

### LINKED ISSUE #2302: Issue running meshery installation script in quick start guide
#### Description

The [Meshery installation bash script](https://github.com/layer5io/meshery/blob/master/meshery) ends with the line `mesheryctl system start`. When run for the first time, the output generated is as shown below:
```
Extracting mesheryctl-v0.5.0-beta-1...
Archive:  /usr/bin/meshery.zip
  inflating: LICENSE                 
  inflating: README.md               
  inflating: mesheryctl              

Installing mesheryctl in /usr/local/bin.
mesheryctl installed.
permissions moved to pranav
Removing installation files and opening Meshery...Missing Meshery config file.
Create default config now [y/n]? EOF
```

#### Expected Behavior

Instead of waiting for user input (y/N), the script reads `EOF`, and exits.

[Line 99](https://github.com/layer5io/meshery/blob/566261f9f9618af1200a16ec593b327644e98d67/meshery#L99) should be moved out of the script, and the tutorials/docs should explicitly tell the user to run the `mesheryctl system start` command.

#### Environment:
- Host OS: Ubuntu 20.04
- Meshery Version: 0.5.0-beta-1
- Kubernetes Version: 1.20.2
- Browser: Firefox 84.0.2

#### To Reproduce
1. Follow steps in the [Meshery quick start guide](https://docs.meshery.io/installation/quick-start). Issue arises on the "Install Meshery" step.

### PR DESCRIPTION
**Pull request by hexxdump**
**Description**
There was an open issue with PR #1859, where the startdockerdaemon
does not prompt user for confirmation, i.e., during install.

To avoid the issue of not starting docker and exiting prematurely,
use the silentFlag to proceed with docker start process.

Signed-off-by: Hussaina Begum Nandyala <hexxdump@gmail.com>
This PR fixes #2302

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/pkg/utils/helpers.go [hunk 1]
```diff
@@ -237,13 +237,14 @@ func PreReqCheck(subcommand string) error {
...
-	var userinput string
-	fmt.Printf("Start Docker now [y/n]? ")
-	fmt.Scan(&userinput)
-	userinput = strings.TrimSpace(userinput)
-	userinput = strings.ToLower(userinput)
-	if userinput == "n" || userinput == "no" {
+	if SilentFlag {
+		userResponse = true
+	} else {
+		userResponse = AskForConfirmation("Start Docker now?")
```
Comment (navendu-pottekkat) [inline mesheryctl/pkg/utils/helpers.go:245]: Change "Start Docker now?" to "Start Docker now". i.e remove the question mark, since `AskForConfirmation` method already has a question mark.

Great spot with this error. And great work changing to the `AskForConfirmation` function.

Other than removing the question mark, rest LGTM. @hexxdump please make that tiny change and you can merge.

**Review by navendu-pottekkat — APPROVED** [review]
Very tiny change needed, please make that and merge.

File: mesheryctl/pkg/utils/helpers.go (hunk 1 above)
Comment (hexxdump) [reply mesheryctl/pkg/utils/helpers.go]: > Change "Start Docker now?" to "Start Docker now". i.e remove the question mark, since `AskForConfirmation` method already has a question mark.
> 
> Great spot with this error. And great work changing to the `AskForConfirmation` function.
> 
> Other than removing the question mark, rest LGTM. @hexxdump please make that tiny change and you can merge.

Done.

**Review by navendu-pottekkat — APPROVED** [review]
Nice! LGTM @leecalcote Please check and merge the changes.

**Review by leecalcote — APPROVED** [review]
Beautiful. Nice work.
