### PR TITLE
Fix: Informative and User Friendly Connections Modals

### LINKED ISSUE #14407: [UI] Connections: Improve level of detail of disconnect behavior
### Current Behavior
Warning messages request confirmation from users upon delete or disconnect of various items in Meshery. The screenshot below comes from the Connections screen and is presented when a Kubernetes connection is selected to be Disconnected. This modal doesn't offer enough info to prevent the user from having to visit the Docs for an explanation of what really occurs.

### Desired Behavior
Prevent users from having to visit Meshery Docs.

### Screenshots

Image

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by vr-varad**
**Notes for Reviewers**

- This PR fixes #14407

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
This is very good to see, @vr-varad 👍

File: ui/components/connections/ConnectionTable.js [hunk 1]
```diff
@@ -455,11 +455,34 @@ const ConnectionTable = ({
...
+        return `Are you sure that you want to transition the connection status to ${status}?`;
+    }
+  };
+
   const handleStatusChange = async (e, connectionId, connectionKind) => {
     e.stopPropagation();
+    const status = e.target.value.toUpperCase();
+    let subtitle = getSubtitle(status);
     let response = await modalRef.current.show({
       title: `Connection Status Transition`,
```
Comment (leecalcote) [inline ui/components/connections/ConnectionTable.js:484]:
```suggestion
      title: `Transition connection to ${e.target.value.toUpperCase()}?`,
```

File: ui/components/connections/ConnectionTable.js [hunk 2]
```diff
@@ -455,11 +455,34 @@ const ConnectionTable = ({
...
+      case 'DELETED':
+        return 'Are you sure you want to delete this connection? This will permanently remove the connection from Meshery’s management view. All associated and previously collected data will also be deleted and cannot be recovered.';
+      case 'REGISTERED':
+        return 'Are you sure you want to mark this connection as Registered? This means the connection has been verified for reachability but is not yet in active use. It will now await further administrative action, such as being connected, put under maintenance, or marked as not found.';
+      case 'DISCOVERED':
+        return 'Are you sure you want to mark this connection as Discovered? This indicates that the connection was identified by MeshSync’s discovery process or configuration input, but its usability and reachability haven’t been verified yet. It will now appear in the Meshery UI for further action like registration or ignoring.';
+      case 'CONNECTED':
+        return 'Are you sure you want to mark this connection as Connected? Meshery will begin actively managing this connection. It may auto-transition to Disconnected if communication is lost.';
```
Comment (leecalcote) [inline ui/components/connections/ConnectionTable.js:473]:
```suggestion
        return 'Meshery will begin actively managing this connection. It may auto-transition to Disconnected if communication is lost.';
```

File: ui/components/connections/ConnectionTable.js [hunk 3]
```diff
@@ -455,11 +455,34 @@ const ConnectionTable = ({
...
+      case 'DELETED':
+        return 'Are you sure you want to delete this connection? This will permanently remove the connection from Meshery’s management view. All associated and previously collected data will also be deleted and cannot be recovered.';
+      case 'REGISTERED':
+        return 'Are you sure you want to mark this connection as Registered? This means the connection has been verified for reachability but is not yet in active use. It will now await further administrative action, such as being connected, put under maintenance, or marked as not found.';
+      case 'DISCOVERED':
+        return 'Are you sure you want to mark this connection as Discovered? This indicates that the connection was identified by MeshSync’s discovery process or configuration input, but its usability and reachability haven’t been verified yet. It will now appear in the Meshery UI for further action like registration or ignoring.';
```
Comment (leecalcote) [inline ui/components/connections/ConnectionTable.js:471]:
```suggestion
        return 'Connections with "discovered" status have been identified through MeshSync’s discovery process. Meshery's ability to reach (connectivity) and manage (authenticate and authorization) have yet to be verified.';
```

This message needs further thought...

**Review by leecalcote — COMMENTED** [review]
Are these messages only for Kubernetes connections or all connections?

File: ui/components/connections/ConnectionTable.js (hunk 3 above)
Comment (vr-varad) [reply ui/components/connections/ConnectionTable.js:471]: all connections

**Review by zihanKuang — COMMENTED** [review]
Great work on this! 🙌
I just have a small question: I noticed that only the `Discovered` and `Connected` states don’t include a confirmation phrase like *“Are you sure you want to...”*, while the others do.  
If the intention is to only prompt confirmation for destructive or risky actions, then maybe the `Registered` state wouldn’t necessarily need a confirmation eitherr, or was there a different consideration behind this choice?

**Comment by vr-varad** [comment]
> Great work on this! 🙌 I just have a small question: I noticed that only the `Discovered` and `Connected` states don’t include a confirmation phrase like _“Are you sure you want to...”_, while the others do. If the intention is to only prompt confirmation for destructive or risky actions, then maybe the `Registered` state wouldn’t necessarily need a confirmation eitherr, or was there a different consideration behind this choice?

Removal for "Are you sure.." was a suggestion from Lee, that's why I removed it.
And what I think the user should know is what he/she is doing if they are changing from one state to another, whether its dangerous or not, just for informative purpose 
@zihanKuang thoughts

**Comment by vishalvivekm** [comment]
@vr-varad 
Thank you for your contributions! Let's discuss this today, during Meshery Development call at 9:00 AM CT | 7:30 PM IST. Add it as an agenda item to the :memo: [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1&tab=t.0#), if you would.
https://meet.meshery.io/dev

**Comment by vr-varad** [comment]
Screenshot from 2025-04-26 17-13-43
Screenshot from 2025-04-26 17-53-02
Screenshot from 2025-04-26 17-53-08
Screenshot from 2025-04-26 17-53-14
Screenshot from 2025-04-26 17-53-19
Screenshot from 2025-04-26 17-53-33
Screenshot from 2025-04-26 17-53-39
Screenshot from 2025-04-26 17-53-57
Screenshot from 2025-04-26 17-54-03
Screenshot from 2025-04-26 17-54-17
Screenshot from 2025-04-26 17-54-22
Screenshot from 2025-04-26 17-54-33

**Review by leecalcote — APPROVED** [review]
