### PR TITLE
used theme pallete

### LINKED ISSUE #13870: [UI] Wrong color is used for adapter icon in the sidebar
### Current Behavior

Image

### Desired Behavior
It should be same as other item color

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by AMRITESH240304**
**Notes for Reviewers**

- This PR fixes #13870 
**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
[Screencast from 2025-03-07 14-01-42.webm](https://github.com/user-attachments/assets/ea4225d2-e592-4820-b98e-3938c876aa23)

- [ x] Yes, I signed my commits.

### CODE REVIEW

File: ui/assets/icons/ServiceMeshIcon.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ const ServiceMeshIcon = (props) => {
         <g id="Layer_1-2" data-name="Layer 1">
           <path
             d="M146.32 184.19A26.29 26.29 0 0 1 120 157.94a26.3 26.3 0 0 1 26.28-26.28 26.28 26.28 0 0 1 26.27 26.28 26.27 26.27 0 0 1-26.23 26.25ZM74.55 118.37a26.3 26.3 0 0 1-26.28-26.28 26.29 26.29 0 0 1 26.28-26.27 26.27 26.27 0 0 1 26.27 26.27 26.28 26.28 0 0 1-26.27 26.28ZM146.32 118.37A26.3 26.3 0 0 1 120 92.09a26.29 26.29 0 0 1 26.28-26.27 26.27 26.27 0 0 1 26.27 26.27 26.28 26.28 0 0 1-26.23 26.28ZM146.35 52.54a26.27 26.27 0 0 1-26.27-26.27A26.27 26.27 0 0 1 146.35 0a26.28 26.28 0 0 1 26.28 26.27 26.28 26.28 0 0 1-26.28 26.27Z"
-            className="cls-1"
+            className="cls-1{fill:none}"
```
Comment (ritzorama) [inline ui/assets/icons/ServiceMeshIcon.js:28]:
```suggestion
            fill=${fill}
```

Comment (ritzorama) [reply ui/assets/icons/ServiceMeshIcon.js:28]: No, not quite.

**Comment by ritzorama** [comment]
@AMRITESH240304, make sure that you test your changes. Include a screenshot of your changes, too.

**Comment by AMRITESH240304** [comment]
added a video of the change test

**Comment by amitamrutiya** [comment]
@AMRITESH240304 any progress?

**Comment by AMRITESH240304** [comment]
> @AMRITESH240304 any progress?
correct color on servicemesh is getting through this ``className="cls-1{fill:none}"`` only and some changes on rendering the icon 
cant find any other way to solve this

File: ui/components/Navigator.js [hunk 2]
```diff
@@ -822,6 +822,9 @@ const Navigator_ = (props) => {
   };
 
   const linkContent = (iconc, titlec, hrefc, linkc, drawerCollapsed) => {
+    const updatedIcon = React.cloneElement(iconc, {
+      fill: state.path === hrefc ? theme.palette.icon.brand : undefined,
```
Comment (amitamrutiya) [inline ui/components/Navigator.js:826]:
```suggestion
      fill: state.path === hrefc ? theme.palette.icon.brand : theme.palette.icon.default,
```

Comment (amitamrutiya) [inline ui/components/Navigator.js:826]:
```suggestion
      fill: state.path === hrefc ? theme.palette.icon.brand : theme.palette.common.white,
```

File: ui/assets/icons/ServiceMeshIcon.js (hunk 1 above)
Comment (amitamrutiya) [inline ui/assets/icons/ServiceMeshIcon.js:28]:
```suggestion
            className="cls-1"
```

Comment (amitamrutiya) [inline ui/assets/icons/ServiceMeshIcon.js]:
```suggestion
```
