### PR TITLE
[BUG] Fix mastering-meshery link

### LINKED ISSUE #15574: [BUG] Broken “Mastering Meshery” tutorial link in Meshery Playground
### Current Behavior
Clicking on _Mastering Meshery_ tutorial in Meshery playground leads to a broken url.

### Expected Behavior
Users should be redirected to [this page](https://cloud.layer5.io/academy/learning-paths/11111111-1111-1111-1111-111111111111/mastering-meshery/) instead.

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Siddhi-sahu**
**Notes for Reviewers**

- This PR fixes #15574

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c8a4a40fbd196170a7441c126a0801e19b1742fa at: https://689c72e4f6e919b36fa57d1b--meshery-docs-preview.netlify.app

**Comment by vr-varad** [comment]
Thank you @Siddhi-sahu   for your contribution!!
If this work is complete, this is a good item to add to the weekly [Meshery Development meeting agenda](https://docs.google.com/document/d/15IEwtTxPOkQXN2r_1LzGXuAv2mIUlmbdtmxpyxXF-KI/edit). You can add this item in the doc, attend, and present it. Meeting details at https://meet.layer5.io/meshery.

File: ui/components/Dashboard/widgets/getting-started/data.js [hunk 1]
```diff
@@ -222,7 +222,10 @@ export const stepsData = [
         previousButton: false,
         actionName: ActionName.LEARN,
         primaryAction: () => {
-          window.open(`${MESHERY_CLOUD_PROD}/academy/learning-paths/mastering-meshery`, '_blank');
+          window.open(
+            `${MESHERY_CLOUD_PROD}/academy/learning-paths/11111111-1111-1111-1111-111111111111/mastering-meshery`,
```
Comment (leecalcote) [inline ui/components/Dashboard/widgets/getting-started/data.js:226]: How does this behave when the "None" (local) provider is selected?

Comment (leecalcote) [reply ui/components/Dashboard/widgets/getting-started/data.js:226]: @vr-varad

File: docs/pages/guides/tutorials/deploy-aws-ec2-instances-with-meshery.md [hunk 2]
```diff
@@ -110,7 +110,7 @@ While this step is already handled in the design, but it's worth clarifying how
 
 #### Deploy EC2 Controller Design
 
-After configuring your design, the next step is deployment. To learn more about deploying your designs in Meshery, see [Deploying Meshery Designs](https://cloud.layer5.io/academy/learning-paths/mastering-meshery/introduction-to-meshery?chapter=deploying-meshery-designs). To deploy the resources, follow these steps:
+After configuring your design, the next step is deployment. To learn more about deploying your designs in Meshery, see [Deploying Meshery Designs](https://cloud.layer5.io/academy/learning-paths/11111111-1111-1111-1111-111111111111/mastering-meshery/introduction-to-meshery?chapter=deploying-meshery-designs). To deploy the resources, follow these steps:
```
[the remark this answers is not in the document]
Comment (leecalcote) [reply docs/pages/guides/tutorials/deploy-aws-ec2-instances-with-meshery.md:113]: 11111111-1111-1111-1111-111111111111 is appropriate.

**Comment by Siddhi-sahu** [comment]
> Thank you @Siddhi-sahu for your contribution!! If this work is complete, this is a good item to add to the weekly [Meshery Development meeting agenda](https://docs.google.com/document/d/15IEwtTxPOkQXN2r_1LzGXuAv2mIUlmbdtmxpyxXF-KI/edit). You can add this item in the doc, attend, and present it. Meeting details at https://meet.layer5.io/meshery.

I just changed the url😅

File: ui/components/Dashboard/widgets/getting-started/data.js (hunk 1 above)
Comment (hortison) [reply ui/components/Dashboard/widgets/getting-started/data.js:226]: How does this behave when the "None" (local) provider is selected, @Siddhi-sahu?

**Comment by miacycle** [comment]
> > Thank you @Siddhi-sahu for your contribution!! If this work is complete, this is a good item to add to the weekly [Meshery Development meeting agenda](https://docs.google.com/document/d/15IEwtTxPOkQXN2r_1LzGXuAv2mIUlmbdtmxpyxXF-KI/edit). You can add this item in the doc, attend, and present it. Meeting details at https://meet.layer5.io/meshery.
> 
> I just changed the url😅

Yes, and did you test the change?

File: ui/components/Dashboard/widgets/getting-started/data.js (hunk 1 above)
Comment (Siddhi-sahu) [reply ui/components/Dashboard/widgets/getting-started/data.js:226]: @hortison @miacycle With the "None" (local) provider, it shows “session expired”. For context, I replaced the URL with the one @vr-varad shared in a slack conversation.

**Comment by vr-varad** [comment]
Thank you @Siddhi-sahu  for your contribution!!
If this work is complete, this is a good item to add to the weekly [Meshery Development meeting agenda](https://docs.google.com/document/d/15IEwtTxPOkQXN2r_1LzGXuAv2mIUlmbdtmxpyxXF-KI/edit). You can add this item in the doc, attend, and present it. Meeting details at https://meet.layer5.io/meshery.

**Comment by leecalcote** [comment]
> > > Thank you @Siddhi-sahu for your contribution!! If this work is complete, this is a good item to add to the weekly [Meshery Development meeting agenda](https://docs.google.com/document/d/15IEwtTxPOkQXN2r_1LzGXuAv2mIUlmbdtmxpyxXF-KI/edit). You can add this item in the doc, attend, and present it. Meeting details at https://meet.layer5.io/meshery.
> > 
> > 
> > I just changed the url😅
> 
> Yes, and did you test the change?

@Siddhi-sahu, that's a "no"?

**Comment by Siddhi-sahu** [comment]
> > > > Thank you @Siddhi-sahu for your contribution!! If this work is complete, this is a good item to add to the weekly [Meshery Development meeting agenda](https://docs.google.com/document/d/15IEwtTxPOkQXN2r_1LzGXuAv2mIUlmbdtmxpyxXF-KI/edit). You can add this item in the doc, attend, and present it. Meeting details at https://meet.layer5.io/meshery.
> > > 
> > > 
> > > I just changed the url😅
> > 
> > 
> > Yes, and did you test the change?
> 
> @Siddhi-sahu, that's a "no"?

yes, I am sorry, I didn't test it for the "none" provider😓. Is it fine to replace the url with this one = > https://docs.layer5.io/learning-paths/mastering-meshery/ ??

**Comment by zihanKuang** [comment]
> > > > > Thank you @Siddhi-sahu for your contribution!! If this work is complete, this is a good item to add to the weekly [Meshery Development meeting agenda](https://docs.google.com/document/d/15IEwtTxPOkQXN2r_1LzGXuAv2mIUlmbdtmxpyxXF-KI/edit). You can add this item in the doc, attend, and present it. Meeting details at https://meet.layer5.io/meshery.
> > > > 
> > > > 
> > > > I just changed the url😅
> > > 
> > > 
> > > Yes, and did you test the change?
> > 
> > 
> > @Siddhi-sahu, that's a "no"?
> 
> yes, I am sorry, I didn't test it for the "none" provider😓. Is it fine to replace the url with this one = > https://docs.layer5.io/learning-paths/mastering-meshery/ ??

Hi @Siddhi-sahu,

We've moved all the original Academy content to the cloud platform. You should replace the link with https://cloud.layer5.io/academy/learning-paths/11111111-1111-1111-1111-111111111111/mastering-meshery

You can find any other links you need at https://cloud.layer5.io/academy?orgId=11111111-1111-1111-1111-111111111111

**Comment by Siddhi-sahu** [comment]
hello @zihanKuang 👋. The link you gave me, is exactly what I replaced  in the original PR commit.

**Review by zihanKuang — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 9b52a0e537a7db1588a94cc3d49b5bd725dc6d58 at: https://68a718d88284de3c04d43a40--meshery-docs-preview.netlify.app
