### PR TITLE
file:ui/components/Popup.js bug fix for 6488

### LINKED ISSUE #6488: [UI] Pop-up: cutoff on smaller width screens
#### Current Behavior
Meshery UI has a recently added popup (see https://github.com/meshery/meshery/pull/6479), which is cutoff of on smaller screen sizes.

#### Desired Behavior

1. The popup should be absolutely positioned in reference to the browser.
2. The popup title should be in bold.
3. The caption should have a reduced line-height.
4. The graphic should have slightly more top and bottom padding.

#### Screenshots/Logs
Screen Shot 2022-11-03 at 4 28 13 PM

#### Environment

- Browser: Safari
- Host OS: Mac 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by franklinekoh**
Signed-off-by: Ekoh Franklin <ekohfranklin@gmail.com>

**FIxed popup cutoff on smaller screen width**

This PR fixes #6488

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
@franklinekoh Would you attack a screenshot here with your fix. That would be great.

File: ui/components/Popup.js [hunk 1]
```diff
@@ -102,18 +116,22 @@ function Popup() {
...
+            </div>
 
+            <div className={classes.imgWrapper}>
+              <img className={classes.drawer} src="/static/img/designer-drawer.png" />
+              <img className={classes.canvas} src="/static/img/designer-canvas.png" />
             </div>
-            <img className={classes.drawer} src="/static/img/designer-drawer.png" />
-            <img className={classes.canvas} src="/static/img/designer-canvas.png" />
-            <Typography variant="subtitle1"><i>Friends dont let friends GitOps alone. Visually design and collaborate in real-time with other MeshMap users.</i></Typography>
+            <Typography className={classes.caption} variant="subtitle1"><i>Friends dont let friends GitOps alone. Visually design and collaborate in real-time with other MeshMap users.</i></Typography>
```
Comment (Abhishek-kumar09) [inline ui/components/Popup.js:134]: btw there is a variant called "caption" also, maybe it wasn't useful here?

**Review by Abhishek-kumar09 — COMMENTED** [review]
Looks good @franklinekoh

File: ui/components/Popup.js (hunk 1 above)
Comment (franklinekoh) [reply ui/components/Popup.js:134]: @Abhishek-kumar09 what do you mean by "variant"? the className "caption" has css for styling the text. removing it would mean adding inline css which isn't ideal. please clarify

Comment (franklinekoh) [reply ui/components/Popup.js:127]: Hi @Abhishek-kumar09 I have also attached a screenshot of the completed work below

Comment (franklinekoh) [reply ui/components/Popup.js:127]: Screenshot 2022-11-14 at 12 38 52

**Review by Abhishek-kumar09 — APPROVED** [review]

File: ui/components/Popup.js (hunk 1 above)
Comment (franklinekoh) [reply ui/components/Popup.js:127]: Ok

**Review by warunicorn19 — APPROVED** [review]
Screenshot 2022-11-15 at 12 10 50 AM

**Comment by leecalcote** [comment]
@franklinekoh, yay! 🎈 

Thank you, @warunicorn19 @Abhishek-kumar09
