### PR TITLE
Fix connection page issues

### LINKED ISSUE #9834: [UI] Connections: Use Consistent Naming across chip locations
### Current Behavior
The Connections page and the Kubernetes Context Switcher, use different display names for the same connection. It's confusing.

See http://localhost:9081/management/connections page.

### Desired Behavior
Use only one display name for any given connection.

### Screenshots/Logs

Screenshot 2024-01-04 at 4 56 41 PM

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Notes for Reviewers**

This PR fixes #9834 

1. Consistent connection name and fix ping not working
2. Meshsync issue of crashing ui

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
"fix ping not working" - why?

**Review by leecalcote — APPROVED** [review]

File: ui/components/connections/index.js [hunk 1]
```diff
@@ -349,9 +349,7 @@ function Connections(props) {
     ['environments', 'm'],
     ['kind', 'm'],
     ['type', 's'],
-    ['sub_type', 'm'],
-    ['updated_at', 'l'],
-    ['created_at', 'na'],
```
Comment (leecalcote) [inline ui/components/connections/index.js:354]: @sudhanshutech Created At could be quite helpful... it should probably be included.

**Review by leecalcote — CHANGES_REQUESTED** [review]

File: ui/components/connections/index.js (hunk 1 above)
Comment (sudhanshutech) [reply ui/components/connections/index.js:354]: ok , i removed because we were already showing date in row expansion so thought need not to be in two places. In that case i will re add it

Comment (leecalcote) [reply ui/components/connections/index.js:354]: @sudhanshutech Not having it means that users can sort based on date, though. 

A compromise is to have the column included, but not displayed by default.

Comment (sudhanshutech) [reply ui/components/connections/index.js:354]: ok yes, i added it back it back
