### PR TITLE
[mesheryctl] Read user consent before starting Docker daemon in PreReqCheck

### LINKED ISSUE #1770: [Meshery] Ask user confirmation before starting docker in the PreReqCheck
**Description**
`mesheryctl system XXXX` commands try to start docker daemon, if its not running already.
However User should be prompted before docker daemon is started.

**Expected Behavior**
Introduce an user prompt before starting docker daemon

**Screenshots**
This sample code was added in PreReqCheck() code in helpers.go,
however it was not giving desired result, need to rework on it:
```
var resp string 
fmt.Printf("Do you want to start docker daemon?(y/n): ")
_, err := fmt.Scan(&resp)
fmt.Printf("Response read:%s, err: %v\n", resp, err)
if err != nil {
   log.Info("Run `masheryctl system start` once docker is started.")
   return nil
}
resp = strings.TrimSpace(resp)
resp = strings.ToLower(resp)
if resp == "n" || resp == "no" {
	log.Info("Run `masheryctl system start` once docker is started.")
	return nil
}
```

**Environment:**
- Host OS: Unix, MacOS
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

---
[Optional] **To Reproduce**
1. Stop docker daemon
2. Run "mesheryctl system start" command

[Optional] **Additional Context**
Check PR: #1685  #1697

### PR DESCRIPTION
**Pull request by hexxdump**
[mesheryctl] Read user consent before starting Docker daemon in PreReqCheck

Signed-off-by: Hussaina Begum Nandyala <hexxdump@gmail.com>

**Description**
PreReqCheck function attempts to start Docker daemon, if
its not running already. Modified the code to ask user
whether they want to start Docker or not.

This PR fixes #1770 

**Notes for Reviewers**
The meshery script reads user input when run directly ( For e.g. `./meshery`)
 However `cat meshery | bash -` fails to read user input

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@sladyn98 interesting in reviewing?

**Review by leecalcote — APPROVED** [review]
@hexxdump good improvement. 👍 Output from my machine:

```
➜  mesheryctl git:(hexxdump/master) ✗ ./mesheryctl system start
Docker daemon is not running
Do you want to start Docker daemon now?(y/n): y
Attempting to start Docker daemon
Error: failed to start Docker daemon. Run `mesheryctl system start` once docker is started.: please start Docker then run the command `mesheryctl system start`: exit status 1
Usage:
  mesheryctl system start [flags]

Flags:
  -h, --help          help for start
      --reset         (optional) reset Meshery's configuration file to default settings.
      --skip-update   (optional) skip checking for new Meshery's container images.

Global Flags:
      --config string              config file (default location is: /Users/lee/.meshery/meshery.yaml)
      --mesheryctl-config string   mesheryctl config file to override defaults (default file: <unset>)
```

My Docker Desktop still fails to start in time it seems, but this is an improvement. Continuing on this path, we might re-prompt the user to ask if `mesheryctl` should continue to wait for Docker to become available until the user says "n".

File: mesheryctl/pkg/utils/helpers.go [hunk 1]
```diff
@@ -186,8 +186,17 @@ func PreReqCheck(subcommand string) error {
...
 
 func startdockerdaemon(subcommand string) error {
+	// read user input on whether to start Docker daemon or not.
+	var userinput string
+	fmt.Printf("Do you want to start Docker daemon now?(y/n): ")
+	fmt.Scan(&userinput)
+	userinput = strings.TrimSpace(userinput)
+	userinput = strings.ToLower(userinput)
+	if userinput == "n" || userinput == "no" {
+		return errors.Errorf("please start Docker then run the command `mesheryctl system %s`", subcommand)
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/helpers.go:196]: @hexxdump, we may be able to exclude this message as it is duplicative of another message. Example here:

```
➜  mesheryctl git:(hexxdump/master) ✗ ./mesheryctl system start
Docker daemon is not running
Do you want to start Docker daemon now?(y/n): n
Error: failed to start Docker daemon. Run `mesheryctl system start` once docker is started.: please start Docker then run the command `mesheryctl system start`
Usage:
  mesheryctl system start [flags]

Flags:
  -h, --help          help for start
      --reset         (optional) reset Meshery's configuration file to default settings.
      --skip-update   (optional) skip checking for new Meshery's container images.

Global Flags:
      --config string              config file (default location is: /Users/lee/.meshery/meshery.yaml)
      --mesheryctl-config string   mesheryctl config file to override defaults (default file: <unset>)
```

Comment (sladyn98) [reply mesheryctl/pkg/utils/helpers.go:196]: Agreed :+1:

File: mesheryctl/pkg/utils/helpers.go [hunk 2]
```diff
@@ -201,7 +210,7 @@ func startdockerdaemon(subcommand string) error {
 			return errors.Wrapf(err, "please start Docker then run the command `mesheryctl system %s`", subcommand)
 		}
 		// wait for few seconds for docker to start
-		err = exec.Command("sleep", "20").Run()
+		err = exec.Command("sleep", "30").Run()
```
Comment (sladyn98) [inline mesheryctl/pkg/utils/helpers.go:213]: I am always concerned with sleep commands in code. However, this might be a necessity. Can we do something like `$ systemctl status docker` and sort of run it in a goroutine and get the value.

**Review by sladyn98 — COMMENTED** [review]
All of the changes look really solid. Thanks @hexxdump

File: mesheryctl/pkg/utils/helpers.go (hunk 2 above)
Comment (hexxdump) [reply mesheryctl/pkg/utils/helpers.go:213]: > I am always concerned with sleep commands in code. However, this might be a necessity. Can we do something like `$ systemctl status docker` and sort of run it in a goroutine and get the value.

I need to investigate this further, moreover "systemctl" is not present on MacOS. We discussed about the sleep time in the initial PR too. Agreed, this need to change.

File: mesheryctl/pkg/utils/helpers.go (hunk 1 above)
Comment (hexxdump) [reply mesheryctl/pkg/utils/helpers.go:196]: Fixed the log in the PreReqCheck.

Comment (leecalcote) [reply mesheryctl/pkg/utils/helpers.go:196]: New format:

```
➜  mesheryctl git:(hexxdump/master) ✗ ./mesheryctl system start
Docker daemon is not running
Do you want to start Docker daemon now?(y/n): y
Attempting to start Docker daemon
Error: failed to start Docker daemon.: please start Docker then run the command `mesheryctl system start`: exit status 1
Usage:
  mesheryctl system start [flags]

Flags:
  -h, --help          help for start
      --reset         (optional) reset Meshery's configuration file to default settings.
      --skip-update   (optional) skip checking for new Meshery's container images.

Global Flags:
      --config string              config file (default location is: /Users/lee/.meshery/meshery.yaml)
      --mesheryctl-config string   mesheryctl config file to override defaults (default file: <unset>)
```
An improvement. 👍 Ideally, this will read: "Failed to start Docker. Please start Docker, then run the command `mesheryctl system start`."

**Review by leecalcote — APPROVED** [review]
Thank you, @hexxdump 😄

**Comment by hexxdump** [comment]
> Thank you, @hexxdump 😄

Thanks @leecalcote !
