### PR TITLE
[performance] fix bugs related to load generators

### LINKED ISSUE #3273: [Nighthawk] Handle `0` query testing
#### Current Behavior
When the value of `Query` in the test page is set to `0`, nighthawk load test fails due to the fact that qps is set to `0`.

#### Desired Behavior
The load test should start with indefinite traffic when the `Query` parameter is set to `0`.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### LINKED ISSUE #4174: [Perf] Server panic when Nighthawk is missing
#### Current Behavior
Meshery Server panics when trying to run a perf test using Nighthawk, when the Nighthawk binary is not available.

This issue was seen on a locally built Meshery Server, running on MacOS.

#### Screenshots/Logs
```
INFO[2021-09-12T15:31:07-05:00] perf test with config: &{istio_1631478530243  http://bookinfo.meshery.io/productpage 20 6 <nil> <nil> []  false 15s nighthawk 0    true 0 false  false 0s}  app=meshery
fatal error: sync: unlock of unlocked mutex

goroutine 1269 [running]:
runtime.throw(0x613ecea, 0x1e)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/panic.go:1117 +0x72 fp=0xc000088a98 sp=0xc000088a68 pc=0x4039f12
sync.throw(0x613ecea, 0x1e)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/panic.go:1103 +0x35 fp=0xc000088ab8 sp=0xc000088a98 pc=0x406f095
sync.(*Mutex).unlockSlow(0x7609b88, 0xc0ffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/sync/mutex.go:196 +0xd8 fp=0xc000088ae0 sp=0xc000088ab8 pc=0x4080398
sync.(*Mutex).Unlock(0x7609b88)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/sync/mutex.go:190 +0x48 fp=0xc000088b00 sp=0xc000088ae0 pc=0x40802a8
github.com/layer5io/meshery/helpers.startNighthawkServer(0x37e11d600, 0x643a440, 0xc000ea1100)
	/Users/lee/code/meshery/helpers/load_test_interface.go:184 +0x318 fp=0xc000088b90 sp=0xc000088b00 pc=0x58a1078
github.com/layer5io/meshery/helpers.NighthawkLoadTest(0xc0016fd560, 0xc000d4ce08, 0xc000d4cd58, 0xc0007c1e10, 0xc000d4cf28)
	/Users/lee/code/meshery/helpers/load_test_interface.go:217 +0x4a fp=0xc000088d28 sp=0xc000088b90 pc=0x58a114a
github.com/layer5io/meshery/handlers.(*Handler).executeLoadTest(0xc000a60180, 0x6482db8, 0xc0000521c8, 0xc001413f00, 0xc000546551, 0x13, 0xc00054656a, 0x5, 0xc0005465be, 0x24, ...)
	/Users/lee/code/meshery/handlers/load_test_handler.go:331 +0x1094 fp=0xc000088ef0 sp=0xc000088d28 pc=0x5984af4
github.com/layer5io/meshery/handlers.(*Handler).loadTestHelperHandler.func2(0xc000a60180, 0xc001413f00, 0xc000546551, 0x13, 0xc00054656a, 0x5, 0xc0005465be, 0x24, 0xc000a406c0, 0x64b8660, ...)
	/Users/lee/code/meshery/handlers/load_test_handler.go:305 +0xe6 fp=0xc000088f78 sp=0xc000088ef0 pc=0x599fca6
runtime.goexit()
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000088f80 sp=0xc000088f78 pc=0x40750e1
created by github.com/layer5io/meshery/handlers.(*Handler).loadTestHelperHandler
	/Users/lee/code/meshery/handlers/load_test_handler.go:303 +0x666

goroutine 1 [chan receive, 2 minutes]:
main.main()
	/Users/lee/code/meshery/cmd/main.go:270 +0x2005

goroutine 6 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x744e5e0)
	/Users/lee/code/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/Users/lee/code/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0xd8

goroutine 20 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x744e6c0)
	/Users/lee/code/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:1107 +0x8b
created by k8s.io/klog/v2.init.0
	/Users/lee/code/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:416 +0xd8

goroutine 21 [chan receive, 2 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00052e820)
	/Users/lee/code/go/pkg/mod/github.com/klauspost/compress@v1.11.0/zstd/blockdec.go:215 +0x149
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/lee/code/go/pkg/mod/github.com/klauspost/compress@v1.11.0/zstd/blockdec.go:118 +0x173

goroutine 22 [chan receive, 2 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00052f520)
	/Users/lee/code/go/pkg/mod/github.com/klauspost/compress@v1.11.0/zstd/blockdec.go:215 +0x149
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/lee/code/go/pkg/mod/github.com/klauspost/compress@v1.11.0/zstd/blockdec.go:118 +0x173

goroutine 23 [chan receive, 2 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00052f930)
	/Users/lee/code/go/pkg/mod/github.com/klauspost/compress@v1.11.0/zstd/blockdec.go:215 +0x149
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/lee/code/go/pkg/mod/github.com/klauspost/compress@v1.11.0/zstd/blockdec.go:118 +0x173

goroutine 24 [chan receive, 2 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00052fa00)
	/Users/lee/code/go/pkg/mod/github.com/klauspost/compress@v1.11.0/zstd/blockdec.go:215 +0x149
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/lee/code/go/pkg/mod/github.com/klauspost/compress@v1.11.0/zstd/blockdec.go:118 +0x173

goroutine 25 [chan receive, 2 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00052fc70)
	/Users/lee/code/go/pkg/mod/github.com/klauspost/compress@v1.11.0/zstd/blockdec.go:215 +0x149
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/lee/code/go/pkg/mod/github.com/klauspost/compress@v1.11.0/zstd/blockdec.go:118 +0x173

goroutine 26 [chan receive, 2 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00069c270)
	/Users/lee/code/go/pkg/mod/github.com/klauspost/compress@v1.11.0/zstd/blockdec.go:215 +0x149
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/lee/code/go/pkg/mod/github.com/klauspost/compress@v1.11.0/zstd/blockdec.go:118 +0x173

goroutine 35 [syscall, 2 minutes]:
os/signal.signal_recv(0xc000635b00)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/sigqueue.go:165 +0x9d
os/signal.loop()
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/os/signal/signal.go:151 +0x45

goroutine 14 [select]:
github.com/vmihailenco/taskq/v3.(*Consumer).waitMessage(0xc000635b00, 0x6482db8, 0xc0000521c8, 0xc0000b00f0, 0x0)
	/Users/lee/code/go/pkg/mod/github.com/vmihailenco/taskq/v3@v3.0.0-beta.9.0.20200519124923-d9823546b85a/consumer.go:495 +0x117
github.com/vmihailenco/taskq/v3.(*Consumer).worker(0xc000635b00, 0x6482db8, 0xc0000521c8, 0x0)
	/Users/lee/code/go/pkg/mod/github.com/vmihailenco/taskq/v3@v3.0.0-beta.9.0.20200519124923-d9823546b85a/consumer.go:470 +0xfa
github.com/vmihailenco/taskq/v3.(*Consumer).addWorker.func1(0xc000635b00, 0x6482db8, 0xc0000521c8, 0xc000000000)
	/Users/lee/code/go/pkg/mod/github.com/vmihailenco/taskq/v3@v3.0.0-beta.9.0.20200519124923-d9823546b85a/consumer.go:275 +0x74
created by github.com/vmihailenco/taskq/v3.(*Consumer).addWorker
	/Users/lee/code/go/pkg/mod/github.com/vmihailenco/taskq/v3@v3.0.0-beta.9.0.20200519124923-d9823546b85a/consumer.go:273 +0xd3

goroutine 15 [select]:
github.com/vmihailenco/taskq/v3.(*Consumer).autotune(0xc000635b00, 0x6482db8, 0xc0000521c8, 0xc0003d3740)
	/Users/lee/code/go/pkg/mod/github.com/vmihailenco/taskq/v3@v3.0.0-beta.9.0.20200519124923-d9823546b85a/consumer.go:792 +0x111
github.com/vmihailenco/taskq/v3.(*Consumer).Start.func1(0xc000635b00, 0x6482db8, 0xc0000521c8, 0xc0003d3740)
	/Users/lee/code/go/pkg/mod/github.com/vmihailenco/taskq/v3@v3.0.0-beta.9.0.20200519124923-d9823546b85a/consumer.go:162 +0x76
created by github.com/vmihailenco/taskq/v3.(*Consumer).Start
	/Users/lee/code/go/pkg/mod/github.com/vmihailenco/taskq/v3@v3.0.0-beta.9.0.20200519124923-d9823546b85a/consumer.go:160 +0x14e

goroutine 16 [select, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc0001516c0, 0x6482d80, 0xc0001254c0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/database/sql/sql.go:1133 +0xb5
created by database/sql.OpenDB
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/database/sql/sql.go:740 +0x12a

goroutine 391 [IO wait]:
internal/poll.runtime_pollWait(0x104f1460, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000d39718, 0x72, 0x3d00, 0x3dbe, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000d39700, 0xc000cba000, 0x3dbe, 0x3dbe, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000d39700, 0xc000cba000, 0x3dbe, 0x3dbe, 0x1d7b, 0xc000cbc03e, 0x5)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc001070148, 0xc000cba000, 0x3dbe, 0x3dbe, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc0014225d0, 0xc000cba000, 0x3dbe, 0x3dbe, 0x1d7b, 0x744f7e0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc0009c4978, 0x6436ce0, 0xc0014225d0, 0x400d8c5, 0x5e15640, 0x606d1e0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc0009c4700, 0x10415b40, 0xc001070148, 0x5, 0xc001070148, 0x4fc)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0009c4700, 0x0, 0x0, 0x943cc81d)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc0009c4700, 0xc000e30000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/crypto/tls/conn.go:1276 +0x165
bufio.(*Reader).Read(0xc0003d2e40, 0xc000b3aff8, 0x9, 0x9, 0x44bee6b, 0xc000c15c78, 0x4008e85)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x6436ac0, 0xc0003d2e40, 0xc000b3aff8, 0x9, 0x9, 0x9, 0xc000b7bf70, 0x5f34e1c6a3400, 0xc000b7bf70)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/io/io.go:328 +0x87
io.ReadFull(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/io/io.go:347
golang.org/x/net/http2.readFrameHeader(0xc000b3aff8, 0x9, 0x9, 0x6436ac0, 0xc0003d2e40, 0x0, 0x0, 0x0, 0x0)
	/Users/lee/code/go/pkg/mod/golang.org/x/net@v0.0.0-20210525063256-abc453219eb5/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc000b3afc0, 0xc000f7f620, 0x0, 0x0, 0x0)
	/Users/lee/code/go/pkg/mod/golang.org/x/net@v0.0.0-20210525063256-abc453219eb5/http2/frame.go:492 +0xa5
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000c15fa8, 0x0, 0x0)
	/Users/lee/code/go/pkg/mod/golang.org/x/net@v0.0.0-20210525063256-abc453219eb5/http2/transport.go:1821 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000e24000)
	/Users/lee/code/go/pkg/mod/golang.org/x/net@v0.0.0-20210525063256-abc453219eb5/http2/transport.go:1743 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/Users/lee/code/go/pkg/mod/golang.org/x/net@v0.0.0-20210525063256-abc453219eb5/http2/transport.go:695 +0x6c5

goroutine 57 [select, 2 minutes]:
github.com/layer5io/meshery/models.(*RemoteProvider).SyncPreferences.func1(0xc000103b00)
	/Users/lee/code/meshery/models/remote_provider.go:186 +0xbe
created by github.com/layer5io/meshery/models.(*RemoteProvider).SyncPreferences
	/Users/lee/code/meshery/models/remote_provider.go:184 +0xf3

goroutine 55 [IO wait]:
internal/poll.runtime_pollWait(0x104f2110, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000759518, 0x72, 0x11300, 0x11351, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000759500, 0xc00098e000, 0x11351, 0x11351, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000759500, 0xc00098e000, 0x11351, 0x11351, 0x6e19, 0xc0005981a0, 0xd)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000524008, 0xc00098e000, 0x11351, 0x11351, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc0009badc8, 0xc00098e000, 0x11351, 0x11351, 0x6e19, 0x744f7e0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc000598278, 0x6436ce0, 0xc0009badc8, 0x400d8c5, 0x5e15640, 0x606d1e0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc000598000, 0x10415b40, 0xc000524008, 0x5, 0xc000524008, 0x9)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000598000, 0x0, 0x0, 0x435d03e)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc000598000, 0xc000b71000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/crypto/tls/conn.go:1276 +0x165
bufio.(*Reader).Read(0xc0000a6c00, 0xc000622118, 0x9, 0x9, 0x42fd5cb, 0xc000925c78, 0x4008e85)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x6436ac0, 0xc0000a6c00, 0xc000622118, 0x9, 0x9, 0x9, 0xc001035020, 0xc56833a93ba000, 0xc001035020)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/io/io.go:328 +0x87
io.ReadFull(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/io/io.go:347
net/http.http2readFrameHeader(0xc000622118, 0x9, 0x9, 0x6436ac0, 0xc0000a6c00, 0x0, 0x0, 0xc001031830, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/h2_bundle.go:1477 +0x89
net/http.(*http2Framer).ReadFrame(0xc0006220e0, 0xc001031830, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/h2_bundle.go:1735 +0xa5
net/http.(*http2clientConnReadLoop).run(0xc000925fa8, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/h2_bundle.go:8322 +0xd8
net/http.(*http2ClientConn).readLoop(0xc000001c80)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/h2_bundle.go:8244 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/h2_bundle.go:7208 +0x6c5

goroutine 58 [select, 2 minutes]:
github.com/layer5io/meshkit/utils/broadcast.(*broadcaster).run(0xc000ad4840)
	/Users/lee/code/go/pkg/mod/github.com/layer5io/meshkit@v0.2.25/utils/broadcast/broadcaster.go:52 +0xf3
created by github.com/layer5io/meshkit/utils/broadcast.NewBroadcaster
	/Users/lee/code/go/pkg/mod/github.com/layer5io/meshkit@v0.2.25/utils/broadcast/broadcaster.go:77 +0x105

goroutine 36 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x104f2028, 0x72, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000444698, 0x72, 0x0, 0x0, 0x6108843)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000444680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc000444680, 0x8be200594cdcc9ae, 0x15a94cdcc9ae, 0x100000001)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc00000e1e0, 0x613e62e7, 0xc000923d40, 0x409a586)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00000e1e0, 0xc000923d90, 0x18, 0xc000602f00, 0x433611b)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc000b3a000, 0x647dcd8, 0xc00000e1e0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2961 +0x285
net/http.(*Server).ListenAndServe(0xc000b3a000, 0xc000b3a000, 0xc000923f48)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2890 +0xba
net/http.ListenAndServe(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:3144
github.com/layer5io/meshery/router.(*Router).Run(0xc000b7f7e0, 0xc000000004, 0x6142569)
	/Users/lee/code/meshery/router/server.go:236 +0xfc
main.main.func1(0x2379, 0xc000b7f7e0)
	/Users/lee/code/meshery/cmd/main.go:266 +0xa5
created by main.main
	/Users/lee/code/meshery/cmd/main.go:264 +0x1fe9

goroutine 27 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x104f1f40, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0001d4098, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001d4080, 0xc000702000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0001d4080, 0xc000702000, 0x1000, 0x1000, 0xc00090100c, 0x10, 0xff4)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000010008, 0xc000702000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/net.go:183 +0x91
bufio.(*Reader).fill(0xc000632000)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc000632000, 0x2, 0x8555400, 0x100, 0x86fffff, 0x400, 0x8555500)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:139 +0x4f
github.com/gorilla/websocket.(*Conn).read(0xc00085e000, 0x2, 0x8555400, 0x20300000000000, 0x86fffff, 0x103f5028, 0x103f5028)
	/Users/lee/code/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:370 +0x46
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc00085e000, 0x0, 0x0, 0xc000580000)
	/Users/lee/code/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:798 +0x5c
github.com/gorilla/websocket.(*Conn).NextReader(0xc00085e000, 0x405b3a5, 0x40768a0, 0xc000bc91e0, 0xc085e48a9a, 0x15a885e48a9a)
	/Users/lee/code/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:980 +0x8f
github.com/99designs/gqlgen/graphql/handler/transport.(*wsConnection).readOp(0xc000a4b970, 0x9da48336)
	/Users/lee/code/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/handler/transport/websocket.go:295 +0x45
github.com/99designs/gqlgen/graphql/handler/transport.(*wsConnection).run(0xc000a4b970)
	/Users/lee/code/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/handler/transport/websocket.go:155 +0x19f
github.com/99designs/gqlgen/graphql/handler/transport.Websocket.Do(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x6238648, ...)
	/Users/lee/code/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/handler/transport/websocket.go:85 +0x3da
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc000ad48a0, 0x647dee8, 0xc0008b2460, 0xc000a80100)
	/Users/lee/code/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/handler/server.go:115 +0x21b
github.com/layer5io/meshery/handlers.(*Handler).GraphqlMiddleware.func1(0x647dee8, 0xc0008b2460, 0xc000a80000, 0xc000a406c0, 0xc000112190, 0x64b8660, 0xc000103b00)
	/Users/lee/code/meshery/handlers/middlewares.go:123 +0x4d
github.com/layer5io/meshery/handlers.(*Handler).SessionInjectorMiddleware.func1(0x647dee8, 0xc0008b2460, 0xc00054cc00)
	/Users/lee/code/meshery/handlers/middlewares.go:116 +0x5d3
net/http.HandlerFunc.ServeHTTP(0xc000b52480, 0x647dee8, 0xc0008b2460, 0xc00054cc00)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2049 +0x44
github.com/layer5io/meshery/handlers.(*Handler).AuthMiddleware.func1(0x647dee8, 0xc0008b2460, 0xc00054cc00)
	/Users/lee/code/meshery/handlers/middlewares.go:65 +0x129
net/http.HandlerFunc.ServeHTTP(0xc000ad4980, 0x647dee8, 0xc0008b2460, 0xc00054cc00)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2049 +0x44
github.com/layer5io/meshery/handlers.(*Handler).ProviderMiddleware.func1(0x647dee8, 0xc0008b2460, 0xc00054c500)
	/Users/lee/code/meshery/handlers/middlewares.go:33 +0x1e7
net/http.HandlerFunc.ServeHTTP(0xc000ad49e0, 0x647dee8, 0xc0008b2460, 0xc00054c500)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000192e40, 0x647dee8, 0xc0008b2460, 0xc00054c100)
	/Users/lee/code/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
net/http.serverHandler.ServeHTTP(0xc000b3a000, 0x647dee8, 0xc0008b2460, 0xc00054c100)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc000700000, 0x6482e28, 0xc0004dabc0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2993 +0x39b

goroutine 38 [select]:
github.com/99designs/gqlgen/graphql/handler/transport.(*wsConnection).keepAlive(0xc000a4b970, 0x6482d80, 0xc0005b4cc0)
	/Users/lee/code/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/handler/transport/websocket.go:183 +0xce
created by github.com/99designs/gqlgen/graphql/handler/transport.(*wsConnection).run
	/Users/lee/code/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/handler/transport/websocket.go:150 +0x165

goroutine 61 [IO wait]:
internal/poll.runtime_pollWait(0x104f1e58, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0005a0418, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0005a0400, 0xc00061a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0005a0400, 0xc00061a000, 0x1000, 0x1000, 0x883, 0xc000c11768, 0x432feca)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000114e28, 0xc00061a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/net.go:183 +0x91
net/http.(*connReader).Read(0xc00084d1d0, 0xc00061a000, 0x1000, 0x1000, 0x1, 0xc000c85440, 0x1)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:780 +0x1b9
bufio.(*Reader).fill(0xc0003d3ec0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).ReadSlice(0xc0003d3ec0, 0xa, 0xc000c11878, 0x597d1be, 0xc001436460, 0xc0010f3b00, 0x883)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:360 +0x3d
bufio.(*Reader).ReadLine(0xc0003d3ec0, 0x203000, 0x203000, 0x6482e28, 0xc0006dd1e8, 0xc000c11898, 0x4044dca)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:389 +0x34
net/textproto.(*Reader).readLineSlice(0xc0006a40f0, 0xc0015d2100, 0xc000c119e8, 0x4074d42, 0x405bacc, 0x403ce5c)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/textproto/reader.go:57 +0xd6
net/textproto.(*Reader).ReadLine(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/textproto/reader.go:38
net/http.readRequest(0xc0003d3ec0, 0x0, 0xc0015d2100, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/request.go:1027 +0xaa
net/http.(*conn).readRequest(0xc0005bfb80, 0x6482d80, 0xc000a604c0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:966 +0x19d
net/http.(*conn).serve(0xc0005bfb80, 0x6482e28, 0xc000a604c0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:1858 +0x705
created by net/http.(*Server).Serve
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2993 +0x39b

goroutine 39 [IO wait]:
internal/poll.runtime_pollWait(0x104f1d70, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000444a18, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000444a00, 0xc000aae000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000444a00, 0xc000aae000, 0x1000, 0x1000, 0xc000258000, 0xc00000ea68, 0x432feca)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0005248c0, 0xc000aae000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/net.go:183 +0x91
net/http.(*connReader).Read(0xc000a0b290, 0xc000aae000, 0x1000, 0x1000, 0x40b19b6, 0xc000ac194b, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:780 +0x1b9
bufio.(*Reader).fill(0xc000a407e0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).ReadSlice(0xc000a407e0, 0x406ce0a, 0xc00087cca0, 0x0, 0x0, 0xc000c9b818, 0x4081128)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:360 +0x3d
bufio.(*Reader).ReadLine(0xc000a407e0, 0x203000, 0x203000, 0xc0012dea18, 0xc000e8b7d0, 0x0, 0xc000c9b8b8)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:389 +0x34
net/textproto.(*Reader).readLineSlice(0xc000e87740, 0xc0010ffa00, 0xc000c9b9e8, 0x4074d42, 0x405bacc, 0x403ce5c)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/textproto/reader.go:57 +0xd6
net/textproto.(*Reader).ReadLine(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/textproto/reader.go:38
net/http.readRequest(0xc000a407e0, 0x0, 0xc0010ffa00, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/request.go:1027 +0xaa
net/http.(*conn).readRequest(0xc00081a6e0, 0x6482d80, 0xc0005b4d40, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:966 +0x19d
net/http.(*conn).serve(0xc00081a6e0, 0x6482e28, 0xc0005b4d40)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:1858 +0x705
created by net/http.(*Server).Serve
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2993 +0x39b

goroutine 62 [IO wait]:
internal/poll.runtime_pollWait(0x104f1c88, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0005a0498, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0005a0480, 0xc00061c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0005a0480, 0xc00061c000, 0x1000, 0x1000, 0xc000700320, 0xc0001112d8, 0x432feca)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000114e30, 0xc00061c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/net.go:183 +0x91
net/http.(*connReader).Read(0xc00084d2c0, 0xc00061c000, 0x1000, 0x1000, 0x40b19b6, 0xc0008b316b, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:780 +0x1b9
bufio.(*Reader).fill(0xc0003d3f20)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).ReadSlice(0xc0003d3f20, 0x406ce0a, 0xc00087ccb0, 0x0, 0x0, 0xc0006d5818, 0x4081128)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:360 +0x3d
bufio.(*Reader).ReadLine(0xc0003d3f20, 0x203000, 0x203000, 0xc0012dea18, 0xc000e8b7d0, 0x0, 0xc0006d58b8)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:389 +0x34
net/textproto.(*Reader).readLineSlice(0xc000ccd770, 0xc001413a00, 0xc0006d59e8, 0x4074d42, 0x405bacc, 0x403ce5c)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/textproto/reader.go:57 +0xd6
net/textproto.(*Reader).ReadLine(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/textproto/reader.go:38
net/http.readRequest(0xc0003d3f20, 0x0, 0xc001413a00, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/request.go:1027 +0xaa
net/http.(*conn).readRequest(0xc0005bfc20, 0x6482d80, 0xc000a60580, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:966 +0x19d
net/http.(*conn).serve(0xc0005bfc20, 0x6482e28, 0xc000a60580)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:1858 +0x705
created by net/http.(*Server).Serve
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2993 +0x39b

goroutine 65 [IO wait]:
internal/poll.runtime_pollWait(0x104f1ba0, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0005a0798, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0005a0780, 0xc000ca8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0005a0780, 0xc000ca8000, 0x1000, 0x1000, 0xc000700320, 0xc0001112d8, 0x432feca)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000114f70, 0xc000ca8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/net.go:183 +0x91
net/http.(*connReader).Read(0xc000c8ec60, 0xc000ca8000, 0x1000, 0x1000, 0x40b19b6, 0xc0008b332b, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:780 +0x1b9
bufio.(*Reader).fill(0xc0008ee9c0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).ReadSlice(0xc0008ee9c0, 0xc0010c980a, 0x432de14, 0xc000a60800, 0x737b006, 0x2, 0x2)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:360 +0x3d
bufio.(*Reader).ReadLine(0xc0008ee9c0, 0x203000, 0x203000, 0x0, 0x0, 0xc0010c9898, 0x4044dca)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:389 +0x34
net/textproto.(*Reader).readLineSlice(0xc0006be2a0, 0xc001413900, 0xc0010c99e8, 0x4074d42, 0x405bacc, 0x403ce5c)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/textproto/reader.go:57 +0xd6
net/textproto.(*Reader).ReadLine(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/textproto/reader.go:38
net/http.readRequest(0xc0008ee9c0, 0x0, 0xc001413900, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/request.go:1027 +0xaa
net/http.(*conn).readRequest(0xc0005bff40, 0x6482d80, 0xc000a607c0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:966 +0x19d
net/http.(*conn).serve(0xc0005bff40, 0x6482e28, 0xc000a607c0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:1858 +0x705
created by net/http.(*Server).Serve
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2993 +0x39b

goroutine 83 [IO wait]:
internal/poll.runtime_pollWait(0x104f1ab8, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0005a0918, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0005a0900, 0xc000cc4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0005a0900, 0xc000cc4000, 0x1000, 0x1000, 0xa6c, 0xc00126b768, 0x432feca)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000115010, 0xc000cc4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/net.go:183 +0x91
net/http.(*connReader).Read(0xc000c8f950, 0xc000cc4000, 0x1000, 0x1000, 0x1, 0xc000e8c070, 0x1)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:780 +0x1b9
bufio.(*Reader).fill(0xc0008efaa0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).ReadSlice(0xc0008efaa0, 0xa, 0xc00126b878, 0x597d1be, 0xc0014362a0, 0xc001222c00, 0xa6c)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:360 +0x3d
bufio.(*Reader).ReadLine(0xc0008efaa0, 0x203000, 0x203000, 0x6482e28, 0xc0006dd0f8, 0xc00126b898, 0x4044dca)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:389 +0x34
net/textproto.(*Reader).readLineSlice(0xc000ccd200, 0xc00130b200, 0xc00126b9e8, 0x4074d42, 0x405bacc, 0x403ce5c)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/textproto/reader.go:57 +0xd6
net/textproto.(*Reader).ReadLine(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/textproto/reader.go:38
net/http.readRequest(0xc0008efaa0, 0x0, 0xc00130b200, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/request.go:1027 +0xaa
net/http.(*conn).readRequest(0xc000cb2140, 0x6482d80, 0xc000a60940, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:966 +0x19d
net/http.(*conn).serve(0xc000cb2140, 0x6482e28, 0xc000a60940)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:1858 +0x705
created by net/http.(*Server).Serve
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2993 +0x39b

goroutine 84 [select]:
github.com/layer5io/meshery/handlers.(*Handler).loadTestHelperHandler(0xc000a60180, 0x647dee8, 0xc001436540, 0xc001413f00, 0xc000546551, 0x13, 0xc00054656a, 0x5, 0xc0005465be, 0x24, ...)
	/Users/lee/code/meshery/handlers/load_test_handler.go:308 +0x6e5
github.com/layer5io/meshery/handlers.(*Handler).LoadTestHandler(0xc000a60180, 0x647dee8, 0xc001436540, 0xc001413f00, 0xc000a406c0, 0xc00137e050, 0x64b8660, 0xc000103b00)
	/Users/lee/code/meshery/handlers/load_test_handler.go:255 +0x8f2
github.com/layer5io/meshery/handlers.(*Handler).SessionInjectorMiddleware.func1(0x647dee8, 0xc001436540, 0xc001413d00)
	/Users/lee/code/meshery/handlers/middlewares.go:116 +0x5d3
net/http.HandlerFunc.ServeHTTP(0xc000b53350, 0x647dee8, 0xc001436540, 0xc001413d00)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2049 +0x44
github.com/layer5io/meshery/handlers.(*Handler).AuthMiddleware.func1(0x647dee8, 0xc001436540, 0xc001413d00)
	/Users/lee/code/meshery/handlers/middlewares.go:65 +0x129
net/http.HandlerFunc.ServeHTTP(0xc00059ace0, 0x647dee8, 0xc001436540, 0xc001413d00)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2049 +0x44
github.com/layer5io/meshery/handlers.(*Handler).ProviderMiddleware.func1(0x647dee8, 0xc001436540, 0xc001413c00)
	/Users/lee/code/meshery/handlers/middlewares.go:33 +0x1e7
net/http.HandlerFunc.ServeHTTP(0xc00059ad00, 0x647dee8, 0xc001436540, 0xc001413c00)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000192e40, 0x647dee8, 0xc001436540, 0xc0015d2200)
	/Users/lee/code/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
net/http.serverHandler.ServeHTTP(0xc000b3a000, 0x647dee8, 0xc001436540, 0xc0015d2200)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc000cb21e0, 0x6482e28, 0xc000a60a00)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:2993 +0x39b

goroutine 1179 [select]:
net/http.(*persistConn).writeLoop(0xc000fa18c0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:1744 +0xc9c

goroutine 69 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x104f1630, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00087c498, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00087c480, 0xc0005f9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc00087c480, 0xc0005f9000, 0x1000, 0x1000, 0x403ce5c, 0xc000657c38, 0x406bd60)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000524130, 0xc0005f9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/net.go:183 +0x91
net/http.(*persistConn).Read(0xc0003eefc0, 0xc0005f9000, 0x1000, 0x1000, 0xc0006658c0, 0xc000657d40, 0x4007635)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc000632e40)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc000632e40, 0x1, 0x0, 0x1, 0x4, 0x1, 0x3)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc0003eefc0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:1743 +0xc77

goroutine 70 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc0003eefc0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:1744 +0xc9c

goroutine 1178 [IO wait]:
internal/poll.runtime_pollWait(0x104f1718, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000ea0798, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000ea0780, 0xc0010f6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000ea0780, 0xc0010f6000, 0x1000, 0x1000, 0x403ce5c, 0xc000762c38, 0x406bd60)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000fc2240, 0xc0010f6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/net.go:183 +0x91
net/http.(*persistConn).Read(0xc000fa18c0, 0xc0010f6000, 0x1000, 0x1000, 0xc00118d680, 0xc000762d40, 0x4007635)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc000e4f2c0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc000e4f2c0, 0x1, 0x0, 0x1, 0x4, 0x1, 0x3)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc000fa18c0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:1743 +0xc77

goroutine 1266 [IO wait]:
internal/poll.runtime_pollWait(0x104f19d0, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0005a0998, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0005a0980, 0xc000c8fa21, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0005a0980, 0xc000c8fa21, 0x1, 0x1, 0xc000e4e720, 0x0, 0xc000a60618)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000115018, 0xc000c8fa21, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xc000c8fa10)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:672 +0x58
created by net/http.(*connReader).startBackgroundRead
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/server.go:668 +0xd5

goroutine 1254 [select]:
net/http.(*persistConn).writeLoop(0xc001513c20)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:1744 +0xc9c

goroutine 1253 [IO wait]:
internal/poll.runtime_pollWait(0x875e000, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000ea0c98, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000ea0c80, 0xc0015d5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000ea0c80, 0xc0015d5000, 0x1000, 0x1000, 0xc000118cb0, 0xc000118c68, 0x40a647d)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000fc2530, 0xc0015d5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/net.go:183 +0x91
net/http.(*persistConn).Read(0xc001513c20, 0xc0015d5000, 0x1000, 0x1000, 0x4007570, 0x60, 0x0)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc0003d3380)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc0003d3380, 0x1, 0xc0010e1020, 0xc000118d90, 0x404cf0c, 0xc000665198, 0x18)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc001513c20)
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go@1.16/1.16.7/libexec/src/net/http/transport.go:1743 +0xc77

goroutine 1268 [chan receive]:
github.com/layer5io/meshery/handlers.(*Handler).loadTestHelperHandler.func1(0xc000a60180, 0xc000c7aba0, 0x647dee8, 0xc001436540, 0x8759fc0, 0xc001436540, 0xc001766720)
	/Users/lee/code/meshery/handlers/load_test_handler.go:285 +0x8d
created by github.com/layer5io/meshery/handlers.(*Handler).loadTestHelperHandler
	/Users/lee/code/meshery/handlers/load_test_handler.go:279 +0x5a5
exit status 2
make: *** [run-fast] Error 1
```

#### Environment

- **Host OS:** Mac
- **Platform:** locally built - - missing Nighthawk binary on local Mac
- **Meshery Server Version:** stable-v0.5.56

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by DelusionalOptimist**
Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>**Description**

This PR fixes #4174 fixes #3273 

**Notes for Reviewers**
* Use nighthawk's default value when user specified query == 0.
* Check if nighthawk binary exists before executing test.
* URLs given to nighthawk were missing paths. Load was being generated only on the host service. This PRs fixes that.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

File: helpers/load_test_interface.go [hunk 1]
```diff
@@ -174,8 +175,19 @@ func WRK2LoadTest(opts *models.LoadTestOptions) (map[string]interface{}, *period
...
+	if err != nil {
+		return ErrStartingNighthawkServer(err)
+	}
+
+	command := filepath.Join(curDir, "nighthawk_service")
+	transformCommand := filepath.Join(curDir, "nighthawk_output_transform")
+
+	_, err = os.Stat(command)
+	if err != nil {
+		return ErrStartingNighthawkServer(err)
```
Comment (leecalcote) [inline helpers/load_test_interface.go:189]: Should we deviate from MeshKit-style errors?

Comment (DelusionalOptimist) [reply helpers/load_test_interface.go:189]: Sir, this is a MeshKit error defined here https://github.com/meshery/meshery/blob/d21b9d0f9e7ea40dfc666a325b4cd31e4e98dc4d/helpers/error.go#L131
:stuck_out_tongue:

Comment (leecalcote) [reply helpers/load_test_interface.go:189]: I refuse to be spoken to this way. Your slight corrections and polite edifications are.... well... they just leave me no room to piss and moan and... I'm just not sure what to do when this sort of thing happens.

**Review by leecalcote — APPROVED** [review]
These have haunted Meshery for some time. Thanks for this, @DelusionalOptimist
