### PR TITLE
Fix chevron visibility

### LINKED ISSUE #4709: [UI] Navigator Collapse Chevron Position
#### Current Behavior
The chevron is not responsive with respect to the aspect ratio.

https://user-images.githubusercontent.com/65453826/144587094-626c1ed0-c999-4b59-93bb-2e919e837ce7.mp4

#### Desired Behavior
The chevron should also hide when the navigator is fully collapsed/hidden accordingly to the window aspect ratio.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Prakhar-Agarwal-byte**
**Description**

This PR fixes #4709

**Notes for Reviewers**
Chevron will hide when the drawer is completely closed

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by bariqhibat — CHANGES_REQUESTED** [review]
Hey @Prakhar-Agarwal-byte, thanks for the contribution! Seems like this PR is a bit too big for this changes, could you help revert the `package-lock.json` to the original state, then we can move this PR forward? Thanks! Look forward to this

**Comment by Prakhar-Agarwal-byte** [comment]
@bariqhibat Done

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
@Prakhar-Agarwal-byte There appears to be extra whitespace on the left. Could you please take a look at that. 
Screenshot 2021-12-09 at 12 37 33 PM

File: ui/components/Navigator.js [hunk 1]
```diff
@@ -963,7 +963,9 @@ class Navigator extends React.Component {
     const { path, showHelperButton } = this.state;
     this.updateCategoriesMenus();
     let classname;
-    if (isDrawerCollapsed) {
+    if (other.open == false) {
```
Comment (Nikhil-Ladha) [inline ui/components/Navigator.js:966]: A simple `boolean` check like `if(!other.open)` should be fine?

**Comment by warunicorn19** [comment]
you might consider defining the chevron in a `const` and then call it in the Drawer.

**Comment by Prakhar-Agarwal-byte** [comment]
@warunicorn19 I didn't completely understand. Should I create a new component for it?

**Comment by warunicorn19** [comment]
Yeah, that is sort of what i was suggesting, but you could take any approach you'd like.

**Comment by Prakhar-Agarwal-byte** [comment]
@Nikhil-Ladha  @warunicorn19 I have changed the logic a bit. Please review now

File: ui/components/Navigator.js [hunk 2]
```diff
@@ -1168,6 +1169,7 @@ class Navigator extends React.Component {
     )
     return (
       <NoSsr>
+        { (!("open" in other) || other.open) &&
```
Comment (Abhishek-kumar09) [inline ui/components/Navigator.js:1172]: What is other here?

Comment (Prakhar-Agarwal-byte) [reply ui/components/Navigator.js:1172]: other is rest of the props passed into Navigator component. It's defined above

**Review by warunicorn19 — APPROVED** [review]
LGTM!

File: ui/components/Navigator.js (hunk 2 above)
Comment (Abhishek-kumar09) [reply ui/components/Navigator.js:1172]: oh okay, thanks :+1:

Comment (Abhishek-kumar09) [reply ui/components/Navigator.js:1172]: `!("open" in other)` does this affects the functionality? 
I think the two sides of `OR` condition are somewhat same, or is it required.

Comment (Prakhar-Agarwal-byte) [reply ui/components/Navigator.js:1172]: 1. The first condition checks if the key (i.e. "open") is not present (The key is not present in desktop mode, so it will always show the chevron)

2. The second condition checks if the key is present then is it also true (The key is present which means currently mobile mode is visible, then it checks if the drawer is open `other.open` ,  so it shows the chevron) 

It tested it both with and without the the first condition and found that it is required for correct functioning

**Review by sudo-NithishKarthik — APPROVED** [review]
LGTM 🎉 
Just one thing @Prakhar-Agarwal-byte , please do attach screenshots or screen recordings if possible, it helps making comments on UI easy.
