### PR TITLE
fix: add tooltip on actions buttons

### LINKED ISSUE #6410: [UI] Tooltip for action buttons in Table View
#### Current Behavior

Table View of Patterns Tab in Configuration:
Screenshot 2022-10-19 at 8 37 11 PM

No Tooltip on hover on one of the action buttons.

#### Desired Behavior
Screenshot 2022-10-19 at 8 36 51 PM

User should see a tooltip describing the action to be performed, similar to what is shown above (Grid View of Patterns in Configuration)

I see a delay (too long) before tooltip is shown in GridView, possibly reduce this delay.
#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Udit-takkar**
Signed-off-by: Udit Takkar <udit.07814802719@cse.mait.ac.in>

This PR fixes #6410 

added tooltip to the action button in table view and grid view as mentioned in the issue.

Screenshot 2022-11-19 at 10 38 09 PM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/MesheryPatterns/MesheryPatternCard.js [hunk 1]
```diff
@@ -20,6 +20,16 @@ import PublicIcon from '@material-ui/icons/Public';
 
 const INITIAL_GRID_SIZE = { xl : 4, md : 6, xs : 12 };
 
+function TooltipButton({ children, onClick, title, className, variant,...props }) {
```
Comment (Chadha93) [inline ui/components/MesheryPatterns/MesheryPatternCard.js:23]: @Udit-takkar This is a good one to be added in `utils` as a global reusable component. Would you also use this across all configurations? - filters/applications/designs

File: ui/components/MesheryPatterns.js [hunk 2]
```diff
@@ -1118,6 +1117,7 @@ function MesheryPatterns({
           </div>
           }
         </div>
+        {console.log(patterns)}
```
Comment (Chadha93) [inline ui/components/MesheryPatterns.js:1120]: can be removed safely. :)

File: ui/components/MesheryPatterns/MesheryPatternCard.js (hunk 1 above)
Comment (Udit-takkar) [reply ui/components/MesheryPatterns/MesheryPatternCard.js:23]: ok sure

Comment (Udit-takkar) [reply ui/components/MesheryPatterns/MesheryPatternCard.js:23]: @Chadha93  can you tell how to import data in filter ?
Screenshot 2022-11-19 at 11 22 24 PM

Comment (Chadha93) [reply ui/components/MesheryPatterns/MesheryPatternCard.js:23]: You should be able to see public filters by clicking the Catalog eye button. 
And you can import the filters from raw url example - https://raw.githubusercontent.com/service-mesh-patterns/service-mesh-patterns/master/samples/IstioFilterPattern.yaml

**Comment by Udit-takkar** [comment]
@Chadha93  made the changes everywhere

**Comment by Udit-takkar** [comment]
@Chadha93 sorry i was not available at that time. although i'll be joining the new comers meeting tomorrow. can we can discuss it there?

File: ui/components/MesheryFilters/FiltersCard.js [hunk 3]
```diff
@@ -112,16 +114,17 @@ function FiltersCard({
               >
                 <DoneAllIcon className={classes.iconPatt}/>
               Deploy
-              </Button>
-              {visibility === "public" ? <Button
+              </TooltipButton>
+              {visibility === "public" ? <TooltipButton
+                title="clone"
```
Comment (leecalcote) [inline ui/components/MesheryFilters/FiltersCard.js:119]: Please be consistent with capitalization.

**Comment by leecalcote** [comment]
> @Chadha93 sorry i was not available at that time. although i'll be joining the new comers meeting tomorrow. can we can discuss it there?

Sounds great to me!

File: ui/components/MesheryFilters/FiltersCard.js (hunk 3 above)
Comment (Udit-takkar) [reply ui/components/MesheryFilters/FiltersCard.js:119]: @leecalcote sorry didn't understand what you mean by  consistent with capitalization. Do you mean  TooltipButton should be named something else?

Comment (leecalcote) [reply ui/components/MesheryFilters/FiltersCard.js:119]: No, the text contained within. e.g. Clone

Comment (Udit-takkar) [reply ui/components/MesheryFilters/FiltersCard.js:119]: Got it

**Comment by leecalcote** [comment]
@Udit-takkar was a verdict arrived at?

**Comment by leecalcote** [comment]
@Chadha93 is out this week. @eeshaanSA might be hosting, though.

**Comment by Chadha93** [comment]
@Udit-takkar Please add this as an agenda item, if you would, in the Meshery [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) for feedback/review.

**Comment by Chadha93** [comment]
@Udit-takkar Apologies for missing out on this PR. Could you please resolve the Merge conflicts, Let's merge then. 
Thank you for presenting this in the Dev call. :+1:

**Comment by Udit-takkar** [comment]
@Chadha93 done rebased now.

**Review by Chadha93 — APPROVED** [review]
LGTM
