### PR TITLE
Fix theme toggle failure on first click in preferences

### LINKED ISSUE #13087: [UI] First Click in Preferences Fails to Change Theme
### Current Behavior

When attempting to change the theme through the Preferences menu, the theme does not apply on the first click

### Desired Behavior

When a user selects a theme from the Preferences menu and applies the change, the theme should immediately update across the UI on the first click

### Screenshots/Logs

[Screencast from 01-01-25 10:10:48 PM IST.webm](https://github.com/user-attachments/assets/2f8e5ba2-03c4-4ca8-8339-bce468d6804f)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Tharanishwaran**
**Notes for Reviewers**

- This PR fixes #13087 

## Video/Logs

https://github.com/user-attachments/assets/2b4566c7-c40c-4745-8b79-3f3e006782e7

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tharanishwaran** [comment]
Hi @aabidsofi19  could you please review this PR and let me know if any changes are needed for merging?

**Comment by vishalvivekm** [comment]
@Tharanishwaran 
Thank you for your contributions! Let's discuss this today, during Meshery Development call at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1&tab=t.0#) || [meeting link.](https://meet.layer5.io/meshery)

**Comment by Tharanishwaran** [comment]
Hi @Yashsharma1911   could you please review this PR and let me know if any changes are needed.

File: ui/components/UserPreferences/index.js [hunk 1]
```diff
@@ -165,28 +165,31 @@ const styles = (theme) => ({
...
+            color="primary"
+            classes={{
+              switchBase: classes.switchBase,
+              track: classes.track,
+              checked: classes.checked,
+            }}
+            checked={mode === 'dark'}
+            onChange={() => {
+              toggleTheme();
+              handleUpdateUserPref(mode === 'dark' ? 'light' : 'dark');
```
Comment (Yashsharma1911) [inline ui/components/UserPreferences/index.js:183]: Why are we passing `light` when mode is `dark`?

**Review by Yashsharma1911 — COMMENTED** [review]
Other then this it looks good to me

File: ui/components/UserPreferences/index.js (hunk 1 above)
Comment (Tharanishwaran) [reply ui/components/UserPreferences/index.js:183]: We pass 'light' when mode is 'dark' because that's the theme we want to switch TO when a user clicks the toggle.

Comment (Tharanishwaran) [reply ui/components/UserPreferences/index.js:183]: When checked={mode === 'dark'} is true and user clicks switch, they want to change TO light mode, so we pass 'light' to handleUpdateUserPref.

**Comment by Tharanishwaran** [comment]
Hi @vishalvivekm could you please review this PR and let me know if any changes are needed.

File: ui/components/UserPreferences/index.js (hunk 1 above)
Comment (Yashsharma1911) [reply ui/components/UserPreferences/index.js:183]: Okay I see makes sense

**Review by Yashsharma1911 — DISMISSED** [review]
LGTM now

**Comment by Yashsharma1911** [comment]
Please resolve merge conflict

**Comment by Tharanishwaran** [comment]
@Yashsharma1911 Thank you so much for the review! I'll take care of those merge conflicts right away.

**Comment by Tharanishwaran** [comment]
@sudhanshutech  could you please review this PR and let me know if any changes are needed for merging ?

**Comment by Tharanishwaran** [comment]
@leecalcote
