### PR TITLE
[mesheryctl] fix Bug: `system reset` on `stable` channel breaks if no version is specified

### LINKED ISSUE #2366: [mesheryctl] Bug: `system reset` on `stable` channel breaks if no version is specified
#### Description

When `mesheryctl system reset` is run it will fetch the `docker-compose.yaml` file from GitHub corresponding to the `channel` and `version` specified in the `current-context`. 

If the `channel` is `stable` and the `version` is not specified in the `config.yaml` file in the `~/.meshery` folder, it will fail to pick up a valid file.

`version` _is not specified by default when Meshery is installed._

Example `config.yaml` where `system reset` fails-

```
(base) user@computer:~/.meshery$ cat config.yaml 
contexts:
  local:
    endpoint: http://localhost:9081
    token:
      name: Default
      location: auth.json
    platform: kubernetes
    adapters:
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-octarine
    - meshery-nsm
    - meshery-kuma
    - meshery-cpx
    - meshery-osm
    - meshery-nginx-sm
    channel: stable #stable channel but version is not specified
current-context: local
tokens: {}
```

Here, `system reset` will try to pick up a file from `fileURL = "https://raw.githubusercontent.com/layer5io/meshery/" + currVersion + "/docker-compose.yaml"` (line 83 in reset.go).

Since there is no current version specified, the URL will be `https://raw.githubusercontent.com/layer5io/meshery/docker-compose.yaml` which is invalid.

#### Expected Behavior

Instead if the `channel` is `stable` and the `version` is not specified in the `config.yaml` file, it should pick up the `docker-compose.yaml` file from the latest release(_not the edge release but the latest stable release_).

_May need to use GitHub API for this._

### PR DESCRIPTION
**Pull request by aneeshnema**
**Description**

This PR fixes #2366 
- Added a helper function `GetLatestStableReleaseTag` in `mesheryctl/pkg/utils/helpers.go` to fetch latest stable release tag using GitHub API
- This is later used by `resetMesheryConfig` in case no version is specified while using `stable` channel

**Notes for Reviewers**
Should I rather move the `GetLatestStableReleaseTag` logic inside the `resetMesheryConfig` itself? (will have to import additional packages in `reset.go` which are already imported in `helpers.go`)

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/internal/cli/root/system/reset.go [hunk 1]
```diff
@@ -80,6 +80,13 @@ func resetMesheryConfig() error {
 		if currChannel == "edge" {
 			fileURL = "https://raw.githubusercontent.com/layer5io/meshery/master/docker-compose.yaml"
 		} else if currChannel == "stable" {
+			if currVersion == "" {
+				log.Info("Version unspecified, fetching latest stable release...\n")
```
Comment (navendu-pottekkat) [inline mesheryctl/internal/cli/root/system/reset.go:84]: We may not need to log this to the user. It would be confusing.

Since we output the version at the end, I don't think we need this. If this looks good to everyone, then don't mind me.

File: mesheryctl/pkg/utils/helpers.go [hunk 2]
```diff
@@ -591,3 +591,24 @@ func ValidateURL(URL string) error {
 	}
 	return nil
 }
+
+// GetLatestStableReleaseTag fetch and return latest stable release tag
+func GetLatestStableReleaseTag() (string, error) {
```
Comment (navendu-pottekkat) [inline mesheryctl/pkg/utils/helpers.go:596]: This function is neat! It would be best to have it in the helpers.go file as this would be reused in the future.

Maybe this small change in the function doc.
```suggestion
// GetLatestStableReleaseTag fetches and returns the latest release tag from GitHub
func GetLatestStableReleaseTag() (string, error) {
```

**Review by navendu-pottekkat — APPROVED** [review]
That was fast and neat @aneeshnema . LGTM. 💯

I have _suggested_ some small changes.

The rest looks good and you can merge.

**Comment by navendu-pottekkat** [comment]
> Should I rather move the GetLatestStableReleaseTag logic inside the resetMesheryConfig itself? (will have to import additional packages in reset.go which are already imported in helpers.go)

We can have this function in the `helpers.go` file itself. We will need to add the `context` support and `platform` support for some more commands and it would be reused a lot.

File: mesheryctl/internal/cli/root/system/reset.go (hunk 1 above)
Comment (aneeshnema) [reply mesheryctl/internal/cli/root/system/reset.go:84]: I was also a little confused about this while adding it. Seemed a little verbose. Let's see what others suggest 👀.

Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/reset.go:84]: Yes, that is what I thought. Maybe this could be a debug(verbose) log?

**Comment by anirudhjain75** [comment]
Nice work @aneeshnema . The changes are looking great.

**Review by anirudhjain75 — DISMISSED** [review]
I still see the logs in the file, I agree that removing it would be better

File: mesheryctl/internal/cli/root/system/reset.go (hunk 1 above)
Comment (aneeshnema) [reply mesheryctl/internal/cli/root/system/reset.go]: removed it ✔

**Review by navendu-pottekkat — APPROVED** [review]
LGTM

**Review by leecalcote — APPROVED** [review]
