### PR TITLE
[mesheryctl] Unit Tests for `mesheryctl exp relationships generate` command

### LINKED ISSUE #12135: Create Unit and Integration Tests for `mesheryctl relationships generate`Command`
### Description
We need to create unit and integration tests for the `mesheryctl relationships generate` command. This command is responsible for generating relationship documents by fetching data from a Google Spreadsheet and saving the processed data in JSON format.

The goal of these tests is to ensure that the command functions correctly, handles errors appropriately, and processes the data as expected. This will improve the reliability of the feature and allow for better debugging in case of issues.

---

### Current Behavior
At present, there are no tests covering the functionality of the `mesheryctl relationships generate` command, which includes:
- Fetching data from a Google Spreadsheet.
- Parsing and validating the data.
- Creating and writing the data to a JSON file.

### Desired Behavior
Tests should be created to verify the following:
1. **Successful Data Fetching**: Verify that the command can successfully fetch data from a Google Spreadsheet using valid credentials and a valid sheet ID.
2. **Data Parsing and Validation**: Ensure that the fetched data is parsed correctly and matches the expected structure (columns such as `Model`, `Version`, `Kind`, etc.).
3. **Error Handling**: The following error cases should be tested:
    - Missing or invalid Google Sheet credentials.
    - Missing or invalid sheet ID.
    - Network errors or failed API responses.
    - Empty or improperly formatted data in the Google Sheet.
    - Missing or unreadable file paths.
4. **File Writing**: Verify that the processed data is written correctly to the `docs/_data/RelationshipsData.json` file and is formatted as expected.

### Suggested Test Cases
- **Test Case 1**: Successfully fetching and generating relationships data from a valid Google Spreadsheet.
- **Test Case 2**: Handling missing Google Sheet credentials (ensure that the appropriate error is returned).
- **Test Case 3**: Handling missing or invalid sheet ID.
- **Test Case 4**: Simulating an empty spreadsheet and ensuring that a proper message is logged (`No data(relationships) found in the sheet`).
- **Test Case 5**: Ensuring that the `docs/_data/RelationshipsData.json` file is generated and contains the correct data structure.
- **Test Case 6**: Handling improperly formatted data (e.g., missing fields or invalid data types in the sheet).

### Implementation Details
- Mock the Google Sheets API using a suitable mock package to simulate API responses for testing.
- Use existing test suites and patterns for `mesheryctl`.
- Add file system checks to ensure that the correct JSON file is created and contains the expected data.

### Resources
- The file to be tested: `mesheryctl/pkg/exp/relationships/generate.go`
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by riyaa14**
**Notes for Reviewers**

- This PR fixes #12135 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

**Tests Covered**
- [x] Data Parsing and Validation: Ensure that the fetched data is parsed correctly and matches the expected structure (columns such as Model, Version, Kind, etc.).
- [x] Error Handling: Missing Google Sheet credentials, Missing sheet ID

**Implementation Details**
1. `TestExperimentalGenerate_CreateJsonFile` : CreateJsonFile is the core logic of relationship generate command, thus a unit test ensuring that a mock google sheet API response in form of `ValueRange` object is correctly parsed into a JSON file in expected format.
2. `TestExperimentalGenerate_MissingArguments` : This test covers - missing credentials and sheet ID

**Note:** `TestExperimentalGenerate_MissingArguments` is in `experimental` package because command `relationship generate` is under experimental feature currently. The command doesn't execute under `relationship` package.

### CODE REVIEW

File: mesheryctl/internal/cli/root/experimental/generate_test.go [hunk 1]
```diff
@@ -107,3 +108,42 @@ func TestExperimentalGenerate(t *testing.T) {
 
 	utils.StopMockery(t)
 }
+
+func TestExperimentalGenerate_MissingArguments(t *testing.T) {
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/experimental/generate_test.go:112]: looks to me this should be in `relationships/generate_test.go` as well

Comment (riyaa14) [reply mesheryctl/internal/cli/root/experimental/generate_test.go:112]: > looks to me this should be in `relationships/generate_test.go` as well

The `TestExperimentalGenerate_MissingArguments` makes use of `exp relationship generate` command. (line - 141)

The problem with shifting this test to `relationships/generate_test.go` is that the command won't be able to execute because currently `relationship generate` isn't under available commands.

The command - `exp relationship generate` would work, which comes under experimental package and thus, I had to shift this test to `experimental` package so that the command could be executed. I mentioned the same as a note in the PR, but I hope this explanation clarifies it. Thanks for reviewing!

File: mesheryctl/internal/cli/root/relationships/generate_test.go [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+		Range:          "Relationships!A1:O1000",
+		Values: [][]interface{}{
+			{},
+			{},
+			sheetDataParsed["ROW3"].([]interface{}),
+		},
+	}
+
+	// for testing, relative path is required in createJsonFile function
+	jsonFilePath := "../../../../../docs/_data/RelationshipsDataTest.json"
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/generate_test.go:37]: should use golden files instead 

example of implementation

File: mesheryctl/internal/cli/root/experimental/generate_test.go (hunk 1 above)
Comment (lekaf974) [reply mesheryctl/internal/cli/root/experimental/generate_test.go:112]: just retake a look on this you just need to move the test and replace the command after it is done otherwise we will need to do it once the registry command will be promoted.

File: mesheryctl/internal/cli/root/relationships/generate_test.go (hunk 2 above)
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/generate_test.go:37]: Can we create the file in a testdata folder instead ?

File: mesheryctl/internal/cli/root/experimental/generate_test.go (hunk 1 above)
Comment (riyaa14) [reply mesheryctl/internal/cli/root/experimental/generate_test.go:112]: > just retake a look on this you just need to move the test and replace the command after it is done otherwise we will need to do it once the registry command will be promoted.

I moved the test to `relationships/generate_test.go` and replaced the command with `GenerateRelationshipDocsCmd`
image

and here's the error I get
image

arguments tried - [the first one should be correct but tried others just in case]
1. generate
2. relationship generate
3. exp relationship generate

The error suggests that I am using the wrong command, and when I checked the mesheryctl available commands, it doesn't have this command - `mesheryctl relationship generate` currently, `exp` needs to be added, which isn't possible from relationships package.

Comment (lekaf974) [reply mesheryctl/internal/cli/root/experimental/generate_test.go:112]: @riyaa14, ok keep it as previous we will re-work on it later.

**Review by lekaf974 — APPROVED** [review]
LGTM

**Comment by lekaf974** [comment]
@alphaX86 could you have a second review

**Review by alphaX86 — APPROVED** [review]
