### PR TITLE
[CI] Stabilize go-testing-ci.yml Workflow by Fixing Flaky Tests

### LINKED ISSUE #15311: [CI] CI/CD Pipeline: go-testing-ci.yml is Frequently Failing
### Current Behavior
The [go-testing-ci.yml](https://github.com/meshery/meshery/actions/workflows/go-testing-ci.yml) workflow in the repository fails frequently, disrupting the development workflow. This instability makes it difficult to reliably validate code changes and merge pull requests.

### Desired Behavior
All tests in the workflow should pass consistently. The CI/CD pipeline should provide accurate feedback on code quality and integration status, without frequent or flaky failures.

### Implementation
- Investigate and address common points of failure in the workflow jobs.
- Review and stabilize flaky or unreliable tests.
- Improve error logging to make debugging failures easier.

### Acceptance Tests
- All jobs in the go-testing-ci.yml workflow pass consistently for new pull requests and commits.
- Contributors can rely on the CI status to reflect actual code quality and integration state.
- Flaky failures are identified, documented, and addressed.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

### PR DESCRIPTION
**Pull request by yash37158**
**Notes for Reviewers**
This PR addresses the frequent failures in the go-testing-ci.yml workflow by identifying and fixing unstable tests, improving CI job reliability, and enhancing error logging for better debugging.

- This PR fixes #15311

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by yash37158** [comment]
@lekaf974 The "broken pipe" error continues to impact our tests, and it appears to be a systemic issue affecting multiple test cases across the infrastructure. Do you have any insights or suggestions on how we should proceed with resolving this?

File: mesheryctl/internal/cli/root/environments/list.go [hunk 1]
```diff
@@ -15,69 +15,75 @@
...
+        }
+        return nil
+    },
+    RunE: func(cmd *cobra.Command, args []string) error {
+        orgID, _ := cmd.Flags().GetString("orgID")
 
-		environmentResponse, err := api.Fetch[environments.EnvironmentPage](fmt.Sprintf("api/environments?orgID=%s", orgID))
+        // Validate UUID before making API call
+        if _, err := uuid.Parse(orgID); err != nil {
+            return fmt.Errorf("invalid organization ID format: %w", err)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/environments/list.go]: This should be convert to a meshkit error 
documentation: https://docs.meshery.io/project/contributing/contributing-error
example: https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/registry/error.go

File: mesheryctl/internal/cli/root/environments/list.go [hunk 2]
```diff
@@ -15,69 +15,75 @@
...
-		}
+        environmentResponse, err := api.Fetch[environments.EnvironmentPage](fmt.Sprintf("api/environments?orgID=%s", orgID))
 
-		header := []string{"ID", "Name", "Organization ID", "Description", "Created At", "Updated At"}
-		rows := [][]string{}
-		for _, environment := range environmentResponse.Environments {
-			rows = append(rows, []string{environment.ID.String(), environment.Name, environment.OrganizationID.String(), environment.Description, environment.CreatedAt.String(), environment.UpdatedAt.String()})
-		}
+        if err != nil {
+            return fmt.Errorf("failed to fetch environments: %w", err)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/environments/list.go]: same here

**Review by lekaf974 — APPROVED** [review]
small comments that could be done in another PR, LGTM

**Comment by lekaf974** [comment]
> @lekaf974 The "broken pipe" error continues to impact our tests, and it appears to be a systemic issue affecting multiple test cases across the infrastructure. Do you have any insights or suggestions on how we should proceed with resolving this?

I saw a PR open were it was fixing the `broken file` issue recently but not yet merged, basically it is caused by multiple processes are writing to the same `coverage.txt` file at the same time from my understanding

**Comment by yash37158** [comment]
Thanks @lekaf974. Yes, absolutely

**Comment by yash37158** [comment]
Didn't mean to dismiss your review 🥲. I have converted this to meshkit error

**Review by lekaf974 — APPROVED** [review]
LGTM

**Comment by yash37158** [comment]
@lekaf974 Could you please merge this PR when convenient? I appreciate your time!

**Comment by yash37158** [comment]
@vr-varad Do you mind merging this one ?

**Comment by vr-varad** [comment]
the checks are failing @yash37158

**Comment by yash37158** [comment]
@vr-varad Sure I'll fix this

**Comment by yash37158** [comment]
@vr-varad It's fixed. please have a look

**Comment by lekaf974** [comment]
@yash37158 needs a sync with master

**Comment by lekaf974** [comment]
also your changes were not related to the failing eslint check so it could have been merged
