### PR TITLE
fix ui bug in dark mode of modal

### LINKED ISSUE #9384: [UI] Dark Mode Bug in Kubernetes Config Modal
### Current Behavior

Screenshot 2023-11-17 at 7 09 36 PM

### Desired Behavior

We should be using our standard dark mode styling for action buttons.

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by vaibhavpnimkar**
**Notes for Reviewers**

This PR fixes #9384 
now We are  using our standard dark mode styling for action buttons.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by vaibhavpnimkar** [comment]
@yash37158 @theBeginner86 
added hover line to overwrite its default hovering which is making button lighter
plz review this

File: ui/components/PromptComponent.js [hunk 1]
```diff
@@ -64,14 +64,17 @@ const styles = (theme) => ({
   },
 });
 
-const PromptActionButton = styled(Button)(({ theme, promptVariant }) => ({
+const PromptActionButton = styled(Button)(({ theme }) => ({
   margin: theme.spacing(0.5),
   padding: theme.spacing(1),
   borderRadius: 5,
-  backgroundColor: theme.palette.secondary[promptVariant || 'primary'],
+  backgroundColor: theme.palette.type === 'dark' ? '#00B39F' : '#607d8b',
```
Comment (Yashsharma1911) [inline ui/components/PromptComponent.js:71]: @vaibhavpnimkar there should be a theme color defined for this, we are using so many place 🤔

File: ui/components/PromptComponent.js [hunk 2]
```diff
@@ -64,14 +64,17 @@ const styles = (theme) => ({
...
   color: '#fff',
   '&:hover': {
-    backgroundColor: theme.palette.secondary[promptVariant || 'primary'],
+    backgroundColor:
+      theme.palette.type === 'dark'
+        ? theme.palette.secondary.focused
+        : theme.palette.secondary.focused,
```
Comment (Yashsharma1911) [inline ui/components/PromptComponent.js:77]: when we use same theme color you don't need to add a condition
```suggestion
    backgroundColor: theme.palette.secondary.focused,
```

**Review by Yashsharma1911 — CHANGES_REQUESTED** [review]
Thanks for looking into this

File: ui/components/PromptComponent.js (hunk 2 above)
Comment (vaibhavpnimkar) [reply ui/components/PromptComponent.js]: hey @Yashsharma1911 i have changes now  plz review sorry for intial mistakes!!

Comment (Yashsharma1911) [reply ui/components/PromptComponent.js]: Ohh good, it would be helpful if you can share video or screenshot in both light and dark mode of changes

Comment (vaibhavpnimkar) [reply ui/components/PromptComponent.js]: sure !
image
image

Comment (vaibhavpnimkar) [reply ui/components/PromptComponent.js]: [Screencast from 19-11-23 12:59:43 PM IST.webm](https://github.com/meshery/meshery/assets/128807866/78e79adc-ce32-4ec0-ae0f-8d62a5521ed8)

Comment (vaibhavpnimkar) [reply ui/components/PromptComponent.js]: hey  @Yashsharma1911 plz have a look.

File: ui/components/PromptComponent.js [hunk 3]
```diff
@@ -64,14 +64,14 @@ const styles = (theme) => ({
...
+const PromptActionButton = styled(Button)(({ theme }) => ({
   margin: theme.spacing(0.5),
   padding: theme.spacing(1),
   borderRadius: 5,
-  backgroundColor: theme.palette.secondary[promptVariant || 'primary'],
+  backgroundColor: theme.palette.secondary.focused,
   color: '#fff',
   '&:hover': {
-    backgroundColor: theme.palette.secondary[promptVariant || 'primary'],
+    backgroundColor: theme.palette.secondary.focused,
```
Comment (Yashsharma1911) [inline ui/components/PromptComponent.js:74]: @vaibhavpnimkar LGTM thanks, only one things as we now keeping background color same even on hover so we can remove this background color line on hover as this will also result same

Comment (Yashsharma1911) [inline ui/components/PromptComponent.js:74]:
```suggestion
```

**Review by Yashsharma1911 — APPROVED** [review]
Thankyou @vaibhavpnimkar

**Comment by vaibhavpnimkar** [comment]
hey @Yashsharma1911 
[Screencast from 20-11-23 04:53:59 PM IST.webm](https://github.com/meshery/meshery/assets/128807866/71a5d129-b84d-4628-a3e7-46aeb4e66716)
to avoid this i added that hover line after removing it is showing this effect

**Review by vaibhavpnimkar — COMMENTED** [review]
in my local env if we this remove this line this happens
[Screencast from 20-11-23 04:53:59 PM IST.webm](https://github.com/meshery/meshery/assets/128807866/3c98d900-6203-4628-8f42-51af64c846fa)
