### PR TITLE
[Perf] fixed search issue

### LINKED ISSUE #4914: [UI] Searching performances on the performance table view is not working properly
#### Current Behavior
When a user searches a performance profile on the Performance Table view, we get the desired result, but when we clear the search we are not shown with the other remaining profiles. Instead we are just shown with the one profile that matched the previous search query.

#### Desired Behavior
After clearing the search box, we should be able to see all the performance profile.

#### Screenshots/Logs

https://user-images.githubusercontent.com/51183483/148689068-cd303b75-1f64-48a7-a385-652f4aa8266c.mov

#### Environment

- Browser: Safari 
- Host OS: Mac 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by asubedy**
Signed-off-by: asubedy <frexpe@pm.me>

**Description**
- Shows all the profiles if the query did not match any Performance Profile.
- Shows all the profiles if the query is cleared out after searching for profiles.
- Does not search if the search query starts with a space.

This PR fixes #4914

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — DISMISSED** [review]
LGTM!

File: ui/components/MesheryPerformance/PerformanceProfileTable.js [hunk 1]
```diff
@@ -288,7 +288,8 @@ function MesheryTestProfiles({
         case "search":
           if (searchTimeout.current) clearTimeout(searchTimeout.current);
           searchTimeout.current = setTimeout(() => {
-            if (search !== tableState.searchText && tableState.searchText !== null) setSearch(tableState.searchText);
+            const regexp = /^\S/ //search should not start with space
```
Comment (leecalcote) [inline ui/components/MesheryPerformance/PerformanceProfileTable.js:291]: @piyushsingariya do we prevent performance tests from initially being named with a leading whitespace?

We might need to trim this on the endpoint handler side, if so.

File: ui/components/MesheryPerformance/PerformanceProfiles.js [hunk 2]
```diff
@@ -103,7 +103,7 @@ function PerformanceProfile({ updateProgress, enqueueSnackbar, closeSnackbar })
         // @ts-ignore
         let result = res?.getPerformanceProfiles;
         updateProgress({ showProgress : false });
-        if (typeof result !== "undefined") {
+        if (typeof result !== "undefined" && result.profiles.length !== 0) {
```
Comment (leecalcote) [inline ui/components/MesheryPerformance/PerformanceProfiles.js:106]: What about new users, who have zero results? Are they not allowed to establish a subscription?

File: ui/components/MesheryPerformance/PerformanceProfileTable.js (hunk 1 above)
Comment (piyushsingariya) [reply ui/components/MesheryPerformance/PerformanceProfileTable.js:291]: Yeah, we should, but it doesn't affect any current functionality, because we implement regex-based profile searching on the backend.

File: ui/components/MesheryPerformance/PerformanceProfiles.js (hunk 2 above)
Comment (asubedy) [reply ui/components/MesheryPerformance/PerformanceProfiles.js:106]: Sorry, I didn't get this point. New user will not have any profiles, so they will be seeing this page. Is there something I am missing? 😓 
image

File: ui/components/MesheryPerformance/PerformanceProfileTable.js (hunk 1 above)
Comment (leecalcote) [reply ui/components/MesheryPerformance/PerformanceProfileTable.js:291]: And in Meshery UI?

**Comment by leecalcote** [comment]
This sounds like undesired behavior:

"Shows all the profiles if the query did not match any Performance Profile."

File: ui/components/MesheryPerformance/PerformanceProfiles.js (hunk 2 above)
Comment (leecalcote) [reply ui/components/MesheryPerformance/PerformanceProfiles.js:106]: So long as new users see this message, no we're good.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please ensure the behavior is "Shows NO profiles if the query did not match any Performance Profile."

**Comment by asubedy** [comment]
> Please ensure the behavior is "Shows NO profiles if the query did not match any Performance Profile."

This is the current behavior of Meshery UI but there is no way to go back and see the profiles without reloading the site, so to fix this I thought of showing all the profiles. This way user can see that there is no profiles with this query. But I can understand this can be confusing too, as it might look like all the profiles match the query. So maybe we can add an error prompt saying `No profile found with that query`? 

https://user-images.githubusercontent.com/51183483/148905622-9842086e-54c9-455a-a58a-7dd6eb483bc5.mov

File: ui/components/MesheryPerformance/PerformanceProfileTable.js (hunk 1 above)
Comment (piyushsingariya) [reply ui/components/MesheryPerformance/PerformanceProfileTable.js:291]: I think we can restrict people from adding leading whitespaces in Meshery-UI. It's a good issue to open.

**Comment by warunicorn19** [comment]
Might be better if we show the message inside the table itself. `No matching Performance Profiles`

**Comment by warunicorn19** [comment]
Let's discuss on the meshery dev call tomorrow.

**Comment by leecalcote** [comment]
The table needs to stay on the screen. Showing an empty table works.

Taking one step forward to bring a better user experience would be to, again, leave the table on the screen (column headers and filter panel), but display the `No matching performance profiles found.` message where the rows of results would otherwise be.

**Comment by leecalcote** [comment]
@asubedy ping when ready for review. Please do include a screenshot or quick recording when you are.

**Comment by asubedy** [comment]
I was able to do the desired task, here is a demo of it.

https://user-images.githubusercontent.com/51183483/150275031-5cfd1231-4cf7-4c5d-a07d-4ab78e45b0d9.mov

But there is one more problem now, If we find nothing on the search, and we go to the grid view, we do not see the present  profiles instead the empty results persist, Here is what I am talking about:

https://user-images.githubusercontent.com/51183483/150276508-247cab32-1938-4c7f-99fb-6a262d911ca6.mov

We get all the profiles after a refresh, or following what I did on the recording.

**Comment by asubedy** [comment]
@leecalcote @warunicorn19 please review.

**Comment by piyushsingariya** [comment]
I think you set the code whenever someone switches the grid/table view the search things is abandoned and fresh set of results are fetched.
In short making both views isolated from each other.

**Comment by asubedy** [comment]
> I think you can do whenever someone switches the grid/table view the search things is abandoned and fresh set of results are fetched.
> In short making both views isolated from each other.

Yes, that's exactly what I was thinking. When a user switches view set the search query empty, this way we will get all the profiles.

**Comment by asubedy** [comment]
Behavior after this commit:

https://user-images.githubusercontent.com/51183483/150389990-b3273639-e6ac-4e6f-a23e-c9031a1940b2.mov

File: ui/components/MesheryPerformance/PerformanceProfiles.js [hunk 3]
```diff
@@ -198,7 +213,7 @@ function PerformanceProfile({ updateProgress, enqueueSnackbar, closeSnackbar })
               </Button>
             </div>
           )}
-          <div style={{ justifySelf : "flex-end", marginLeft : "auto", paddingLeft : "1rem" }}>
+          <div style={{ justifySelf : "flex-end", marginLeft : "auto", paddingLeft : "1rem" }} onClick={() => setSearch("") }>
```
Comment (Abhishek-kumar09) [inline ui/components/MesheryPerformance/PerformanceProfiles.js:216]: oh styles here and there, should we use makeStyles?

Comment (asubedy) [reply ui/components/MesheryPerformance/PerformanceProfiles.js:216]: We can, but it might be difficult, as we do not have any definitive class name for these divs, that have style in it.

Comment (leecalcote) [reply ui/components/MesheryPerformance/PerformanceProfiles.js:216]: Let's start now. Drive clarity. Give names to the classes. Propagate their use.

File: ui/components/MesheryPerformance/PerformanceProfileTable.js (hunk 1 above)
Comment (Abhishek-kumar09) [reply ui/components/MesheryPerformance/PerformanceProfileTable.js:291]: If there is trouble for leading whitespace, why we are wasting efforts in terms of regex checking and all. 
[Just use a trim for the search text. ](https://www.w3schools.com/jsref/jsref_trim_string.asp)

```diff
-            const regexp = /^\S/ //search should not start with space
- if (search !== tableState.searchText && regexp.test(tableState.searchText)) setSearch(tableState.searchText);
+  if (search !== tableState.searchText) setSearch(tableState.searchText.trim());
```

We can also live validate the text-box for whitespaces and all: (probably that won't be required, seeking the current use-case)
https://github.com/meshery/meshery/pull/4931

**Comment by Abhishek-kumar09** [comment]
https://github.com/meshery/meshery/pull/4915#discussion_r793924695

**Comment by Abhishek-kumar09** [comment]
resolved conflicts, you have to pull the changes locally.

File: ui/components/MesheryPerformance/PerformanceProfileTable.js (hunk 1 above)
Comment (asubedy) [reply ui/components/MesheryPerformance/PerformanceProfileTable.js:291]: Yes I think I'll just remove this regex and checking. If a user enters space he will be displayed with a `Sorry no matching profiles found` message. I guess that should be fine, as I checked this is the same behavior on the pattern tables too. @Abhishek-kumar09

**Comment by asubedy** [comment]
@Abhishek-kumar09 I removed the regex testing, is there anything more that needs to be updated?

**Comment by warunicorn19** [comment]
@Abhishek-kumar09 are we good here?

File: ui/components/MesheryPerformance/PerformanceCard.js [hunk 4]
```diff
@@ -63,8 +102,8 @@ function PerformanceCard({
             </div>
           </div>
         </div>
-        <div style={{ display : "flex", justifyContent : "space-between", alignItems : "center" }}>
-          <div style={{ marginRight : "0.5rem" }}>
+        <div className={classes.bottomPart} >
```
Comment (warunicorn19) [inline ui/components/MesheryPerformance/PerformanceCard.js:105]: sorry, small nitpick. Could you please use a better name here?

**Review by warunicorn19 — APPROVED** [review]
Looking good.
