### PR TITLE
fix[ui]: Improve contrast and enhance readability in performance page

### LINKED ISSUE #13638: [UI] Dark Theme Contrast of Calendar on Performance Page
### Current Behavior

The performance page in Meshery has a dark theme with low contrast, making it difficult to read and distinguish elements. The grid lines in the schedule are faint, blending into the background, and the text visibility is reduced.

Image

### Desired Behavior

- Improve the contrast between the background and text to enhance readability.
- Adjust the grid lines to be more visible while maintaining the dark theme.

### Environment

- Browser:  Firefox
- Host OS:  Linux 
- Meshery Server Version: stable-v
- Platform:  Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Karan-Palan**
**Notes for Reviewers**

image

- Calendar grid lines and off-range days are brighter for better distinction.
- Toolbar buttons have improved hover and active states.
- Today’s date has better highlighting in dark mode.

This PR fixes #13638 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/MesheryPerformance/style.js [hunk 1]
```diff
@@ -63,38 +63,37 @@ export const ResultContainerWrap = styled('div')(() => ({
...
   },
   '& .rbc-toolbar button.rbc-active:hover': {
     backgroundColor: theme.palette.mode === 'dark' ? '#909090' : '#eaf6ff',
   },
   '& .rbc-toolbar button:focus ': {
     backgroundColor: theme.palette.mode === 'dark' ? '#505050' : '#eaf6ff',
-    color: theme.palette.mode === 'dark' ? 'white' : 'black',
+    color: theme.palette.mode === 'dark' ? '#FFFFFF' : '#000000',
   },
 }));
```
Comment (amitamrutiya) [inline ui/components/MesheryPerformance/style.js:99]: Since you are here. This is not the work we try to do everywhere like putting a hard code color hex code for the dark and light mode. use the sistent token instead.

**Review by amitamrutiya — CHANGES_REQUESTED** [review]

File: ui/components/MesheryPerformance/style.js (hunk 1 above)
Comment (amitamrutiya) [reply ui/components/MesheryPerformance/style.js:99]: else it LGTM

Comment (Karan-Palan) [reply ui/components/MesheryPerformance/style.js]: Alright, did that

image

**Review by amitamrutiya — APPROVED** [review]
