### PR TITLE
fix(mesheryctl): system provider return proper error, remove logrus, …

### LINKED ISSUE #18281: [mesheryctl] system provider uses meshkit error properly + remove logrus + flags validation
## Parent Issue
#17709

## Current Behavior
In `provider.go`:
- Errors are being logged and swallowed:
  utils.Log.Error(err)
  return nil
- No flag struct validation using `mesheryctlflags.ValidateCmdFlags()`

## Desired Behavior
- returning error properly
- remove logrus
- flags validation

### PR DESCRIPTION
**Pull request by Omkar-Ugal**
Fixes #18281 

## Testing

Before fix: `--all` and `--force` flags accepted any value silently (no validation)

After fix:

$ ./mesheryctl system provider view --all=invalid
Error: invalid argument "invalid" for "-a, --all" flag: strconv.ParseBool: parsing "invalid": invalid syntax

$ ./mesheryctl system provider set --force=invalid Meshery
Error: invalid argument "invalid" for "-f, --force" flag: strconv.ParseBool: parsing "invalid": invalid syntax

Valid usage:

$ ./mesheryctl system provider view
Context: local
Provider:

$ ./mesheryctl system provider view --all
Context: local
Provider:
Current Context: local

- [x] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/internal/cli/root/system/provider.go [hunk 1]
```diff
@@ -115,21 +118,19 @@ mesheryctl system provider list
...
-			return nil
+			return ErrGetCurrentContext(err)
 		}
 
 		utils.Log.Infof("Current provider: %s", currCtx.Provider)
 
 		providers, err := utils.GetProviderInfo(mctlCfg)
 		if err != nil {
-			utils.Log.Fatalf("could not fetch providers as Meshery server was unreachable\nStart Meshery to list available providers")
+return errors.Wrap(err, "could not fetch providers as Meshery server was unreachable. Start Meshery to list available providers")
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/provider.go]: must be a meshkit error

File: mesheryctl/internal/cli/root/system/provider.go [hunk 2]
```diff
@@ -217,15 +219,12 @@ mesheryctl system provider set [provider]
...
-				utils.Log.Info("Available providers:\n")
-				//sorting the contexts to get a consistent order on each subsequent run
+				providerList := "\n\nAvailable providers:"
 				sort.Strings(keys)
 				for _, k := range keys {
-					utils.Log.Infof("- %s", k)
+    				providerList += "\n- " + k
 				}
-				os.Exit(1)
+				return fmt.Errorf("%w%s", ErrValidProvider(), providerList)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/provider.go]: must be a meshkit error

**Review by lekaf974 — CHANGES_REQUESTED** [review]
please return meshkit error

File: mesheryctl/internal/cli/root/system/provider.go [hunk 3]
```diff
@@ -217,15 +219,7 @@ mesheryctl system provider set [provider]
...
-				utils.Log.Error(ErrValidProvider())
-
-				utils.Log.Info("Available providers:\n")
-				//sorting the contexts to get a consistent order on each subsequent run
-				sort.Strings(keys)
-				for _, k := range keys {
-					utils.Log.Infof("- %s", k)
-				}
-				os.Exit(1)
+				return ErrValidProvider()
```
[the remark this answers is not in the document]
Comment (lekaf974) [reply mesheryctl/internal/cli/root/system/provider.go:225]: this is legit please modify the error to display valid providers list

File: mesheryctl/internal/cli/root/system/provider.go [hunk 4]
```diff
@@ -173,11 +174,14 @@ mesheryctl system provider set [provider]
 		}
 		return nil
 	},
+PreRunE: func(cmd *cobra.Command, args []string) error {
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/provider.go]: indentation looks weird

File: mesheryctl/internal/cli/root/system/provider.go [hunk 5]
```diff
@@ -27,12 +26,17 @@ import (
...
 )
-
+type cmdProviderViewFlags struct {
+    All bool `json:"all" validate:"boolean"`
+}
+type cmdProviderSetFlags struct {
+    Force bool `json:"force" validate:"boolean"`
+}
+var providerViewFlags cmdProviderViewFlags
+var providerSetFlags cmdProviderSetFlags
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/provider.go]: please keep type and var near the command also add blank line

**Review by lekaf974 — CHANGES_REQUESTED** [review]
Added minor comments

**Comment by lekaf974** [comment]
@Omkar-Ugal linter is failing, can you take care of this .

**Review by lekaf974 — APPROVED** [review]
