### PR TITLE
Fix performance profile retrieval issue

### LINKED ISSUE #4102: [GraphQL] Perf: Unhandled nil test result set
#### Current Behavior
Nil PerformanceResultQuery is causing a panic.

#### Expected Behavior
A zero result perf test query shouldn't cause a panic.

#### Screenshots/Logs
```
meshery_1               | time="2021-09-07T18:32:34Z" level=info msg="retrieved user: {lcalcote   http://pbs.twimg.com/profile_images/880205475643441152/V_vhfnzb_normal.jpg}"
meshery_1               | time="2021-09-07T18:32:34Z" level=info msg="attempting to fetch results from cloud"
meshery_1               | runtime error: invalid memory address or nil pointer dereference
meshery_1               |
meshery_1               | goroutine 6807 [running]:
meshery_1               | runtime/debug.Stack(0x1, 0x0, 0x0)
meshery_1               | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
meshery_1               | runtime/debug.PrintStack()
meshery_1               | 	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
meshery_1               | github.com/99designs/gqlgen/graphql.DefaultRecover(0x32abd28, 0xc001335140, 0x2c12100, 0x41b2c90, 0x8, 0x1100000000000000)
meshery_1               | 	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/recovery.go:16 +0xaa
meshery_1               | github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0xc0071f2b00, 0x32abd28, 0xc001335140, 0x2c12100, 0x41b2c90, 0x8, 0x0)
meshery_1               | 	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/context_operation.go:110 +0x56
meshery_1               | github.com/layer5io/meshery/internal/graphql/generated.(*executionContext)._Query_fetchResults.func1(0xc0086f2250, 0xc0086f22a0, 0xc00833d0f0)
meshery_1               | 	/github.com/meshery/meshery/internal/graphql/generated/generated.go:3918 +0x7d
meshery_1               | panic(0x2c12100, 0x41b2c90)
meshery_1               | 	/usr/local/go/src/runtime/panic.go:965 +0x1b9
meshery_1               | github.com/layer5io/meshery/models.(*RemoteProvider).DoRequest(0xc0009c8180, 0xc0071f2e00, 0x0, 0x0, 0xc00668a6c0, 0x74, 0x0)
meshery_1               | 	/github.com/meshery/meshery/models/remote_auth.go:35 +0x6c
meshery_1               | github.com/layer5io/meshery/models.(*RemoteProvider).FetchResults(0xc0009c8180, 0x0, 0x0, 0x4228020, 0x1, 0xc0085068b0, 0x2, 0x0, 0x0, 0x0, ...)
meshery_1               | 	/github.com/meshery/meshery/models/remote_provider.go:404 +0x3fa
meshery_1               | github.com/layer5io/meshery/internal/graphql/resolver.(*Resolver).fetchResults(0xc000ba1f80, 0x32abd28, 0xc001335140, 0x32e17c0, 0xc0009c8180, 0x4228020, 0x1, 0xc0085068b0, 0x2, 0xc0086f22f0, ...)
meshery_1               | 	/github.com/meshery/meshery/internal/graphql/resolver/performance.go:96 +0x30a
meshery_1               | github.com/layer5io/meshery/internal/graphql/resolver.(*queryResolver).FetchResults(0xc006154fb0, 0x32abd28, 0xc001335140, 0x4228020, 0x1, 0xc0085068b0, 0x2, 0xc0086f22f0, 0xc0086f22d0, 0x0, ...)
meshery_1               | 	/github.com/meshery/meshery/internal/graphql/resolver/schema.resolvers.go:89 +0x105
meshery_1               | github.com/layer5io/meshery/internal/graphql/generated.(*executionContext)._Query_fetchResults.func2(0x32abd28, 0xc001335140, 0x20, 0x2d52640, 0x1, 0xc001418540)
meshery_1               | 	/github.com/meshery/meshery/internal/graphql/generated/generated.go:3940 +0x202
meshery_1               | github.com/99designs/gqlgen/graphql/executor.processExtensions.func3(0x32abd28, 0xc001335140, 0xc001418540, 0xc001335170, 0xc0013351a0, 0x0, 0x0)
meshery_1               | 	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/executor/extensions.go:62 +0x3a
meshery_1               | github.com/layer5io/meshery/internal/graphql/generated.(*executionContext)._Query_fetchResults(0xc0086f2250, 0x32abd28, 0xc001335110, 0xc0011d7600, 0xc008af1ec0, 0x4, 0x4, 0x0, 0x0)
meshery_1               | 	/github.com/meshery/meshery/internal/graphql/generated/generated.go:3938 +0x2ba
meshery_1               | github.com/layer5io/meshery/internal/graphql/generated.(*executionContext)._Query.func10(0x0, 0x0)
meshery_1               | 	/github.com/meshery/meshery/internal/graphql/generated/generated.go:6304 +0xa8
meshery_1               | github.com/99designs/gqlgen/graphql.(*FieldSet).Dispatch(0xc0078099f0)
meshery_1               | 	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/fieldset.go:34 +0x1dd
meshery_1               | github.com/layer5io/meshery/internal/graphql/generated.(*executionContext)._Query(0xc0086f2250, 0x32abd28, 0xc0013350e0, 0xc0074cbd90, 0x1, 0x1, 0x203002, 0xc00833d4b0)
meshery_1               | 	/github.com/meshery/meshery/internal/graphql/generated/generated.go:6318 +0x452
meshery_1               | github.com/layer5io/meshery/internal/graphql/generated.(*executableSchema).Exec.func1(0x32abd28, 0xc0013350e0, 0x30)
meshery_1               | 	/github.com/meshery/meshery/internal/graphql/generated/generated.go:827 +0x7b
meshery_1               | github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1.1(0x32abd28, 0xc0013350e0, 0xc0086f2260)
meshery_1               | 	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/executor/executor.go:105 +0x43
meshery_1               | github.com/99designs/gqlgen/graphql/executor.processExtensions.func2(0x32abd28, 0xc0013350e0, 0xc0086f2260, 0x322aa70)
meshery_1               | 	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/executor/extensions.go:59 +0x3a
meshery_1               | github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1(0x32abd28, 0xc001334ff0, 0xc001334fc0)
meshery_1               | 	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/executor/executor.go:104 +0x12c
meshery_1               | github.com/99designs/gqlgen/graphql/handler/transport.POST.Do(0x32a6e28, 0xc000a268c0, 0xc0071f2a00, 0x3299e08, 0xc00040fe60)
meshery_1               | 	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/handler/transport/http_post.go:53 +0x3a5
meshery_1               | github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc0004bf840, 0x32a6e28, 0xc000a268c0, 0xc0071f2a00)
meshery_1               | 	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/handler/server.go:115 +0x21b
meshery_1               | github.com/layer5io/meshery/handlers.(*Handler).GraphqlMiddleware.func1(0x32a6e28, 0xc000a268c0, 0xc0071f2900, 0xc00729c060, 0xc007b967d0, 0x32e17c0, 0xc0009c8180)
meshery_1               | 	/github.com/meshery/meshery/handlers/middlewares.go:123 +0x4d
meshery_1               | github.com/layer5io/meshery/handlers.(*Handler).SessionInjectorMiddleware.func1(0x32a6e28, 0xc000a268c0, 0xc007905200)
meshery_1               | 	/github.com/meshery/meshery/handlers/middlewares.go:116 +0x5d3
meshery_1               | net/http.HandlerFunc.ServeHTTP(0xc000c3abe8, 0x32a6e28, 0xc000a268c0, 0xc007905200)
meshery_1               | 	/usr/local/go/src/net/http/server.go:2049 +0x44
meshery_1               | github.com/layer5io/meshery/handlers.(*Handler).AuthMiddleware.func1(0x32a6e28, 0xc000a268c0, 0xc007905200)
meshery_1               | 	/github.com/meshery/meshery/handlers/middlewares.go:65 +0x129
meshery_1               | net/http.HandlerFunc.ServeHTTP(0xc0004bf8a0, 0x32a6e28, 0xc000a268c0, 0xc007905200)
meshery_1               | 	/usr/local/go/src/net/http/server.go:2049 +0x44
meshery_1               | github.com/layer5io/meshery/handlers.(*Handler).ProviderMiddleware.func1(0x32a6e28, 0xc000a268c0, 0xc007905100)
meshery_1               | 	/github.com/meshery/meshery/handlers/middlewares.go:33 +0x1e7
meshery_1               | net/http.HandlerFunc.ServeHTTP(0xc0004bf8c0, 0x32a6e28, 0xc000a268c0, 0xc007905100)
meshery_1               | 	/usr/local/go/src/net/http/server.go:2049 +0x44
meshery_1               | github.com/gorilla/mux.(*Router).ServeHTTP(0xc000189800, 0x32a6e28, 0xc000a268c0, 0xc0071f2300)
meshery_1               | 	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
meshery_1               | net/http.serverHandler.ServeHTTP(0xc000d96000, 0x32a6e28, 0xc000a268c0, 0xc0071f2300)
meshery_1               | 	/usr/local/go/src/net/http/server.go:2867 +0xa3
meshery_1               | net/http.(*conn).serve(0xc0074a40a0, 0x32abd28, 0xc0084a81c0)
meshery_1               | 	/usr/local/go/src/net/http/server.go:1932 +0x8cd
meshery_1               | created by net/http.(*Server).Serve
meshery_1               | 	/usr/local/go/src/net/http/server.go:2993 +0x39b
```

#### Environment

- **Host OS:** Mac
- **Platform:** Docker 
- **Meshery Server Version:** stable-v0.5.53

Screen Shot 2021-09-07 at 1 38 18 PM

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by tangledbytes**
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>

**Description**
This PR fixes #4102 

Screenshot_20210908_184959

**Notes for Reviewers**
The root cause of the issue was Meshery was expecting refresh tokens to be present however that was not true. This PR just adds a few error checks and fallbacks to access token if refresh token is absent.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: internal/graphql/resolver/performance.go [hunk 1]
```diff
@@ -91,7 +91,7 @@ func (r *Resolver) fetchResults(ctx context.Context, provider models.Provider, s
 		return nil, handlers.ErrQueryGet("*profileID")
 	}
 
-	tokenString := ctx.Value("token").(string)
+	tokenString := ctx.Value(models.TokenCtxKey).(string)
```
Comment (bariqhibat) [inline internal/graphql/resolver/performance.go:94]: we use the previous "token" key for getting the tokenString from the context for other resolvers and providers for REST, so should this change be propagated to those functions too?

Comment (utkarsh-pro) [reply internal/graphql/resolver/performance.go:94]: `models.TokenCtxKey` is actually `"token"`

**Review by leecalcote — APPROVED** [review]
