### PR TITLE
[Patterns] Fix Pattern upload/update issues from the patterns & configurator page

### LINKED ISSUE #4903: [UI] Patterns local YAML file import fails (request body’s file content is missing, test expects “pattern_data.pattern_file”)
#### Current Behavior

Patterns local YAML file import fails (request body’s file content is missing, test expects “pattern_data.pattern_file”)

File (taken from [service-mesh-patterns/service-mesh-patterns/commit/5eb2369](https://github.com/service-mesh-patterns/service-mesh-patterns/commit/5eb2369f41f6c585c95426c85441e2764ecbbeba#diff-20f0f5fa48767e85736f2a5406d79855b6d216dd190f637c13d8f3a45f29e399)):

File attachment **(github uploads do not support .yaml, remove .txt before using it)**: [bookInfoPattern-commit-5eb2369.yaml.txt](https://github.com/meshery/meshery/files/7831877/bookInfoPattern-commit-5eb2369.yaml.txt)

#### Desired Behavior

Patterns Service Mesh Configuration Management page should allow local Pattern YAML file upload/import

#### Screenshots/Logs

upload/import request body missing file content:
image

Failed cypress e2e test result:
image

#### Environment

- Browser: Chrome
- Host OS: Mac
- Meshery Server Version: v0.6.0-rc-2 & latest master as of 01/07/2022
- Meshery Client Version: v0.6.0-rc-2 & latest master as of 01/07/2022
- Platform: Docker Kubernetes

---

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
**Description**
This fixes all the upload issues at all the different instances of pattern uploads

This PR fixes #4903

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
Local file upload is working. But still not being able to upload using URL. 

https://github.com/service-mesh-patterns/service-mesh-patterns/blob/master/samples/IstioFilterPattern.yaml 

Is this an incorrect format ^^

**Comment by warunicorn19** [comment]
Screenshot 2022-01-11 at 1 41 57 PM

**Comment by Abhishek-kumar09** [comment]
> 

Yes @warunicorn19,  You have to upload raw URL, by clicking on the raw button on the github.
like: https://raw.githubusercontent.com/service-mesh-patterns/service-mesh-patterns/master/samples/IstioFilterPattern.yaml

**Comment by warunicorn19** [comment]
Aah, okay gotcha, still don't see it being uploaded though. 

https://user-images.githubusercontent.com/53532328/149005554-db61b4b2-7ec1-4363-967c-394675d6ade1.mov

**Comment by Abhishek-kumar09** [comment]
Are you sure you are on the latest changes done in this PR:

https://user-images.githubusercontent.com/48255244/149006142-aba69f13-2cc0-45ea-858d-a3c26aad4b42.mp4


because I can do it successfully:

**Comment by warunicorn19** [comment]
I'm checking out this PR 🤔, okay let me re-build.

**Comment by Abhishek-kumar09** [comment]
you can try running dev server instantly

**Comment by warunicorn19** [comment]
Okay, I checked again, for some reason when I copy the above link that you gave, it doesn't work😅. I went and copied from the `service-mesh-patterns` repo it works.

**Review by warunicorn19 — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]
LGTM

**Review by leecalcote — CHANGES_REQUESTED** [review]
Wait... @Abhishek-kumar09, do you know why your pattern url doesn't work? Invalid pattern format?

**Comment by Abhishek-kumar09** [comment]
Got it, if you look at the @warunicorn19 video again, you will see he has added a whitespace in the beginning by mistake, due to which the URL get's problems uploading.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Oh, I see. Thank you. 👍

**Comment by MarioArriaga92** [comment]
Don't see the point in requesting my review if its being merged before I get a chance to take a look anyways 😅🙃

File: ui/components/MesheryPatterns.js [hunk 1]
```diff
@@ -394,7 +400,13 @@ function MesheryPatterns({
     if (type === FILE_OPS.FILE_UPLOAD || type === FILE_OPS.URL_UPLOAD) {
       let body;
       if (type === FILE_OPS.FILE_UPLOAD) {
-        body = JSON.stringify({ pattern_data : { pattern_file : data }, save : true })
+        body = JSON.stringify({
+          pattern_data : {
+            name,
```
Comment (MarioArriaga92) [inline ui/components/MesheryPatterns.js:405]: @Abhishek-kumar09 what's the value for this 'name' key?

Comment (MarioArriaga92) [reply ui/components/MesheryPatterns.js:405]: is the actual value for this property kept 'undefined' for a valid reason?

Comment (MarioArriaga92) [reply ui/components/MesheryPatterns.js:405]: As far as I can see, `handlers/meshery_pattern_handler.go` checks for empty string and `handleSubmit` call passes either the file's name or a random name.. but we're never passing any of those values in line 405 for pattern_data object's 'name' key @Abhishek-kumar09

**Comment by leecalcote** [comment]
Yeah, I hear that. This thought crossed my mind as I merged. There's a tug-of-war that goes on in making this decision, understanding that Meshery users are currently facing this bug and having its fix out the door sooner, is better.  For my part, I'm it's never clear who has time, or who won't be back for days on end. So, I lean into pressing forward, because more often than not individuals will take days to come back (if at all). This isn't the case for @MarioArriaga92, specifically, though, and so I should allow more time for review. 

Your review post-merge is still valid and helpful, particularly in that this should fix a bug that you reported (so you're sweetly positioned to confirm), which also means that you're perfectly positioned to be the most prominent reviewer - only adding a +1 to letting the PR remain open longer. I'll make a point of waiting out PRs that fall into this category with @MarioArriaga92 involved, considering that he has been and is quite dedicated to the project.

**Comment by MarioArriaga92** [comment]
Thanks @leecalcote and no worries, for now I'll wait for @Abhishek-kumar09 to answer above comments made (there could be good reasons for leaving 'name' prop unassigned). 

Meanwhile rebase master onto my branch (or is it my branch onto master? I always get that wrong lol) to re-run cypress e2e tests locally

Will comment in this PR and in Slack in case there's any other relevant observations in functionality 👌🙏🏼

File: ui/components/MesheryPatterns.js (hunk 1 above)
Comment (Abhishek-kumar09) [reply ui/components/MesheryPatterns.js:405]: Hi @MarioArriaga92,
Earlier the pattern name was not sent to the server, so your experience may have been due to that. 
If we are talking about the current scenario, when you upload a pattern with file, the file_name would be the pattern name and it will sent by the UI, or if you are creating your own pattern from the pattern configurator the random name like `meshery_23` would be your pattern name and will sent to server. When you are uploading the pattern from the URL, the name of the pattern is retrieved from the pattern_file sent to the server.
> .. but we're never assigning the value in line 405 for pattern_data object's 'name' property as the value

Actually, that's an es6 syntax, if your key and value variables are both having same name you can omit writing it.
e.g.
```
function f(name) {
  return {name};
}
```
is equivalent to:
```
function f(name) {
  return {name: name};
}
```

Comment (MarioArriaga92) [reply ui/components/MesheryPatterns.js:405]: Wow neat, thanks for clarifying @Abhishek-kumar09

**Comment by adithyaakrishna** [comment]
> Got it, if you look at the @warunicorn19 video again, you will see he has added a whitespace in the beginning by mistake, due to which the URL get's problems uploading.

@Abhishek-kumar09 @leecalcote @warunicorn19 I had a similar issue at my work as well (Users were adding space and the API would give a Error), tbh we will never know if a user/customer/client will add trailing whitespace. How about if we add a trim() method to the input value so that even if a user adds trailing spaces, It will still be considered?

**Comment by MarioArriaga92** [comment]
> > Got it, if you look at the @warunicorn19 video again, you will see he has added a whitespace in the beginning by mistake, due to which the URL get's problems uploading.
> 
> @Abhishek-kumar09 @leecalcote @warunicorn19 I had a similar issue at my work as well (Users were adding space and the API would give a Error), tbh we will never know if a user/customer/client will add trailing whitespace. How about if we add a trim() method to the input value so that even if a user adds trailing spaces, It will still be considered?
> 
> More info: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim


@leecalcote @Abhishek-kumar09 @warunicorn19  if possible, I'd suggest to do some client-side validation to avoid form is sent & provide proper validation error message so as user is shown what he/she should do in order to fix it. But not sure if that'd require major ui/ux design and/or additional work in Meshery UI components to enable such functionality

**Comment by MarioArriaga92** [comment]
Although, server-side it'd still be useful to return user-friendly message letting mesheryctl user (or any process invoking Meshery API directly) know what's wrong with the payload

**Comment by Abhishek-kumar09** [comment]
So this has been fixed with url upload with validation as you type in the textField. So, client side validation is now full proof. https://github.com/meshery/meshery/pull/4931

> Although, server-side it'd still be useful to return user-friendly message letting mesheryctl user (or any process invoking Meshery API directly) know what's wrong with the payload

It is done, here in the video you saw by @warunicorn19, the request was not getting made in the first place, that's why no response from server.
