### PR TITLE
Parsing the relative path correctly

### LINKED ISSUE #7908: [mesheryctl] relative path cannot be parsed correctly for `mesheryctl pattern apply --file `
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

When use relative path for `mesheryctl pattern apply --file `, the path will be parsed as a URL:
```
$ mesheryctl pattern apply -f CryptoMB-TLS-handshake-acceleration-for-Istio-v2.yaml
Error: only github urls are supported
``` 
It works when I change the relative path to absolute one.

#### Desired Behavior

It should work to parse file path whenever I use relative path or absolute path.

#### Screenshots/Logs

After investigation of meshery code, I don't think this function can parse relative path correctly and so it parsed the path as a URL:

https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/pattern/apply.go#L120

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by suhail34**
**Notes for Reviewers**

This PR fixes #7908

The govalidator.IsUrl() is giving true if "./"  is not given in the argument like `mesheryctl pattern apply -f ./IstioSpire` will work but `mesheryctl pattern apply -f IstioSpire` won't work because it gives true

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/internal/cli/root/pattern/apply.go [hunk 1]
```diff
@@ -117,7 +116,8 @@ mesheryctl pattern apply [pattern-name]
 			}
 		} else {
 			// Method to check if the entered file is a URL or not
-			if validURL := govalidator.IsURL(file); !validURL {
+			validURL := strings.HasPrefix(file, "https://github.com")
```
Comment (leecalcote) [inline mesheryctl/internal/cli/root/pattern/apply.go:119]: We’re not mandating that URLs contain github.com, are we?

Comment (suhail34) [reply mesheryctl/internal/cli/root/pattern/apply.go:119]: This line calls ParseUrlGithub and i saw the function it works for host github.com and raw.githubusercontent.com
https://github.com/meshery/meshery/blob/ad9b22e3f32a13b30fc7f5a120be075ab22d324f/mesheryctl/internal/cli/root/pattern/apply.go#L170

For Reference
https://github.com/meshery/meshery/blob/ad9b22e3f32a13b30fc7f5a120be075ab22d324f/mesheryctl/pkg/utils/helpers.go#L573

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Thanks, @suhail34

**Comment by suhail34** [comment]
I think I should add one more condition
