### PR TITLE
fix(style): fix #15202 help button hover 

### LINKED ISSUE #15202: [UI] Hover Background Circle Fix
### Current Behavior

Make the hover circle uniform.

Image

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by dipanshurdev**
## Title: 
Fix Help Icon hover background circle in Sidebar

## Changes made:

 - In ui/components/General/style.tsx

 Adjusted the HelpButton component to have uniform dimensions (width: 32px, height: 32px) and uniform padding to ensure the underlying Material-UI IconButton base creates a perfect hover circle.
In 

- ui/components/Navigator.tsx

1.  Migrated the HelpIcon styling from the inline React style prop to the Material-UI sx
 prop. 
2.  Standard style objects don't fully support CSS pseudo-classes like &:hover. 
3.  Using sx
 correctly applies the intended transparency hover effects natively.

## Screenshots
Screenshot 2026-03-08 022317

## Testing:

- Verified that hovering over the Help icon now successfully triggers a perfectly circular hover animation/background that aligns with the rest of the UI aesthetics.

- Verified that npm run lint:fix passes locally.

### CODE REVIEW

**Review by yi-nuo426 — DISMISSED** [review]
Thanks

**Review by Rajesh-Nagarajan-11 — APPROVED** [review]

**Review by kishore08-07 — CHANGES_REQUESTED** [review]
@dipanshurdev kindly address the gemini's suggestions.

**Review by rishiraj38 — APPROVED** [review]

**Review by rishiraj38 — COMMENTED** [review]
try fixing the lint error

**Comment by dipanshurdev** [comment]
> try fixing the lint error

I think it's fixed now

**Comment by rishiraj38** [comment]
@kishore08-07  @yi-nuo426, please take a look at this PR.

**Review by rishiraj38 — APPROVED** [review]

File: ui/components/General/style.tsx [hunk 1]
```diff
@@ -426,8 +426,10 @@ export const HelpListItem = styled(ListItem)(({ theme }) => ({
 export const HelpButton = styled(IconButton, {
   shouldForwardProp: (prop) => prop !== 'isCollapsed',
 })(({ isCollapsed }) => ({
+  height: '32px',
```
Comment (saurabhraghuvanshii) [inline ui/components/General/style.tsx:429]: @dipanshurdev why 32 px I think 24px is good can you test 24px

**Review by saurabhraghuvanshii — CHANGES_REQUESTED** [review]

File: ui/components/General/style.tsx (hunk 1 above)
Comment (saurabhraghuvanshii) [reply ui/components/General/style.tsx:429]: @dipanshurdev  any updates?

**Review by saurabhraghuvanshii — APPROVED** [review]
