### PR TITLE
Settings page font changed.

### LINKED ISSUE #12739: Consistent Qanelas Soft font family
### Current Behavior
Currently, there is no consistent font usage across platforms like Cloud, Meshery, and Extensions. This inconsistency affects the overall user experience and branding uniformity.

### Expected Behavior
All platforms should consistently use the Qanelas Soft font to ensure a cohesive look and feel across applications.

### To Reproduce

1. Open any UI on Cloud, Meshery, or other meshery extensions.
2. Observe the inconsistent font styles across different components or pages.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Pratik-050**
**Notes for Reviewers**
Changed all different fonts and made some sistent changes in settings page.

- This PR partially fixes #12739

https://github.com/user-attachments/assets/80793720-7cdf-4402-b5aa-595c934b9873

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/MeshModelRegistry/MeshModelDetails.js [hunk 1]
```diff
@@ -404,7 +396,9 @@ const Description = ({ description }) => (
 const TitleWithImg = ({ displayName, iconSrc }) => (
   <div style={{ display: 'flex', alignItems: 'center', flexBasis: '60%' }}>
     {iconSrc && <img src={iconSrc} height="55px" width="55px" style={{ marginRight: '0.6rem' }} />}
-    <Title title={displayName} />
+    <UsesSistent>
```
Comment (amitamrutiya) [inline ui/components/MeshModelRegistry/MeshModelDetails.js:399]: don't use the usesSistent in small codes try to wrap it with the parent

Comment (Pratik-050) [reply ui/components/MeshModelRegistry/MeshModelDetails.js]: Done @amitamrutiya only the parent is now wrapped with usesSistent.

**Review by amitamrutiya — APPROVED** [review]

**Comment by amitamrutiya** [comment]
Can you check one test failing is not because of your changes?
