### PR TITLE
Fix inconsistency between K8s context switcher and Settings page

### LINKED ISSUE #6163: [UI] MeshSync Status: Inconsistency between K8s context switcher and Settings page
#### Current Behavior
Screen Shot 2022-09-01 at 9 53 09 PM
mu

#### Environment

- Meshery Server Version: stable-v06.4
- Meshery Client Version: stable-v06.4

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by MUzairS15**
Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>

**Description**

This PR fixes #6163 

**Notes for Reviewers**
Screenshot 2022-09-11 at 8 58 55 PM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/Header.js [hunk 1]
```diff
@@ -354,18 +388,19 @@ function K8sContextMenu({
                 }
                 {contexts?.contexts?.map(ctx => {
                   const meshStatus = getMeshSyncStatus(ctx.id);
+                  const brokerStatus = getBrokerStatus(ctx.id);
                   const operStatus = getOperatorStatus(ctx.id);
 
                   function getStatus(status) {
                     if (status) {
-                      return "Active"
+                      return status
```
Comment (Chadha93) [inline ui/components/Header.js:396]:
```suggestion
                      return STATUS.ACTIVE
```

**Review by Chadha93 — CHANGES_REQUESTED** [review]
@MUzairS15 From the ss - The MeshSync Status is only showing the port number, not the status. It should show Active since it's connected.

**Comment by leecalcote** [comment]
@asubedy @Chadha93 we're in need of having portions of the Docs troubleshooting toolkit published into Meshery Docs Troubleshooting Guide.

File: ui/components/Header.js (hunk 1 above)
Comment (MUzairS15) [reply ui/components/Header.js]: > @MUzairS15 From the ss - The MeshSync Status is only showing the port number, not the status. It should show Active since it's connected.

The IP address indicates, it's active, otherwise status will be something else (Disabled)

Comment (Chadha93) [reply ui/components/Header.js]: Okay, Gotcha. 
The above suggestion is valid, right?

**Comment by warunicorn19** [comment]
@MUzairS15 let's discuss this PR on the Meshery Dev call today.

**Comment by Chadha93** [comment]
> @asubedy @Chadha93 we're in need of having portions of the Docs troubleshooting toolkit published into Meshery Docs Troubleshooting Guide.

@asubedy Will you open an issue on this?

**Review by Chadha93 — APPROVED** [review]
LGTM

**Comment by MUzairS15** [comment]
https://github.com/meshery/meshery/issues/6196 issue already exist
