### PR TITLE
Meshery Management Page: Fixes Dark Mode Dialog Bug

### LINKED ISSUE #7697: Add dark mode support to dialogs in lifecycle page
#### Current Behavior

dialog modal in [life cycle page](https://playground.meshery.io/managementl) does not support full dark mode

https://github.com/meshery/meshery/assets/71271069/f13fa938-78bb-4f60-a947-3d4c358821eb

#### Expected Behavior
- Dialogs header should be in dark color in dark mode as in below image dialog
- sub tab `Deploy` and `Undeploy` in above video should be in kepple green color

Screenshot 2023-05-17 at 10 27 33 PM

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by ciradu2204**
**Notes for Reviewers**
This PR: 
- Updates the title background colour to only be used in the light theme mode
- Enforces the use of tabs selected colour in the app.js file
- Removes the undeploy svg and replaced it with MUI identical icon. I realised the SVG version was not adapting to the different colors. Hence the reason to use the MUI icon. 

After: 

https://github.com/meshery/meshery/assets/37863089/56744f85-5160-4708-a654-19aec5c6d83b

This PR fixes #7697 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ciradu2204** [comment]
@Yashsharma1911 you can review it and let me know. Thanks.

File: ui/components/ConfirmationModal.js [hunk 1]
```diff
@@ -62,7 +62,7 @@ const styles = (theme) => ({
     // minWidth : 300,
     padding : theme.spacing(1),
     color : '#fff',
-    backgroundColor : 'rgb(57, 102, 121)',
+    backgroundColor : theme.palette.type == "light"? 'rgb(57, 102, 121)': 'none',
```
Comment (Yashsharma1911) [inline ui/components/ConfirmationModal.js:65]: Hey @ciradu2204 in dark mode, title has a dark color you can see in the below image so if you can change that `none` to the dark color that we are using in this dialog

Screenshot 2023-05-17 at 10 27 33 PM

File: ui/components/ConfirmationModal.js [hunk 2]
```diff
@@ -13,8 +13,8 @@ import { pingKubernetes } from "./ConnectionWizard/helpers/kubernetesHelpers";
 import { getK8sConfigIdsFromK8sConfig } from "../utils/multi-ctx";
 import { bindActionCreators } from "redux";
 import { useEffect, useState } from "react";
-import UndeployIcon from "../public/static/img/UndeployIcon";
 import DoneAllIcon from '@material-ui/icons/DoneAll';
+import RemoveDoneIcon from '@mui/icons-material/RemoveDone';
```
Comment (Yashsharma1911) [inline ui/components/ConfirmationModal.js:17]: it's good to directly use icon from mui but as `UndeployIcon` is also used in other files deleting it can cause an error so please restore it

File: ui/themes/app.js [hunk 3]
```diff
@@ -115,6 +115,7 @@ darkTheme = {
       root : { marginLeft : darkTheme.spacing(1), },
       indicator : {
         height : 3,
+        backgroundColor : "#00B39F",
```
Comment (Yashsharma1911) [inline ui/themes/app.js:118]: nice work 👏 here

File: ui/components/ConfirmationModal.js (hunk 2 above)
Comment (ciradu2204) [reply ui/components/ConfirmationModal.js:17]: Hi @Yashsharma1911, you are right.  I totally forgot about that. Another alternative could be replacing all the undeploy svg in the file with the mui. The SVG file does not adapt itself based on them. What do you think?

Comment (Yashsharma1911) [reply ui/components/ConfirmationModal.js:17]: yes I think it will be good

File: ui/themes/app.js (hunk 3 above)
Comment (leecalcote) [reply ui/themes/app.js:118]: Reference to a theme color is ideal.

Comment (ciradu2204) [reply ui/themes/app.js:120]: Thanks @leecalcote. This would not be possible in the app.js file unless I define the light theme colour before the dark theme. However, this is possible in other files which use the theme. You can check the changes I made in the confirmationModal.js.

File: provider-ui/package-lock.json
Comment (Yashsharma1911) [inline provider-ui/package-lock.json:1]: @ciradu2204 this file is not necessary to update

Comment (ciradu2204) [reply provider-ui/package-lock.json:1]: Thanks @Yashsharma1911. I have updated that

**Comment by leecalcote** [comment]
Thanks for this PR, @ciradu2204 🙂

**Review by Yashsharma1911 — DISMISSED** [review]
LGTM 👏

File: ui/themes/app.js (hunk 3 above)
Comment (leecalcote) [reply ui/themes/app.js:121]: @meshery/meshery-ui-maintainers any counsel here?

File: ui/components/ConfirmationModal.js (hunk 2 above)
Comment (nebula-aac) [reply ui/components/ConfirmationModal.js:17]: Is this the intended to use `@mui/*` instead of `@material-ui/*`?

while I understand the packages for `@mui/*` is still within the list of packages, `@mui/*` is not to be used until we've migrated to `@mui/*` from `@material-ui/*`.

Meaning we are still on Material UI v4, not MUI v5.

On a side note, I need to remove these packages from `ui` to avoid further confusion.

Comment (ciradu2204) [reply ui/components/ConfirmationModal.js:17]: okay, thanks for the heads up. I will return it back to its normal way.

**Comment by ciradu2204** [comment]
@leecalcote , @Yashsharma1911 , @nebula-aac , please if you get time, look at the changes I have made. And let me know if there is any change I need to make or approve. Thanks.

File: ui/themes/app.js (hunk 3 above)
Comment (Chadha93) [reply ui/themes/app.js:121]: Note - This is the file where we are adding all our theme colors, which are then referenced across the Meshery and Extensions. // @leecalcote

**Review by Chadha93 — APPROVED** [review]
LGTM, good work @ciradu2204 :medal_sports:
