### PR TITLE
fixed component view

### LINKED ISSUE #14624: [mesheryctl] mesheryctl component view fix
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

Image
component view sub-command is not assigning outFormatFlag variable as json or yaml and the output always shows the output format has not been given.
### Desired Behavior

It should be giving the component details in yaml and json format.
### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- ⌨️ [Meshkit errors Guide](https://docs.meshery.io/project/contributing/contributing-error)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by VinayCheripally**
**Notes for Reviewers**

- This PR fixes #14624 

The component view is giving the component details in json and yaml format.
image
image
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by VinayCheripally** [comment]
@lekaf974 can you take a look at this PR?

File: mesheryctl/internal/cli/root/components/view.go [hunk 1]
```diff
@@ -58,6 +58,8 @@ mesheryctl component view [component-name]
 			log.Fatalln(err, "error processing config")
 		}
 
+		outFormatFlag, _ = cmd.Flags().GetString("output-format")
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/components/view.go:61]:
```suggestion
		outFormatFlag, _ := cmd.Flags().GetString("output-format")
```

also can yuou remove the variable declaration in component.go file after it will be ok to merge

**Review by lekaf974 — CHANGES_REQUESTED** [review]
added review to clean variable management

**Review by lekaf974 — APPROVED** [review]

**Comment by lekaf974** [comment]
Good job! :rocket:
