### PR TITLE
[Server] Policies: Port OPA/Rego policy engine to native Go

### LINKED ISSUE #17240: [Server] Migrate OPA/Rego policies to Golang
### Current Behavior
Meshery's relationship evaluation engine relies on OPA (Open Policy Agent) with ~20 Rego policy files under `server/meshmodel/meshery-core/0.7.2/v1.0.0/policies/`. The server loads these via the OPA Go SDK and evaluates them at runtime through `RegoPolicyHandler`.

### Desired Behavior
Rewrite the built-in Rego policies as native Golang implementations. OPA-based policies will still be supported, but the shipped policy set should be pure Go.

## Relationship Status

- Hiearchical Parent Inventory Relationship 
  - [x] Configuration Patching  
  - [x] Identifcation

- Hierarchical Parent Alias 
  - [x] Configuration Patching  
  - [x] Identifcation
  - [x] After a alias component is deleted the relationship should be cleaned up and alias shouldnt come back again
  - [x]  Creation 

- Hierarchical Parent Wallet
  - [x] Configuration Patching  
  - [x] Identifcation
  - [x]  Creation  

- Edge network relationship
  - [x]  Configuration Patching  
  - [x] Creation  
  - [x]  Identifcation

- Edge reference relationship
  - [x]  Configuration Patching  
  - [x] Creation  
  - [x]  Identifcation
 
- Edge binding relationships relationship
  - [x]  Configuration Patching  
  - [x] Creation  
  - [x]  Identifcation

- Sibling
  - [x]  No patching behavior need  
  - [x] Creation  ( manully by inputting matching labeles )
  - [x]  Identifcation
  - [x] Max Limit of 20 per design  

## Acceptance Tests
- [x]  Evaluation response should contain the trace of action taken
- [x] Relationship evaluation should be controllable from layers preferences in designs
- [x] Evaluation engine should use strict contruct types from schemas instead of maps
- [x] Relationships e2e tests should be passing ( those validate identification behavior ) 
- [x] Need e2e tests for robust non hardcoded tests for relationship creation,config patching.  ( proposal ? ) .

## Issues 
- [x] Parent–inventory (parent–child) relationships are not functioning correctly (e.g., namespace to namespaced components).
- [x] Hierarchical alias relationships (e.g., between deployments and containers) are not working.
- [x] Edge-binding relationships (e.g., mounts and permissions) are not functioning.
- [x] The trace returned by evaluation does not include all expected fields.
- [x] Component configuration mutation is not working as intended.
- [x] Styles missing for added components from engine
- [x] Permission role binding relationship not working properly ( configuration not patched for binding ) 
- [x] Evaluation was slow . ( other aspects of server were slow too ) . need to check if its the machine or evaluation engine that is slow
- [x] Wallet relationship not working properly ( configuration not being patched )

## Benchmarks

Micro-benchmarks (Apple M1 Max, `go test -bench=. -benchtime=3s`):

| Benchmark | Go | OPA | Speedup |
|---|---|---|---|
| Validation | 596 ns/op | 65,321 ns/op | ~110x |
| Identify | 21,547 ns/op | 42,475 ns/op | ~2x |
| Actions | 383 ns/op | 52,981 ns/op | ~138x |
| Full Pipeline (prepared) | 81,878 ns/op | 1,030,114 ns/op | ~12.6x |
| Full Pipeline (cold compile) | 81,878 ns/op | 37,463,580 ns/op | ~457x |
| MatchValues | 18 ns/op | 5,474 ns/op | ~300x |

Catalog alignment test (382 live catalog designs, Go vs OPA):

| Category | Designs | Avg Go | Avg OPA | Max Speedup |
|---|---|---|---|---|
| OPA_CRASH | 151 | 140ms | crashed | — |
| LEGACY_PREPASS | 51 | 6ms | 275ms | 125x |
| REL_COUNT_DIFF | 45 | 39ms | 167ms | 102x |
| DEEP_MATCH | 45 | 14ms | 96ms | 179x |
| OPA_TIMEOUT | 10 | 2,616ms | 10,000ms (timeout) | 229x |

## Test results 

**Unit Tests**                                                                                                                                                                   

```                                                                                                                                                                               
go test ./server/policies/ -count=1 -timeout 300s
                                                                                                                                                                             
--- PASS: TestBehaviorAlignment (0.21s)                                                                                                                                      
--- PASS: TestCatalogAlignment (203.86s)
--- PASS: TestIsRelationshipFeasible (0.00s)                                                                                                                                 
--- PASS: TestIsRelationshipDenied (0.00s)                                                                                                                                   
--- PASS: TestIsAliasRelationship (0.00s)                                                                                                                                    
--- PASS: TestPolicyImplication (0.00s)                                                                                                                                      
--- PASS: TestFromAndToComponentsExist (0.00s)                              
--- PASS: TestValidateRelationshipsInDesign (0.00s)                                                                                                                          
--- PASS: TestEdgeBindingPolicyImplication (0.00s)                          
--- PASS: TestIsValidBinding (0.00s)                                                                                                                                         
--- PASS: TestHierarchicalIdentifyRelationship (0.00s)                                                                                                                       
--- PASS: TestHierarchicalSideEffects (0.00s)                                                                                                                                
--- PASS: TestGoEngineCreation (0.00s)                                                                                                                                       
--- PASS: TestAliasIsInvalidStatusMatrix (0.00s)                                                                                                                             
--- PASS: TestWalletPatching (0.00s)                                                                                                                                         
--- PASS: TestWalletPatchingFullPipeline (0.00s)                                                                                                                             
--- PASS: TestBindingPatching (0.00s)                                                                                                                                        
--- PASS: TestAliasSideEffects (0.00s)                                                                                                                                       
--- PASS: TestBindingIdentification (0.00s)                                                                                                                                  
--- PASS: TestBindingIdentificationEmptyValues (0.00s)                      
--- PASS: TestBindingIdentificationFullPipeline (0.00s)                                                                                                                      
--- PASS: TestInventoryNamespaceIdentification (0.00s)                                                                                                                       
--- PASS: TestInventoryPatchingFullPipeline (0.00s)                                                                                                                          
--- PASS: TestRegoPolicy (0.10s)                                                                                                                                             
--- PASS: TestRegoPolicyRules (0.12s)                                                                                                                                        
--- PASS: TestRelationshipEvaluationScenarios (0.23s)                       
--- PASS: TestRegoSyntax (0.02s)                                                                                                                                             
--- PASS: TestObjectGetNested (0.00s)                                                                                                                                        
--- PASS: TestMatchName (0.00s)                                                                                                                                              
--- PASS: TestMatchValues (0.00s)                                                                                                                                            
--- PASS: TestPopLast (0.00s)                                               
--- PASS: TestIsDirectReference (0.00s)                                                                                                                                      
--- PASS: TestStringSliceToInterface (0.00s)                                
--- PASS: TestResolvePath (0.00s)                                                                                                                                            
--- PASS: TestCanonicalSeedDeterminism (0.00s)                                                                                                                               
--- PASS: TestStaticUUIDDeterminism (0.00s)
--- PASS: TestNewUUIDNonDeterminism (0.00s)                                                                                                                                  
PASS                                                                                                                                                                         
ok  github.com/meshery/meshery/server/policies  205.412s
```

**E2E Tests**

```
Running 8 tests using 1 worker

[local-setup] › tests/e2e/local.setup.js:12:6 › authenticate as None provider
Provider in auth setup: None

Container-Hierarchical-Parent-Alias-Relationship @relationship
Total relationship failures for container-hierarchical-parent-alias-relationship: 0

deployment-configmap-reference-relationship @relationship
Total relationship failures for deployment-configmap-reference-relationship: 0

Hierarchical-Parent-Namespace-Relationship @relationship
Total relationship failures for hierarchical-parent-namespace-relationship: 0

Service-To-Deployment-Network @relationship
Total relationship failures for service-to-deployment-network: 0

pv-pvc-edge-non-binding-reference-relationship @relationship
Total relationship failures for pv-pvc-edge-non-binding-reference-relationship: 0

meshery-design @relationship
Total relationship failures for meshery-design-fixture.json: 1

All Relationships @relationship
Total relationship failures for Understanding Relationships: 0

  8 passed (2.1m)
```

**Remaining 1 failure:** `edge/non-binding/reference from=ClusterRoleBinding to=ClusterRole` in meshery-design fixture. Root cause: relDef path uses `configuration.spec.roleRef.name` but ClusterRoleBinding stores roleRef at top level (`configuration.roleRef.name`, no `spec` layer). This is a relationship definition data issue.

### Future Considerations

- [x] track the publication of evaluation engine test results to [qa.meshery.io](http://qa.meshery.io/) - https://github.com/meshery/meshery/issues/18421

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 📺 [Self-paced Contributor Trainings](https://meshery.io/talks-and-trainings#trainings)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by guan404ming**
**Notes for Reviewers**

- This PR fixes #17240

## Discussion Forum Thread: 
 https://discuss.layer5.io/t/how-to-run-meshery-with-the-alternative-go-evaluation-engine/7731

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by guan404ming** [comment]
The comment action in ci causes the problem, which is fixed in https://github.com/meshery/meshery/pull/17332

**Comment by leecalcote** [comment]
> The comment action in ci causes the problem, which is fixed in #17332

Mostly / halfway fixed, yes.

**Comment by guan404ming** [comment]
Agree with you. We could tell it is already fixed after we got the pre-commit hook

File: server/handlers/policy_relationship_handler.go [hunk 1]
```diff
@@ -171,13 +173,33 @@ func (h *Handler) EvaluateDesign(
 	var lastEvaluationResponse pattern.EvaluationResponse
 	lastEvaluationResponse.Design = relationshipPolicyEvalPayload.Design
 
+	useGoEngine := viper.GetBool("USE_GO_POLICY_ENGINE")
```
Comment (reaper8055) [inline server/handlers/policy_relationship_handler.go:294]: No comments on the code, just wanted to check have you tried using this flag to see if the switch is happening (it should from your code logic below) but it's good to test

Comment (guan404ming) [reply server/handlers/policy_relationship_handler.go:294]: Yes, I've run with that feature flag and it looks good to me. I also update with a alignment and benchmark test to ensure the behaviour alignment wiht OPA and prevent regression.

Here is my local test

```
=== RUN   TestBehaviorAlignment
=== RUN   TestBehaviorAlignment/match_values
=== RUN   TestBehaviorAlignment/from_and_to_components_exist
=== RUN   TestBehaviorAlignment/from_and_to_missing_component
=== RUN   TestBehaviorAlignment/validation_invalidates_orphaned_relationship
=== RUN   TestBehaviorAlignment/identify_relationships
--- PASS: TestBehaviorAlignment (0.25s)

  Benchmarks (Apple M1 Max, 3 runs)
┌───────────────┬────────────┬──────────────────────┬─────────┬───────────┬────────────┐
│     Phase     │ Go (ns/op) │     OPA (ns/op)      │ Speedup │ Go allocs │ OPA allocs │
├───────────────┼────────────┼──────────────────────┼─────────┼───────────┼────────────┤
│ MatchValues   │ 23         │ 6,420                │ ~272x   │ 0         │ 79         │
├───────────────┼────────────┼──────────────────────┼─────────┼───────────┼────────────┤
│ Validation    │ 603        │ 82,236               │ ~136x   │ 4         │ 633        │
├───────────────┼────────────┼──────────────────────┼─────────┼───────────┼────────────┤
│ Actions       │ 505        │ 65,128               │ ~129x   │ 2         │ 563        │
├───────────────┼────────────┼──────────────────────┼─────────┼───────────┼────────────┤
│ Identify      │ 15,095     │ 50,306               │ ~3.3x   │ 131       │ 528        │
├───────────────┼────────────┼──────────────────────┼─────────┼───────────┼────────────┤
│ Full Pipeline │ 75,470     │ 1,232,982 (prepared) │ ~16x    │ 642       │ 8,703      │
├───────────────┼────────────┼──────────────────────┼─────────┼───────────┼────────────┤
│ Full Pipeline │ 75,470     │ 47,435,344 (cold)    │ ~629x   │ 642       │ 334,194    │
└───────────────┴────────────┴──────────────────────┴─────────┴───────────┴────────────┘
```

Comment (guan404ming) [reply server/handlers/policy_relationship_handler.go:294]: Thanks for great question!

**Comment by guan404ming** [comment]
Hi I found that I could edit my pr title. But I think to add [Server] as prefix would be better align to the convention here. Could you help with me, thanks!

File: server/handlers/policy_relationship_handler.go [hunk 2]
```diff
@@ -171,13 +173,33 @@ func (h *Handler) EvaluateDesign(
...
-		// on successful eval the event containing details like comps evaulated, relationships indeitified should be emitted and peristed.
-		evaluationResponse, err := h.Rego.RegoPolicyHandler(lastEvaluationResponse.Design,
-			RelationshipPolicyPackageName,
-		)
+		var evaluationResponse pattern.EvaluationResponse
+		var err error
+
+		if useGoEngine && h.GoEngine != nil {
+			// Use native Go policy engine
+			registeredRels, _, _, relErr := h.registryManager.GetEntities(&regv1alpha3.RelationshipFilter{})
```
Comment (reaper8055) [inline server/handlers/policy_relationship_handler.go]: Please add a comment briefly explaining why the two values are skipped here

File: server/policies/engine.go [hunk 3]
```diff
@@ -0,0 +1,276 @@
...
+	e.log.Info("models in design: ", len(modelsInDesign), ", registered rels: ", len(relMaps), ", rels in scope: ", len(relsInScope))
+
+	resultDesign, allActions := e.evaluate(designMap, relsInScope)
+
+	resp, err = fromGenericMap(resultDesign)
+	if err != nil {
+		return resp, ErrConvertResult(err)
+	}
+
+	for _, a := range allActions {
```
Comment (reaper8055) [inline server/policies/engine.go]: please use singular-plural range verb:

```go
for _, acition := range Actions {
... 
}
```

**Comment by guan404ming** [comment]
Thanks for you nice suggestions, just updated. Pleas take another look, thanks!

File: server/policies/policy_alias.go
Comment (reaper8055) [inline server/policies/policy_alias.go:1]: Add tests for:
- IsInvalid status matrix: pending, approved, deleted, malformed.
- aliasRefFromRelationship extraction with missing/partial selectors.
- getArrayAwareConfigPaths direct vs wildcard refs.
- IdentifyRelationship with one/multiple matched paths.
- AlreadyExists duplicate detection (including deleted existing rels).
- SideEffects add/delete component actions by status.

File: server/policies/policy_hierarchical.go
Comment (reaper8055) [inline server/policies/policy_hierarchical.go:1]: Add tests for:
- deny selector rejection path.
- feasibility rejection path.
- approved status assignment on valid pair.
- side effects skipped when status=deleted

File: server/policies/actions.go
Comment (reaper8055) [inline server/policies/actions.go:1]: Add tests for:
- grouping logic correctness.
- dedup of components inside group.
- maxMatchLabels cap behavior.
- deterministic ID generation across repeated invocation on same input.
- malformed config/match refs handling (no panic, empty result).

File: server/policies/policy_binding.go
Comment (reaper8055) [inline server/policies/policy_binding.go:1]: Add test covering:
- from-binding-to triple matching.
- mismatch rejection when one leg fails.
- deny-selector enforcement.
- self-reference exclusions.

File: server/policies/policy_edge_network.go
Comment (reaper8055) [inline server/policies/policy_edge_network.go:1]: Add tests for:
- implication positive/negative.
- IdentifyRelationship positive case.
- deny-selector case (currently likely failing, documents gap).
- SideEffects no-op on deleted, patch action otherwise.

File: server/policies/policy_matchlabels.go
Comment (reaper8055) [inline server/policies/policy_matchlabels.go:1]: Add tests for:
- grouping logic correctness.
- dedup of components inside group.
- maxMatchLabels cap behavior.
- deterministic ID generation across repeated invocation on same input.
- malformed config/match refs handling (no panic, empty result).

File: server/policies/utils.go
Comment (reaper8055) [inline server/policies/utils.go:1]: Add tests for:
- popLast, isDirectReference, stringSliceToInterface, relationshipPreferenceKey.
- resolvePath with wildcard present/absent, empty/non-array target.
- canonicalSeed determinism on equivalent maps.
- staticUUID determinism and newUUID non-determinism contract.

**Comment by guan404ming** [comment]
@reaper8055 I just updated with mentioned tests. Please take another look, thanks!

utils.go (7 tests):                                                                                                  
- TestPopLast - slice without last element                                                                           
- TestIsDirectReference - direct vs wildcard ref detection                                                           
- TestStringSliceToInterface - type conversion                                          
- TestRelationshipPreferenceKey - preference key building
- TestResolvePath - wildcard present/absent, empty/non-array target
- TestCanonicalSeedDeterminism - determinism on equivalent maps
- TestStaticUUIDDeterminism / TestNewUUIDNonDeterminism - UUID contracts

policy_alias.go (5 tests):
- TestAliasIsInvalidStatusMatrix - pending, approved, deleted, malformed
- TestAliasRefFromRelationshipMissingSelectorParts - missing/partial selectors
- TestGetArrayAwareConfigPaths - direct vs wildcard refs
- TestAliasIdentifyRelationshipMultiplePaths - one/multiple matched paths
- TestAliasAlreadyExistsDuplicateDetection - duplicates including deleted rels
- TestAliasSideEffectsByStatus - add/delete component actions by status

policy_hierarchical.go (4 tests):
- TestHierarchicalDenySelectorRejection - deny selector rejection path
- TestHierarchicalFeasibilityRejection - feasibility rejection path
- TestHierarchicalApprovedStatusOnValidPair - approved status on valid pair
- TestHierarchicalSideEffectsSkippedWhenDeleted - side effects skipped when deleted

policy_binding.go (4 tests):
- TestBindingTripleMatching - from-binding-to triple matching
- TestBindingMismatchRejection - mismatch rejection when one leg fails
- TestBindingDenySelectorEnforcement - deny-selector enforcement
- TestBindingSelfReferenceExclusion - self-reference exclusions

policy_edge_network.go (3 tests):
- TestEdgeNonBindingImplication - positive/negative implication
- TestEdgeNonBindingIdentifyPositive - identify positive case
- TestEdgeNonBindingSideEffectsDeletedNoop - no-op on deleted, patch otherwise

policy_matchlabels.go (5 tests):
- TestMatchLabelsGroupingLogic - grouping correctness
- TestMatchLabelsDedupInGroup - dedup of components inside group
- TestMatchLabelsMaxCap - maxMatchLabels cap behavior
- TestMatchLabelsDeterministicID - deterministic ID generation
- TestMatchLabelsMalformedInput - nil config/empty refs (no panic, empty result)

File: server/policies/engine_test.go [hunk 4]
```diff
@@ -742,3 +743,1753 @@ func TestGoEngineCreation(t *testing.T) {
 		t.Errorf("Expected 5 policies, got %d", len(engine.policies))
 	}
 }
+
+// --- utils.go tests ---
+
+func TestPopLast(t *testing.T) {
+	tests := []struct {
```
Comment (reaper8055) [inline server/policies/engine_test.go]: Another small thing that I would like to see for these tests is a "testCase":

eg:

```go
tests := []struct {
  testCase string
  // ... other fields 
} {
  // ...
}
```

In use that name in the loop:

```go
for _, test := range tests {
   t.Run(test.testCase, func(t *testing.T) {
     // compare got and want logic
   }
}
```

This give the reviewer context on what this test actually tests for.
 
do this for all the tests.

---

EDIT: You are already doing this, sorry my bad, just add a little more description to "multiple", "two", "single" maybe?

File: server/policies/engine_test.go [hunk 5]
```diff
@@ -742,3 +743,1753 @@ func TestGoEngineCreation(t *testing.T) {
...
+				t.Errorf("isDirectReference(%v) = %v, want %v", tt.ref, result, tt.expected)
+			}
+		})
+	}
+}
+
+func TestStringSliceToInterface(t *testing.T) {
+	input := []string{"a", "b", "c"}
+	result := stringSliceToInterface(input)
+	if len(result) != 3 {
```
Comment (reaper8055) [inline server/policies/engine_test.go]: The actual function this is testing for can only convert StringSliceToInterface when slice length == 3, no more no less?

File: server/policies/engine_test.go [hunk 6]
```diff
@@ -742,3 +743,1753 @@ func TestGoEngineCreation(t *testing.T) {
...
+		name     string
+		ref      []string
+		expected bool
+	}{
+		{"direct", []string{"configuration", "name"}, true},
+		{"wildcard", []string{"configuration", "containers", "_"}, false},
+		{"empty", []string{}, true},
+		{"single direct", []string{"name"}, true},
+		{"single wildcard", []string{"_"}, false},
+	}
```
Comment (reaper8055) [inline server/policies/engine_test.go]: Can you add some more description to the name field?

File: server/policies/engine_test.go
Comment (reaper8055) [inline server/policies/engine_test.go:1]: Not a big deal but instead of having all tests in one file, and having comments // -- <file-name> test -- you can just separate them into individual files. It's considered a good practice and it's easier for reviewing as well!

And as always great work on these tests!!

Comment (guan404ming) [reply server/policies/engine_test.go:1]: Thanks! I think we could work to together to refactor those test in better way after this one!

File: server/policies/engine_test.go (hunk 5 above)
Comment (guan404ming) [reply server/policies/engine_test.go]: Great point, it could be dynamic. I just updated the tests to make it more robust!

File: server/handlers/policy_relationship_handler.go (hunk 1 above)
Comment (leecalcote) [reply server/handlers/policy_relationship_handler.go:294]: Along similar lines, it would be helpful to have the option for designs to be evaluated by both engines, so that we can compare their output in terms of decisions, made with respect to the number and type of relationships (with respect to the evaluation results and comparing between the two engines).

File: server/policies/policy_edge_network.go
Comment (leecalcote) [reply server/policies/policy_edge_network.go:1]: @reaper8055, your robust review is super helpful. 💯

File: server/policies/utils.go
Comment (leecalcote) [reply server/policies/utils.go:1]: @guan404ming, I _think_ that you've created these tests now. If so, please resolve this comment and any others that have been addressed.

Comment (guan404ming) [reply server/policies/utils.go:1]: Sure, I will resolve them if I addressed that. Thanks!

**Comment by guan404ming** [comment]
# Catalog Alignment Test: Go vs OPA Engine

Compares Go and OPA policy engines on real [Meshery Catalog](https://meshery.io/catalog/designs) designs.

```bash
go test ./server/policies/ -run TestCatalogAlignment -v
```

## Results

| Category | Count | Verdict |
|---|---|---|
| OPA_CRASH | 35 (43%) | OPA bug |
| LEGACY_PREPASS | 18 (22%) | OPA legacy code |
| MATCH | 15 (18%) | Engines agree |
| SET_ORDERING | 6 (7%) | OPA bug |
| REL_COUNT_DIFF | 6 (7%) | OPA legacy side-effect |
| DELETE_RETAIN | 2 (2%) | OPA legacy side-effect |

Base on my understanding and investigation, all divergences are OPA-side. Go engine needs no changes.
Please help me recheck this and feel free to correct me, thanks!

## Root Causes

**OPA_CRASH (35):** `patch_helper_rules.rego:74` produces multiple outputs for same inputs on alias designs.

**LEGACY_PREPASS (26 total):** `evaluation.rego:76-198` runs a legacy diff pass before the 3-phase pipeline. It only handles `inventory` rels and explicitly skips alias, annotation, non-binding. This deletes valid rels the 3-phase pipeline would keep. The Go engine correctly skips this legacy pass.

**SET_ORDERING (6):** `evaluation.rego:206` converts arrays to sets, reordering selectors. `from_component_id()` checks only `selectors[0].allow.from[0].id`, so reordering breaks validation.

## Designs Used (82 with relationships)

Designs are stored as `.json` files in this directory. Drop any new `.json` file here and the test picks it up automatically.

<details>
<summary>Full list (82 evaluated)</summary>

| Design | Comps | Rels | Category |
|---|---|---|---|
| 3-Tier-Architecture | 13 | 12 | OPA_CRASH |
| AWS-RDS-Controller | 7 | 6 | OPA_CRASH |
| AWS-cloudfront-controller | 7 | 6 | OPA_CRASH |
| Accelerated-mTLS-handshake-for-Envoy-data-planes | 23 | 14 | OPA_CRASH |
| Apache-Airflow | 8 | 14 | OPA_CRASH |
| Autogenerated | 7 | 6 | OPA_CRASH |
| Busybox-single-fresh | 8 | 35 | OPA_CRASH |
| Complete-Kubernetes-Application-Pattern | 15 | 4 | MATCH |
| CryptoMB-TLS-handshake-acceleration-for-Istio | 12 | 42 | OPA_CRASH |
| DaemonSet-GKE-Autopilot | 8 | 23 | LEGACY_PREPASS |
| Delay-Action-for-Chaos-Mesh | 3 | 4 | SET_ORDERING |
| Deploy-Meshery-using-Meshery | 6 | 6 | OPA_CRASH |
| Deployable-simple-web-architecture-design | 7 | 8 | OPA_CRASH |
| Double-Bubble-Map | 67 | 26 | MATCH |
| Edge-Firewall-relationship | 7 | 12 | DELETE_RETAIN |
| Edge-Relationships-diff | 9 | 12 | OPA_CRASH |
| Edge-mount-relationship | 5 | 39 | DELETE_RETAIN |
| Exam-Portal-with-Real-Time-Leaderboard-AWS | 22 | 2 | MATCH |
| Example-Edge-Network | 4 | 4 | LEGACY_PREPASS |
| Example-Edge-Network-Relationship- | 4 | 4 | LEGACY_PREPASS |
| Example-Labels-and-Annotations | 6 | 12 | SET_ORDERING |
| Fault-tolerant-batch-GKE | 9 | 37 | LEGACY_PREPASS |
| Fault-tolerant-batch-workloads-on-GKE | 9 | 37 | LEGACY_PREPASS |
| GCP-DataMesh | 6 | 5 | MATCH |
| Hello-Kubernetes-Tutorial | 15 | 23 | OPA_CRASH |
| Hierarchical-Parent-Inventory-Relationship | 6 | 17 | MATCH |
| Hierarchical-Parent-Matchlabels-Relationship | 10 | 1 | MATCH |
| HorizontalPodAutoscaler | 3 | 3 | LEGACY_PREPASS |
| Istio-Operator | 7 | 10 | OPA_CRASH |
| Jaeger-operator | 7 | 9 | OPA_CRASH |
| K8s-Workload-Controllers | 11 | 5 | MATCH |
| Key-cloak-operator | 7 | 6 | OPA_CRASH |
| Keycloak-Operator | 7 | 6 | OPA_CRASH |
| Kubernetes-Engine-Training-Example- | 9 | 26 | SET_ORDERING |
| Kubernetes-Workload-Controllers-Overview | 11 | 5 | MATCH |
| Kubernetes-cronjob | 5 | 14 | LEGACY_PREPASS |
| Kubernetes-service-Design | 20 | 10 | REL_COUNT_DIFF |
| Litmus-Chaos-Operator | 7 | 6 | OPA_CRASH |
| LoxiLB-K8S-External-Load-Balancer | 11 | 25 | MATCH |
| Match-Labels-Relationship | 11 | 39 | SET_ORDERING |
| Minecraft-App | 4 | 6 | OPA_CRASH |
| Namespaces-in-kubernetes | 16 | 11 | REL_COUNT_DIFF |
| Observable-K8s-Workloads | 5 | 7 | MATCH |
| ObserverbalKubernetesWorkloads | 5 | 7 | MATCH |
| Online-Polling-Application | 10 | 9 | OPA_CRASH |
| Oracle-e-commerce-microservices-on-kubernetes | 68 | 7 | MATCH |
| Persistence-volume-claim | 3 | 2 | LEGACY_PREPASS |
| Pod-Multi-Containers | 4 | 3 | OPA_CRASH |
| Pod-Readiness | 3 | 2 | OPA_CRASH |
| Pod-Resource-Request | 3 | 2 | OPA_CRASH |
| Redis-PHP-Guestbook | 34 | 49 | OPA_CRASH |
| Resilient-Web-App | 8 | 15 | OPA_CRASH |
| Run-DaemonSet-on-GKE-Autopilot | 8 | 23 | LEGACY_PREPASS |
| Simple-Kubernetes-Pod | 4 | 6 | OPA_CRASH |
| Simple-Web-Architecture | 7 | 8 | OPA_CRASH |
| URL-Shortener-Application | 10 | 9 | OPA_CRASH |
| VPC-WORKFLOW-DESIGN | 41 | 24 | REL_COUNT_DIFF |
| Weather-Forecasting-App | 10 | 9 | OPA_CRASH |
| WordPress-and-MySQL-with-Persistent-Volume-on-Kubernetes | 3 | 4 | LEGACY_PREPASS |
| clickhouse-otel-hyperdx | 9 | 14 | REL_COUNT_DIFF |
| clickhouse-otel-hyperdx-arch | 9 | 14 | REL_COUNT_DIFF |
| container-alias-relationship | 7 | 4 | MATCH |
| container-hierarchical-parent-alias-relationship | 7 | 4 | MATCH |
| default-ns | 2 | 1 | LEGACY_PREPASS |
| doks-nginx-deployment | 9 | 21 | OPA_CRASH |
| example-project | 3 | 2 | LEGACY_PREPASS |
| gitlab-runner-deployment | 7 | 8 | OPA_CRASH |
| grafana-deployment | 7 | 8 | OPA_CRASH |
| hierarchical-parent-namespace-relationship | 2 | 1 | LEGACY_PREPASS |
| katib-242 | 32 | 20 | OPA_CRASH |
| kibana-helm-design-fixed | 4 | 2 | OPA_CRASH |
| meshery-cilium-deployment | 3 | 4 | LEGACY_PREPASS |
| meshery-design-fixturejson | 33 | 32 | SET_ORDERING |
| my-first-app-design | 12 | 49 | SET_ORDERING |
| my-sql-with-cinder-vol-plugin | 4 | 6 | OPA_CRASH |
| postgreSQL-cluster | 2 | 1 | LEGACY_PREPASS |
| prometheus-operator-crd-cluster-roles | 3 | 2 | LEGACY_PREPASS |
| prometheus_kubernetes | 10 | 50 | LEGACY_PREPASS |
| service-to-deployment-network | 4 | 4 | REL_COUNT_DIFF |
| sqlcl-liquibase-100tgz | 5 | 3 | OPA_CRASH |
| test-design-account | 31 | 2 | MATCH |
| voting_app | 3 | 4 | LEGACY_PREPASS |

</details>

File: server/policies/eval_rules.go [hunk 7]
```diff
@@ -0,0 +1,624 @@
...
+		compID := getMapString(comp, "id")
+		if compID == id {
+			return comp
+		}
+	}
+	return nil
+}
+
+// fromComponentID returns the from component ID from a relationship declaration.
+func fromComponentID(rel map[string]interface{}) string {
```
Comment (aabidsofi19) [inline server/policies/eval_rules.go]: @guan404ming  use the relationshipDefintion struct instead of map from schemas

File: server/policies/eval_rules.go [hunk 8]
```diff
@@ -0,0 +1,624 @@
...
+	}
+	fromSel, ok := from[0].(map[string]interface{})
+	if !ok {
+		return ""
+	}
+	return getMapString(fromSel, "id")
+}
+
+// toComponentID returns the to component ID from a relationship declaration.
+func toComponentID(rel map[string]interface{}) string {
```
Comment (aabidsofi19) [inline server/policies/eval_rules.go]: @guan404ming  use the relationshipDefintion struct instead of map from schemas

File: server/policies/eval_rules.go [hunk 9]
```diff
@@ -0,0 +1,624 @@
...
+	}
+	toSel, ok := to[0].(map[string]interface{})
+	if !ok {
+		return ""
+	}
+	return getMapString(toSel, "id")
+}
+
+// fromAndToComponentsExist checks if both from and to components still exist in the design.
+func fromAndToComponentsExist(rel, design map[string]interface{}) bool {
```
Comment (aabidsofi19) [inline server/policies/eval_rules.go]: @guan404ming  use the relationshipDefintion and design struct instead of map from schemas

File: server/policies/eval_rules.go [hunk 10]
```diff
@@ -0,0 +1,624 @@
...
+		// try without "spec" (handles relDefs that include "spec" but
+		// components that store fields directly under configuration).
+		if val == nil && len(rest) > 1 && rest[0] == "spec" {
+			val = objectGetNested(config, rest[1:], nil)
+		}
+		return val
+	}
+
+	val := objectGetNested(component, path, nil)
+	// Fallback: if path doesn't start with "configuration" but value is nil,
```
Comment (aabidsofi19) [inline server/policies/eval_rules.go]: @guan404ming  we dont need this behavior . the relationship definition need to be updated with proper mutators

File: server/policies/eval_rules.go [hunk 11]
```diff
@@ -0,0 +1,624 @@
...
+	}
+	return val
+}
+
+// getComponentConfiguration returns the configuration for a component,
+// resolving aliases if present.
+func getComponentConfiguration(component, design map[string]interface{}) interface{} {
+	compID := getMapString(component, "id")
+
+	// Check for alias
```
Comment (aabidsofi19) [inline server/policies/eval_rules.go]: extract into a helper ( or reuse one ) for checking aliases and getting

File: server/policies/eval_rules.go [hunk 12]
```diff
@@ -0,0 +1,624 @@
...
+
+// sameRelationshipSelectorClause checks if two selector clauses reference the same component.
+func sameRelationshipSelectorClause(clauseA, clauseB map[string]interface{}) bool {
+	return getMapString(clauseA, "kind") == getMapString(clauseB, "kind") &&
+		getMapString(clauseA, "id") == getMapString(clauseB, "id") &&
+		deepEqual(clauseA["patch"], clauseB["patch"])
+}
+
+// relationshipsAreSame checks if two relationships are equivalent.
+func relationshipsAreSame(relA, relB map[string]interface{}) bool {
```
Comment (aabidsofi19) [inline server/policies/eval_rules.go]: @guan404ming where is this used . dedupe ? . proprably this should we placed in relationships helpers . so can be reused can handlers

Comment (aabidsofi19) [reply server/policies/eval_rules.go]: or schemas .

File: server/policies/eval_rules.go [hunk 13]
```diff
@@ -0,0 +1,624 @@
...
+		}
+		return true
+	}
+
+	return deepEqual(fromValue, toValue)
+}
+
+// identifyRelationshipsBasedOnMatchingMutatorAndMutatedFields identifies relationships
+// where components have matching values at mutator/mutated paths.
+func identifyRelationshipsBasedOnMatchingMutatorAndMutatedFields(
```
Comment (aabidsofi19) [inline server/policies/eval_rules.go]: this function is hard to read , break into smaller reusable functions

File: server/policies/identify_additions.go [hunk 14]
```diff
@@ -0,0 +1,140 @@
+package policies
+
+import "strings"
+
+// identifyAdditions finds components that should be added to the design based on
```
Comment (aabidsofi19) [inline server/policies/identify_additions.go]: the code in this policy probaly needs to die . as this is from the older policy  code.

**Review by aabidsofi19 — CHANGES_REQUESTED** [review]

File: server/policies/engine.go [hunk 15]
```diff
@@ -0,0 +1,409 @@
...
+				continue
+			}
+			updates = append(updates, pl)
+		}
+	}
+
+	for _, comp := range resp.Design.Components {
+		var patches []patching.Patch
+		for _, up := range updates {
+			if up.ID == comp.ID.String() {
```
Comment (aabidsofi19) [inline server/policies/engine.go]: we are again harcoding the pating logic here . this shouldnt be needed

File: server/policies/eval_rules.go (hunk 7 above)
Comment (guan404ming) [reply server/policies/eval_rules.go]: Done. Now takes `*relationship.RelationshipDefinition`, accesses selectors via typed fields.

File: server/policies/eval_rules.go (hunk 8 above)
Comment (guan404ming) [reply server/policies/eval_rules.go]: Done. Same change as fromComponentID.

File: server/policies/eval_rules.go (hunk 9 above)
Comment (guan404ming) [reply server/policies/eval_rules.go]: Done. Takes `*relationship.RelationshipDefinition` and `*pattern.PatternFile`. The entire `RelationshipPolicy` interface and all 6 implementations converted to typed structs.

File: server/policies/eval_rules.go (hunk 10 above)
Comment (guan404ming) [reply server/policies/eval_rules.go]: Removed the fallback. Also fixed 427 relationship definition JSON files where mutatedRef paths like `["metadata","name"]` were missing the `"configuration"` prefix.

File: server/policies/eval_rules.go (hunk 11 above)
Comment (guan404ming) [reply server/policies/eval_rules.go]: Extracted `resolveComponentAlias(compID, design)` as a reusable helper. `getComponentConfiguration` now calls it.

File: server/policies/eval_rules.go (hunk 12 above)
Comment (guan404ming) [reply server/policies/eval_rules.go]: Exported as `RelationshipsAreSame` for reuse. Used for dedup during identification.

File: server/policies/eval_rules.go (hunk 13 above)
Comment (guan404ming) [reply server/policies/eval_rules.go]: Split into `componentMatchesKind`, `buildIdentifiedRelationship`, and `matchComponentPairs`.

File: server/policies/identify_additions.go (hunk 14 above)
Comment (guan404ming) [reply server/policies/identify_additions.go]: Deleted file and removed all calls.

File: server/policies/engine.go (hunk 15 above)
Comment (guan404ming) [reply server/policies/engine.go]: Simplified. Removed the if/else branching, only strips `"configuration"` prefix when present. RelDefs updated with correct paths.

File: server/policies/actions.go [hunk 16]
```diff
@@ -0,0 +1,371 @@
...
+func getComponentUpdateOp(path []string) string {
+	if len(path) > 0 && path[0] == "configuration" {
+		return UpdateComponentConfigurationOp
+	}
+	return UpdateComponentOp
+}
+
+// applyUpdatesToItem applies all update actions matching the given op and item ID
+// to the original item map, returning the updated version.
+func applyUpdatesToItem(original map[string]interface{}, actions []PolicyAction, op string) map[string]interface{} {
```
Comment (aabidsofi19) [inline server/policies/actions.go]: use a strict schema type here if possible

File: server/policies/actions.go [hunk 17]
```diff
@@ -0,0 +1,371 @@
...
+		item := getMapMap(action.Value, "item")
+		if item != nil {
+			result = append(result, item)
+		}
+	}
+	return result
+}
+
+// applyAllActionsToDesign applies all actions to a design map.
+func applyAllActionsToDesign(design map[string]interface{}, actions []PolicyAction) map[string]interface{} {
```
Comment (aabidsofi19) [inline server/policies/actions.go]: use schema types

File: server/policies/feasibility.go [hunk 18]
```diff
@@ -0,0 +1,134 @@
...
+	return selectorAndComponentKindMatches(sel, comp) &&
+		selectorAndComponentModelMatches(sel, comp)
+}
+
+func selectorAndComponentKindMatches(sel relationship.SelectorItem, comp *component.ComponentDefinition) bool {
+	k := selectorItemKind(sel)
+	if k == "*" {
+		return true
+	}
+	return k == comp.Component.Kind
```
Comment (aabidsofi19) [inline server/policies/feasibility.go]: the string match ( supporting regex, wildcards , etc ) should be reusable function and reused for the matchers

File: server/policies/policy.go [hunk 19]
```diff
@@ -0,0 +1,105 @@
...
+// validateRelationshipsInDesign validates relationships in the design for a policy.
+func validateRelationshipsInDesign(design *pattern.PatternFile, policy RelationshipPolicy) []PolicyAction {
+	implicated := implicableRelationships(design.Relationships, policy)
+
+	var actions []PolicyAction
+	for _, rel := range implicated {
+		if fromOrToComponentsDontExist(rel, design) && policy.IsInvalid(rel, design) {
+			actions = append(actions, PolicyAction{
+				Op: UpdateRelationshipOp,
+				Value: map[string]interface{}{
```
Comment (aabidsofi19) [inline server/policies/policy.go]: strict types for the value payload would be helpful

File: server/policies/policy.go [hunk 20]
```diff
@@ -0,0 +1,105 @@
...
+	var actions []PolicyAction
+	seen := make(map[string]bool)
+
+	for _, relDef := range implicated {
+		identified := policy.IdentifyRelationship(relDef, design)
+
+		for _, rel := range identified {
+			if relationshipAlreadyExists(design, rel) {
+				continue
+			}
```
Comment (aabidsofi19) [inline server/policies/policy.go]: this seems to be redundant if the policy is also checking the same.

File: server/policies/policy_alias.go [hunk 21]
```diff
@@ -0,0 +1,285 @@
...
+		}
+		identified := identifyAliasRelationships(comp, relDef, design)
+		allIdentified = append(allIdentified, identified...)
+	}
+	return allIdentified
+}
+
+func (p *AliasPolicy) SideEffects(rel *relationship.RelationshipDefinition, design *pattern.PatternFile) []PolicyAction {
+	status := getRelStatus(rel)
+	if status == "identified" || status == "pending" {
```
Comment (aabidsofi19) [inline server/policies/policy_alias.go]: these should be constants from the schema

File: server/policies/policy_alias.go [hunk 22]
```diff
@@ -0,0 +1,285 @@
...
+func isAliasRelationship(rel *relationship.RelationshipDefinition) bool {
+	return strings.EqualFold(string(rel.Kind), "hierarchical") &&
+		strings.EqualFold(rel.RelationshipType, "parent") &&
+		strings.EqualFold(rel.SubType, "alias")
+}
+
+// isAliasRelationshipValid checks if an alias relationship is still valid.
+func isAliasRelationshipValid(rel *relationship.RelationshipDefinition, design *pattern.PatternFile) bool {
+	status := getRelStatus(rel)
+	if status == "pending" {
```
Comment (aabidsofi19) [inline server/policies/policy_alias.go]: use schemas

File: server/policies/actions.go (hunk 16 above)
Comment (guan404ming) [reply server/policies/actions.go]: Done. Replaced raw `map[string]interface{}` action construction with typed constructor functions (`newUpdateRelationshipAction`, `newDeleteRelationshipAction`, `newComponentUpdateAction`, etc.) that enforce the correct payload shape at the call site.

File: server/policies/actions.go (hunk 17 above)
Comment (guan404ming) [reply server/policies/actions.go]: Ditto

File: server/policies/feasibility.go (hunk 18 above)
Comment (guan404ming) [reply server/policies/feasibility.go]: Done. Consolidated into the existing `matchName` helper (supports exact match, wildcard `*`, and regex). `componentMatchesKind` and `isRelationshipFeasibleTo` in `feasibility.go` now both delegate to `matchName` instead of inline string comparisons.

File: server/policies/policy.go (hunk 19 above)
Comment (guan404ming) [reply server/policies/policy.go]: Done. `PolicyAction.Value` is now typed as `map[string]interface{}` with a fixed key schema enforced by the constructor functions. Each action type has a dedicated constructor that populates the correct keys, so callers can't accidentally produce malformed payloads.\n\nFull typed value structs (e.g. a `ComponentUpdatePayload` struct) would be a cleaner next step, tracked as a follow-up since it touches the handler deserialization layer too.

File: server/policies/policy.go (hunk 20 above)
Comment (guan404ming) [reply server/policies/policy.go]: Done. Removed the orchestrator-level `AlreadyExists` guard. Each policy now owns its own deduplication check via its `AlreadyExists` method, which is the right place for policy-specific logic.

File: server/policies/policy_alias.go (hunk 21 above)
Comment (guan404ming) [reply server/policies/policy_alias.go]: Done. Extracted `StatusApproved`, `StatusDeleted`, `StatusPending` from `relationship.Approved`, `relationship.Deleted`, `relationship.Pending` schema constants, and added `StatusIdentified = "identified"` as a local constant. All status string literals in production code are now replaced with these constants.

File: server/policies/policy_alias.go (hunk 22 above)
Comment (guan404ming) [reply server/policies/policy_alias.go]: Ditto

**Review by aabidsofi19 — DISMISSED** [review]

**Comment by guan404ming** [comment]
Hi @aabidsofi19 I just update ci for adding testing result to `qa` repo. This is my local test screenshot.

https://github.com/user-attachments/assets/f9322b59-20f0-4193-b9fb-700fa6837348

**Review by aabidsofi19 — DISMISSED** [review]

**Comment by aabidsofi19** [comment]
> Hi @aabidsofi19 I just update ci for adding testing result to `qa` repo. This is my local test screenshot.
> Screen.Recording.2026-04-07.at.5.01.24.PM.mov

great job . we are very close to merging this pr

**Comment by guan404ming** [comment]
Thanks for the review. Feel free to let me know if there is anything still needed to make this merged.

**Comment by guan404ming** [comment]
Hi @leecalcote I think we are good to merge this one. I've discussed with @aabidsofi19 and we believe this is ready for next step. Additionally, we could able to see the detailed testing result on the https://qa.meshery.io/ after merging this.

**Comment by guan404ming** [comment]
More detailed result and working item progress is documented in https://github.com/meshery/meshery/issues/17240#issue-3878097077.
Feel free to let me if there is anything still missing, thanks!

**Comment by guan404ming** [comment]
Thanks @leecalcote and @aabidsofi19.
