### PR TITLE
fix: [UI] Kubernetes context switcher pulls down too far

### LINKED ISSUE #12380: [UI] Kubernetes context switcher pulls down too far
### Current Behavior
See video.

### Desired Behavior
The panel should slide down, but not this far. There should not be a gap. The top of the panel should remain just underneath the nav bar.

### Screenshots/Logs

https://github.com/user-attachments/assets/bec594b2-bf6b-4dde-8cee-191e3729019f

### Environment

- Browser: Safari 
- Host OS: Mac
- Meshery Server Version: stable-v0.7.122

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Divyansh200102**
**Notes for Reviewers**

- This PR fixes #12380

Video:

https://github.com/user-attachments/assets/82c71a65-4860-4efc-a863-15b80cb1f03a

Before
image

After
image

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/Header.js [hunk 1]
```diff
@@ -288,7 +288,7 @@ function K8sContextMenu({
     position: 'absolute',
     left: '-7rem',
     zIndex: '-1',
-    bottom: showFullContextMenu ? '-55%' : '-110%',
+    bottom: showFullContextMenu ? '40%' : '-110%',
```
Comment (leecalcote) [inline ui/components/Header.js:291]: This should be a factor of the size of the nav header.

**Review by leecalcote — CHANGES_REQUESTED** [review]

File: ui/components/Header.js (hunk 1 above)
Comment (leecalcote) [reply ui/components/Header.js:291]: Let's merge this, but hold out hope that you will follow up with either:
1. relative positioning (ideal).
2. a calc to ensure that if/when the header changes size, that this adjusts (not ideal).
