### PR TITLE
fix(mesheryctl): move completion to root level and fix oh-my-zsh command

### LINKED ISSUE #5870: [mesheryctl] incorrect command for installing oh-my-zsh completions
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

https://github.com/meshery/meshery/blob/088f08f5b674a2d44856385890b5fa5bcb18b075/mesheryctl/internal/cli/root/system/completion.go#L48

This command doesn't work for me probably because, I get the following output on running these commands.
```
➜ echo ${fpath}
/Users/nishantwrp/.oh-my-zsh/custom/plugins/zsh-nvm /Users/nishantwrp/.oh-my-zsh/plugins/git /Users/nishantwrp/.oh-my-zsh/functions /Users/nishantwrp/.oh-my-zsh/completions /Users/nishantwrp/.oh-my-zsh/cache/completions /usr/local/share/zsh/site-functions /usr/share/zsh/site-functions /usr/share/zsh/5.8.1/functions
```

```
➜ echo ${fpath[1]}
/Users/nishantwrp/.oh-my-zsh/custom/plugins/zsh-nvm
```

The current documentation probably expects the output to be

```
➜ echo ${fpath[1]}
/Users/nishantwrp/.oh-my-zsh/completions
```

#### Desired Behavior
The command should work for everyone regardless of the plugins installed by the user in their oh-my-zsh terminal. 

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by nishantwrp**
Signed-off-by: Nishant Mittal <mittalnishant14@outlook.com>

**Description**

This PR fixes #5870, fixes part of #5895.

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by AugustasV** [comment]
@nishantwrp how I should test this?

**Comment by nishantwrp** [comment]
Hi @AugustasV

**Testing the migration of command to root-level**
- Pull these changes
- `cd mesheryctl`
- Build mesheryctl using `go build cmd/mesheryctl`.
 - `./mesheryctl completion zsh` should work
 - `./mesheryctl system completion zsh` shouldn't work

**Testing the oh-my-zsh command**
- Run this command: `COMPLETION_DIR=$(echo $fpath | grep -o '[^ ]*completions' | grep -v "cache") && ./mesheryctl completion zsh > "${COMPLETION_DIR}/_mesheryctl"`
- Completions should be installed in your shell now

**Comment by hexxdump** [comment]
> @nishantwrp how I should test this?

This is a good blog to test mesheryctl changes - https://layer5.io/blog/meshery/validating-meshery-cli-functionality

File: mesheryctl/internal/cli/root/completion.go [hunk 1]
```diff
@@ -42,15 +42,15 @@ const example = `  # bash <= 3.2
   # Might need to start a new shell for this setup to take effect.
   $ echo "autoload -U compinit; compinit" >> ~/.zshrc
 
-  source <(mesheryctl system completion zsh)
+  source <(mesheryctl completion zsh)
 
   # zsh on osx / oh-my-zsh
-  mesheryctl system completion zsh > "${fpath[1]}/_mesheryctl"
+  COMPLETION_DIR=$(echo $fpath | grep -o '[^ ]*completions' | grep -v "cache") && mesheryctl completion zsh > "${COMPLETION_DIR}/_mesheryctl"
```
Comment (hexxdump) [inline mesheryctl/internal/cli/root/completion.go:48]: there is some issue here. I did not have $HOME/.oh-my-zsh/completions directory on my local m/c. It was failing to define COMPLETION_DIR because of it. Please have a fall back for COMPLETION_DIR

**Comment by l5io** [comment]
🚀 Preview for commit 825276e1d608c8e9784d91d580a9b8824282ee4c at: https://62e52121676826054b4bcd94--meshery-docs-preview.netlify.app

File: mesheryctl/internal/cli/root/completion.go (hunk 1 above)
Comment (nishantwrp) [reply mesheryctl/internal/cli/root/completion.go]: Fixed the command to create the dir if it doesn't exist.

Can you try this command instead?
 `COMPLETION_DIR=$(echo $fpath | grep -o '[^ ]*completions' | grep -v cache) && mkdir -p $COMPLETION_DIR && mesheryctl completion zsh > "${COMPLETION_DIR}/_mesheryctl"`

**Comment by l5io** [comment]
🚀 Preview for commit 693cf8a0db580560309864e1c5647b22834ebd78 at: https://62e528c5f71fda0a3ea15f69--meshery-docs-preview.netlify.app

**Comment by leecalcote** [comment]
Are we still tracking on a better UX?

```
$ mesheryctl completion
Error: accepts 1 arg(s), received 0
```

**Comment by nishantwrp** [comment]
> Are we still tracking on a better UX?
> 
> ```
> $ mesheryctl completion
> Error: accepts 1 arg(s), received 0
> ```

I thought we have #5661 for tracking better messages in mesheryctl.

**Comment by harkiratsm** [comment]
> r

I have already fixed that in my PR,  just removed it due to some conflicts error.
