### PR TITLE
[UI][FIX] Publish to meshery catalog action prevented for users signed in using local provider

### LINKED ISSUE #7102: [UI] Publish to Meshery Catalog Action should not be available while using Local Provider
#### Current Behavior
Publishing to Meshery Catalog isn't a capability of the Local Provider. 

#### Desired Behavior
When users are signed in under the "None" (Local) Provider, the "Publish" button should not be displayed in the Designs, Filters, or Applications pages.

#### Screenshots/Logs
Screenshot 2023-02-16 at 9 23 11 AM

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by krishna9304**
This PR fixes #7102 

### Changes Made:
- ~~Added a new local state `isLocalUser` to track whether the user signed in using `None` provider.~~
- Added a new local state `canPublishPattern` to track whether the user signed in using a provider has the capability of publishing a pattern.
- Finally, controlling the render and functional behaviour of the publish method in various subcomponents.

### Demo

https://user-images.githubusercontent.com/71918441/220381969-1e1c1104-7657-44fb-82fd-afa1ffe1ced8.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

cc: @leecalcote

### CODE REVIEW

**Comment by Chadha93** [comment]
@krishna9304  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

**Comment by krishna9304** [comment]
> @krishna9304 Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

sure thing! Added. @Chadha93

**Comment by leecalcote** [comment]
@harkiratsm please review.

File: ui/components/MesheryPatterns.js [hunk 1]
```diff
@@ -508,11 +519,13 @@ function MesheryPatterns({
   }
 
   const handlePublishModal = (ev, pattern) => {
-    ev.stopPropagation();
-    setPublishModal({
-      open : true,
-      pattern : pattern
-    });
+    if (!isLocalUser) {
```
Comment (harkiratsm) [inline ui/components/MesheryPatterns.js:522]: Can this additional check be avoided?

Comment (krishna9304) [reply ui/components/MesheryPatterns.js:522]: @harkiratsm Probably! Although I don't want any loose ends when dealing with modals which are controlled from various components.

File: ui/components/MesheryPatterns.js [hunk 2]
```diff
@@ -600,27 +613,28 @@ function MesheryPatterns({
...
+                  <CloseIcon />
+                </IconButton>
+              );
+            },
+            autoHideDuration : 2000,
+          });
+        },
+        handleError(ACTION_TYPES.PUBLISH_CATALOG),
+      );
+    }
```
[the remark this answers is not in the document]
Comment (krishna9304) [reply ui/components/MesheryPatterns.js:637]: I think i get the context and it seems more right then the approach i went for. Sure, I'll have a look into it and do the needful changes ASAP.

[the remark this answers is not in the document]
Comment (krishna9304) [reply ui/components/MesheryPatterns.js:637]: I don't think `ErrLocalProviderSupport` is thrown when the API is triggered. As per the code below ([ref](https://github.com/meshery/meshery/blob/2bc5c83b9a07fcaf7303f04039eca292c785f6da/server/models/default_local_provider.go#L573)), we're passing error as `nil`, so the parent function ([ref](https://github.com/meshery/meshery/blob/2bc5c83b9a07fcaf7303f04039eca292c785f6da/server/handlers/meshery_pattern_handler.go#L461)) never knows that any errors occured while publish route is being hit by a local provider.

```
func (l *DefaultLocalProvider) PublishCatalogPattern(req *http.Request, publishPatternRequest *MesheryCatalogPatternRequestBody) ([]byte, error) {
	return []byte(""), nil
}
```

I'll make the necessary changes to handle this.

**Comment by leecalcote** [comment]
@krishna9304 solid presentation today. 👍

**Comment by krishna9304** [comment]
> @krishna9304 solid presentation today. 👍

@leecalcote Thanks!🤩

File: ui/components/MesheryPatterns.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (krishna9304) [reply ui/components/MesheryPatterns.js]: @theBeginner86 added latest changes. Please review.

File: ui/components/MesheryPatterns.js (hunk 1 above)
Comment (krishna9304) [reply ui/components/MesheryPatterns.js]: @harkiratsm added latest changes. Please review.

**Review by theBeginner86 — CHANGES_REQUESTED** [review]
@krishna9304 
We are almost there....

File: ui/constants/capabilities.js [hunk 3]
```diff
@@ -0,0 +1,39 @@
+export const capabilties = {
+  SyncPrefs : "sync-prefs", // /user/preferences
```
Comment (theBeginner86) [inline ui/constants/capabilities.js:2]: Please don't hard code these in UI. it would lead to all kind of inconsistencies.

You can directly check for the presence of `"meshery-patterns-catalog"` this string in the `capabilityRegistry?.capabilities`.  Then based on that boolean value you set the `canPublish` var and then perform the remaining checks as you did.

Comment (krishna9304) [reply ui/constants/capabilities.js:2]: Sure @theBeginner86 , I think I'm late on this PR update, but will do the changes asap.

**Review by theBeginner86 — APPROVED** [review]
