### PR TITLE
[Server] reduce retry log spam when capability fetch fails

### LINKED ISSUE #16989: Excessive and duplicate retry logging when capability fetch fails (no rate limiting)
### Current Behavior
When the Meshery server is unable to reach external endpoints (e.g., remote provider capabilities due to DNS/network issues), it enters a retry loop that produces excessive and duplicate warning logs.

Observed behavior includes:

- Warning-level logs emitted every ~3 seconds for each retry
- No apparent upper bound or rate limiting on retry logs
- Duplicate log lines for the same attempt number
This results in high log volume during transient failures.

### Expected Behavior
The retry mechanism should be more log-efficient and operator-friendly. 
- Log the initial failure at WARN
- Reduce verbosity for subsequent retries (e.g., move per-attempt logs to DEBUG)
- Apply rate limiting or periodic summary logs for ongoing retries
- Avoid duplicate log entries for the same retry attempt
This would preserve debuggability while preventing log spam during temporary network or DNS issues.

### Screenshots/Logs
Excerpt from Meshery server logs during external DNS unavailability:
Image
Once DNS/network connectivity was restored, Meshery recovered successfully. The concern here is the logging behavior during retries, not the retry logic itself.

### Environment

- **Host OS:** Linux
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-latest
- **Meshery Client Version:** stable-latest

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
- 📺 [Self-paced Contributor Trainings](https://meshery.io/talks-and-trainings#trainings)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by guan404ming**
**Notes for Reviewers**

- This PR fixes #16989

**How**
- First failure: log one WARN so operators know something is wrong.                                                                                      
- Each retry attempt: log at DEBUG level (visible only when debugging).                                                                                  
- All retries exhausted: log a final WARN summary. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by saurabhraghuvanshii** [comment]
Duplicate Pr https://github.com/meshery/meshery/pull/17007

File: server/models/remote_provider.go [hunk 1]
```diff
@@ -182,15 +182,20 @@ func (l *RemoteProvider) loadCapabilities(token string) (ProviderProperties, err
...
+		const maxRetries = 10
+		for i := 0; i < maxRetries; i++ {
 			resp, err = c.Do(req)
 			if err == nil && resp != nil {
 				break // Successfully fetched response
-
 			}
-			l.Log.Warnf("Attempt %d: Failed to fetch capabilities. Retrying in 3 seconds...", i+1)
+			if i == 0 {
+				l.Log.Warnf("failed to fetch capabilities from remote provider, retrying")
```
Comment (leecalcote) [inline server/models/remote_provider.go]:
```suggestion
				l.Log.Warnf("Failed to fetch capabilities from remote provider. Retrying (%s)... ", i)
```

Comment (leecalcote) [reply server/models/remote_provider.go]: @guan404ming, it would be great if we could include the URL of the remote provider in this message.

Comment (guan404ming) [reply server/models/remote_provider.go]: Just updated, thanks for your review!

**Comment by guan404ming** [comment]
Hi @leecalcote please let me know whether there is anything need to be updated if you have time. Thanks!
