### PR TITLE
[Fix]: Canvas Popup Fixed

### LINKED ISSUE #13868: [UI] Show only the open kanvas popup in the dashboard if user haven't click on the open kanvas button
### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Saurav-Pant**
**Notes for Reviewers**

- This PR fixes #13868

-  If user clicks on "Sign Up" then it not show this popup again and get close directly
- If user clicks on "Sign Up" and after that go to other sidebar links and come to Dashboard again the popup will not show
- Only when user clicks on "closeIcon" then the popup will again come in dashboard

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
-  Yes, I signed my commits.

### CODE REVIEW

File: ui/components/Popup.js [hunk 1]
```diff
@@ -117,6 +112,8 @@ export function MesheryExtensionEarlyAccessCard({
   const [title, setTitle] = useState(signupHeader);
   const { push } = useRouter();
   const theme = useTheme();
+  const cookies = new Cookies('registered');
```
Comment (leecalcote) [inline ui/components/Popup.js:115]:
```suggestion
  const cookies = new Cookies('extension-popup');
```

File: ui/components/Popup.js [hunk 2]
```diff
@@ -126,6 +123,12 @@ export function MesheryExtensionEarlyAccessCard({
     } else {
       push(mesheryExtensionRoute);
     }
+    const oneDayFromNow = new Date();
+    oneDayFromNow.setDate(oneDayFromNow.getDate() + 1);
+
+    cookies.set('registered', 'true', { path: '/' });
```
Comment (leecalcote) [inline ui/components/Popup.js:129]:
```suggestion
    cookies.set('extension-popup', 'true', { path: '/' });
```

**Review by leecalcote — APPROVED** [review]
Thanks, @Saurav-Pant!
