### PR TITLE
User Friendly Error msg 

### LINKED ISSUE #5572: [mesheryctl] User Friendly Error Message
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

1. `mesheryctl` doesn't explicitly tells the missing arguments or gives examples of correct usage of commands.

Screenshot 2022-06-06 at 11 23 52 PM

2. While using an incorrect sub command, `mesheryctl` always points to the docs for `mesheryctl system` command. But ideally it should always refer to the docs of that particular command. Like in the below case, it should be pointing to `mesh` command [docs](https://docs.meshery.io/reference/mesheryctl/mesh) and `pattern` command [docs](https://docs.meshery.io/reference/mesheryctl/pattern) but it always points to system command.

Screenshot 2022-06-07 at 12 03 49 AM

>  Or possibly should give the correct usage in the command line itself rather than pointing to a link that might distract the user

#### Desired Behavior

`mesheryctl` should give out correct error message, that should include better error message(more user friendly message) and some examples usage of a given command.

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by harkiratsm**
Signed-off-by: harkiratsm <multaniharry714@gmail.com>

**Description**

This PR fixes #5572 #5831

**Notes for Reviewers**

image

image

Added User friendly msg for following commands -
- [x] mesh
- [x] perf
- [x] exp
- [x] system
- [x] pattern
- [x] app
- [x] filter 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/internal/cli/root/mesh/mesh.go [hunk 1]
```diff
@@ -21,11 +21,15 @@ var MeshCmd = &cobra.Command{
 // Lifecycle management of service meshes
 mesheryctl mesh 
 	`,
-	Args: cobra.MinimumNArgs(1),
+
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if len(args) != 1 {
+			return errors.New(utils.MeshError(fmt.Sprintln("requires at least 1 arg(s), only received 0 ")))
+		}
```
Comment (alphaX86) [inline mesheryctl/internal/cli/root/mesh/mesh.go:28]: I see that you're trying to implement the docker-compose style of error referencing, which is good. My suggestion is you can add the command in the statement too.

Eg: `Error: mesheryctl mesh requires at least 1 arg(s), only received 0`

The style can be changed a bit... I'll let you know what kind to use after some search

File: mesheryctl/internal/cli/root/mesh/mesh.go [hunk 2]
```diff
@@ -21,11 +21,15 @@ var MeshCmd = &cobra.Command{
...
 		if ok := utils.IsValidSubcommand(availableSubcommands, args[0]); !ok {
-			return errors.New(utils.SystemError(fmt.Sprintf("invalid command: \"%s\"", args[0])))
+			return errors.New(utils.MeshError(fmt.Sprintf(" '%s' command not found. See 'mesheryctl mesh --help'\n ", args[0])))
```
Comment (alphaX86) [inline mesheryctl/internal/cli/root/mesh/mesh.go:30]: Similarly...
`[___] command not found. Use 'mesheryctl mesh --help' for usage guide`

Comment (harkiratsm) [reply mesheryctl/internal/cli/root/mesh/mesh.go:30]: Ok , I will do that 😄

**Review by alphaX86 — DISMISSED** [review]
LGTM

**Review by hershd23 — APPROVED** [review]
LGTM

File: mesheryctl/internal/cli/root/system/system.go [hunk 3]
```diff
@@ -37,10 +37,12 @@ var SystemCmd = &cobra.Command{
 	Use:   "system",
 	Short: "Meshery Lifecycle Management",
 	Long:  `Manage the state and configuration of Meshery server, components, and client.`,
-	Args:  cobra.MinimumNArgs(1),
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if len(args) != 1 {
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/system/system.go:41]: Similarly in other commands as well.

```suggestion
		if len(args) == 0 {
```

It can give incorrect error messages in some cases. For example, here if a user slightly misspells `context`, this gives the following output.

```
➜ mesheryctl system contexta view
Error: mesheryctl system requires at least 1 arg(s), got only 0

See https://docs.meshery.io/reference/mesheryctl/system for usage details
```

**Review by nishantwrp — CHANGES_REQUESTED** [review]

File: mesheryctl/internal/cli/root/system/system.go (hunk 3 above)
Comment (harkiratsm) [reply mesheryctl/internal/cli/root/system/system.go:41]: Thanks @nishantwrp for pointing that out.

**Comment by leecalcote** [comment]
This is coming along nicely, gents.

**Comment by harkiratsm** [comment]
Tracker for following commands .

- [] system 
 - [] context
   - [] create 
   - [] 
- [x] mesh
- [x] perf
- [x] exp
- [x] pattern
- [x] app
- [x] filter

**Review by alphaX86 — CHANGES_REQUESTED** [review]
@harkiratsm resolve the errors obtained in lint checks

**Comment by harkiratsm** [comment]
Need Some Suggestion for final changes for this PR, so do pass in your suggestions 😃 

1) For ```mesheryctl```  incorrect sub commands .

Let cobra handle it.
image

Custom handling .
image


2) For ```mesheryctl``` sub commands like ```system```, ```app``` , ```mesh``` , etc  when user pass no args.

i) Displaying an Error Message 
image

ii) Display the ```cmd.Help()``` , when no args are passed .
image

**Comment by nishantwrp** [comment]
Hi @harkiratsm, according to me "Let cobra handle it." for part 1 and "Display the cmd.Help() , when no args are passed ." for part 2 looks good.

Btw, how would we handle the case when user enters incorrect sub sub commands. For example - `mesheryctl system contexta view`.

**Comment by leecalcote** [comment]
A human-friendly message needed here:

```
$ mesheryctl app onboard
Error: open : no such file or directory
```

**Comment by leecalcote** [comment]
A human-friendly message needed here:

```
$ mesheryctl app
Error: requires at least 1 arg(s), only received 0
```

**Comment by harkiratsm** [comment]
Refer to this [tracker](https://github.com/meshery/meshery/pull/5661#issuecomment-1191504452)

**Review by alphaX86 — APPROVED** [review]
Hmm... so you taken out `Args.ExactArgs` and made `cmd.Help()` to print message when user gives <1 or 0 args... Bit hard to track on review 😅 took me a min or two to understand

Anyway, LGTM for now

**Review by alphaX86 — CHANGES_REQUESTED** [review]
But it seems you simultaneously need to look on unit tests too coz now it returns error due to mismatch of messages in sample test files and with real output of the command....

Could you look on to this @harkiratsm or if not it's ok, I'll take care of this after this PR...

File: mesheryctl/internal/cli/root/system/channel.go [hunk 4]
```diff
@@ -164,7 +172,15 @@ var switchCmd = &cobra.Command{
 // Switch between release channels
 mesheryctl system channel switch [stable|stable-version|edge|edge-version]
 	`,
-	Args: cobra.ExactArgs(1),
+	Args: func(_ *cobra.Command, args []string) error {
+		const errMsg = `Usage: mesheryctl system channel switch [stable|stable-version|edge|edge-version]
+Example: mesheryctl system channel switch stable`
+
+		if len(args) == 0 {
+			return fmt.Errorf("accepts single argument, received %d\n\n%v", len(args), errMsg)
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/system/channel.go:180]: cmd.help()? 

Also, Should we handle the case where there will be more than 1 args given to the function?

File: mesheryctl/internal/cli/root/system/channel.go [hunk 5]
```diff
@@ -93,7 +93,15 @@ var setCmd = &cobra.Command{
 // Subscribe to release channel or version
 mesheryctl system channel set [stable|stable-version|edge|edge-version]
 	`,
-	Args: cobra.ExactArgs(1),
+	Args: func(_ *cobra.Command, args []string) error {
+		const errMsg = `Usage: mesheryctl system channel set [stable|stable-version|edge|edge-version]
+Example: mesheryctl system channel set stable`
+
+		if len(args) != 1 {
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/system/channel.go:100]:
```
		if len(args) == 0 {
```

Also, can we show cmd.help() here?

File: mesheryctl/internal/cli/root/root.go [hunk 6]
```diff
@@ -61,10 +60,14 @@ mesheryctl -v [or] --verbose
 	`,
 	// Uncomment the following line if your bare application
 	// has an action associated with it:
-	PreRunE: func(cmd *cobra.Command, args []string) error {
-		log.Println("Args passed in", args)
+
+	Args: cobra.MaximumNArgs(1),
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/root.go:64]: You should remove this line. Because now, here is the behaviour if there's a slight misspell in a large command.

```
➜ mesheryctl syste context view --all
 
Error: accepts at most 1 arg(s), received 2
```

File: mesheryctl/internal/cli/root/perf/perf.go [hunk 7]
```diff
@@ -66,8 +65,12 @@ mesheryctl perf result -o yaml
 		return hc.RunPreflightHealthChecks()
 	},
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if len(args) == 0 {
+			return cmd.Help()
+			// return errors.New(utils.PerfError(fmt.Sprintln("mesheryctl perf requires at least 1 arg(s), got only 0")))
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/perf/perf.go:70]: I guess this comment can be removed.

File: mesheryctl/internal/cli/root/pattern/pattern.go [hunk 8]
```diff
@@ -33,8 +32,12 @@ mesheryctl pattern view [pattern name | ID]
 mesheryctl pattern list
 	`,
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if len(args) == 0 {
+			return cmd.Help()
+			// return errors.New(utils.PatternError(fmt.Sprintln("mesheryctl pattern requires at least 1 arg(s), got only 0")))
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/pattern/pattern.go:37]: This comment can be removed.

File: mesheryctl/internal/cli/root/mesh/mesh.go [hunk 9]
```diff
@@ -21,11 +21,17 @@ var MeshCmd = &cobra.Command{
 // Lifecycle management of service meshes
 mesheryctl mesh 
 	`,
-	Args: cobra.MinimumNArgs(1),
+
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if len(args) == 0 {
+			// return errors.New(utils.MeshError(fmt.Sprintln("mesheryctl mesh requires at least 1 arg(s), got only 0")))
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/mesh/mesh.go:27]: This comment can be reoved.

File: mesheryctl/internal/cli/root/filter/filter.go [hunk 10]
```diff
@@ -22,10 +22,13 @@ var FilterCmd = &cobra.Command{
 // Base command for WASM filters (experimental feature)
 mesheryctl exp filter [subcommands]	
 	`,
-	Args: cobra.MinimumNArgs(1),
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if len(args) == 0 {
+			return cmd.Help()
+			// return errors.New(utils.FilterError(fmt.Sprintln("mesheryctl filter requires at least 1 arg(s), got only 0")))
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/filter/filter.go:28]: This comment can be removed.

File: mesheryctl/internal/cli/root/app/offboard.go [hunk 11]
```diff
@@ -27,6 +27,10 @@ var offboardCmd = &cobra.Command{
 mesheryctl app offboard -f [filepath]
 	`,
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if len(args) == 0 {
+			const errMsg = `Usage: mesheryctl app offboard -f [filepath]`
+			return fmt.Errorf("no file path provided \n\n%v", errMsg)
+		}
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/app/offboard.go:33]: Please remove this block because flags are not considered as args, and this command doesn't need any args to work correctly.

File: mesheryctl/internal/cli/root/app/onboard.go [hunk 12]
```diff
@@ -45,6 +44,16 @@ mesheryctl app onboard -f ./application.yml -s "Kubernetes Manifest"
...
+	Args: func(_ *cobra.Command, args []string) error {
+		const errMsg = `Usage: mesheryctl app onboard -f [filepath] -s [source type]
+Example: mesheryctl app onboard -f ./application.yml -s "Kubernetes Manifest"
+Description: Onboard application`
+
+		if len(args) == 0 {
+			return fmt.Errorf("the path does not exist \n\n%v", errMsg)
+		}
+		return nil
+	},
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/app/onboard.go:56]: Same, I don't think this command expects any args either.

File: mesheryctl/internal/cli/root/filter/error.go [hunk 13]
```diff
@@ -1,9 +1,9 @@
 package filter
 
 import (
-	"strconv"
-
 	"github.com/layer5io/meshkit/errors"
+
+	"strconv"
```
Comment (hershd23) [inline mesheryctl/internal/cli/root/filter/error.go:6]: Is this order relevant or can this be reverted back

File: mesheryctl/internal/cli/root/system/config.go [hunk 14]
```diff
@@ -329,7 +329,16 @@ var configCmd = &cobra.Command{
...
+	Args: func(_ *cobra.Command, args []string) error {
+		const errMsg = `Usage: mesheryctl system config [aks|eks|gke|minikube]
+Example: mesheryctl system config eks
+Description: Configure the Kubernetes cluster used by Meshery.`
+
+		if len(args) == 0 {
+			return fmt.Errorf("accepts single argument, received %d\n\n%v", len(args), errMsg)
+		}
+		return nil
+	},
```
Comment (hershd23) [inline mesheryctl/internal/cli/root/system/config.go:341]: I think we should also handle the case for more that 1 command here. Is this case being handled or is there an error in my understanding?

**Review by hershd23 — COMMENTED** [review]
Added a couple on comments

File: mesheryctl/internal/cli/root/system/context.go [hunk 15]
```diff
@@ -352,7 +368,10 @@ Description: Configures mesheryctl to actively use one one context vs. the anoth
 		}
 		_, exists := configuration.Contexts[args[0]]
 		if !exists {
-			return errors.New("requested context does not exist")
+			const errMsg = `Try running the following to create the context:
+mesheryctl system context create `
+
```
[the remark this answers is not in the document]
Comment (harkiratsm) [reply mesheryctl/internal/cli/root/system/context.go:373]: It didn't worked I had tried it already !

File: mesheryctl/internal/cli/root/system/context.go [hunk 16]
```diff
@@ -339,7 +355,7 @@ mesheryctl system context switch sample
 Example: mesheryctl system context switch k8s-sample
 Description: Configures mesheryctl to actively use one one context vs. the another context`
 
-		if len(args) != 1 {
+		if len(args) == 0 {
 			return fmt.Errorf("accepts single argument, received %d\n\n%v", len(args), errMsg)
```
[the remark this answers is not in the document]
Comment (harkiratsm) [reply mesheryctl/internal/cli/root/system/context.go:359]: It was discussed in the ```dev call``` that, we should provide some info to user about that command. So I landed here .

File: mesheryctl/internal/cli/root/system/context.go [hunk 17]
```diff
@@ -252,9 +263,14 @@ mesheryctl system context view --all
 * Usage of mesheryctl context view
 # ![context-view-usage](../../../../docs/assets/img/mesheryctl/context-view.png)
 	`,
-	Args:         cobra.MaximumNArgs(1),
```
[the remark this answers is not in the document]
Comment (harkiratsm) [reply mesheryctl/internal/cli/root/system/context.go:255]: It is already handled in the ```RunE``` block

File: mesheryctl/internal/cli/root/system/context.go [hunk 18]
```diff
@@ -252,9 +263,14 @@ mesheryctl system context view --all
...
+
 	SilenceUsage: true,
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if len(args) == 0 {
+			const errMsg = `Please provide a context name to view.
+Usage: mesheryctl system context view [context name]`
+			return errors.New(utils.SystemContextSubError(fmt.Sprintf("%s\n", errMsg), "view"))
+		}
```
[the remark this answers is not in the document]
Comment (harkiratsm) [reply mesheryctl/internal/cli/root/system/context.go:273]: *Fixed

File: mesheryctl/pkg/utils/helpers.go [hunk 19]
```diff
@@ -45,23 +45,38 @@ const (
...
+	systemUsageURL   = docsBaseURL + "reference/mesheryctl/system"
+	meshUsageURL     = docsBaseURL + "reference/mesheryctl/mesh"
+	expUsageURL      = docsBaseURL + "reference/mesheryctl/exp"
+	filterUsageURL   = docsBaseURL + "reference/mesheryctl/exp/filter"
+	patternUsageURL  = docsBaseURL + "reference/mesheryctl/pattern"
+	appUsageURL      = docsBaseURL + "reference/mesheryctl/app"
+	contextDeleteURL = docsBaseURL + "reference/mesheryctl/system/context/delete"
+	contextViewURL   = docsBaseURL + "reference/mesheryctl/system/context/view"
+	contextCreateURL = docsBaseURL + "reference/mesheryctl/system/context/create"
+	contextUsageURL  = docsBaseURL + "reference/mesheryctl/system/context"
```
[the remark this answers is not in the document]
Comment (harkiratsm) [reply mesheryctl/pkg/utils/helpers.go:60]: For ```system channel``` we can handle but I have logged out most of information to the user.

File: mesheryctl/internal/cli/root/system/config.go (hunk 14 above)
Comment (harkiratsm) [reply mesheryctl/internal/cli/root/system/config.go:341]: We are handling error when ```noArgs``` is passed in the above statement.

Comment (harkiratsm) [reply mesheryctl/internal/cli/root/system/config.go:341]: @hershd23 Can you brief about what issues are you facing with ```config``` command !

File: mesheryctl/internal/cli/root/system/context.go (hunk 17 above)
[the remark this answers is not in the document]
Comment (nishantwrp) [reply mesheryctl/internal/cli/root/system/context.go:255]: It was not, you should also handle when more than one args are provided.

File: mesheryctl/pkg/utils/helpers.go (hunk 19 above)
[the remark this answers is not in the document]
Comment (nishantwrp) [reply mesheryctl/pkg/utils/helpers.go:60]: IMO, we should still do it for sake of consistency across the codebase.

[the remark this answers is not in the document]
Comment (harkiratsm) [reply mesheryctl/pkg/utils/helpers.go:60]: @alphaX86 fyi

[the remark this answers is not in the document]
Comment (alphaX86) [reply mesheryctl/pkg/utils/helpers.go:60]: There would be some folks who would search for links... I know it would be a bit overkill but as @nishantwrp said we need to be consistent on the codebase, if you include links, then include for all of them

[the remark this answers is not in the document]
Comment (harkiratsm) [reply mesheryctl/pkg/utils/helpers.go:60]: Let's then do it :+1:

**Comment by alphaX86** [comment]
@harkiratsm you have still included the `examples` field in every command right?

**Comment by harkiratsm** [comment]
@nishantwrp @alphaX86 Let's make this PR merged by today.

**Comment by harkiratsm** [comment]
@nishantwrp @alphaX86 Let's make this PR merged by today.

**Comment by leecalcote** [comment]
Resyncing with `master`. Let's see if the failing build check is cleaned up.

File: mesheryctl/internal/cli/root/root.go [hunk 20]
```diff
@@ -61,10 +60,19 @@ mesheryctl -v [or] --verbose
...
 	// has an action associated with it:
-	PreRunE: func(cmd *cobra.Command, args []string) error {
-		log.Println("Args passed in", args)
+	DisableSuggestions: true,
+	Args: func(cmd *cobra.Command, args []string) error {
+
+		if len(args) == 0 {
+			return cmd.Help()
+		}
+		return nil
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/root.go:69]: This should be moved to the `RunE` block, right now I'm getting the following error.

```
➜ go run mesheryctl/cmd/mesheryctl/main.go    
Meshery is the service mesh management plane, providing lifecycle, performance, and configuration management of service meshes and their workloads.

Usage:
  mesheryctl [flags]
  mesheryctl [command]

Examples:

// Base command
mesheryctl

// Display help about command/subcommand
mesheryctl --help
mesheryctl system start --help

// For viewing verbose output
mesheryctl -v [or] --verbose
	

Available Commands:
  app         Service Mesh Apps Management
  completion  Output shell completion code
  exp         Experimental commands for mesheryctl
  help        Help about any command
  mesh        Service Mesh Lifecycle Management
  pattern     Service Mesh Patterns Management
  perf        Performance Management
  system      Meshery Lifecycle Management
  version     Version of mesheryctl

Flags:
      --config string   path to config file (default "/Users/nishantwrp/.meshery/config.yaml")
  -h, --help            help for mesheryctl
  -v, --verbose         verbose output

Use "mesheryctl [command] --help" for more information about a command.
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/layer5io/meshery/mesheryctl/internal/cli/root.glob..func3(0x108cd6640?, {0x108ecfb90?, 0x0?, 0x0?})
	/Users/nishantwrp/Dev/open-source/layer5/meshery/mesheryctl/internal/cli/root/root.go:74 +0x188
github.com/spf13/cobra.(*Command).execute(0x108cd6640, {0x140001921c0, 0x0, 0x0})
	/Users/nishantwrp/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x4d0
github.com/spf13/cobra.(*Command).ExecuteC(0x108cd6640)
	/Users/nishantwrp/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/nishantwrp/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/layer5io/meshery/mesheryctl/internal/cli/root.Execute()
	/Users/nishantwrp/Dev/open-source/layer5/meshery/mesheryctl/internal/cli/root/root.go:89 +0x5c
main.main()
	/Users/nishantwrp/Dev/open-source/layer5/meshery/mesheryctl/cmd/mesheryctl/main.go:24 +0x20
exit status 2
```

File: mesheryctl/internal/cli/root/system/channel.go [hunk 21]
```diff
@@ -219,12 +235,17 @@ var channelCmd = &cobra.Command{
...
-mesheryctl system channel [stable|stable-version|edge|edge-version]
+// Base command
+mesheryctl system channel 
 	`,
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if len(args) == 0 {
+			return cmd.Help()
+		}
+		if ok := utils.IsValidSubcommand(availableSubcommands, args[0]); !ok {
+			return errors.New(utils.SystemChannelSubError(fmt.Sprintf("'%s' is a invalid command.  Use 'mesheryctl system context --help' to display usage guide.\n", args[0]), "channel"))
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/system/channel.go:247]:
```suggestion
			return errors.New(utils.SystemChannelSubError(fmt.Sprintf("'%s' is a invalid command.  Use 'mesheryctl system channel --help' to display usage guide.\n", args[0]), "channel"))
```

File: mesheryctl/internal/cli/root/system/context.go [hunk 22]
```diff
@@ -252,9 +263,14 @@ mesheryctl system context view --all
...
 	`,
-	Args:         cobra.MaximumNArgs(1),
+
 	SilenceUsage: true,
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if len(args) == 0 && cmd.Flags().Lookup("all").Value.String() == "false" {
+			const errMsg = `Please provide a context name to view.
+Usage: mesheryctl system context view [context name]`
+			return errors.New(utils.SystemContextSubError(fmt.Sprintf("%s\n", errMsg), "context view"))
+		}
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/system/context.go:273]: Still won't work. This command can also be used with `--context` flag. Eg. `mesheryctl system context view --context context-name`

**Review by nishantwrp — CHANGES_REQUESTED** [review]

File: mesheryctl/internal/cli/root/root.go (hunk 6 above)
Comment (nishantwrp) [reply mesheryctl/internal/cli/root/root.go:63]: This is not resolved?

File: mesheryctl/internal/cli/root/app/onboard.go [hunk 23]
```diff
@@ -45,6 +44,16 @@ mesheryctl app onboard -f ./application.yml -s "Kubernetes Manifest"
 * Usage of mesheryctl app onboard
 # ![app-onboard-usage](/assets/img/mesheryctl/app-onboard.png)
 	`,
+	Args: func(_ *cobra.Command, args []string) error {
+		const errMsg = `Usage: mesheryctl app onboard -f [filepath] -s [source type]
+Example: mesheryctl app onboard -f ./application.yml -s "Kubernetes Manifest"
+Description: Onboard application`
+
+		if file == "" && len(args) == 0 {
+			return fmt.Errorf("the path does not exist \n\n%v", errMsg)
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/app/onboard.go:53]: Let's improve the error message to be something along the lines of `file path or application name not provided`?

File: mesheryctl/internal/cli/root/root.go (hunk 6 above)
Comment (nishantwrp) [reply mesheryctl/internal/cli/root/root.go:63]: @harkiratsm

File: mesheryctl/internal/cli/root/system/config.go (hunk 14 above)
Comment (nishantwrp) [reply mesheryctl/internal/cli/root/system/config.go:341]: I think he probably means that the case when there are more than 1 args should also be handled.

File: mesheryctl/internal/cli/root/system/context.go [hunk 24]
```diff
@@ -252,9 +263,14 @@ mesheryctl system context view --all
...
 	`,
-	Args:         cobra.MaximumNArgs(1),
+
 	SilenceUsage: true,
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if len(args) == 0 && (cmd.Flags().Lookup("all").Value.String() == "false" && cmd.Flags().Lookup("context").Value.String() == "") {
+			const errMsg = `Please provide a context name to view.
+Usage: mesheryctl system context view [context name]`
+			return errors.New(utils.SystemContextSubError(fmt.Sprintf("%s\n", errMsg), "context view"))
+		}
```
Comment (nishantwrp) [inline mesheryctl/internal/cli/root/system/context.go:273]: Let's remove this block. `mesheryctl system context view` is a valid command. It automatically picks up the current-context from meshconfig.

**Review by nishantwrp — CHANGES_REQUESTED** [review]

File: mesheryctl/internal/cli/root/app/onboard.go (hunk 23 above)
Comment (leecalcote) [reply mesheryctl/internal/cli/root/app/onboard.go:53]: Nice suggestion

Comment (harkiratsm) [reply mesheryctl/internal/cli/root/app/onboard.go:53]: Thanks for the suggestions

File: mesheryctl/internal/cli/root/root.go (hunk 6 above)
Comment (harkiratsm) [reply mesheryctl/internal/cli/root/root.go:63]: If I remove that then It would be handled by the ```cobra``` itself , which is good and bad at same time. 
```bash
-> mesheryctl syste context
Error: unknown command "syste" for "mesheryctl"

Did you mean this?
        system

Run 'mesheryctl --help' for usage.
```
```bash 
-> mesheryctl asdsd conte
Error: unknown command "asdsd" for "mesheryctl"
Run 'mesheryctl --help' for usage.
```

File: mesheryctl/internal/cli/root/system/context.go (hunk 24 above)
Comment (harkiratsm) [reply mesheryctl/internal/cli/root/system/context.go:273]: ok

File: mesheryctl/internal/cli/root/system/config.go (hunk 14 above)
Comment (harkiratsm) [reply mesheryctl/internal/cli/root/system/config.go:341]: @nishantwrp Any Suggestions over this 
```
mesheryctl system config eks --token auth.json sad
Error: too many arguments
```

Comment (nishantwrp) [reply mesheryctl/internal/cli/root/system/config.go:341]: That works, maybe something like "More than one config name provided" would be better?

Comment (harkiratsm) [reply mesheryctl/internal/cli/root/system/config.go:341]: Nice

File: mesheryctl/internal/cli/root/root.go (hunk 6 above)
Comment (harkiratsm) [reply mesheryctl/internal/cli/root/root.go:63]: @nishantwrp

Comment (nishantwrp) [reply mesheryctl/internal/cli/root/root.go:63]: @harkiratsm totally missed this comment 🤦‍♂️. Yes removing it would have better behaviour than it has now.

Comment (harkiratsm) [reply mesheryctl/internal/cli/root/root.go:63]: @nishantwrp Ok

File: mesheryctl/internal/cli/root/system/channel.go [hunk 25]
```diff
@@ -219,12 +235,18 @@ var channelCmd = &cobra.Command{
...
+mesheryctl system channel 
 	`,
 	RunE: func(cmd *cobra.Command, args []string) error {
+		if len(args) == 0 {
+			return cmd.Help()
+		}
+		if ok := utils.IsValidSubcommand(availableSubcommands, args[0]); !ok {
+			const errMsg = `See https://docs.meshery.io/reference/mesheryctl/system/channel for usage details.`
+			return errors.New(fmt.Sprintf("'%s' is a invalid command.  Use 'mesheryctl system context --help' to display usage guide.\n\n%s", args[0], errMsg))
+		}
```
[the remark this answers is not in the document]
Comment (harkiratsm) [reply mesheryctl/internal/cli/root/system/channel.go]: @nishantwrp I am sticking to previous behaviour for this command .

**Comment by harkiratsm** [comment]
@nishantwrp @alphaX86  ^^^
