### PR TITLE
Fix operator lifecycle for update and reset

### LINKED ISSUE #2958: [mesheryctl] `system update` does not update operator manifests for Docker platform
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system update` for Docker platform will only update the running containers and not the Meshery operator pods deployed on the Kubernetes cluster.

#### Desired Behavior

`mesheryctl system update` should also update the meshery-operator similar to how this command function for the Kubernetes platform.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by metonymic-smokey**
**Description**
This PR fixes the operator lifecycle for `system update` and `system reset` commands.  It also adds the `skip-reset` flag for docker in `update`.
It also adds a few messages for a better user experience.  

This PR fixes #2958. 

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by metonymic-smokey** [comment]
I think the lifecycle part is fixed here but I have a doubt: in `update.go`, for docker, should I create manifests folder assuming cases where user runs this before `start`?

Also, let me know if any of the messages logged need to be improved. Just added them for a more consistent UX.

Thanks!

**Comment by leecalcote** [comment]
@metonymic-smokey, you're difficult to keep up with... and I love it. 😄

**Comment by navendu-pottekkat** [comment]
@metonymic-smokey Ideally yes. We should always handle such errors. So even if the user runs `update` as their first command, we should handle it gracefully.

**Comment by metonymic-smokey** [comment]
Pushed an extra commit since `golangci-lint` was failing on a merge commit.

**Comment by metonymic-smokey** [comment]
> @metonymic-smokey Ideally yes. We should always handle such errors. So even if the user runs `update` as their first command, we should handle it gracefully.

@navendu-pottekkat for that situation, I'm creating the manifests folder only if Meshery is not running.

**Comment by metonymic-smokey** [comment]
Some changes I thought of:  
1. Set skipUpdate flag to true in update.go - since an update has just been performed, there is no need to repeat it before restart; can save a few seconds - a minute.
2. Consider overwriting the version of the current context in meshconfig to ‘latest’.  

What do you think?
@navendu-pottekkat @leecalcote

**Comment by metonymic-smokey** [comment]
Made the changes.  
Could you pls test these out locally @navendu-pottekkat ?  I'm not entirely sure of the changes for the kubernetes platform.  

Also, the command description and the opening confirmation question need to be updated to sound more generic(right now, they are very docker specific).  

Thanks!

**Comment by metonymic-smokey** [comment]
Any more changes that I could add @navendu-pottekkat @leecalcote ?
Updated the logging messages, command descriptions and confirmatory question in the last 2-3 commits.  

Thanks!

**Comment by navendu-pottekkat** [comment]
Running update without starting Meshery results in all adapters being pulled-

Screenshot from 2021-05-28 10-38-31

This is undesired right? Not related to your work but a general observation while testing.

**Comment by navendu-pottekkat** [comment]
Since we are pulling a new compose file, the existing one where the adapters have been overwritten are not used. Hence causes this issue

**Comment by metonymic-smokey** [comment]
Yep, this is definitely undesirable.    
The general idea of the update flag is to update to the newest version of _everything_ by default, unless otherwise specified.  
If we have to change this behaviour, we might have to overhaul the update command by making skip reset the default option and reseting files to be chosen using flags.

File: mesheryctl/internal/cli/root/system/update.go [hunk 1]
```diff
@@ -122,14 +184,42 @@ var updateCmd = &cobra.Command{
...
 				}
+
+				err = utils.ApplyOperatorManifest(client, true, false)
+
+				if err != nil {
+					return err
+				}
 			}
+
+			skipUpdateFlag = true
```
Comment (navendu-pottekkat) [inline mesheryctl/internal/cli/root/system/update.go:195]: Why do we need this flag here?

File: mesheryctl/internal/cli/root/system/update.go [hunk 2]
```diff
@@ -67,15 +67,77 @@ var updateCmd = &cobra.Command{
...
+				}
+
+				err = utils.ApplyOperatorManifest(kubeClient, true, false)
+
+				if err != nil {
+					return err
+				}
+			}
+
+			skipUpdateFlag = true
```
Comment (navendu-pottekkat) [inline mesheryctl/internal/cli/root/system/update.go:117]: Why skipUpdate?

**Comment by metonymic-smokey** [comment]
If we want to fix it without overhauling the update command, we could try something like this:
1. Check if meshery is running.
2. If not, update based on existing `meshery.yaml`.
3. If it is running and `skip-reset` is not used, re-download `meshery.yaml`.

File: mesheryctl/internal/cli/root/system/update.go [hunk 3]
```diff
@@ -67,15 +67,77 @@ var updateCmd = &cobra.Command{
...
+			err = utils.ViperDocker.Unmarshal(&dockerCompose)
+			if err != nil {
+				return err
+			}
+
+			utils.ViperDocker.Set("contexts."+mctlCfg.CurrentContext, currCtx)
+
+			err = utils.ViperDocker.WriteConfig()
+			if err != nil {
+				return err
```
Comment (navendu-pottekkat) [inline mesheryctl/internal/cli/root/system/update.go:140]: What is the purpose of this block?

File: mesheryctl/internal/cli/root/system/update.go [hunk 4]
```diff
@@ -122,14 +184,42 @@ var updateCmd = &cobra.Command{
...
+			}
+
+			utils.ViperK8s.Set("contexts."+mctlCfg.CurrentContext, currCtx)
+
+			err = utils.ViperK8s.WriteConfig()
+			if err != nil {
+				return err
+			}
+
```
Comment (navendu-pottekkat) [inline mesheryctl/internal/cli/root/system/update.go:222]: Same here. I am not sure if the intention is clear here.

**Review by navendu-pottekkat — COMMENTED** [review]
@metonymic-smokey I need some clarifications to make sure we are doing this right. Could you check it out?

File: mesheryctl/internal/cli/root/system/update.go (hunk 1 above)
Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/system/update.go:195]: This is to avoid redundant updates on `start`(when restarted) since it has already been updated.

File: mesheryctl/internal/cli/root/system/update.go (hunk 3 above)
Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/system/update.go:140]: This is to change the version of the current context to `latest` in `meshconfig`, since the version is effectively changed while updating.

File: mesheryctl/internal/cli/root/system/update.go (hunk 4 above)
Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/system/update.go:222]: This is for the same purpose as the previous, when platform: kubernetes.

File: mesheryctl/internal/cli/root/system/update.go (hunk 3 above)
Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/update.go:140]: Okay, then why do we have multiple instances of viper for the same config file?

File: mesheryctl/internal/cli/root/system/update.go (hunk 1 above)
Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/update.go:195]: But system update does not call system start right?

Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/system/update.go:195]: Same changes that I proposed here - https://github.com/layer5io/meshery/pull/3001#issuecomment-848857022

Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/system/update.go:195]: `update` does call `restart`, which calls `start`(for docker).  
Maybe for kubernetes, I could remove it.

File: mesheryctl/internal/cli/root/system/update.go (hunk 3 above)
Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/system/update.go:140]: I'll try to fix that @navendu-pottekkat 
Thanks!

File: mesheryctl/internal/cli/root/system/update.go (hunk 1 above)
Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/update.go:195]: We do not need to restart for docker right? Just updating the container images should work

Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/system/update.go:195]: I called `restart` in docker, seeing how it was called in kubernetes.  
Should I remove it?

Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/system/update.go:176]: @navendu-pottekkat I have re worked the behaviour when platform: docker and removed `restart` from it.

File: mesheryctl/internal/cli/root/system/update.go (hunk 3 above)
Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/system/update.go]: @navendu-pottekkat done this in my latest commit.

Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/update.go]: Thank you. I will check it out.

File: mesheryctl/internal/cli/root/system/update.go [hunk 5]
```diff
@@ -29,8 +29,8 @@ import (
 // updateCmd represents the update command
 var updateCmd = &cobra.Command{
 	Use:   "update",
-	Short: "Pull new Meshery images from Docker Hub.",
-	Long:  `Pull Docker Hub for new Meshery container images and pulls if new image version(s) are available.`,
+	Short: "Pull new Meshery images/manifest files and operator manifests.",
+	Long:  `Pull new Meshery container images/manifests and operator manifests from Github/Docker Hub and pull if new version(s) are available.`,
```
Comment (navendu-pottekkat) [inline mesheryctl/internal/cli/root/system/update.go:33]: Should we need to specify about operator manifests? I think just specifying images and manifests should be enough. Keep the user above a level of abstraction.

File: mesheryctl/internal/cli/root/system/update.go [hunk 6]
```diff
@@ -50,12 +50,12 @@ var updateCmd = &cobra.Command{
...
 		if currCtx.Version != "latest" {
 			// ask confirmation if user has pinned the version in config
-			log.Infof("You have pinned version: %s in your current conext", currCtx.Version)
+			log.Infof("You have pinned version: %s in your current context", currCtx.Version)
 			userResponse := false
 			if utils.SilentFlag {
 				userResponse = true
 			} else {
-				userResponse = utils.AskForConfirmation("Updating Meshery container images will supersede the version to latest. Are you sure you want to continue")
+				userResponse = utils.AskForConfirmation("Updating Meshery container images/manifest files and Meshery operator manifests will supersede the version to latest. Are you sure you want to continue")
```
Comment (navendu-pottekkat) [inline mesheryctl/internal/cli/root/system/update.go:58]: Same as above

**Review by navendu-pottekkat — APPROVED** [review]
Looks neat @metonymic-smokey . Thank you 💯

File: mesheryctl/internal/cli/root/system/update.go (hunk 5 above)
Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/system/update.go]: agreed @navendu-pottekkat 
Done that in the latest commit.

**Review by navendu-pottekkat — APPROVED** [review]
Looks Good!

**Comment by leecalcote** [comment]
I could be thinking of this incorrectly, but it seem that a fresh manifest for the operator is not being retrieved. I checked out branch at commit 697f2233, built mesheryctl, and executed `updated` in a `platform: docker` deployment.


```
➜  mesheryctl git:(update-reset-fix) ✗ ./mesheryctl system update
Fetching latest docker-compose file for channel: stable...

Updating Meshery...
Updating Meshery now...
Pulling meshery              ... done
Pulling meshery-istio        ... done
Pulling meshery-linkerd      ... done
Pulling meshery-consul       ... done
Pulling meshery-nsm          ... done
Pulling meshery-traefik-mesh ... done
Pulling meshery-kuma         ... done
Pulling meshery-cpx          ... done
Pulling meshery-osm          ... done
Pulling watchtower           ... done
Meshery is now up-to-date
```

**Comment by metonymic-smokey** [comment]
@leecalcote it assumes the manifests folder is already created when Meshery is running, hence the check using `isMesheryRunning`.  
Do you think that check should be removed and the manifests folder should be created in all cases?

**Comment by metonymic-smokey** [comment]
@leecalcote this was the output for me(I had deleted the `~/.meshery/manifests` folder prior to running start): 
1.  Here the folder is shown as being created:  
image

2. 
image

**Review by kumarabd — APPROVED** [review]
LGTM

**Review by leecalcote — APPROVED** [review]
Nice!!!

**Comment by leecalcote** [comment]
Thank you for pointing out the difference in behavior, @metonymic-smokey
