### PR TITLE
Fix: Prevent panic in GetMeshSyncInfo when broker is nil

### LINKED ISSUE #15143: [Server] Broker: GraphQL getBrokerInfo panic
### Current Behavior
```
goroutine 53826 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:18 +0x13
github.com/99designs/gqlgen/graphql.DefaultRecover({0x0?, 0x1cacef2?}, {0x52bf800?, 0x93c3bd0?})
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.45/graphql/recovery.go:17 +0x6a
github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0x1c69fc0?, {0x713a488, 0xc0055f8b70}, {0x52bf800?, 0x93c3bd0?})
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.45/graphql/context_operation.go:124 +0x38
github.com/meshery/meshery/server/internal/graphql/generated.(*executionContext)._Query_getMeshsyncStatus.func1()
	/github.com/meshery/meshery/server/internal/graphql/generated/generated.go:12495 +0x6e
panic({0x52bf800?, 0x93c3bd0?})
	/usr/local/go/src/runtime/panic.go:791 +0x132
github.com/meshery/meshery/server/internal/graphql/model.GetMeshSyncInfo({0x0, 0x0}, {0x0, 0x0}, {0x7159bd8, 0xc00110bbf0})
	/github.com/meshery/meshery/server/internal/graphql/model/operator_helper.go:95 +0x71
github.com/meshery/meshery/server/internal/graphql/resolver.(*Resolver).getMeshsyncStatus(0xc027162840, {0x713a488, 0xc0055f8b70}, {0xc0010a4c01?, 0xc0010a4cc0?}, {0xc004698840, 0x24})
	/github.com/meshery/meshery/server/internal/graphql/resolver/operator.go:231 +0x1d6
github.com/meshery/meshery/server/internal/graphql/resolver.(*queryResolver).GetMeshsyncStatus(0xc00170a118, {0x713a488, 0xc0055f8b70}, {0xc004698840, 0x24})
	/github.com/meshery/meshery/server/internal/graphql/resolver/schema.resolvers.go:80 +0xbd
github.com/meshery/meshery/server/internal/graphql/generated.(*executionContext)._Query_getMeshsyncStatus.func2({0x713a488, 0xc0055f8b70})
	/github.com/meshery/meshery/server/internal/graphql/generated/generated.go:12501 +0xca
github.com/99designs/gqlgen/graphql/executor.processExtensions.func4({0x713a488?, 0xc0055f8b70?}, 0xc0004ba1c0?)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.45/graphql/executor/extensions.go:72 +0x22
github.com/meshery/meshery/server/internal/graphql/generated.(*executionContext)._Query_getMeshsyncStatus(0xc0117e4760, {0x713a488, 0xc0055f8a80}, {0xc0022861b0, {0xc0055f8a20, 0x3, 0x3}, 0x0})
	/github.com/meshery/meshery/server/internal/graphql/generated/generated.go:12499 +0x20b
github.com/meshery/meshery/server/internal/graphql/generated.(*executionContext)._Query.func16({0x713a488?, 0xc0055f8a80?}, 0xc00d342be0)
	/github.com/meshery/meshery/server/internal/graphql/generated/generated.go:18660 +0x97
github.com/meshery/meshery/server/internal/graphql/generated.(*executionContext)._Query.func17.1({0x713a488?, 0xc0055f8a80?})
	/github.com/meshery/meshery/server/internal/graphql/generated/generated.go:18669 +0x25
github.com/99designs/gqlgen/graphql/executor.processExtensions.func3({0x713a488?, 0xc0055f8a80?}, 0xc0055c7620?)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.45/graphql/executor/extensions.go:69 +0x22
github.com/meshery/meshery/server/internal/graphql/generated.(*executionContext)._Query.func17({0x713a488, 0xc0055f8a80})
	/github.com/meshery/meshery/server/internal/graphql/generated/generated.go:18668 +0xa2
github.com/meshery/meshery/server/internal/graphql/generated.(*executionContext)._Query.func18({0x0?, 0x0?})
	/github.com/meshery/meshery/server/internal/graphql/generated/generated.go:18672 +0x1f
github.com/99designs/gqlgen/graphql.(*FieldSet).Dispatch(0xc00d342be0, {0x713a488?, 0xc0055f8a50?})
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.45/graphql/fieldset.go:41 +0xa2
github.com/meshery/meshery/server/internal/graphql/generated.(*executionContext)._Query(0xc0117e4760, {0x713a488, 0xc0055f89c0}, {0xc0055c7320, 0x1, 0x1})
	/github.com/meshery/meshery/server/internal/graphql/generated/generated.go:18946 +0x3373
github.com/meshery/meshery/server/internal/graphql/generated.(*executableSchema).Exec.func1({0x713a488, 0xc0055f8990})
	/github.com/meshery/meshery/server/internal/graphql/generated/generated.go:2174 +0x230
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1.1({0x713a488, 0xc0055f8990})
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.45/graphql/executor/executor.go:120 +0x25
github.com/99designs/gqlgen/graphql/executor.processExtensions.func2({0x713a488?, 0xc0055f8990?}, 0x5048600?)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.45/graphql/executor/extensions.go:66 +0x22
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1({0x713a488, 0xc0055f88d0})
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.45/graphql/executor/executor.go:119 +0x104
github.com/99designs/gqlgen/graphql/handler/transport.POST.Do({0x713a488?}, {0x711ec50, 0xc001644000}, 0xc00ae10140, {0x71233e0, 0xc0190db7c0})
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.45/graphql/handler/transport/http_post.go:91 +0x6dd
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc01a7e4420, {0x711ec50, 0xc001644000}, 0xc00ae10140)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.45/graphql/handler/server.go:122 +0x225
github.com/meshery/meshery/server/handlers.(*Handler).GraphqlMiddleware.func1({0x711ec50?, 0xc001644000?}, 0x5044f00?, 0x70e0700?, 0x576ffc0?, {0xc00100bae0?, 0xc00c410000?})
	/github.com/meshery/meshery/server/handlers/middlewares.go:215 +0x32
github.com/meshery/meshery/server/handlers.(*Handler).SessionInjectorMiddleware.func1({0x711ec50, 0xc001644000}, 0xc001d08780)
	/github.com/meshery/meshery/server/handlers/middlewares.go:208 +0x463
net/http.HandlerFunc.ServeHTTP(0xc000ce2200?, {0x711ec50?, 0xc001644000?}, 0x3?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
github.com/meshery/meshery/server/handlers.(*Handler).AuthMiddleware.func1({0x711ec50, 0xc001644000}, 0xc001d08780)
	/github.com/meshery/meshery/server/handlers/middlewares.go:126 +0x1e7
net/http.HandlerFunc.ServeHTTP(0x713a488?, {0x711ec50?, 0xc001644000?}, 0x70e0260?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
github.com/meshery/meshery/server/handlers.(*Handler).ProviderMiddleware.func1({0x711ec50, 0xc001644000}, 0xc001d08640)
	/github.com/meshery/meshery/server/handlers/middlewares.go:60 +0x48e
net/http.HandlerFunc.ServeHTTP(0xc001d08500?, {0x711ec50?, 0xc001644000?}, 0x10?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000ce8240, {0x711ec50, 0xc001644000}, 0xc001d083c0)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2
net/http.serverHandler.ServeHTTP({0x710e6f0?}, {0x711ec50?, 0xc001644000?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc0039bc090, {0x713a488, 0xc0016ccdb0})
	/usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 638
	/usr/local/go/src/net/http/server.go:3360 +0x485
runtime error: invalid memory address or nil pointer dereference
```

### Environment

- **Meshery Server Version:** stable-v0.8.107

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by leecalcote**
The GetMeshSyncInfo function could panic if the Meshery Broker controller was nil. This typically occurs when the broker is not available or not connected.

This commit adds a nil check for the broker before attempting to access its methods. If the broker is nil, the MeshSync status is now set to 'Unknown'.

A new unit test, TestGetMeshSyncInfo_NilBroker, has been added to verify this fix and ensure that the function behaves as expected when the broker is not available.

**Notes for Reviewers**

- This PR fixes #15143

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: server/internal/graphql/model/operator_helper.go [hunk 1]
```diff
@@ -94,17 +94,25 @@ func GetBrokerInfo(broker controllers.IMesheryController, log logger.Handler) Op
 func GetMeshSyncInfo(meshsync controllers.IMesheryController, broker controllers.IMesheryController, log logger.Handler) OperatorControllerStatus {
 	meshsyncStatus := meshsync.GetStatus().String()
```
Comment (n2h9) [inline server/internal/graphql/model/operator_helper.go:95]: I think,according to the error posted in the issue the panic happens on line 95
```
/github.com/meshery/meshery/server/internal/graphql/model/operator_helper.go:95 +0x71
```

meshsync variable is also nil here.

They both are taken from MesheryControllersHelper::ctxControllerHandlers and look like they both (meshsync and broker) are created in a single place in a [AddCtxControllerHandlers](https://github.com/meshery/meshery/blob/master/server/models/meshery_controllers.go#L258).  Which is supposed to be called when connect state of state machine is executed: [here](https://github.com/meshery/meshery/blob/master/server/machines/kubernetes/connect.go#L55).

Comment (n2h9) [reply server/internal/graphql/model/operator_helper.go:95]: I created a pr to this branch which also adds check that meshsync is not nil
https://github.com/meshery/meshery/pull/15151

**Review by n2h9 — APPROVED** [review]
That looks nice, reasonable fix and covered with tests. 
Thank you Lee, great job :hugs:

File: server/internal/graphql/model/operator_helper.go (hunk 1 above)
Comment (leecalcote) [reply server/internal/graphql/model/operator_helper.go:95]: Good deal. 😀 I will see that both of these PRs merge now…

**Comment by leecalcote** [comment]
Oh, no, @n2h9.  When I merged this PR, its branch was auto deleted, causing #15151 to be closed automatically as it was dependent on the same branch. We’ll want to recreate that last change and PR again.
