### PR TITLE
[UI] Prevent duplicate snackbar 🐛 bug fix

### LINKED ISSUE #5015: [UI] Duplicate snackbar in Meshery UI
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._
Duplicate snackbars when there are no k8s config present

Adding prevent duplicate property to it will resolve this: 
like this: 
```js

const message = 'You only see me once.';
props.enqueueSnackbar(message, { 
    preventDuplicate: true,
});
```

#### Current Behavior

image

#### Desired Behavior

No duplicate snackbar is desired, only one.
#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**
Prevent duplicate snackbar

This PR fixes #5015 

**Notes for Reviewers**
Screenshot from 2022-01-29 00-06-45

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — DISMISSED** [review]

File: ui/components/DashboardComponent.js [hunk 1]
```diff
@@ -463,7 +463,7 @@ class DashboardComponent extends React.Component {
   handleError = (msg) => (error) => {
     this.props.updateProgress({ showProgress : false });
     const self = this;
-    this.props.enqueueSnackbar(`${msg}: ${error}`, { variant : "error",
+    this.props.enqueueSnackbar(`${msg}: ${error}`, { variant : "error", preventDuplicate : "true",
```
Comment (Abhishek-kumar09) [inline ui/components/DashboardComponent.js:466]:
```suggestion
    this.props.enqueueSnackbar(`${msg}: ${error}`, { variant : "error", preventDuplicate : true,
```

File: ui/components/MeshConfigComponent.js [hunk 2]
```diff
@@ -575,7 +575,7 @@ handleNATSClick = () => {
   handleError = (msg) => (error) => {
     this.props.updateProgress({ showProgress : false });
     const self = this;
-    this.props.enqueueSnackbar(`${msg}: ${error}`, { variant : "error",
+    this.props.enqueueSnackbar(`${msg}: ${error}`, { variant : "error", preventDuplicate : "true",
```
Comment (Abhishek-kumar09) [inline ui/components/MeshConfigComponent.js:578]:
```suggestion
    this.props.enqueueSnackbar(`${msg}: ${error}`, { variant : "error", preventDuplicate : true,
```

**Review by Abhishek-kumar09 — APPROVED** [review]

**Review by Abhishek-kumar09 — APPROVED** [review]

**Comment by Abhishek-kumar09** [comment]
Thanks @Chadha93
