### PR TITLE
[mesheryctl] Changed context to case sensitive

### LINKED ISSUE #17461: [mesheryctl] Inconsistent case while context creation
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
- The CLI accepts non-lowercase and mixed-case context names during creation (e.g., Name). However, it stores the name in lowercase (e.g., Name -> name). This creates inconsistency between user input and stored value. It may lead to unexpected overrides if a lowercase context already exists.
- When creating a context with an existing name the validation correctly restricts duplicate names only if the name is entirely in lowercase. However if the name contains any uppercase letters the system does not enforce this restriction and instead allows the creation of the context and overriding already existing context.

Image

### Desired Behavior

Since `context create` ultimately stores context names in lowercase, the CLI should validate input and reject non-lowercase names during creation.
For example, kubectl rejects non-lowercase pod names (e.g., `kubectl run Nginx-Pod` throws an RFC 1123 validation error), so following a similar approach here would make the behavior more predictable and consistent

### Approach
By implementing new meshkit error code stating
```bash
The context name "Name" is invalid: 
A name must consist of lower case alphanumeric characters or '-' and must start and end with an alphanumeric character (e.g. 'name', 'my-name', 'name1')
``` 

### Environment

- Host OS: Linux 
- Platform: Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- ⌨️ [Meshkit errors Guide](https://docs.meshery.io/project/contributing/contributing-error)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)
- 📺 [Self-paced Contributor Trainings](https://meshery.io/talks-and-trainings#trainings)

### PR DESCRIPTION
**Pull request by DharunMR**
**Notes for Reviewers**

- This PR fixes #17461

When creating a context using mixed case (e.g., "Name"), the CLI stores it as lowercase ("name"). If a lowercase context already exists, the new command ("Name") overrides it.

Before:
Screenshot_2026-02-15_11 11 54

After:
Screenshot_2026-02-16_15 52 29

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by DharunMR** [comment]
@PragalvaXFREZ Thanks for the feedback.
I felt that rejecting non-lowercase names might be too strict, but i think rejecting would simplify the behavior and avoids confusion.
For example, kubectl rejects non-lowercase pod names (e.g., `kubectl run nGinx-pod` throws an RFC 1123 validation error), so following a similar approach here would make the behavior more predictable and consistent???

**Comment by lekaf974** [comment]
Like mentionned from a UX perspective it is a good idea. 
But on a community aspect is this change being discussed publicly in slack or ina dev meeting ? 
PS: this question is because this break current behavior which was like that since years so we need to ensure that we don't break anything.

Also what will happen if I have already a context in capitalize or upper case ?

File: mesheryctl/internal/cli/root/system/context.go [hunk 1]
```diff
@@ -103,12 +104,14 @@ Usage: mesheryctl system context create [context-name]`
 			tempCntxt.Components = components
 		}
 
-		err := config.AddContextToConfig(args[0], tempCntxt, viper.ConfigFileUsed(), set, false)
+		componentName := strings.ToLower(args[0])
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context.go]: is it a component or a context ?

**Comment by DharunMR** [comment]
@lekaf974 
Since the server already stores context names in lowercase, I assume there wouldn’t be existing contexts stored in uppercase.

However, if there are edge cases where uppercase names were preserved earlier (before normalization), we should verify that to avoid breaking existing setups.

**Comment by lekaf974** [comment]
> @lekaf974 Since the server already stores context names in lowercase, I assume there wouldn’t be existing contexts stored in uppercase.

Perhaps I was not aware of this but I was sure that mesheryctl context was stored locally and not on server.

> However, if there are edge cases where uppercase names were preserved earlier (before normalization), we should verify that to avoid breaking existing setups.

Even if it is stored locally or server side this PR should handle edge cases.

**Comment by DharunMR** [comment]
@lekaf974 
Previously i was converting names to lowercase ,but now i have introduced meshkit error code.
So the newly created context will reject uppercase 
While `view`, `switch`, `delete` only validates existence, old users with upparcase context name can use those without getting any error

The current implementation only rejects uppercase names during creation, so new users won’t be confused.

**Comment by lekaf974** [comment]
> @lekaf974 Previously i was converting names to lowercase ,but now i have introduced meshkit error code. So the newly created context will reject uppercase While `view`, `switch`, `delete` only validates existence, old users with upparcase context name can use those without getting any error
> 
> The current implementation only rejects uppercase names during creation, so new users won’t be confused.

Perhaps I didn't fully understand the intention of the PR but if the changes only affect new created contexts, we can just store it in lower case as long as the new created context name is clearly indicated and highlighted in the output.

**Comment by DharunMR** [comment]
I think i need to be more clear,

- If i create context with name ("example") it stores as "example" everythig is fine
- If i create context with name ("Example", mixed uppercase or complete uppercase) also it stores it as "example" ,however, when the user later runs `mesheryctl system context view Example` it throws error saying `not found Example` because "Example" is automatically converted and stored as "example", same error follows for delete and switch.  
- The automatic convertion of "Example" to "example" could be suprising to users ,that's why i later changed the code 

Sorry for making it too complicated : ) 
Thanks for your feedback👍🏻

**Comment by lekaf974** [comment]
> If i create context with name ("Example", mixed uppercase or complete uppercase) also it stores it as "example" ,however, when the user later runs mesheryctl system context view Example it throws error saying not found Example because "Example" is automatically converted and stored as "example", same error follows for delete and switch.

What if a context with `Example` was already created before we merge this PR ?

**Comment by DharunMR** [comment]
@lekaf974 already existing context wont gets affected anyways

File: mesheryctl/internal/cli/root/system/error.go [hunk 2]
```diff
@@ -336,5 +337,14 @@ func ErrUploadFileParams(err error) error {
 		[]string{err.Error()},
 		[]string{"Unable to upload parameters from config file with provided context"},
 		[]string{"Ensure you have a strong network connection and the right configuration set in your Meshconfig file." + FormatErrorReference()})
+}
 
+func ErrInvalidLowerCase(err error) error {
```
Comment (matrixkavi) [inline mesheryctl/internal/cli/root/system/error.go]: Could we add some supporting positive and negative test cases for this please?

**Comment by lekaf974** [comment]
> Left a review comment. It would be beneficial to add a test to support the validation change

this is a good point adding unit test so we will be confident on the changes

**Comment by DharunMR** [comment]
@lekaf974  i added unit test 👍🏻

**Comment by lekaf974** [comment]
Also all these question is really a matter of UX

**Comment by matrixkavi** [comment]
@DharunMR - could you please squash all those commits into a single commit so that the commit history looks fine please?

**Comment by lekaf974** [comment]
> @DharunMR - could you please squash all those commits into a single commit so that the commit history looks fine please?

this is not required, merge squash is also doing the trick

File: mesheryctl/internal/cli/root/system/context_test.go [hunk 3]
```diff
@@ -68,9 +68,7 @@ func TestViewContextCmd(t *testing.T) {
 			}
 
 			if tt.ExpectError {
-				if err == nil {
-					t.Fatalf("expected error, got nil")
-				}
+				t.Fatalf("expected error, got nil")
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context_test.go:74]: not sure to understand why you remove this check ?

File: mesheryctl/internal/cli/root/system/context.go [hunk 4]
```diff
@@ -160,15 +174,15 @@ mesheryctl system context delete [context name]`
 					return errors.New("new context wrongly set")
 				}
 
-				if newContext == args[0] {
+				if newContext == contextName {
 					return errors.New("choose a new context other than the context being deleted")
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context.go]: meshkit error

File: mesheryctl/internal/cli/root/system/context.go [hunk 5]
```diff
@@ -72,13 +73,21 @@ mesheryctl system context create [context-name]
...
+	Args: func(_ *cobra.Command, args []string) error {
 		if len(args) == 0 {
 			const errMsg = `Please provide a context name.
 Usage: mesheryctl system context create [context-name]`
 			return errors.New(utils.SystemContextSubError(fmt.Sprintf("%s\n", errMsg), "create"))
 		}
 
+		if args[0] != strings.ToLower(args[0]) {
+			return ErrInvalidLowerCase(fmt.Errorf("context name %s is invalid", args[0]))
+		}
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context.go]: why not simply create name in lower case ?

Comment (DharunMR) [reply mesheryctl/internal/cli/root/system/context.go]: I will put this in Today's dev meeting agenda, so that i can show the demo of whats happening.

edited: (due to time constraints I couldn’t present it)

File: mesheryctl/internal/cli/root/system/context_test.go (hunk 3 above)
Comment (DharunMR) [reply mesheryctl/internal/cli/root/system/context_test.go:74]: Previously we are checking `if err != nil` , so if that case doesnt pass it is obviously `err == nil` .That `if err == nil` case doesnt do much, also my code editor showed warning so i removed it

File: mesheryctl/internal/cli/root/system/context.go (hunk 5 above)
Comment (DharunMR) [reply mesheryctl/internal/cli/root/system/context.go]: It always creates name in lowercase no matter what user input. The code mentioned here will check name case and return error if it had uppercase. I'm slightly confused, could you please give me any suggestion of what should i do?

Comment (lekaf974) [reply mesheryctl/internal/cli/root/system/context.go]: Why just not save to lowercase instead of returning an error ?  I don't see any value here

Comment (DharunMR) [reply mesheryctl/internal/cli/root/system/context.go]: Yes i can do that, i just thought of making it strict with case

Comment (lekaf974) [reply mesheryctl/internal/cli/root/system/context.go]: just apply it without error, LGTM

File: mesheryctl/internal/cli/root/system/context.go [hunk 6]
```diff
@@ -74,16 +74,16 @@ mesheryctl system context create context-name --components meshery-nsm --platfor
...
 	Annotations: linkDocContextCreate,
 	Args: func(_ *cobra.Command, args []string) error {
-		if len(args) == 0 {
+		if len(args) != 1 {
+			return utils.ErrInvalidArgument(fmt.Errorf("%s", errArgMsg))
+		}
+
+		if len(args) > 1 {
 			const errMsg = `Please provide a context name.
 Usage: mesheryctl system context create [context-name]`
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context.go]: error message does not explicitly explain too many args were provided

File: mesheryctl/internal/cli/root/system/context.go [hunk 7]
```diff
@@ -112,14 +112,17 @@ Usage: mesheryctl system context create [context-name]`
...
 
 		err := config.AddContextToConfig(contextName, tempCntxt, viper.ConfigFileUsed(), set, false)
 		if err != nil {
 			return err
 		}
 
 		log.Printf("Added `%s` context", contextName)
+		if args[0] != strings.ToLower(args[0]) {
+			log.Printf("Context `%s` converted to lowercase `%s`", contextName, strings.ToLower(args[0]))
+		}
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context.go]: this is not needed, updating previous message would have been enough

**Comment by DharunMR** [comment]
@lekaf974  Made changes as suggestions 👍

File: mesheryctl/internal/cli/root/system/context.go [hunk 8]
```diff
@@ -74,14 +74,12 @@ mesheryctl system context create context-name --components meshery-nsm --platfor
...
-			return utils.ErrInvalidArgument(fmt.Errorf("%s", errArgMsg))
+		if len(args) == 0 {
+			return utils.ErrInvalidArgument(fmt.Errorf("%s\n%s", errNoArgMsg, errContextUsageMsg))
 		}
 
 		if len(args) > 1 {
-			const errMsg = `Please provide a context name.
-Usage: mesheryctl system context create [context-name]`
-			return errors.New(utils.SystemContextSubError(fmt.Sprintf("%s\n", errMsg), "create"))
+			return utils.ErrInvalidArgument(fmt.Errorf("%s\n%s", errMultiArgMsg, errContextUsageMsg))
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context.go]: this could be handle with one check `if lan(args) != 1`

File: mesheryctl/internal/cli/root/system/context.go [hunk 9]
```diff
@@ -119,9 +117,10 @@ Usage: mesheryctl system context create [context-name]`
 			return err
 		}
 
-		log.Printf("Added `%s` context", contextName)
 		if args[0] != strings.ToLower(args[0]) {
-			log.Printf("Context `%s` converted to lowercase `%s`", contextName, strings.ToLower(args[0]))
+			log.Printf("Added `%s` context (converted to lowercase)", contextName)
+		} else {
+			log.Printf("Added `%s` context", contextName)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context.go]: we have a work in progress to get ride of logrus and use utils.Log from meshkit logger

**Comment by DharunMR** [comment]
@lekaf974 @PragalvaXFREZ 
Made changes in arg validation and logging msg, Good to merge?

File: mesheryctl/internal/cli/root/system/testdata/check/check.output.golden
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/system/testdata/check/check.output.golden:1]: is this intentional change?

File: mesheryctl/internal/cli/root/system/error.go [hunk 10]
```diff
@@ -57,9 +57,11 @@ const (
...
 
 var (
-	cmdType     string
-	contextdocs string = "See https://docs.meshery.io/reference/mesheryctl/system/context for usage details."
-	contextDir  string = "see that you have a correct context in your  meshconfig at `$HOME/.meshery/config.yaml`."
+	errArgMsg          = "only one argument must be provided"
+	errContextUsageMsg = `Usage: mesheryctl system context create [context-name]`
+	cmdType            string
+	contextdocs        string = "See https://docs.meshery.io/reference/mesheryctl/system/context for usage details."
+	contextDir         string = "see that you have a correct context in your  meshconfig at `$HOME/.meshery/config.yaml`."
```
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/system/error.go]:
```suggestion
	contextDir         string = "See that you have a correct context in your meshconfig at `$HOME/.meshery/config.yaml`."
```

File: mesheryctl/internal/cli/root/system/context.go [hunk 11]
```diff
@@ -189,9 +201,9 @@ mesheryctl system context delete [context name]`
 			fmt.Printf("The current context is now %q\n", result)
 			viper.Set("current-context", result)
 		}
-		delete(configuration.Contexts, args[0])
+		delete(configuration.Contexts, contextName)
 		viper.Set("contexts", configuration.Contexts)
-		log.Printf("deleted context %s", args[0])
+		log.Printf("deleted context %s", contextName)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context.go]:
```suggestion
		utils.Log.Infof("deleted context %s", contextName)
```

File: mesheryctl/internal/cli/root/system/context.go [hunk 12]
```diff
@@ -380,15 +392,18 @@ Description: Configures mesheryctl to actively use one one context vs. the anoth
...
+
+		contextName := strings.ToLower(args[0])
+
+		_, exists := configuration.Contexts[contextName]
 		if !exists {
 			const errMsg = `Try running the following to create the context:
 mesheryctl system context create `
 
-			return fmt.Errorf("requested context does not exist \n\n%v%s", errMsg, args[0])
+			return fmt.Errorf("requested context does not exist \n\n%v%s", errMsg, contextName)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context.go]: We can take advantage to move to meshkit error

File: mesheryctl/internal/cli/root/system/context.go [hunk 13]
```diff
@@ -407,9 +422,9 @@ mesheryctl system context create `
 			utils.Log.Info("Meshery is running... switching context without stopping Meshery deployments.")
 		}
 
-		configuration.CurrentContext = args[0]
+		configuration.CurrentContext = contextName
 		viper.Set("current-context", configuration.CurrentContext)
-		log.Printf("switched to context '%s'", args[0])
+		log.Printf("switched to context '%s'", contextName)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context.go]:
```suggestion
		utils.Log.Infof("switched to context '%s'", contextName)
```

File: mesheryctl/internal/cli/root/system/testdata/check/check.output.golden
Comment (DharunMR) [reply mesheryctl/internal/cli/root/system/testdata/check/check.output.golden:1]: thanks for mentioning, it is not intentional. I think some came when i did -update i'll revert those

File: mesheryctl/internal/cli/root/system/context.go [hunk 14]
```diff
@@ -103,12 +106,18 @@ Usage: mesheryctl system context create [context-name]`
...
 		if err != nil {
 			return err
 		}
 
-		log.Printf("Added `%s` context", args[0])
+		if args[0] != strings.ToLower(args[0]) {
+			utils.Log.Infof("Added `%s` context (converted to lowercase)", contextName)
+		} else {
+			utils.Log.Infof("Added `%s` context", contextName)
+		}
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context.go]:
```suggestion
    utils.Log.Infof("Added `%s` context ", contextName)
```

File: mesheryctl/internal/cli/root/system/testdata/check/check.output.golden
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/testdata/check/check.output.golden:1]: I was in this test yesterday and have the same output before which look weird for a unit test

File: mesheryctl/internal/cli/root/system/context.go [hunk 15]
```diff
@@ -380,15 +392,18 @@ Description: Configures mesheryctl to actively use one one context vs. the anoth
 			utils.Log.Error(ErrUnmarshallConfig(err))
 			return nil
```
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/system/context.go:383]: The positional argument is lowercased but the --context flag bypasses this completely. A user running `mesheryctl system context view --context MyCtx` might get an error even though `myctx` exists. 

Could you ensure that this is not the case?

File: mesheryctl/internal/cli/root/system/testdata/reset/TestResetContexts.yaml
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/system/testdata/reset/TestResetContexts.yaml:1]: i think this should be reverted as well

File: mesheryctl/internal/cli/root/system/context.go
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/system/context.go]:
```suggestion
				utils.Log.Infof("Delete aborted")
```

Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/system/context.go:131]: could you update this in a similar way as context create. Currently `mesheryctl system context delete ctx1 ctx2` silently ignores `ctx2`

Comment (DharunMR) [reply mesheryctl/internal/cli/root/system/context.go:131]: Sure ok!

File: mesheryctl/internal/cli/root/system/context.go [hunk 16]
```diff
@@ -157,18 +169,18 @@ mesheryctl system context delete [context name]`
 			if newContext != "" {
 				_, exists := configuration.Contexts[newContext]
 				if !exists {
-					return errors.New("new context wrongly set")
+					return ErrSetCurrentContext(fmt.Errorf("new context wrongly set"))
```
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/system/context.go:166]: should use meshkit error `ErrSetCurrentContext`

File: mesheryctl/internal/cli/root/system/context.go (hunk 12 above)
Comment (PragalvaXFREZ) [reply mesheryctl/internal/cli/root/system/context.go]: +1

File: mesheryctl/internal/cli/root/system/context.go (hunk 15 above)
Comment (DharunMR) [reply mesheryctl/internal/cli/root/system/context.go:383]: Do we even need --context flag? It will work fine with `mesheryctl system context view MyCtx`

**Comment by DharunMR** [comment]
@lekaf974 @PragalvaXFREZ 
- Changed log to utils.log added
- meshkit error for required err 
- One question is do we need --context flag for view? Because view works fine even without flag

File: mesheryctl/internal/cli/root/system/context.go [hunk 17]
```diff
@@ -103,12 +105,15 @@ Usage: mesheryctl system context create [context-name]`
 			tempCntxt.Components = components
 		}
 
-		err := config.AddContextToConfig(args[0], tempCntxt, viper.ConfigFileUsed(), set, false)
+		contextName := strings.ToLower(args[0])
+
+		err := config.AddContextToConfig(contextName, tempCntxt, viper.ConfigFileUsed(), set, false)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context.go:110]: should we check if a context name with same value already exists before saving ?

Comment (DharunMR) [reply mesheryctl/internal/cli/root/system/context.go:110]: The duplicate check is already handled inside AddContextToConfig, which returns an error if a context with the same name already exists

File: mesheryctl/internal/cli/root/system/context_test.go [hunk 18]
```diff
@@ -218,20 +219,54 @@ func TestAddContextCmd(t *testing.T) {
 	utils.SetupCustomContextEnv(t, currDir+"/testdata/context/ExpectedAdd.yaml")
 	tests := []utils.CmdTestInput{
 		{
-			Name:             "add given context",
-			Args:             []string{"context", "create", "local3"},
-			ExpectedResponse: "createContext.golden",
+			Name:                 "given a valid context name provided when running mesheryctl system context create [valid-name] then a context gets created",
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context_test.go]:
```suggestion
			Name:                 "given context name provided when system context create [valid-name] then context is created",
```

File: mesheryctl/internal/cli/root/system/context_test.go [hunk 19]
```diff
@@ -218,20 +219,54 @@ func TestAddContextCmd(t *testing.T) {
...
+			Args:                 []string{"context", "create", "local3"},
+			ExpectedResponse:     "createContext.golden",
+			ExpectedResponseYaml: "addExpected.golden",
+		},
+		{
+			Name:                 "given a valid context name which contains uppercase letters provided when running mesheryctl system context create [valid-name] then a context gets created",
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context_test.go]:
```suggestion
			Name:                 "given context name which contains uppercase provided when system context create then context is created in lowercase",
```

test should also validate this behavior since it is the purpose of the PR

File: mesheryctl/internal/cli/root/system/context_test.go [hunk 20]
```diff
@@ -218,20 +219,54 @@ func TestAddContextCmd(t *testing.T) {
...
+			Args:                 []string{"context", "create", "Local4"},
+			ExpectedResponse:     "createContext.uppercase.golden",
+			ExpectedResponseYaml: "addExpected.uppercase.golden",
+		},
+		{
+			Name:           "given no valid context name provided when running mesheryctl system context create [valid-name] then an error message displayed",
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context_test.go]:
```suggestion
			Name:           "given no context provided when system context create  then thorw error",
```

File: mesheryctl/internal/cli/root/system/context_test.go [hunk 21]
```diff
@@ -218,20 +219,54 @@ func TestAddContextCmd(t *testing.T) {
...
+			Args:           []string{"context", "create"},
+			ExpectError:    true,
+			ExpectedError:  utils.ErrInvalidArgument(fmt.Errorf("%s\n%s", errArgMsg, contextCreateUsageMsg)),
+			IsOutputGolden: false,
+		},
+		{
+			Name:           "given multiple context name provided when running mesheryctl system context create then an error message displayed",
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context_test.go]:
```suggestion
			Name:           "given multiple context name provided when system context create then throw error",
```

File: mesheryctl/internal/cli/root/system/context_test.go [hunk 22]
```diff
@@ -218,20 +219,54 @@ func TestAddContextCmd(t *testing.T) {
...
+			IsOutputGolden: false,
 		},
 	}
+
 	for _, tt := range tests {
 		t.Run(tt.Name, func(t *testing.T) {
-			utils.SetupMeshkitLoggerTesting(t, false)
-			b := utils.SetupLogrusGrabTesting(t, false)
+			b := utils.SetupMeshkitLoggerTesting(t, false)
+			utils.Log.SetLevel(logrus.InfoLevel)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context_test.go:326]:
```suggestion
			b := utils.SetupMeshkitLoggerTesting(t, true)
```

File: mesheryctl/internal/cli/root/system/context_test.go [hunk 23]
```diff
@@ -255,7 +290,7 @@ func TestAddContextCmd(t *testing.T) {
 				t.Error(err)
 			}
 			actualResponse = string(content)
-			golden = utils.NewGoldenFile(t, "addExpected.golden", testdataDir)
+			golden = utils.NewGoldenFile(t, tt.ExpectedResponseYaml, testdataDir)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context_test.go:367]:
```suggestion
			golden = utils.NewGoldenFile(t, tt.ExpectedResponse, testdataDir)
```
why Yaml suffix ?

Comment (DharunMR) [reply mesheryctl/internal/cli/root/system/context_test.go:367]: it needs 2 golden to validate ,one for cli output and another for verify context got created

Previously it was hardcoded , now i used existing var

File: mesheryctl/internal/cli/root/system/context_test.go (hunk 22 above)
Comment (DharunMR) [reply mesheryctl/internal/cli/root/system/context_test.go:326]: without this `utils.Log.SetLevel(logrus.InfoLevel)` it also prints debug msg in test so i added it

Comment (lekaf974) [reply mesheryctl/internal/cli/root/system/context_test.go:326]: ok, let's keep it like this for now, I have a WIP that should be helpful to avoid this tweaks

File: mesheryctl/internal/cli/root/system/context_test.go [hunk 24]
```diff
@@ -297,6 +299,27 @@ func TestAddContextCmd(t *testing.T) {
...
+			}
+
+			contexts := data["contexts"].(map[string]interface{})
+
+			if (len(tt.Args) > 2) && (tt.Args[2] != strings.ToLower(tt.Args[2])) {
+				_, existsUpper := contexts[tt.Args[2]]
+				if existsUpper {
+					t.Fatalf("uppercase context should not exist")
+				}
+			}
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context_test.go:393]: I don't think we need to validate it for all tests instead a dedicated test should be created
