### PR TITLE
fix(MesheryPatterns): update designs data when updating information through info modal

### LINKED ISSUE #10593: Design page requires reload to reflect changes made in catalog data from info modal
### Current Behavior
Presently as I made changes in info modal it get's saved and I also got toaster notification however, after clicking on info modal again I don't see my changes, however after reloading the page it get's updated

https://github.com/meshery/meshery/assets/71271069/13789ff5-e26d-465d-9e0d-e3950605a356

### Expected Behavior
Make sure when we open info modal instead of using cache data we make new API request to make sure we are always updated in info modal

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by dragon-slayer875**
**Notes for Reviewers**

This PR fixes #10593 

To update the designs data, I have made it so that every time the info modal is closed, the `fetchPatterns` function is fired.
Thus making the API request for the latest data and storing it for display when the modal is opened again.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/MesheryPatterns.js [hunk 1]
```diff
@@ -750,6 +750,7 @@ function MesheryPatterns({
     setInfoModal({
       open: false,
     });
+    fetchPatterns(page, pageSize, search, sortOrder, visibilityFilter);
```
Comment (Yashsharma1911) [inline ui/components/MesheryPatterns.js:753]: @dragon-slayer875 thanks for raising PR, this change will always pull the latest pattern after closing info modal, which will make unnecessary API calls, instead we want to fetch latest changes after user clicks on Save button in info modal which will ensure that we fetch latest changes when change is made only

**Review by Yashsharma1911 — CHANGES_REQUESTED** [review]

File: ui/components/MesheryPatterns.js (hunk 1 above)
Comment (dragon-slayer875) [reply ui/components/MesheryPatterns.js]: @Yashsharma1911 I have updated the PR.
I made a new function which returns the latest fetchPatterns. The said function can be passed any future child components to update data on any further actions.

**Review by Yashsharma1911 — CHANGES_REQUESTED** [review]

File: ui/components/MesheryPatterns.js (hunk 1 above)
Comment (Yashsharma1911) [reply ui/components/MesheryPatterns.js]: Makes sense, although eventually as we will migrate to RTK we will not require to do this, because RTK always fetch latest changes on mutating data

@sudhanshutech FYI as you are tracking RTK migration

File: ui/components/Modals/Information/InfoModal.js [hunk 2]
```diff
@@ -130,6 +131,9 @@ const InfoModal_ = React.memo((props) => {
             event_type: EVENT_TYPES.SUCCESS,
           });
         })
+        .then(() => {
+          patternFetcher()();
+        })
```
[the remark this answers is not in the document]
Comment (Yashsharma1911) [reply ui/components/Modals/Information/InfoModal.js:136]: After this we are good to merge

File: ui/components/Modals/Information/InfoModal.js [hunk 3]
```diff
@@ -130,6 +131,9 @@ const InfoModal_ = React.memo((props) => {
             event_type: EVENT_TYPES.SUCCESS,
           });
```
Comment (Yashsharma1911) [inline ui/components/Modals/Information/InfoModal.js:132]:
```suggestion
          });
          patternFetcher()();
```

File: ui/components/Modals/Information/InfoModal.js (hunk 2 above)
Comment (Yashsharma1911) [inline ui/components/Modals/Information/InfoModal.js:136]:
```suggestion
```

[the remark this answers is not in the document]
Comment (Yashsharma1911) [reply ui/components/Modals/Information/InfoModal.js:136]: Although it doesn't hurt, but it always good to prevent ourself from promise chaining

File: ui/components/MesheryPatterns.js (hunk 1 above)
Comment (dragon-slayer875) [reply ui/components/MesheryPatterns.js]: @Yashsharma1911 I did think about RTK but wasn't sure how many changes I was allowed to introduce without prior discussions. But I am glad that we will soon be migrating to a more novel solution.

File: ui/components/Modals/Information/InfoModal.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (dragon-slayer875) [reply ui/components/Modals/Information/InfoModal.js]: Sure, I'll read more into it. Thanks for the heads-up. 👍

**Review by Yashsharma1911 — APPROVED** [review]
LGTM thankyou @dragon-slayer875
