### PR TITLE
fixes environment fetch failures by aligning the server’s query parameter handling with the UI contract.

### LINKED ISSUE #18638: [UI]  On `/management/connections`  currently `/api/environments` failing with `orgID is required`
### Current Behavior

https://github.com/user-attachments/assets/b7a3d5f1-cb36-4fc6-869d-2701f374429f

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)
- 📺 [Self-paced Contributor Trainings](https://meshery.io/talks-and-trainings#trainings)

### PR DESCRIPTION
**Pull request by saurabhraghuvanshii**
**Notes for Reviewers**
- Updated server/handlers/environments_handlers.go to read orgId for environment endpoints (instead of legacy orgID).
- Updated validation error messaging to return orgId is required, matching the expected request shape.

The UI sends orgId on /api/environments. The server was enforcing orgID, causing 400 Bad Request and breaking environment loading on Connections/Environments pages.

/api/environments and /api/environments/{id} now work with the query param used by UI.

Removes casing mismatch between frontend and backend parameter names.

## Mesheryctl 
standardizes Meshery CLI environment commands to use orgId instead of orgID, aligning with the server API and existing CLI conventions.

-  Updated mesheryctl environment create|list|view to use --orgId in flags, examples, and validation/error messages.
- Updated environment API requests to send orgId query parameter.
- Updated related tests and fixtures to reflect the new flag/usage text.

The server and newer UI/API contracts now expect orgId. Using orgID in mesheryctl caused request mismatches (400 responses like orgId is required) and confusion. 

Standardizing to `orgId` improves UX and consistency because other Meshery CLI areas (notably organization/workspace workflows) already follow `orgId naming`. This gives users one predictable parameter style across commands.

`mesheryctl environment list --orgId <id>`
`mesheryctl environment view --orgId <id>`

- This PR fixes #18638

## before 

https://github.com/user-attachments/assets/a03b0a7d-48ff-4191-85b3-d8acae4afc40

## after 

https://github.com/user-attachments/assets/05e7ffe5-e18c-490a-aa58-d55249869cfa

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by PragalvaXFREZ — DISMISSED** [review]

File: server/handlers/environments_handlers.go [hunk 1]
```diff
@@ -42,9 +42,9 @@ func (h *Handler) GetEnvironments(w http.ResponseWriter, req *http.Request, _ *m
 func (h *Handler) GetEnvironmentByIDHandler(w http.ResponseWriter, r *http.Request, _ *models.Preference, _ *models.User, provider models.Provider) {
 	environmentID := mux.Vars(r)["id"]
 	q := r.URL.Query()
-	orgID := q.Get("orgID")
+	orgID := q.Get("orgId")
```
Comment (lekaf974) [inline server/handlers/environments_handlers.go:45]: FYI this will break the CLI

https://github.com/meshery/meshery/blob/a0f6f0dff4938abc56ef375b1dfa2f171b3ecc9d/mesheryctl/internal/cli/root/environments/view.go#L125

**Review by lekaf974 — DISMISSED** [review]
Please check comments

File: server/handlers/environments_handlers.go (hunk 1 above)
Comment (PragalvaXFREZ) [reply server/handlers/environments_handlers.go:45]: @lekaf974, should the changes be done on CLI instead of making server side compatible?
The gemini suggestion seems like band-aid to me, thoughts?

File: server/handlers/environments_handlers.go [hunk 2]
```diff
@@ -21,9 +21,9 @@ func (h *Handler) GetEnvironments(w http.ResponseWriter, req *http.Request, _ *m
 
 	q := req.URL.Query()
 
-	orgID := q.Get("orgID")
+	orgID := q.Get("orgId")
 	if orgID == "" {
-		http.Error(w, "orgID is required", http.StatusBadRequest)
+		http.Error(w, "orgId is required", http.StatusBadRequest)
 		return
```
[the remark this answers is not in the document]
Comment (saurabhraghuvanshii) [reply server/handlers/environments_handlers.go:27]: /gemini but I'm focused on completely use of  `orgId`.

File: server/handlers/environments_handlers.go [hunk 3]
```diff
@@ -42,9 +42,9 @@ func (h *Handler) GetEnvironments(w http.ResponseWriter, req *http.Request, _ *m
 func (h *Handler) GetEnvironmentByIDHandler(w http.ResponseWriter, r *http.Request, _ *models.Preference, _ *models.User, provider models.Provider) {
 	environmentID := mux.Vars(r)["id"]
 	q := r.URL.Query()
-	orgID := q.Get("orgID")
+	orgID := q.Get("orgId")
 	if orgID == "" {
-		http.Error(w, "orgID is required", http.StatusBadRequest)
+		http.Error(w, "orgId is required", http.StatusBadRequest)
 		return
```
[the remark this answers is not in the document]
Comment (saurabhraghuvanshii) [reply server/handlers/environments_handlers.go:48]: same

File: server/handlers/environments_handlers.go (hunk 1 above)
Comment (lekaf974) [reply server/handlers/environments_handlers.go:45]: I remember there were lot of discussion around using orgID or orgId but I don't remember the final decision about it

@leecalcote do you remember this or what is the one we need to use across all the projects ?

**Review by PragalvaXFREZ — APPROVED** [review]
