### PR TITLE
Fix dashboard grid resize jitter with debounced width updates

### LINKED ISSUE #18768: [UI] Dashboard flickering issue
**Steps to reproduce this bug**

- Open the dashboard.
- Right-click and select Inspect (open DevTools).
- Enable responsive mode and set the screen size to 1200 × 800.
- Close the DevTools (or exit responsive mode).
- Observe the dashboard — it starts jittering / flickering.

https://github.com/user-attachments/assets/5b81bc8a-aeae-408a-8f87-e690687a4caf

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
- 📺 [Self-paced Contributor Trainings](https://meshery.io/talks-and-trainings#trainings)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Rajesh-Nagarajan-11**
**PR Description**
This PR fixes #18768
This PR fixes dashboard grid jitter during fast window resize by debouncing width updates (100ms) before recalculating layout. This reduces unnecessary re-renders and keeps the layout stable.

**What was happening**

The dashboard grid used react-grid-layout legacy WidthProvider, which updated width continuously during resize. That caused frequent re-layout/repaint cycles, leading to jitter/fluctuation and occasional broken rendering.

**Before**

[Screencast from 2026-04-19 12-59-43.webm](https://github.com/user-attachments/assets/4ef14d66-8ade-44f2-b158-aae2be51c973)

**After** 

[Screencast from 2026-04-19 12-59-06.webm](https://github.com/user-attachments/assets/0448be49-88fc-4160-ba4a-00b1033f2b25)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by banana-three-join — APPROVED** [review]
LGTM!

**Review by rishiraj38 — COMMENTED** [review]
https://github.com/user-attachments/assets/9ebd4f04-d4e7-4ca7-98bc-865441c66df5

@Rajesh-Nagarajan-11  Has this issue also been resolved in this PR ?

**Review by rishiraj38 — APPROVED** [review]
Looks Good . LGTM !!!!!

**Comment by Rajesh-Nagarajan-11** [comment]
> Screen.Recording.2026-04-20.at.11.39.47.AM.mov 
> @Rajesh-Nagarajan-11 Has this issue also been resolved in this PR ?

yes, this PR is meant for this issue

**Comment by rishiraj38** [comment]
> > Screen.Recording.2026-04-20.at.11.39.47.AM.mov
> > @Rajesh-Nagarajan-11 Has this issue been resolved in this PR?
> 
> Yes, this PR is for this issue.

I checked it locally and it fixed it. Thanks!

**Review by kishore08-07 — APPROVED** [review]
@Rajesh-Nagarajan-11 LGTM.

File: ui/components/Dashboard/debounceWidthProvider.tsx [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+        if (debounceTimeout > 0) {
+          if (debounceTimerRef.current !== null) clearTimeout(debounceTimerRef.current);
+          debounceTimerRef.current = window.setTimeout(() => {
+            performUpdate();
+            debounceTimerRef.current = null;
+          }, debounceTimeout);
+        } else {
+          performUpdate();
+        }
+      };
```
Comment (YASHMAHAKAL) [inline ui/components/Dashboard/debounceWidthProvider.tsx]: @Rajesh-Nagarajan-11 the layout is forced to delay at the 1280px default width for 100ms, can it be causing an initial load flash ?

File: ui/components/Dashboard/debounceWidthProvider.tsx [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+    return (
+      <div
+        className={[className, layoutClassName].filter(Boolean).join(' ')}
+        style={style}
+        ref={elementRef}
+      >
+        {(!measureBeforeMount || mounted) && <ComposedComponent {...(rest as P)} width={width} />}
+      </div>
+    );
+  };
```
Comment (YASHMAHAKAL) [inline ui/components/Dashboard/debounceWidthProvider.tsx:70]: React Grid Layout's inner generic component natively applies the .react-grid-layout class to itself. Injecting it onto this outer wrapper creates a duplicate nested CSS target which can break RGL's rendering logic (like double applying position: relative). can we just use className={className} here ?

Comment (Rajesh-Nagarajan-11) [reply ui/components/Dashboard/debounceWidthProvider.tsx:70]: Thanks for the review. You are right on both points.

- I fixed the initial load flash by applying the first width measurement immediately (no debounce on first update).
- I removed the extra react-grid-layout class from the outer wrapper to avoid duplicate nested styling.
- I verified the dashboard still works and the UI build passes.

[Screencast from 2026-04-20 13-25-30.webm](https://github.com/user-attachments/assets/80a6d72f-f513-41a3-b15c-a2f0d7c6b52b)

**Review by YASHMAHAKAL — APPROVED** [review]
LGTM !

**Review by Sbragul26 — APPROVED** [review]
Looks good to me.

**Comment by KhushamBansal** [comment]
@Rajesh-Nagarajan-11 
This looks good to me.

**Comment by Junnygram** [comment]
LGTM

**Review by Junnygram — APPROVED** [review]

**Review by Oluwatunmise-olat — APPROVED** [review]
Ran it locally, and it checks out fine.
