### PR TITLE
UI info display fix

### LINKED ISSUE #4265: [UI] Nighthawk test results don't contain test title and URL
#### Current Behavior
The results displayed after running a performance test have empty "title" and "URL" fields.

#### Desired Behavior
The results should have both of these fields.

#### Screenshots/Logs
This can't be a back end issue as the results returned by Meshery server do contain these. See in the below ss:

#### Environment

- Browser: Firefox
- Host OS: Linux
- Meshery Server Version: stable-v0.5.61
- Meshery Client Version: stable-v0.5.61
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sudhay23**
Signed-off-by: sudhay23 <sudhay2001@gmail.com>

Signed off now

**Description**
The fields in response have now been modified appropriately 

This PR fixes #4265 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudhay23** [comment]
@DelusionalOptimist Please verify the changes. Thank you

**Review by DelusionalOptimist — CHANGES_REQUESTED** [review]
@sudhay23 seems like some auto-formatter went over the code and made some unneeded changes. Please revert those and try to use `make run-ui-lint` for linting your changes instead :slightly_smiling_face:

**Comment by warunicorn19** [comment]
Yeah @sudhay23 I can't really find the lines you've made changes to😅, could you please revert the unwanted changes.

**Comment by sudhay23** [comment]
@DelusionalOptimist @warunicorn19 Hope this is fine

**Comment by DelusionalOptimist** [comment]
This is from fortio. URL is fine. Title is missing now. It was working earlier. Could you take a look into it?



This is from nighthawk. URL shows up now. Nice! : )

**Comment by sudhay23** [comment]
@DelusionalOptimist Looks like the 'res' object doesn't have sufficient info.

**Comment by leecalcote** [comment]
@DelusionalOptimist can we provide ourselves named keys and not rely on an index number?

**Comment by sudhay23** [comment]
@warunicorn19 @DelusionalOptimist Can you have a look now and see if the changes are right?

File: helpers/load_test_interface.go [hunk 1]
```diff
@@ -290,7 +290,8 @@ func NighthawkLoadTest(opts *models.LoadTestOptions) (map[string]interface{}, *p
 		OpenLoop:                             &wrappers.BoolValue{Value: false},
 		JitterUniform:                        durationpb.New(0 * time.Second),
 		ExperimentalH2UseMultipleConnections: &wrappers.BoolValue{Value: false},
-		Labels:                               make([]string, 0),
+		// Labels:                               make([]string, 0),
+		Labels:                               labels,
```
Comment (warunicorn19) [inline helpers/load_test_interface.go:294]: The golang lint test is failing here because you're using a using string in place of a struct literal, could you please take a look.

**Comment by DelusionalOptimist** [comment]
@sudhay23 @warunicorn19 do we need this change in Meshery server? JSON returned by the server already contains two separate `URL` and `Title` fields. I'm curious, can't we read the entire JSON in the `res` object? So that we don't need to read these from the `labels`? This seems hacky to me:
https://github.com/meshery/meshery/blob/df44458404f7456b8d5e15434dcce13e912f06f2/ui/lib/chartjs-formatter.js#L60-L70

**Comment by warunicorn19** [comment]
🤔you're right @DelusionalOptimist, since the JSON already contains separate fields for the `Title` and the `URL` there's no need for this change in the Meshery server.

**Comment by sudhay23** [comment]
> 🤔you're right @DelusionalOptimist, since the JSON already contains separate fields for the `Title` and the `URL` there's no need for this change in the Meshery server.

Oh yeah. But I still believe that only the sub-property of the whole object that excludes URL and Title are being returned though they are logged. Correct me if I'm wrong 😅 @warunicorn19 @DelusionalOptimist

**Comment by sudhay23** [comment]
This change was done as I see that the other tests like Fortio are having the Labels field properly filled unlike Nighthawk which lacks it

File: helpers/load_test_interface.go (hunk 1 above)
Comment (sudhay23) [reply helpers/load_test_interface.go:294]: @leecalcote @warunicorn19 Thanks for pointing it out. I've made the appropriate fix locally but haven't committed yet. I think I'm close to a potential solution
