### PR TITLE
Fix capture and handle expired token 

### LINKED ISSUE #3935: [UI] Capture and Handle Expired Token
#### Current Behavior
Users with expired tokens will see the following on the performance management page:

Screen Shot 2021-08-18 at 6 49 50 PM

#### Desired Behavior
Irrespective of the page, users should universally see the same message - a modal informing the user that they their session has expired and that they will be directed to login in 3... 2... 1..

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by MUzairS15**
Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>

**Description**

This PR fixes #3935 

**Notes for Reviewers**
This PR also addresses #3919 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 

https://user-images.githubusercontent.com/79860504/151032929-79e5b5c3-94c9-4d6f-a7d5-ff90eac44b1e.mov

### CODE REVIEW

**Comment by MUzairS15** [comment]
I am not able to see the full coverage report.
Can anyone help me to increase coverage?

File: ui/components/MesheryPerformance/PerformanceProfiles.js [hunk 1]
```diff
@@ -156,19 +208,27 @@ function PerformanceProfile({ updateProgress, enqueueSnackbar, closeSnackbar })
 
   function handleError(msg) {
     return function (error) {
-      updateProgress({ showProgress : false });
+      if (error.source.errors[0].message != undefined) {
```
Comment (bariqhibat) [inline ui/components/MesheryPerformance/PerformanceProfiles.js:211]: Can we do a type check here? And additionally use optional chaining

**Review by bariqhibat — COMMENTED** [review]
A comment! Thanks for the contribution! @MUzairS15

**Comment by leecalcote** [comment]
[Grover] "Cookie Monster, come out and play."

**Review by leecalcote — CHANGES_REQUESTED** [review]
@MUzairS15, thanks for this PR! 

This PR was discussed on today's Meshery meeting (we missed you ;) ). A couple comments were given such as "Can the cookie be used to determine session state / token expiry?", "How is this going to be applied to each UI / endpoint? It could be easy to miss an endpoint.", "Can this be achieved in NextJS with one central configuration?", "The golang middleware attached to each endpoint verifies token expiration and can redirect the user. This would be a central approach, too."

**Comment by MUzairS15** [comment]
>  "The golang middleware attached to each endpoint verifies token expiration and can redirect the user. This would be a central approach, too."

Current implementation redirects user to login but it fails. 
Screenshot 2022-01-20 at 8 53 01 AM
Similar to #3919 
Even if, we happen to solve this, without any alert user will be redirected.

> "Can the cookie be used to determine session state/token expiry?"

In the UI itself? Yes, we can do this.I thought about this but later resolved to rely on the server as in `AuthMiddleware` we were doing the same, 

> "How is this going to be applied to each UI / endpoint? It could be easy to miss an endpoint."

In data-fetch.js ` const dataFetch = (url, options = {}, successFn, errorFn) => {`, we can handle the error here itself, (this will secure all the endpoint making a query),

Pls correct me if I am wrong.

**Comment by MUzairS15** [comment]
@leecalcote Can you suggest, should I handle error or add check for whether token is still valid or not in `const dataFetch = (url, options = {}, successFn, errorFn) => {`

(Now, I regret not being able to join the meeting🥲, things have been clear)

**Comment by Abhishek-kumar09** [comment]
> Current implementation redirects user to login but it fails.

Are you referring to the current implementation (on master branch)?
It seems like the login request can't be sent directly from the server to the cloud, just by clients like mesheryctl or UI which is the required behaviour. Youy should try for UI redirection to login page, instead. Is it what you are doing now??

**Comment by Abhishek-kumar09** [comment]
> t, should I handle error or add check for whether token is still valid or not in const dataFetch = (url, options = {}, successFn, errorFn) => {

Token validation can only be done on the server/cloud. Rather you can check for the cookie key (token) be present on all requests that includes credential(also called cookies).

**Comment by MUzairS15** [comment]
> > Current implementation redirects user to login but it fails.
> 
> Are you referring to the current implementation (on master branch)? It seems like the login request can't be sent directly from the server to the cloud, just by clients like mesheryctl or UI which is the required behaviour. Youy should try for UI redirection to login page, instead. Is it what you are doing now??

Yes, on master branch (server code, redirect fails, see screenshot above). And I have added logic to redirect from UI.
Based on https://github.com/meshery/meshery/pull/4956#pullrequestreview-857294128, concern is to apply to each endpoint. So, if I instead of checking for errors in individual query call, what if I move this to `dataFetch`?

**Comment by MUzairS15** [comment]
> > t, should I handle error or add check for whether token is still valid or not in const dataFetch = (url, options = {}, successFn, errorFn) => {
> 
> Token validation can only be done on the server/cloud. Rather you can check for the cookie key (token) be present on all requests that includes credential(also called cookies).

When token expires, cookie is not cleared, so cookie (token) will be present.

**Comment by Abhishek-kumar09** [comment]
> Based on #4956 (review), concern is to apply to each endpoint. So, if I instead of checking for errors in individual query call, what if I move this to dataFetch?

Yeah that's what you should do, intercept every request that passes cookie to server. Do it in data fetch itself.

> When token expires, cookie is not cleared, so cookie (token) will be present.

That's a good thought, but token is set to session expire policy, i.e, it will not expire frequently and only in two conditions: 
1. The user closes the browser (session is lost and so is the token)
2. Token has timeout for 1 day or probably more (@leecalcote could confirm). 

SO the case is extremely rare, meanwhile in case it is not correct (i.e., the auth token expired) the server will automatically redirect to the provider UI.

**Comment by MUzairS15** [comment]
> SO the case is extremely rare, meanwhile in case it is not correct (i.e., the auth token expired) the server will automatically redirect to the provider UI.

I tried with an expired token but was not redirected to provider UI.

**Comment by Abhishek-kumar09** [comment]
Okay let's have a check at two levels: 
1. the client level for auth token present which is just one liner.
2. the server for auth token expiry, and redirection to the provider UI instead of handling the login request itself.

What do you say @MUzairS15 ? What are the things needed for the 2 to be done, if you have any idea.

**Comment by MUzairS15** [comment]
> Okay let's have a check at two levels:
> 
> 1. the client level for auth token present which is just one liner.
> 2. the server for auth token expiry, and redirection to the provider UI instead of handling the login request itself.
> 
> What do you say @MUzairS15 ? What are the things needed for the 2 to be done, if you have any idea.

In server `AuthMiddleware` checks for session validity, I can use the error to handle the redirect. But, then it will not be graceful handling 
> Irrespective of the page, users should universally see the same message - a modal informing the user that they their session has expired and that they will be directed to login in 3... 2... 1...

File: handlers/middlewares.go [hunk 2]
```diff
@@ -56,7 +65,26 @@ func (h *Handler) AuthMiddleware(next http.Handler) http.Handler {
 			// }
 			// return
 			if provider.GetProviderType() == models.RemoteProviderType {
-				provider.Logout(w, req)
+				if err.Error() == "http: named cookie not present" {
+					provider.Logout(w, req)
+				}
+
+				graphQlError := []Body{{"expired"}}
```
Comment (Abhishek-kumar09) [inline handlers/middlewares.go:72]: What is this doing?

File: handlers/middlewares.go [hunk 3]
```diff
@@ -56,7 +65,26 @@ func (h *Handler) AuthMiddleware(next http.Handler) http.Handler {
 			// }
 			// return
 			if provider.GetProviderType() == models.RemoteProviderType {
-				provider.Logout(w, req)
+				if err.Error() == "http: named cookie not present" {
```
Comment (Abhishek-kumar09) [inline handlers/middlewares.go:68]: use contains function for this. https://pkg.go.dev/strings#Contains

File: handlers/middlewares.go [hunk 4]
```diff
@@ -67,13 +95,14 @@ func (h *Handler) AuthMiddleware(next http.Handler) http.Handler {
...
+func (h *Handler) validateAuth(provider models.Provider, req *http.Request) (bool, error) {
+	err := provider.GetSession(req)
+	if err == nil {
 		// logrus.Debugf("session: %v", sess)
-		return true
+		return true, err
 	}
 	// logrus.Errorf("session invalid, error: %v", err)
-	return false
+	return false, err
```
Comment (Abhishek-kumar09) [inline handlers/middlewares.go:105]: You can delete the unusable comments like seen here.

File: ui/components/MesheryPerformance/PerformanceProfiles.js [hunk 5]
```diff
@@ -299,9 +359,25 @@ function PerformanceProfile({ updateProgress, enqueueSnackbar, closeSnackbar })
...
+            <Typography id="transition-modal-title" variant="h6" component="h2" className={classes.modal}>
+              <span className = {classes.span}>&#9432;</span>Session Expired
+            </Typography>
+            { counter && <Typography id="transition-modal-description" className = {classes.modalText} >
+               Your session has expired.
+               You will now be redirected to login... {counter}
+            </Typography>
+            }
+          </Box>
+        } />
```
Comment (Abhishek-kumar09) [inline ui/components/MesheryPerformance/PerformanceProfiles.js:380]: Please extract this dialog and it's style in a separate component. They have been used twice on different pages.

File: ui/components/MesheryPerformance/Dashboard.js [hunk 6]
```diff
@@ -140,17 +184,25 @@ function Dashboard({ updateProgress, enqueueSnackbar, closeSnackbar, grafana, ro
...
-      enqueueSnackbar(`${msg}: ${error}`, { variant : "error",
-        action : function Action(key) {
-          return (
-            <IconButton key="close" aria-label="Close" color="inherit" onClick={() => closeSnackbar(key)}>
-              <CloseIcon />
-            </IconButton>
-          );
-        },
-        autoHideDuration : 8000, });
+      if (error.source.errors[0].message != undefined) {
```
Comment (Abhishek-kumar09) [inline ui/components/MesheryPerformance/Dashboard.js:187]:
```suggestion
      if (error?.source?.errors?.[0]?.message) {
```

File: ui/components/MesheryPerformance/Dashboard.js [hunk 7]
```diff
@@ -82,6 +120,12 @@ function Dashboard({ updateProgress, enqueueSnackbar, closeSnackbar, grafana, ro
     fetchTests();
   }, []);
 
+  useEffect(() => {
+    const timer = setTimeout(() => {
+      setCounter(counter - 1)
+    }, 1000)
+    return () => clearTimeout(timer)
+  })
```
Comment (Abhishek-kumar09) [inline ui/components/MesheryPerformance/Dashboard.js:128]: The useEffect Body runs on every state change which is not desired. Actually this modal can be placed in it's own functional component for the purpose of re-usability and then this implementation will look good.

File: handlers/middlewares.go [hunk 8]
```diff
@@ -56,7 +65,26 @@ func (h *Handler) AuthMiddleware(next http.Handler) http.Handler {
 			// }
 			// return
 			if provider.GetProviderType() == models.RemoteProviderType {
-				provider.Logout(w, req)
+				if err.Error() == "http: named cookie not present" {
+					provider.Logout(w, req)
```
Comment (Abhishek-kumar09) [inline handlers/middlewares.go:69]: Earlier we had the problem for wildcard response set, 

Are we solving it now?

**Review by Abhishek-kumar09 — CHANGES_REQUESTED** [review]
Thanks for the PR @MUzairS15 
So what you have done on the server is:
1. check for token cookie being present 
2. If not present redirect to provider UI 
3. else marshal the cookie token and authenticate the user.

Just one concern, WHy you have added graphql in between? Is there any specific usecase?
I think this is not touching any graphql domain. Do we?

File: handlers/middlewares.go (hunk 2 above)
Comment (MUzairS15) [reply handlers/middlewares.go:72]: No, we are not touching graphQL, (just for sake of the name `graphQlError`) I will change the name.
I am sending `{
          "errors": {[
                "error" : "expired"
            ]}

}
` as json to get it when we do a query when token becomes invalid.

File: handlers/middlewares.go (hunk 3 above)
Comment (MUzairS15) [reply handlers/middlewares.go:68]: Sure

File: handlers/middlewares.go (hunk 4 above)
Comment (MUzairS15) [reply handlers/middlewares.go:105]: Yes, will remove.

File: handlers/middlewares.go (hunk 8 above)
Comment (MUzairS15) [reply handlers/middlewares.go:69]: Yes, this is solved with the proposed changes, as we will not redirect from the server in case of an invalid session, instead query will fail, and UI will handle it by alerting the user.

File: handlers/middlewares.go (hunk 2 above)
Comment (Abhishek-kumar09) [reply handlers/middlewares.go:72]: I think giving more verbose error will help, like `auth token expired`

Comment (MUzairS15) [reply handlers/middlewares.go]: done

File: handlers/middlewares.go (hunk 3 above)
Comment (MUzairS15) [reply handlers/middlewares.go]: done

File: ui/components/MesheryPerformance/PerformanceProfiles.js (hunk 5 above)
Comment (MUzairS15) [reply ui/components/MesheryPerformance/PerformanceProfiles.js]: done

File: ui/components/MesheryPerformance/Dashboard.js (hunk 6 above)
Comment (MUzairS15) [reply ui/components/MesheryPerformance/Dashboard.js]: done

File: ui/components/MesheryPerformance/Dashboard.js (hunk 7 above)
Comment (MUzairS15) [reply ui/components/MesheryPerformance/Dashboard.js]: done

File: handlers/middlewares.go [hunk 9]
```diff
@@ -56,7 +66,26 @@ func (h *Handler) AuthMiddleware(next http.Handler) http.Handler {
...
+					return
+				}
+				authError := []Body{{"auth-token expired"}}
+				errors := Error{authError}
+				jsonMsg, err := json.Marshal(errors)
+				if err != nil {
+					logrus.Errorf("Error marshaling response")
+					http.Error(w, "unable to authenticate user", http.StatusInternalServerError)
+					return
+				}
```
Comment (Abhishek-kumar09) [inline handlers/middlewares.go:80]:
```suggestion
```

**Review by Abhishek-kumar09 — APPROVED** [review]
After 30 mins long iteration, we got the root of the problem. 

SO the `/user/login` is redirecting to the meshery cloud for the user login, but since the redirection is from the server the cloud takes server on localhost:9081 as client and further failing because server can't act as a client and this is the reason behind the cors error. 

Cross origin request from the server is denied on the cloud for the Login and that's how it should behave. You can't **instantiate** a login from the server. 


Now since we are redirecting to the provider UI now, the actual selection of login can be done through client. 

Cookie Policy: 
1. The cookie expiration policy is set to session, i.e., the cookie invalidates on the new session.
2. It has its own expiry time more than 24 hours in case the session is not closed,

We are touching both the cases and all the cases the user can open meshery and cannot use any meshery service without being authenticated. 

There can be a need of slight UX improvemnt in terms of the first load with invalid token sent to meshery and being validated, but that's a seperate concern and is out of the scope of this PR. 

I think this PR can be merged, and you can see the changes with your eyes, the all functions being working the way they should. 

UI improvements (minor flash between meshery homepage to going to provider login page) can be done seprately.

**Comment by Abhishek-kumar09** [comment]
// @leecalcote

**Comment by leecalcote** [comment]
@MUzairS15, it'd be great for you to quick a quick demo of this work on a Meshery Development Meeting. There's one today in 30 minutes, if you're free. Details here: https://meet.layer5.io

**Comment by leecalcote** [comment]
@sudo-NithishKarthik what do you think? https://github.com/meshery/meshery/pull/4956#pullrequestreview-864057301

**Comment by MUzairS15** [comment]
@sudo-NithishKarthik ping

**Comment by leecalcote** [comment]
@MUzairS15 will you put this on the agenda for next week's Meshery Dev meeting?

**Comment by MUzairS15** [comment]
Yes @leecalcote

**Comment by leecalcote** [comment]
Discussed again today. The current server-side redirect is good and the return of the user-facing modal is also desirable.

File: handlers/provider_handler.go [hunk 10]
```diff
@@ -24,7 +23,6 @@ func (h *Handler) ProviderHandler(w http.ResponseWriter, r *http.Request) {
 			http.SetCookie(w, &http.Cookie{
 				Name:     h.config.ProviderCookieName,
 				Value:    p.Name(),
-				Expires:  time.Now().Add(h.config.ProviderCookieDuration),
```
Comment (MUzairS15) [inline handlers/provider_handler.go:27]: Changes `meshery-provider` cookie as Session cookie.

Comment (leecalcote) [reply handlers/provider_handler.go:27]: ✔️
