### PR TITLE
[mesheryctl] fix: Added description for the `system logs` command

### LINKED ISSUE #3018: [mesheryctl] system logs: help missing component name filter
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
```
 mesheryctl system logs -h
Print history of Meshery's container logs and begin tailing them.

Usage:
  mesheryctl system logs [flags]

Flags:
  -h, --help   help for logs

Global Flags:
      --config string     config file (default location is: /Users/lee/.meshery/config.yaml)
  -c, --context string    (optional) temporarily change the current context.
  -p, --platform string   platform to deploy Meshery to
  -v, --verbose           verbose output
  -y, --yes               (optional) assume yes for user interactive prompts.
```

#### Desired Behavior
`system logs` should have help describing how to view logs for a specific component; e.g. `mesheryctl system logs meshery-istio`

#### Environment

- Host OS: Mac
- Meshery Server Version: stable-v0.5.15
- Meshery Client Version: stable-v0.5.15
- Platform: Kubernetes

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by muskankhedia**
Signed-off-by: muskankhedia <muskan.khedia2000@gmail.com>

**Description**
Added a long description for the `system logs` command for the user to view the logs of a specific component.
Screenshot 2021-06-27 at 12 11 01 PM

This PR fixes #3018 

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/internal/cli/root/system/logs.go [hunk 1]
```diff
@@ -41,7 +41,8 @@ import (
 var logsCmd = &cobra.Command{
 	Use:   "logs",
 	Short: "Print logs",
-	Long:  `Print history of Meshery's logs and begin tailing them.`,
+	Long:  `Print history of Meshery's logs and begin tailing them.
+	To view the logs of a specific component e.g. mesheryctl system logs meshery-istio`,
```
Comment (piyushsingariya) [inline mesheryctl/internal/cli/root/system/logs.go:45]: @navendu-pottekkat Should we specify that this feature works for only the Kubernetes platform?

Comment (muskankhedia) [reply mesheryctl/internal/cli/root/system/logs.go:45]: IMO, we should as it will provide proper clarity to the user.

**Review by navendu-pottekkat — COMMENTED** [review]
Should the example be in the "Example" section of the help? (refer `mesheryctl perf`) There could be three examples one just with `system logs` and other with a component name `system logs meshery-istio` and finally with multiple components `system logs meshery-broker meshery-istio`.

The usage should be updated to include "`<component name>`" as well so the users will know they can get the logs of individual components.

File: mesheryctl/internal/cli/root/system/logs.go (hunk 1 above)
Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/logs.go]: We should add tailing support for Kubernetes 😄 

@muskankhedia if the contributor is not working on this issue, could you follow up and take it up? https://github.com/layer5io/meshery/issues/3234

Comment (muskankhedia) [reply mesheryctl/internal/cli/root/system/logs.go]: @navendu-pottekkat Yes sure. I think we should wait for a day for @divyanshugit reply.

Comment (divyanshugit) [reply mesheryctl/internal/cli/root/system/logs.go]: @navendu-pottekkat I am in the middle of solving this issue. Delay is caused by some electricity issues in my locality.

Comment (muskankhedia) [reply mesheryctl/internal/cli/root/system/logs.go]: > We should add tailing support for Kubernetes 😄

@navendu-pottekkat the logs and tailing feature is used both for the Docker and Kubernetes platform but the <component-name> support is only for the Kubernetes platform. So specifying the support globally for Kubernetes only could go wrong. Please correct me if I am wrong.

Comment (divyanshugit) [reply mesheryctl/internal/cli/root/system/logs.go]: If this PR solves the issue. Then I will look into another issue.

Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/logs.go]: The logs should be "tailable" as well as "detached" for both docker and kubernetes ideally. For docker, it is handled by docker-compose installed on the user's machine. So instead of modifying the docs, let's make sure that we have a consistent behaviour across both the platforms.

Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/logs.go]: I will start a discussion on this and we can decide the best route.

Comment (muskankhedia) [reply mesheryctl/internal/cli/root/system/logs.go]: > So instead of modifying the docs, let's make sure that we have a consistent behaviour across both the platforms.

In that case, should I work on this PR after the implementation is done?

Comment (navendu-pottekkat) [reply mesheryctl/internal/cli/root/system/logs.go]: Yes, that would be most helpful.

**Comment by navendu-pottekkat** [comment]
@muskankhedia Were you able to make the changes?

**Comment by muskankhedia** [comment]
> In that case, should I work on this PR after the implementation is done?

@navendu-pottekkat I think we discussed that I will take it up after #3234.

**Comment by navendu-pottekkat** [comment]
@muskankhedia Sure, that jumped from my mind

**Comment by navendu-pottekkat** [comment]
@muskankhedia let's merge this PR and come back to it after you add the tailing feature. Could you let me know if this is ready to be reviewed again? I think we can merge with [these](https://github.com/meshery/meshery/pull/3284#pullrequestreview-693427236) changes.

**Comment by leecalcote** [comment]
Uh-oh, we're three days away from the 3 week rule.

_ok, there isn't a 21 day rule. I just wanted to razz @muskankhedia 😉 _

**Comment by navendu-pottekkat** [comment]
@muskankhedia Could you quickly fix the lint error? We can merge it after that

**Comment by muskankhedia** [comment]
@navendu-pottekkat @leecalcote Sorry for the delay. I have updated the description, please have a look.

File: mesheryctl/internal/cli/root/system/logs.go [hunk 2]
```diff
@@ -41,8 +41,10 @@ import (
 var logsCmd = &cobra.Command{
 	Use:   "logs",
 	Short: "Print logs",
-	Long:  `Print history of Meshery's logs and begin tailing them.`,
-	Args:  cobra.ArbitraryArgs,
+	Long: `Print history of Meshery's logs and begin tailing them for the Kubernetes platform.
```
Comment (navendu-pottekkat) [inline mesheryctl/internal/cli/root/system/logs.go:44]: This could just be "Print history of Meshery's container logs and begin tailing them."

File: mesheryctl/internal/cli/root/system/logs.go [hunk 3]
```diff
@@ -41,8 +41,10 @@ import (
...
+
+It also shows the tailing logs of a specific component e.g. "mesheryctl system logs meshery-istio"`,
```
Comment (navendu-pottekkat) [inline mesheryctl/internal/cli/root/system/logs.go:46]: This could be moved to an examples section right? And other general use cases could also be added.

In this example, this would not tail the logs as this is for the Kubernetes platform. We have to add this tailing feature as we discussed.

**Review by navendu-pottekkat — CHANGES_REQUESTED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 2b5c65e2d63e8f163d2c65c2ddfd4a1f0ab2f3fb at: https://60efc92205dafca75801ffb3--meshery-docs-preview.netlify.app

**Comment by muskankhedia** [comment]
@navendu-pottekkat I have made the updates. Please have a look.

**Comment by l5io** [comment]
🚀 Preview for commit 0e6843660d8533ea6fb30d77a1f38950dc5ed6b6 at: https://60efd2ccb31f4fb095b2bf09--meshery-docs-preview.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 58d2fae31485258b4c4765a0e38b93aa2d59cc61 at: https://60efd3feadbc62b7e72398db--meshery-docs-preview.netlify.app

File: docs/_data/mesheryctlcommands/lifecycle/system/logs/command/logs.yml [hunk 4]
```diff
@@ -1,4 +1,9 @@
...
+description: Starts tailing Meshery server debug logs
 usage: |
-    mesheryctl system logs
\ No newline at end of file
+
+    # View the logs for a specific component
+    mesheryctl system logs [component-name]
+
+    # Example
+    mesheryctl system logs meshery-istio
```
Comment (navendu-pottekkat) [inline docs/_data/mesheryctlcommands/lifecycle/system/logs/command/logs.yml:9]: Could you add a newline here?

**Review by navendu-pottekkat — APPROVED** [review]
Looks good, let's merge this after you add the newline.

**Comment by l5io** [comment]
🚀 Preview for commit 24ad5477a20aede815292fa0d24ff4167c262e14 at: https://60f595a7f706db6e691b6b35--meshery-docs-preview.netlify.app

**Comment by muskankhedia** [comment]
@navendu-pottekkat made the changes. Please have a look.

**Comment by l5io** [comment]
🚀 Preview for commit 62c384de3c6fd37c0dca4bf4f2f55c29ee80f81a at: https://60f59730b66d4b3d1b03cdaf--meshery-docs-preview.netlify.app

**Review by navendu-pottekkat — APPROVED** [review]
