### PR TITLE
fix: update design onboard error not formatting placeholder properly on server.

### LINKED ISSUE #14585: [mesheryctl]  "%s" placeholder not resolved in Meshery design deployment error message
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

When deploying a design using:

`mesheryctl design onboard -f nginx.yaml -s "Kubernetes Manifest"`
the Meshery server logs the following error:
`Unable to deploy the selected design "%s".nginx.yaml
`

### Desired Behavior

`Unable to deploy the selected design "nginx.yaml"`

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes
- Command used: mesheryctl design onboard

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- ⌨️ [Meshkit errors Guide](https://docs.meshery.io/project/contributing/contributing-error)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by lekaf974**
Signed-off-by: lekaf974 <matthieu.evrin@gmail.com>

**Notes for Reviewers**

- This PR fixes #14585

Issue was opened a while ago and the error output changed since then but the core issue was still present.

## Before fix

Issue in error server side

```bash
xxx | Short Description: Unable to deploy the selected design \"%s\".nginx.yaml | Probable Cause: xxx description="Unable to deploy the selected design \"%s\".nginx.yaml" xxx"
```
placeholder is not handle properly server side and error not handle properly in cli with following output

```bash
Error: Response Status Code 500. Server emitted an error: meshery server failed to interact with the Kubernetes cluster due to the cluster not being available | Short Description: Kubernetes cluster is unavailable for .nginx.yaml | Probable Cause: There might be a network disruption or the Meshery server does not have valid credentials. | Suggested Remediation: Try uploading a new kubeconfig..Check the network connection and Kubernetes cluster status..Verify that the Meshery server has valid and updated credentials to access the Kubernetes cluster. | Short Description: Unable to deploy the selected design "%s".nginx.yaml | Probable Cause: Connection Error: There was an error connecting to the selected target platform (i.e. Kubernetes cluster(s))..This connection might not be assigned to the selected environment. | Suggested Remediation: Verify that the Kubernetes connection status is 'Connected' or try uploading a new kubeconfig..Assign the current Kubernetes connection to the selected environment.
 | Short Description: Failed response server error | Probable Cause: Invalid API call | Suggested Remediation: Check your network connection and the status of Meshery Server via `mesheryctl system status`.
```

## After fix

Issue in error server side

```bash
xxx Short Description: Unable to deploy the selected design \"nginx.yaml\" | Probable Cause: xxx short-description="Unable to deploy the selected design \"nginx.yaml\"" xxx"
```
placeholder is now handled properly server side 

New behavior in cli with following output

```bash
Error: Unable to onboard design due to error during the processing | Short Description: Onboarding design failed | Probable Cause: File path or design name not provided. .Meshery server failed to interact with the Kubernetes cluster. .There was an error connecting to the selected target platform (i.e. Kubernetes cluster(s))..This connection might not be assigned to the selected environment. | Suggested Remediation: Provide a valid file path/design name. .Ensure the Meshery server can interact with the Kubernetes cluster. .Check if the selected target platform is assigned to the current environment.
```

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/pkg/utils/error.go [hunk 1]
```diff
@@ -864,3 +865,14 @@ func ErrPromptCancelled() error {
 		[]string{"Run the command again and complete the selection"},
 	)
 }
+
+func ErrInternalServerError(err error) error {
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/error.go]: If these are referring to Meshery Server, it would be nice to use "Meshery Server".

And to include helpful tips like "Check Meshery Server logs using `mesheryct system logs` for more details and try again."

File: mesheryctl/internal/cli/root/design/onboard.go [hunk 2]
```diff
@@ -196,7 +208,7 @@ func multiplepatternsConfirmation(profiles []models.MesheryPattern) int {
 }
 
 func init() {
-	onboardCmd.Flags().StringVarP(&file, "file", "f", "", "Path to design file")
-	onboardCmd.Flags().BoolVarP(&skipSave, "skip-save", "", false, "Skip saving a design")
-	onboardCmd.Flags().StringVarP(&sourceType, "source-type", "s", "", "Type of source file (ex. manifest / compose / helm)")
+	onboardCmd.Flags().StringVarP(&designOnboardFlags.File, "file", "f", "", "Path to design file")
+	onboardCmd.Flags().BoolVarP(&designOnboardFlags.SkipSave, "skip-save", "", false, "Skip saving a design")
+	onboardCmd.Flags().StringVarP(&designOnboardFlags.SourceType, "source-type", "s", "", "Type of source file (ex. manifest / compose / helm)")
```
Comment (leecalcote) [inline mesheryctl/internal/cli/root/design/onboard.go:213]: If the type being onboarded is Meshery Design, I wonder if no --source-type is necessary to specify.

Comment (lekaf974) [reply mesheryctl/internal/cli/root/design/onboard.go:213]: Perhaps it can be reevaluate in renaming issue
