### PR TITLE
Fix exp components cmd bugs

### LINKED ISSUE #9625: [mesheryctl] New command: `exp components [list|view|search]`
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
Create an `exp components [list|view|search]` command similar to that of `exp model` command.

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by alphaX86**
**Notes for Reviewers**

This PR fixes #9625

Related to PR #9726 

Panic error happens when user types `mesheryctl exp components`. This PR is intended to fix the bug as well as make minor changes in the command files.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@MUzairS15, I'm confirming: the design is to have components under root?

File: mesheryctl/internal/cli/root/components/view.go [hunk 1]
```diff
@@ -0,0 +1,170 @@
...
+		// user may pass flag in lower or upper case but we have to keep it lower
+		// in order to make it consistent while checking output format
+		outFormatFlag = strings.ToLower(outFormatFlag)
+		if outFormatFlag == "yaml" {
+			if output, err = yaml.Marshal(selectedComponent); err != nil {
+				return errors.Wrap(err, "failed to format output in YAML")
+			}
+			if saveFlag {
+				fmt.Println("Saving output as YAML file")
+				err = os.WriteFile("./output.yaml", output, 0666)
```
Comment (Althaf66) [inline mesheryctl/internal/cli/root/components/view.go:135]: Give the file name same as component's name otherwise file will be overwritten. My suggestion is change the location to .meshery/content folder.

Comment (alphaX86) [reply mesheryctl/internal/cli/root/components/view.go:135]: Valid point, I'll change this up 👍

**Comment by leecalcote** [comment]
@Althaf66 all feedback accounted for, I think. Ready for another review.

**Comment by RipulHandoo** [comment]
My reviews were in pending state. 
I'll add them in comment section.

File: mesheryctl/internal/cli/root/components/list.go [hunk 2]
```diff
@@ -0,0 +1,200 @@
...
+	Use:   "list",
+	Short: "List registered components",
+	Long:  "List all components registered in Meshery Server",
+	Example: `
+	// View list of components
+mesheryctl exp components list
+// View list of components with specified page number (25 components per page)
+mesheryctl exp components list --page 2
+// View Total number of components
+mesheryctl exp components list --count
```
Comment (RipulHandoo) [inline mesheryctl/internal/cli/root/components/list.go:45]: Using mesheryctl exp components --count would enhance clarity and consistency compared to incorporating the count flag within mesheryctl exp components list --count.

**Review by RipulHandoo — CHANGES_REQUESTED** [review]

File: mesheryctl/internal/cli/root/components/list.go (hunk 2 above)
Comment (alphaX86) [reply mesheryctl/internal/cli/root/components/list.go]: Done

File: mesheryctl/internal/cli/root/components/view.go [hunk 3]
```diff
@@ -0,0 +1,170 @@
...
+			fmt.Println("No component(s) found for the given name: ", component)
+			return nil
+		} else if componentResponse.Count == 1 {
+			selectedComponent = componentResponse.Components[0] // Update the type of selectedModel
+		} else {
+			selectedComponent = selectComponentPrompt(componentResponse.Components)
+		}
+
+		var output []byte
+
```
[the remark this answers is not in the document]
Comment (alphaX86) [reply mesheryctl/internal/cli/root/components/view.go:125]: Done

File: mesheryctl/internal/cli/root/components/list.go [hunk 4]
```diff
@@ -0,0 +1,200 @@
...
+						startIndex = 0
+					}
+					endIndex = min(len(rows), startIndex+maxRowsPerPage)
+				}
+
+				if startIndex >= len(rows) {
+					break
+				}
+
+				whiteBoardPrinter.Println("Press ↑/← or ↓/→ to navigate, Esc or Ctrl+C to exit")
```
[the remark this answers is not in the document]
Comment (alphaX86) [reply mesheryctl/internal/cli/root/components/list.go]: Done

**Review by MUzairS15 — APPROVED** [review]
LGTM!
