### PR TITLE
Fix experimental model command in mesheryctl

### LINKED ISSUE #9470: [mesheryctl] crash in experimental model command
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
```
➜  mesheryctl git:(master) ./mesheryctl exp model
View list of models and detailed information of a specific model

Usage:
  mesheryctl exp model [flags]
  mesheryctl exp model [command]

Examples:

// To view list of components
mesheryctl exp model list

// To view a specific model
mesheryctl exp model view [model-name]


Available Commands:
  list        list models
  search      search models
  view        view model

Flags:
  -h, --help   help for model

Global Flags:
      --config string   path to config file (default "/Users/lee/.meshery/config.yaml")
  -v, --verbose         verbose output

Use "mesheryctl exp model [command] --help" for more information about a command.
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/layer5io/meshery/mesheryctl/internal/cli/root/system.glob..func40(0xc00037ae00?, {0x104f04060?, 0x0, 0x0})
	/Users/lee/code/meshery/mesheryctl/internal/cli/root/system/model.go:360 +0x2fd
github.com/spf13/cobra.(*Command).execute(0x104d13500, {0x104f04060, 0x0, 0x0})
	/Users/lee/code/go/bin/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0x104d0a540)
	/Users/lee/code/go/bin/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/lee/code/go/bin/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/layer5io/meshery/mesheryctl/internal/cli/root.Execute()
	/Users/lee/code/meshery/mesheryctl/internal/cli/root/root.go:82 +0x45
main.main()
	/Users/lee/code/meshery/mesheryctl/cmd/mesheryctl/main.go:26 +0x13
```

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by lakshz**
**Notes for Reviewers**

This PR fixes #9470 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by yash37158** [comment]
Hey @LakshyaSatpal, just a heads up that there are some lint check failures on this PR. If you have a moment, could you please take a look and see if you can address them?

File: mesheryctl/pkg/utils/auth.go [hunk 1]
```diff
@@ -455,7 +455,7 @@ func IsServerRunning(serverAddr string) error {
 	conn, err := net.DialTimeout("tcp", serverAddr, 2*time.Second)
 	if err != nil {
 		// Connection failed, server is not running
-		return errors.WithMessage(err, "Mehsery server is not reachable")
+		return errors.WithMessage(err, "Meshery server is not reachable")
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/auth.go:458]: thanks

**Review by leecalcote — APPROVED** [review]
Good work. Thank you, @LakshyaSatpal
