### PR TITLE
fix user prefs

### LINKED ISSUE #8071: [Server] Overwriting Remote Provider User Preferences
#### Current Behavior

User preferences get request override any preferences set by meshery cloud. (`/api/user/prefs`)

#### Expected Behavior

Update user preferences without affect to existing items.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by MUzairS15**
**Notes for Reviewers**

This PR fixes #8071 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: server/models/preference.go [hunk 1]
```diff
@@ -68,6 +68,7 @@ type Preference struct {
 	AnonymousPerfResults      bool                   `json:"anonymousPerfResults"`
 	UpdatedAt                 time.Time              `json:"updated_at,omitempty"`
 	UsersExtensionPreferences map[string]interface{} `json:"usersExtensionPreferences,omitempty"`
+	GetStarted                []int                  `json:"getStarted,omitempty"`
```
Comment (MUzairS15) [inline server/models/preference.go:71]: @senali-d Instead of storing this like this way, can you please make changes in meshery-cloud, to store it as 
`meshery-cloud-prefs: {
getStarted: ...
}` 
so that in future other prefs can also be handled.

When you do so signal me I also need to update here.

Comment (senali-d) [reply server/models/preference.go:71]: @MUzairS15 Raised a pr. saved prefs under `mesheryCloudPrefs`

Comment (MUzairS15) [reply server/models/preference.go:71]: Thanks, I will add changes here.
