### PR TITLE
fix: system reset uses meshkit error properly, remove logrus

### LINKED ISSUE #18334: [mesheryctl] system reset uses meshkit error properly + remove logrus
## Parent Issue
#17709 

##Current Behavior
-logging error and return nil which ending like exit 0
-not always using meshkit error

## Expected Behavior
- Remove `logrus` import
- Return errors properly using meshkit errors
- Use `utils.Log` for logging

### PR DESCRIPTION
**Pull request by Omkar-Ugal**
Fixes #18334 

- [x] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/internal/cli/root/system/reset_test.go [hunk 1]
```diff
@@ -72,12 +72,12 @@ func RemoveFileAndDirectory() {
 	// from the directory
 	removeMesheryYaml := os.Remove("meshery.yaml")
 	if removeMesheryYaml != nil {
-		log.Fatal(removeMesheryYaml)
+		utils.Log.Fatal(removeMesheryYaml)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/reset_test.go]: Revert this change in test file

File: mesheryctl/internal/cli/root/system/reset_test.go [hunk 2]
```diff
@@ -72,12 +72,12 @@ func RemoveFileAndDirectory() {
...
 	}
 
 	// Removing the .meshery directory
 	removeMesheryHiddenDirectory := os.RemoveAll(".meshery")
 	if removeMesheryHiddenDirectory != nil {
-		log.Fatal(removeMesheryHiddenDirectory)
+		utils.Log.Fatal(removeMesheryHiddenDirectory)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/reset_test.go]: Revert this change in test file

File: mesheryctl/internal/cli/root/system/reset.go [hunk 3]
```diff
@@ -44,7 +40,7 @@ mesheryctl system reset
 	Annotations: linkDocReset,
 	RunE: func(cmd *cobra.Command, args []string) error {
 		if len(args) != 0 {
-			return errors.New(utils.SystemLifeCycleError(fmt.Sprintf("this command takes no arguments. See '%s --help' for more information.\n", cmd.CommandPath()), "reset"))
+			return utils.ErrInvalidArgument(fmt.Errorf("this command takes no arguments. See '%s --help' for more information", cmd.CommandPath()))
 		}
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/reset.go:45]: move this in Args please

**Comment by lekaf974** [comment]
@Omkar-Ugal tests are still failing

File: mesheryctl/internal/cli/root/system/reset.go
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/reset.go]:
```suggestion
	Long:  `Reset Meshery to it's default configuration.
Find more information at: https://docs.meshery.io/reference/mesheryctl/system/reset`,
```

File: mesheryctl/internal/cli/root/system/reset.go [hunk 4]
```diff
@@ -123,26 +122,26 @@ func fetchManifests(mctlCfg *config.MesheryCtlConfig) error {
...
 
 		if err != nil {
 			return err
 		}
 
-		log.Info("...meshconfig has been reset to default settings.")
+		utils.Log.Info("...meshconfig has been reset to default settings.")
 
 	default:
 		return fmt.Errorf("the platform %s is not supported currently. The supported platforms are:\ndocker\nkubernetes\nPlease check %s/config.yaml file", currCtx.Platform, utils.MesheryFolder)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/reset.go]: I think there is an existing meshkit error for unsupported platform, could you update this please
