### PR TITLE
[mesheryctl] fixed silent errors

### LINKED ISSUE #17543: [mesheryctl] exp relationship generate silently swallows all errors
### Current Behavior
Every error in generateCmd.RunE and createJsonFile() is logged but returns nil instead of the error. This means the command always exits with code 0 even when it fails like authentication errors, spreadsheet fetch failures, and file write errors are all silently swallowed. 

### Expected Behavior
Errors should be returned so Cobra can report failure properly.

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
- 📺 [Self-paced Contributor Trainings](https://meshery.io/talks-and-trainings#trainings)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by DharunMR**
**Notes for Reviewers**

- This PR fixes #17543 

- Fixed silent errors
- Since first 2rows of spreadsheet is header sheet with  only headers will create null json file so i changed data validation value from 0 to 2  
- Changed test case

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
This is a good item to add to the weekly Meshery development meeting agenda - [https://meet.meshery.io/dev-minutes](https://meet.meshery.io/dev-minutes). I encourage you to add this item in the doc, attend, and present it. Meeting details at https://meshery.io/calendar.

**Comment by DharunMR** [comment]
@leecalcote Sure, i will👍🏻

File: mesheryctl/internal/cli/root/relationships/generate_test.go [hunk 1]
```diff
@@ -135,6 +135,41 @@ func TestGenerate(t *testing.T) {
...
+								"allowTo",
+								"complete",
+								"visual",
+							},
+						},
+					}, nil
+				}
+			}
+
 			if tt.Fixture != "" {
```
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/relationships/generate_test.go]: Isn't this dead code now? fetchSheetValues is mocked so this HTTP endpoint is never hit.

File: mesheryctl/internal/cli/root/relationships/generate_test.go [hunk 2]
```diff
@@ -196,8 +231,8 @@ func TestGenerate(t *testing.T) {
 
 			utils.Equals(t, cleanedExceptedResponse, cleanedActualResponse)
```
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/relationships/generate_test.go:194]: This golden file (generate.relationship.output.golden) is 0 bytes, so this comparison is "" == "". The command's success message goes through utils.Log.Info, not stdout. We need to also verify the actual JSON output by reading back RelationshipsDataTest.json and comparing it against an expected golden file.

**Comment by DharunMR** [comment]
@PragalvaXFREZ  changed the test logic ~ added meshkit error validation and didnt added generated jsonfile validation since TestGenerateCreateJsonFile already validate it. Removed unused mock http requests.

File: mesheryctl/internal/cli/root/relationships/generate_test.go [hunk 3]
```diff
@@ -79,112 +78,118 @@ func TestGenerate(t *testing.T) {
...
-			URL:              testContext.BaseURL + "/api/meshmodels/relationships",
-			Fixture:          "",
-			ExpectedResponse: "generate.relationship.output.without.spreadsheet.id.golden",
-			Token:            filepath.Join(fixturesDir, "token.golden"),
-			ExpectError:      true,
+			Name:           "Generate registered relationships without spreadsheet creadentials",
+			Args:           []string{"generate", "--spreadsheet-id", "1"},
+			ExpectError:    true,
+			IsOutputGolden: false,
+			ExpectedError:  errors.New(utils.RelationshipsError(errMsg, "generate")),
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/generate_test.go]: It should be a meshkit error

File: mesheryctl/internal/cli/root/relationships/generate_test.go [hunk 4]
```diff
@@ -79,112 +78,118 @@ func TestGenerate(t *testing.T) {
...
-			URL:              testContext.BaseURL + "/api/meshmodels/relationships",
-			Fixture:          "",
-			ExpectedResponse: "generate.relationship.output.without.spreadsheet.cred.golden",
-			Token:            filepath.Join(fixturesDir, "token.golden"),
-			ExpectError:      true,
+			Name:           "Generate registered relationships without spreadsheet id",
+			Args:           []string{"generate", "--spreadsheet-cred", "$CRED"},
+			ExpectError:    true,
+			IsOutputGolden: false,
+			ExpectedError:  errors.New(utils.RelationshipsError(errMsg, "generate")),
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/generate_test.go]: it should be a meshkit error

File: mesheryctl/internal/cli/root/relationships/generate_test.go [hunk 5]
```diff
@@ -79,112 +78,118 @@ func TestGenerate(t *testing.T) {
...
-			_ = utils.SetupMeshkitLoggerTesting(t, false)
+			if tt.Name == "Generate registered relationships" {
+				originalPath := relationshipsOutputPath
+				defer func() { relationshipsOutputPath = originalPath }()
+				relationshipsOutputPath = "./testdata/RelationshipsDataTest.json"
+
+				originalFetch := fetchSheetValues
+				defer func() { fetchSheetValues = originalFetch }()
+
+				sheetData, err := os.ReadFile("./fixtures/generate.relationship.sheet.data.golden")
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/generate_test.go]: please reuse existing methods to read golden files from pkg/utils.go example available in most of our tests

File: mesheryctl/internal/cli/root/relationships/generate_test.go [hunk 6]
```diff
@@ -79,112 +78,118 @@ func TestGenerate(t *testing.T) {
...
+			b := utils.SetupMeshkitLoggerTesting(t, false)
 			defer func() {
 				os.Stdout = originalStdout
 			}()
 
-			_ = utils.SetupMeshkitLoggerTesting(t, false)
+			if tt.Name == "Generate registered relationships" {
+				originalPath := relationshipsOutputPath
+				defer func() { relationshipsOutputPath = originalPath }()
+				relationshipsOutputPath = "./testdata/RelationshipsDataTest.json"
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/generate_test.go]: this could be also a golden file

File: mesheryctl/internal/cli/root/relationships/testdata/relationships-data-test.json
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/testdata/relationships-data-test.json:1]: could we convert filename in lowercase

**Review by lekaf974 — CHANGES_REQUESTED** [review]
Small comments

File: mesheryctl/internal/cli/root/relationships/generate_test.go [hunk 7]
```diff
@@ -79,112 +78,116 @@ func TestGenerate(t *testing.T) {
...
-			os.Stdout = w
-
-			// Ensure stdout is always restored
+			b := utils.SetupMeshkitLoggerTesting(t, false)
 			defer func() {
 				os.Stdout = originalStdout
 			}()
 
-			_ = utils.SetupMeshkitLoggerTesting(t, false)
+			if tt.Name == "Generate registered relationships" {
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/generate_test.go]: this is not a good idea to check on a name, if for any reason it changes it will not work, adding a dedicated field looks a better idea

File: mesheryctl/internal/cli/root/relationships/generate.go [hunk 8]
```diff
@@ -43,44 +54,38 @@ var generateCmd = &cobra.Command{
...
-		if err != nil || resp.HTTPStatusCode != 200 {
-			utils.Log.Error(err)
-			return nil
-		}
-		if len(resp.Values) == 0 {
-			utils.Log.Info("No data(relationships) found in the sheet")
+
+		// Since first two rows are headers
+		if len(resp.Values) <= 2 {
+			return errors.New("no relationship data found in sheet")
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/generate.go]: Meshkit error

File: mesheryctl/internal/cli/root/relationships/generate.go [hunk 9]
```diff
@@ -111,20 +116,17 @@ func createJsonFile(resp *sheets.ValueRange, jsonFilePath string) error {
 
 	jsonData, err := json.MarshalIndent(customResp, "", "    ")
 	if err != nil {
-		utils.Log.Error(err)
-		return nil
+		return err
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/generate.go]: We should have an existing meshkt error for this one

File: mesheryctl/internal/cli/root/relationships/generate.go [hunk 10]
```diff
@@ -111,20 +116,17 @@ func createJsonFile(resp *sheets.ValueRange, jsonFilePath string) error {
...
 	}
 
 	jsonFile, err := os.Create(jsonFilePath)
 	if err != nil {
-		utils.Log.Error(err)
-		return nil
+		return err
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/generate.go]: Check if there is an existing meahkit error

File: mesheryctl/internal/cli/root/relationships/generate.go [hunk 11]
```diff
@@ -111,20 +116,17 @@ func createJsonFile(resp *sheets.ValueRange, jsonFilePath string) error {
...
 	}
 	defer func() { _ = jsonFile.Close() }()
 	_, err = jsonFile.Write(jsonData)
 	if err != nil {
-		utils.Log.Error(err)
-		return nil
+		return err
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/generate.go]: Same

**Comment by DharunMR** [comment]
@lekaf974 Should i also implement save flag or only the logic?

**Comment by lekaf974** [comment]
> @lekaf974 Should i also implement save flag or only the logic?

I don't think generate required save flags but perhaps we could reuse common lib to generate yaml and json (PS: could be done in another PR as well)

**Comment by DharunMR** [comment]
@lekaf974 I implemented in this pr it self 
Screenshot_2026-03-02_08 30 09
My only concern is the last two lines feels repeated

**Comment by PragalvaXFREZ** [comment]
> @lekaf974 I implemented in this pr it self Screenshot_2026-03-02_08 30 09 My only concern is the last two lines feels repeated

I feel it is redundant as well, can't we only keep the latter?

**Comment by DharunMR** [comment]
removing the line "Data saved to file <>" isnt possible since many other command uses this same method

File: mesheryctl/internal/cli/root/relationships/testdata/generate.relationship.output.golden
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/testdata/generate.relationship.output.golden:1]: is this new line a debug one ?

File: mesheryctl/internal/cli/root/relationships/generate.go [hunk 12]
```diff
@@ -43,44 +52,38 @@ var generateCmd = &cobra.Command{
 mesheryctl exp relationship generate --spreadsheet-id [Spreadsheet ID] --spreadsheet-cred $CRED
 `,
 	Args: func(cmd *cobra.Command, args []string) error {
-		const errMsg = "[ Spreadsheet ID | Spreadsheet Credentials ] aren't specified\n\nUsage: mesheryctl exp relationship generate --spreadsheet-id [Spreadsheet ID] --spreadsheet-cred $CRED\nRun 'mesheryctl exp relationship generate --help' to see detailed help message"
 
 		// Check if flag is set
-		if spreadsheeetID == "" || spreadsheeetCred == "" {
-			return errors.New(utils.RelationshipsError(errMsg, "generate"))
+		if spreadsheetID == "" || spreadsheetCred == "" {
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/generate.go]: this could be updated using the flag validator

File: mesheryctl/internal/cli/root/relationships/testdata/generate.relationship.output.golden
Comment (DharunMR) [reply mesheryctl/internal/cli/root/relationships/testdata/generate.relationship.output.golden:1]: No it wasnt debug, it is Info Log msg from the JSONOutputFormatterSaver in the display package when saving the JSON output. It wasn’t added specifically for debugging in this change but is part of the formatter’s save behavior.

Two log messages appear because one already exists in relationships/generate.go and the other comes from display/output.go which is used to create the JSON file.

File: mesheryctl/internal/cli/root/relationships/generate.go [hunk 13]
```diff
@@ -42,45 +54,42 @@ var generateCmd = &cobra.Command{
...
 		// Check if flag is set
-		if spreadsheeetID == "" || spreadsheeetCred == "" {
-			return errors.New(utils.RelationshipsError(errMsg, "generate"))
+		flagValidator, ok := cmd.Context().Value(mesheryctlflags.FlagValidatorKey).(*mesheryctlflags.FlagValidator)
+		if !ok || flagValidator == nil {
+			return utils.ErrCommandContextMissing("flags-validator")
+		}
+		err := flagValidator.Validate(cmdRelationshipGenerateFlag)
+		if err != nil {
+			return utils.ErrFlagsInvalid(fmt.Errorf("%s", errMsg))
```
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/relationships/generate.go]: validate() already returns utils.ErrFlagsInvalid, this just double-wraps it. We should probably return err directly here.

File: mesheryctl/internal/cli/root/relationships/error.go [hunk 14]
```diff
@@ -1,9 +1,36 @@
...
+
+func ErrSpreadsheetFlagMissing(err error) error {
+	return errors.New(
+		ErrSpreadsheetFlagMissingCode,
+		errors.Alert,
+		[]string{"Spreadsheet flags missing"},
+		[]string{err.Error()},
+		[]string{"Either --spreadsheet-id or --spreadsheet-cred flag was not specified"},
+		[]string{"Provide both --spreadsheet-id and --spreadsheet-cred flags to generate relationships"})
+}
```
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/relationships/error.go]: is this ever used? i think this is dead code

File: mesheryctl/internal/cli/root/relationships/generate_test.go [hunk 15]
```diff
@@ -2,189 +2,182 @@ package relationships
...
-			// Ensure stdout is always restored
+			b := utils.SetupMeshkitLoggerTesting(t, false)
 			defer func() {
 				os.Stdout = originalStdout
 			}()
 
-			_ = utils.SetupMeshkitLoggerTesting(t, false)
+			originalPath := relationshipsOutputPath
+			defer func() { relationshipsOutputPath = originalPath }()
+			relationshipsOutputPath = "./fixtures/generate.relationship.json.output.golden"
```
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/relationships/generate_test.go]: nit: any reasons why we are writing to fixtures?

Comment (DharunMR) [reply mesheryctl/internal/cli/root/relationships/generate_test.go]: first createJSON test needed a json file to validate so i write in fixture ,now removed it because that looks repeated. I'll change this to write to testdata

Comment (PragalvaXFREZ) [reply mesheryctl/internal/cli/root/relationships/generate_test.go]: yeah makes sense, thanks

File: mesheryctl/internal/cli/root/relationships/generate.go [hunk 16]
```diff
@@ -1,20 +1,32 @@
...
-var (
-	spreadsheeetID   string
-	spreadsheeetCred string
-)
+type relationshipGenerateFlag struct {
+	SpreadsheetID   string `json:"spreadsheet-id" validate:"required"`
+	SpreadsheetCred string `json:"spreadsheet-cred" validate:"required"`
+}
+
+var cmdRelationshipGenerateFlag relationshipGenerateFlag
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/generate.go]:
```suggestion
type cmdRelationshipGenerateFlag struct {
	SpreadsheetID   string `json:"spreadsheet-id" validate:"required"`
	SpreadsheetCred string `json:"spreadsheet-cred" validate:"required"`
}

var relationshipGenerateFlag relationshipGenerateFlag
```
Looks more accurate by reverse those names

File: mesheryctl/internal/cli/root/relationships/generate.go [hunk 17]
```diff
@@ -42,45 +54,42 @@ var generateCmd = &cobra.Command{
...
 
 		// If no error, fetch the data from the sheet
-		err = createJsonFile(resp, "../docs/_data/RelationshipsData.json")
+		err = createJsonFile(resp, relationshipsOutputPath)
 		if err != nil {
-			utils.Log.Error(err)
-			return nil
+			return err
 		}
 		utils.Log.Info("Relationships data generated in docs/_data/RelationshipsData.json")
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/generate.go]: This look no more necessary since NewJSONOutputFormatterSaver already generate on output

**Comment by lekaf974** [comment]
> > @lekaf974 I implemented in this pr it self Screenshot_2026-03-02_08 30 09 My only concern is the last two lines feels repeated
> 
> I feel it is redundant as well, can't we only keep the latter?

My last comment should fix this

**Comment by DharunMR** [comment]
@lekaf974 I think this pr is now ready to be merged.

File: mesheryctl/internal/cli/root/relationships/error.go [hunk 18]
```diff
@@ -1,9 +1,24 @@
...
+)
+
+func ErrEmptySheetData(err error) error {
+	return errors.New(
+		ErrEmptySheetDataCode,
+		errors.Alert,
+		[]string{"Invalid spreadsheet"},
+		[]string{err.Error()},
+		[]string{"Ensure the spreadsheet contains valid relationship entries before importing"},
+		[]string{"Spreadsheet must contains two headers and values for it's headers"},
```
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/relationships/error.go]:
```suggestion
		[]string{"Spreadsheet must contain two headers and values for it's headers"},
```

File: mesheryctl/internal/cli/root/relationships/generate_test.go [hunk 19]
```diff
@@ -2,189 +2,186 @@ package relationships
...
 
-	resp := &sheets.ValueRange{
-		MajorDimension: "ROWS",
-		Range:          "Relationships!A1:O1000",
-		Values: [][]interface{}{
-			{},
-			{},
-			sheetDataParsed["ROW3"].([]interface{}),
+		{
+			Name:           "Generate registered relationships without spreadsheet creadentials",
```
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/relationships/generate_test.go]:
```suggestion
			Name:           "Generate registered relationships without spreadsheet credentials",
```

File: mesheryctl/internal/cli/root/relationships/error.go [hunk 20]
```diff
@@ -1,9 +1,24 @@
...
+)
 
 var (
-	viewUsageMsg           = "\n\nUsage: mesheryctl exp relationship view [model-name]\nRun 'mesheryctl exp relationship view --help' to see detailed help message"
-	errNoModelNameProvided = fmt.Errorf("[model-name] isn't specified%s", viewUsageMsg)
-	errTooManyArgs         = fmt.Errorf("too many arguments, only [model-name] is expected%s", viewUsageMsg)
+	ErrEmptySheetDataCode = "mesheryctl-1203"
 )
+
+var (
```
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/relationships/error.go]: should this be a const as it's an immutable string

File: mesheryctl/internal/cli/root/relationships/generate_test.go [hunk 21]
```diff
@@ -2,189 +2,186 @@ package relationships
...
-	}
+	// test scenarios for fetching data
+	tests := []struct {
+		Name             string
+		Args             []string
+		Fixture          string
+		ExpectedResponse string
+		ExpectError      bool
+		IsOutputGolden   bool  `default:"true"`
+		ExpectedError    error `default:"nil"`
```
Comment (PragalvaXFREZ) [inline mesheryctl/internal/cli/root/relationships/generate_test.go]: Do these default:"true" and default:"nil" struct tags do anything? Go doesn't honor a default tag, fields  just get zero values (false, nil). Might be worth removing to avoid confusion?

Comment (DharunMR) [reply mesheryctl/internal/cli/root/relationships/generate_test.go]: it is also used in testing.go so i just followed the same pattern here. These tags would only have an effect if something reads them via reflection i think so

If we decide to remove them, we may also want to remove them from all other files for consistency.

@lekaf974 Any thoughts? 
i can open new pr for it?

Comment (lekaf974) [reply mesheryctl/internal/cli/root/relationships/generate_test.go]: think there are place without the default tag, it can be remove

Comment (lekaf974) [reply mesheryctl/internal/cli/root/relationships/generate_test.go]: removal can be done in this PR

Comment (DharunMR) [reply mesheryctl/internal/cli/root/relationships/generate_test.go]: Done changes

File: mesheryctl/internal/cli/root/relationships/error.go [hunk 22]
```diff
@@ -1,9 +1,24 @@
...
 )
+
+func ErrEmptySheetData(err error) error {
+	return errors.New(
+		ErrEmptySheetDataCode,
+		errors.Alert,
+		[]string{"Invalid spreadsheet"},
+		[]string{err.Error()},
+		[]string{"Ensure the spreadsheet contains valid relationship entries before importing"},
+		[]string{"Spreadsheet must contain two headers and values for it's headers"},
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/relationships/error.go]: Reading this if I use meshery f9r the first time, pretty sure it is useless. It should help me to identify what I have to do or where I can find relevant information.

**Review by lekaf974 — APPROVED** [review]

**Review by lekaf974 — APPROVED** [review]
