### PR TITLE
[mesheryctl] Fix Preflight Check for Remote Endpoints 

### LINKED ISSUE #7727: [mesheryctl] Preflight check assumes Docker to be on local machine
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
A Meshery deployment is running on Docker as the platform. When the Meshery deployment is running on a remote host, the `mesheryctl system <any command>` assumes that Docker needs to be locally available.

#### Logs
```
$ mesheryctl system logs
!! Docker is not running
Start Docker now [y/n]? n
Error: failed to start Docker : Please start Docker, then run the command `mesheryctl system logs`
```

meshconfig
```
$ mesheryctl system context view

Current Context: playground

endpoint: https://147.28.149.165
token: default
token-location: auth.json
platform: docker
components:
- meshery-istio
- meshery-linkerd
- meshery-consul
- meshery-nsm
- meshery-kuma
- meshery-osm
- meshery-traefik-mesh
- meshery-nginx-sm
channel: stable
version: latest
provider: Meshery
```

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by PiyushRaj927**
**Notes for Reviewers**

This PR fixes #7727 
Revised the preflight check for `mesheryctl system` commands on the Docker platform to generate an error if an endpoint is a remote URL instead of the `localhost` in meshconfig.

```bash
$ ./mesheryctl system logs
Error: Unsupported command `mesheryctl system logs` for platform Docker on remote endpoint `http://example:9081`
```

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by nebula-aac** [comment]
Reviewing...

I noticed the `mesheryctl` is spelled wrong too.

```bash
$ ./mesheryctl system logs
Error: Unsupported command `**mesherctl** system logs` for platform Docker on remote endpoint `http://example:9081`
```

**Review by nebula-aac — CHANGES_REQUESTED** [review]
`mesherctl` is spelled wrong, can you update the spelling to `mesheryctl`?

**Comment by PiyushRaj927** [comment]
Thanks for catching the typo! I've made the requested change

File: mesheryctl/internal/cli/root/system/check.go [hunk 1]
```diff
@@ -254,6 +254,10 @@ func (hc *HealthChecker) runDockerHealthChecks() error {
 	if hc.Options.PrintLogs {
 		log.Info("\nDocker \n--------------")
 	}
+	endpointParts := strings.Split(hc.context.Endpoint, ":")
+	if !strings.HasSuffix(endpointParts[1], "localhost") {
```
Comment (Azanul) [inline mesheryctl/internal/cli/root/system/check.go:258]: Why not using `!=` instead of `!strings.HasSuffix`

**Review by Azanul — CHANGES_REQUESTED** [review]
Other than the above changes.
I don't think it is a good idea to skip health checks. We can suggest the user to change the docker context to point to the deployed one since the same has to be used for the rest of the commands.

File: mesheryctl/internal/cli/root/system/check.go (hunk 1 above)
Comment (PiyushRaj927) [reply mesheryctl/internal/cli/root/system/check.go:258]: Are you suggesting using `!= "//localhost"`?. I chose `strings.HasSuffix` because it was already used in other parts of the code. Can you please explain your reasoning behind the suggestion?

File: mesheryctl/internal/cli/root/system/check.go [hunk 2]
```diff
@@ -254,6 +254,10 @@ func (hc *HealthChecker) runDockerHealthChecks() error {
 	if hc.Options.PrintLogs {
 		log.Info("\nDocker \n--------------")
 	}
+	endpointParts := strings.Split(hc.context.Endpoint, ":")
```
[the remark this answers is not in the document]
Comment (PiyushRaj927) [reply mesheryctl/internal/cli/root/system/check.go:257]: sure, will do.

File: mesheryctl/internal/cli/root/system/check.go (hunk 1 above)
Comment (Azanul) [reply mesheryctl/internal/cli/root/system/check.go:258]: > Are you suggesting using != "//localhost"?

Yes

> Can you please explain your reasoning behind the suggestion?

You don't really want to check the suffix i.e, if `//notlocalhost` was sent it would pass. Although you may see the example that I gave as an absurd one but my point is we're not trying to check the suffix truly, we're checking if it is `//localhost`.

**Comment by PiyushRaj927** [comment]
> Other than the suggested changes. I don't think it is a good idea to skip health checks. We can suggest the user to change the docker context to point to the deployed one since the same has to be used for the rest of the commands.

I agree with you. It's better to follow this approach instead of skipping the check. I will go ahead and make the required changes.

File: mesheryctl/internal/cli/root/system/check.go (hunk 1 above)
Comment (PiyushRaj927) [reply mesheryctl/internal/cli/root/system/check.go:258]: Got it. I'll make the changes. Thanks for the clarification

**Review by abdullah1308 — APPROVED** [review]

**Review by abdullah1308 — DISMISSED** [review]

File: mesheryctl/internal/cli/root/system/check.go [hunk 3]
```diff
@@ -254,9 +254,13 @@ func (hc *HealthChecker) runDockerHealthChecks() error {
 	if hc.Options.PrintLogs {
 		log.Info("\nDocker \n--------------")
 	}
+	endpointParts := strings.Split(hc.context.GetEndpoint(), ":")
 	//Check whether docker daemon is running or not
 	err := exec.Command("docker", "ps").Run()
 	if err != nil {
+		if endpointParts[1] != "//localhost" {
+			return errors.Wrapf(err, "please ensure that the appropriate Docker context is selected for the %s endpoint", hc.context.GetEndpoint())
```
Comment (Azanul) [inline mesheryctl/internal/cli/root/system/check.go:262]:
```suggestion
			return errors.Wrapf(err, "Meshery is not running locally, please ensure that the appropriate Docker context is selected for Meshery endpoint: %s. To list all configured contexts use `docker context ls`", hc.context.GetEndpoint())
```

Comment (Azanul) [reply mesheryctl/internal/cli/root/system/check.go:262]: @leecalcote

**Review by Azanul — APPROVED** [review]

**Review by abdullah1308 — APPROVED** [review]
