### PR TITLE
fix(mesheryctl-generate): Fix error not handled properly in model generate subcommand

### LINKED ISSUE #15665: [mesheryctl] model generate is not handling error properly
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

If we provide a file path that does not contains csv nothing is happening and nothing is logged

### Desired Behavior

Proper error message should be displayed

### Screenshots/Logs

```bash
~$ ./mesheryctl model generate -f tests/e2e/002-model/fixtures/model-import/valid-model
~$
```

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- ⌨️ [Meshkit errors Guide](https://docs.meshery.io/project/contributing/contributing-error)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by lekaf974**
**Notes for Reviewers**

- This PR fixes #15665 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

New behavior

```bash
~$ ./mesheryctl model generate -f tests/e2e/002-model/fixtures/model-import/valid-model
Error: inside the directory tests/e2e/002-model/fixtures/model-import/valid-model either the model csv or component csv is missing or they are not of write format
```

### CODE REVIEW

File: mesheryctl/internal/cli/root/model/generate.go [hunk 1]
```diff
@@ -48,58 +65,41 @@ mesheryctl model generate --f [URL] -t [path-to-template.json] -r
 
 		register, _ := cmd.Flags().GetBool("register")
 
+		// Path is a url
 		if isUrl {
 			template, _ := cmd.Flags().GetString("template")
```
Comment (Darshan174) [inline mesheryctl/internal/cli/root/model/generate.go:70]: show error if the temple provided is invalid or empty

File: mesheryctl/internal/cli/root/model/generate.go [hunk 2]
```diff
@@ -113,3 +113,58 @@ func init() {
 	generateModelCmd.Flags().BoolP("register", "r", false, "Skip registration of the model")
 
 }
+
+func (u *UrlModelGenerator) Generate() error {
+	utils.Log.Info("Generating model from URL: ", u.Url)
+
+	fileData, err := os.ReadFile(u.TemplateFile)
+	if err != nil {
+		return utils.ErrFileRead(err)
```
Comment (Darshan174) [inline mesheryctl/internal/cli/root/model/generate.go:122]: so this fixes the silent returned error issue right?

File: mesheryctl/internal/cli/root/model/generate.go [hunk 3]
```diff
@@ -113,3 +113,58 @@ func init() {
...
+	}
+
+	err = registerModel(fileData, nil, nil, "", "url", u.Url, !u.SkipRegister)
+	if err != nil {
```
Comment (Darshan174) [inline mesheryctl/internal/cli/root/model/generate.go:126]: adding error log after nil would help

File: mesheryctl/internal/cli/root/model/generate.go [hunk 4]
```diff
@@ -113,3 +113,58 @@ func init() {
...
+	}{
+		{c.ModelFile, &modelData},
+		{c.ComponentFile, &componentData},
+		{c.RelationshipFile, &relationshipData},
+	}
+
+	for _, f := range filePaths {
+		*f.data, err = os.ReadFile(f.path)
+		if err != nil {
+			return utils.ErrFileRead(err)
```
Comment (Darshan174) [inline mesheryctl/internal/cli/root/model/generate.go:154]: here as well, logging the error after this

Comment (lekaf974) [reply mesheryctl/internal/cli/root/model/generate.go:154]: Return the error will automatically log it in `RunE`

File: mesheryctl/internal/cli/root/model/generate.go (hunk 1 above)
Comment (lekaf974) [reply mesheryctl/internal/cli/root/model/generate.go:70]: this is exactly what we are doing 
```golang
if template == "" {
	return ErrTemplateFileNotPresent()
}

File: mesheryctl/internal/cli/root/model/generate.go (hunk 3 above)
Comment (lekaf974) [reply mesheryctl/internal/cli/root/model/generate.go:126]: this is what we do
```golang
  return err
```

File: mesheryctl/internal/cli/root/model/generate.go (hunk 1 above)
Comment (Darshan174) [reply mesheryctl/internal/cli/root/model/generate.go:70]: for invalid template?

**Review by alphaX86 — APPROVED** [review]
