### PR TITLE
K8s Pre-req check

### LINKED ISSUE #2579: [mesheryctl] Failure to detect running Kubernetes and gracefully handle error
#### Description
Meshconfig with "kubernetes" as the platform and no locally running Docker service results in an error.

#### Expected Behavior
mesheryctl should have more graceful error handling when the Kubernetes platform is not available.

#### Screenshots/Logs
**Context**
```
➜  ~ mesheryctl system context view
endpoint: https://localhost:9081
token: Default
platform: kubernetes
adapters:
- meshery-istio
- meshery-linkerd
- meshery-consul
- meshery-nsm
- meshery-kuma
- meshery-cpx
- meshery-osm
- meshery-traefik-mesh
channel: stable
version: latest
```

**Start**
```
➜  ~ mesheryctl system start
creating ~/.meshery/manifests folder...
downloading manifest files from https://github.com/layer5io/meshery/tree/master/install/deployment_yamls/k8s
Starting Meshery...
applying the manifests to Kubernetes cluster...
Error: failed to start Meshery
See https://docs.meshery.io/guides/mesheryctl/#meshery-lifecycle-management for usage details
: failed to apply manifest files: failed to apply manifests: Error Applying manifest.Get https://kubernetes.docker.internal:6443/api?timeout=32s: dial tcp 127.0.0.1:6443: connect: connection refused
Usage:
  mesheryctl system start [flags]
```

#### Environment:
- Meshery Version: v0.5.0-rc-6

### PR DESCRIPTION
**Pull request by metonymic-smokey**
Signed-off-by: metonymic-smokey <ahuja.aditi@gmail.com>

**Description**
Adds a pre-requisite check when platform is Kubernetes to handle errors gracefully when Kubernetes is not running.

This PR fixes #2579 

**Screenshot**
image

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by metonymic-smokey** [comment]
@reviewers
Assumptions in this draft:
Using `${HOMEDIR}/.kube/config` as the location for `kubeconfig`.
To fix: Should I accept a flag to specify the path?(which can be passed in `start.go` to PreReq).

**Comment by leecalcote** [comment]
The —config flag should serve this purpose. We need to add kubeconfig file location in the `context` structure.

File: mesheryctl/pkg/utils/helpers.go [hunk 1]
```diff
@@ -257,7 +263,30 @@ func PreReqCheck(subcommand string, focusedContext string) error {
 			}
 		}
 	} else if currCtx.Platform == "kubernetes" {
+		if err != nil {
+			return errors.Wrap(err, "failed to create new client")
+		}
```
Comment (navendu-pottekkat) [inline mesheryctl/pkg/utils/helpers.go:268]: Where are we creating this client? - Where are we catching this error?

File: mesheryctl/pkg/utils/helpers.go [hunk 2]
```diff
@@ -257,7 +263,30 @@ func PreReqCheck(subcommand string, focusedContext string) error {
...
 
+		config, err := clientcmd.BuildConfigFromFlags("", kubeconfig)
+		if err != nil {
+			return err
+		}
+
+		clientset, err := kubernetes.NewForConfig(config)
+		if err != nil {
+			return err
+		}
```
Comment (navendu-pottekkat) [inline mesheryctl/pkg/utils/helpers.go:284]: We can leverage MeshKit for creating the client. This could be replaced with one line-

```
            // create an kubernetes client
			client, err := meshkitkube.New([]byte(""))

			if err != nil {
				return err
			}
```

Could you refer the system status command in the `status.go` file? It has similar implementation...

This would make the code really simple and we can abstract a lot of functions.

File: mesheryctl/pkg/utils/helpers.go [hunk 3]
```diff
@@ -257,7 +263,30 @@ func PreReqCheck(subcommand string, focusedContext string) error {
...
+
+		_, err = clientset.CoreV1().Pods("").List(context.TODO(), metav1.ListOptions{})
+		if err != nil {
+			return errors.New("kubernetes is not running yet")
+		}
```
Comment (navendu-pottekkat) [inline mesheryctl/pkg/utils/helpers.go:289]: A log and a return error would be good which is consistent with the current implementation for the docker platform...

**Review by navendu-pottekkat — COMMENTED** [review]
@metonymic-smokey I have left some suggestions, please check it out.

Could you also add consideration for Kubernetes in the `IsMesheryRunning` method? It will be similar to this except you will be checking the `meshery` namespace...

File: mesheryctl/pkg/utils/helpers.go (hunk 1 above)
Comment (metonymic-smokey) [reply mesheryctl/pkg/utils/helpers.go:268]: Sorry, this was a typo. :(

**Comment by navendu-pottekkat** [comment]
> The —config flag should serve this purpose. We need to add kubeconfig file location in the `context` structure.


@leecalcote So, we have the default location of the `kubeconfig` file as `.kube/config` and we can add it to the context. And the user can specify a different file if he needs to. Is that the case?

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat thank you for the review!

Incorporated the suggested changes.
Let me know if these are acceptable. I'll then add the check to `IsMesheryRunning` similarly.

**Review by navendu-pottekkat — COMMENTED** [review]
@metonymic-smokey Looks good! You can add the changes to `IsMesheryRunning` to this PR itself and we can merge.

File: mesheryctl/pkg/utils/helpers.go [hunk 4]
```diff
@@ -341,12 +358,36 @@ func installprereq() error {
...
+			return strings.Contains(string(op), "meshery")
+		}
+	case "kubernetes":
+		{
+			client, err := meshkitkube.New([]byte(""))
+
+			if err != nil {
+				return false
+			}
+
```
Comment (navendu-pottekkat) [inline mesheryctl/pkg/utils/helpers.go:378]: `err != nil` would mean that it fails to create the client. So ideally, it should be returning the error. Otherwise, it would be wrong error stating that Meshery is not running...

**Review by navendu-pottekkat — CHANGES_REQUESTED** [review]
@metonymic-smokey could you make the change I mentioned? The rest looks good.

**Review by navendu-pottekkat — APPROVED** [review]
Looks good!

**Comment by leecalcote** [comment]
The documentation link being so specific is both nice and fragile at the same time. That link and anchor are subject to change without notice. Removing the anchor and leaving "https://docs.meshery.io/guides/upgrade" may serve to be both convenient to the user and less fragile to sustain.

File: mesheryctl/pkg/utils/helpers.go [hunk 5]
```diff
@@ -257,7 +262,19 @@ func PreReqCheck(subcommand string, focusedContext string) error {
...
+			return errors.Wrapf(err, "failed to create new client")
+		}
+
+		podInterface := client.KubeClient.CoreV1().Pods("")
+		_, err = podInterface.List(context.TODO(), v1.ListOptions{})
 
+		if err != nil {
+			log.Info("Kubernetes is not running yet")
+			return errors.Wrapf(err, "please start kubernetes. Run `mesheryctl system %s` after kubernetes is running", subcommand)
+		}
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/helpers.go:277]: Always capitalize Kubernetes

File: mesheryctl/pkg/utils/helpers.go [hunk 6]
```diff
@@ -341,12 +358,36 @@ func installprereq() error {
 }
 
 // IsMesheryRunning checks if the meshery server containers are up and running
-func IsMesheryRunning() bool {
-	op, err := exec.Command("docker-compose", "-f", DockerComposeFile, "ps").Output()
-	if err != nil {
-		return false
+func IsMesheryRunning(currPlatform string) (bool, error) {
+	switch currPlatform {
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/helpers.go:362]: Perhaps, we should be using `currCtx.Platform` directly.

**Review by leecalcote — COMMENTED** [review]
I'm ok with the extra commits (not @metonymic-smokey) being included here, but having an out-of-date fork is something to watch out for in general.

**Review by navendu-pottekkat — APPROVED** [review]

**Review by leecalcote — COMMENTED** [review]
Additional comments to address.
