### PR TITLE
Fix: Make a connection chip smaller for the smaller devices

### LINKED ISSUE #13739: [UI] Make a connection chip smaller for the smaller devices
### Current Behavior
Image It keeps same for the mobile screen.

### Desired Behavior
For the mobile screen show only the icon.

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by vr-varad**
**Notes for Reviewers**

- This PR fixes #13739

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vr-varad** [comment]
Done @amitamrutiya

File: ui/components/connections/styles.js [hunk 1]
```diff
@@ -102,6 +102,21 @@ export const ChipWrapper = styled(Chip)(({ theme }) => ({
...
+  [theme.breakpoints.down('sm')]: {
+    width: '8rem',
+    maxWidth: '8rem',
+    minWidth: '6rem',
+  },
+  [theme.breakpoints.down('xs')]: {
+    width: '6rem',
+    maxWidth: '6rem',
+    minWidth: '4rem',
+  },
```
Comment (amitamrutiya) [inline ui/components/connections/styles.js:119]: can you give a try with the clamp CSS property for render this thing.

Comment (vr-varad) [reply ui/components/connections/styles.js]: Worked well with clamp css as well. Thanks for the suggestion

Comment (vr-varad) [reply ui/components/connections/styles.js]: https://github.com/user-attachments/assets/0cb55de5-81a4-447b-933e-d12687ca0ffb
