### PR TITLE
Fixed Cross-site Scripting (XSS) in prometheus_handlers.go

### LINKED ISSUE #14191: Fix Cross-site Scripting (XSS) - prometheus_handlers.go
Path: server/handlers/prometheus_handlers.go, line 377
Path: server/handlers/prometheus_handlers.go, line 406

Info: Unsanitized input from the request URL flows into Write, where it is used to render an HTML page returned to the user. This may result in a Reflected Cross-Site Scripting attack (XSS).

### PR DESCRIPTION
**Pull request by Sumitsh28**
**Notes for Reviewers**

- This PR fixes #14191 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

- Used template.HTMLEscapeString to convert HTML to escaped data

### CODE REVIEW

**Comment by sangramrath** [comment]
@Sumitsh28 take a look at some of the check that are failing. You may want to join [slack](https://slack.meshery.io/) to get help / clarifications on this.

**Comment by vishalvivekm** [comment]
@Sumitsh28 
Thank you for your contributions! Let's discuss this today, during Meshery Development call at 9:00 AM CT | 7:30 PM IST. Add it as an agenda item to the 📝 [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1&tab=t.0#), if you would.
https://meet.meshery.io/dev

File: server/handlers/prometheus_handlers.go [hunk 1]
```diff
@@ -374,7 +375,11 @@ func (h *Handler) PrometheusQueryHandler(w http.ResponseWriter, req *http.Reques
 		http.Error(w, ErrPrometheusQuery(err).Error(), http.StatusInternalServerError)
 		return
 	}
-	_, _ = w.Write(data)
+
+	safeData := template.HTMLEscapeString(string(data))
+
+	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
+	_, _ = w.Write([]byte(safeData))
```
Comment (lekaf974) [inline server/handlers/prometheus_handlers.go:382]: Could this be wrap in a reusable function ?

**Review by lekaf974 — CHANGES_REQUESTED** [review]

**Comment by leecalcote** [comment]
We're almost there, @Sumitsh28 ...

File: server/handlers/prometheus_handlers.go (hunk 1 above)
Comment (Sumitsh28) [reply server/handlers/prometheus_handlers.go:382]: Yes, we can do it. If you want I can update the PR with the required changes.

Comment (lekaf974) [reply server/handlers/prometheus_handlers.go:382]: Yes, please

Comment (Sumitsh28) [reply server/handlers/prometheus_handlers.go]: Created a function in utils named WriteEscaped

**Review by lekaf974 — DISMISSED** [review]

File: server/handlers/grafana_handlers.go [hunk 2]
```diff
@@ -256,7 +257,10 @@ func (h *Handler) GrafanaQueryHandler(w http.ResponseWriter, req *http.Request,
 		http.Error(w, ErrGrafanaQuery(err).Error(), http.StatusInternalServerError)
 		return
 	}
-	_, _ = w.Write(data)
+	
+	if _, err := utils.WriteEscaped(w, data,""); err != nil {
+    h.log.Error(err)
```
Comment (lekaf974) [inline server/handlers/grafana_handlers.go:262]: identation looks weird here

File: server/handlers/grafana_handlers.go [hunk 3]
```diff
@@ -290,7 +294,10 @@ func (h *Handler) GrafanaQueryRangeHandler(w http.ResponseWriter, req *http.Requ
...
```
Comment (lekaf974) [inline server/handlers/grafana_handlers.go:299]: same here

**Comment by Sumitsh28** [comment]
Corrected indentation in both files

**Review by lekaf974 — APPROVED** [review]

**Comment by leecalcote** [comment]
Thanks, @Sumitsh28!
