### PR TITLE
(fix): fixed zIndex of Navbar 

### LINKED ISSUE #11321: [UI]: Overflow Issue in Navbar
### Current Behavior
Navbar does not ensure to stay on top of other elements, leading to a compromised user interface where the navbar is obscured by other page elements under certain conditions.

### Desired Behavior
The navbar should have a sufficient `zIndex` value to ensure it consistently stays on top of all other elements across the website, regardless of the user's actions or the page's state. 

### Possible Solution
Adjust the CSS for the navbar component, setting its `zIndex` to a high enough value (e.g., 1000 or higher) that ensures it will overlay all other page elements.

### Steps to reproduce

1) Navigate to the Lifecycle management dashboard.
2) Enable inspect mode by right-clicking on the page and selecting "Inspect" or pressing `Ctrl+Shift+I` (Windows/Linux) or `Cmd+Opt+I` (Mac).
3) Ensure the inspect mode tab is docked to the right side of the window.
4) Reduce the window size to mobile mode by shrinking the browser window.

### Environment

- Browser: Chrome
- Host OS: Mac
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker, Kubernetes

### ScreenRecording

https://github.com/user-attachments/assets/198618f9-cfc2-46d1-9415-ad8ad4e45f29

### Additional Resources
- [Contributor Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by senthil-athiban**
**Notes for Reviewers**

This PR fixes #11321

### Description

Added [standard zIndex](https://mui.com/material-ui/customization/default-theme/) for navbar.

### ScreenRecording

https://github.com/meshery/meshery/assets/93466587/e3b353b0-2d7c-4eda-8683-8c449714eb37

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/Header.js [hunk 1]
```diff
@@ -74,13 +74,13 @@ const styles = (theme) => ({
   appBarOnDrawerOpen: {
     backgroundColor: theme.palette.secondary.mainBackground,
     shadowColor: ' #808080',
-    zIndex: theme.zIndex.drawer + 1,
+    zIndex: 1100,
```
Comment (dragon-slayer875) [inline ui/components/Header.js:77]: We use an internal utility named `ziCalc` to set zIndex levels.
Would you mind using that instead of hardcoding 1100? :smile: 
This helps us to keep a more clear and easily recognizable track of zIndices.

Comment (senthil-k8s) [reply ui/components/Header.js:77]: thanks @dragon-slayer875, but the result is not as expected, problem occurs on other side. Would you clarify me, Do we need to pas any args in `ziCalc()` in our scenario

https://github.com/meshery/meshery/assets/93466587/a0a49d15-4d3a-46fa-bbc8-c98e3fc70ccb

Comment (dragon-slayer875) [reply ui/components/Header.js:77]: A numerical value sir. :smile:

Comment (senthil-k8s) [reply ui/components/Header.js:77]: @dragon-slayer875 , 'm surprised that removing the zIndex prop from the class works as expected. The default MUI navbar zIndex is applied without any hardcoded values or utils needed. Your suggestions please.

https://github.com/meshery/meshery/assets/93466587/0ef7ec0c-468d-4b89-8399-2850a474897c

Comment (senthil-k8s) [reply ui/components/Header.js]: @dragon-slayer875 , seems to be it doesn't affect any other dashboard. 

https://github.com/meshery/meshery/assets/93466587/5d2322df-2a67-4d20-bc76-a1bbb4394082

**Comment by Yashsharma1911** [comment]
Let's discuss this in today meshery dev meeting, please add this as agenda item here https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1

**Comment by leecalcote** [comment]
How'd we do in the meeting? Thumbs-up or more feedback offered?

**Comment by Ashparshp** [comment]
@senthil-k8s Could we discuss this issue during the Meshery dev meeting call? Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

**Comment by senthil-athiban** [comment]
@dragon-slayer875 Any update ?

**Comment by dragon-slayer875** [comment]
> @dragon-slayer875, any updates on these PRs? Thanks!

@senthil-athiban hello! As per Lee's comment above, we wanted to confirm what feedback (if any) was given at the last dev call. 
If not, I'll be merging this by EOD.

**Comment by senthil-athiban** [comment]
In Last dev meeting, we haven't discussed about this, because we focused on @innocentrda Troubleshoot meshery installation.

**Comment by senthil-athiban** [comment]
@dragon-slayer875 are we good to go, based on yesterday dev meeting feedback?

**Comment by dragon-slayer875** [comment]
Yes @senthil-athiban. Let's get this merged today.

**Review by dragon-slayer875 — APPROVED** [review]
