### PR TITLE
[mesheryctl] Move registry logger setup from initialisation function to `PersistentPreRun` of Registry command

### LINKED ISSUE #14334: failed to build since 0.8.51
```
  panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x1024cbd0c]
  
  goroutine 1 [running]:
  github.com/layer5io/meshery/mesheryctl/internal/cli/root/registry.setupRegistryLogger()
  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/registry/registry.go:65 +0x9c
  github.com/spf13/cobra.(*Command).preRun(...)
  	github.com/spf13/cobra@v1.9.1/command.go:1049
  github.com/spf13/cobra.(*Command).execute(0x1058db1a0, {0x1[400](https://github.com/Homebrew/homebrew-core/actions/runs/14326165935/job/40152028448?pr=218763#step:3:401)0ab4c00, 0x1, 0x1})
  	github.com/spf13/cobra@v1.9.1/command.go:959 +0x418
  github.com/spf13/cobra.(*Command).ExecuteC(0x1058db460)
  	github.com/spf13/cobra@v1.9.1/command.go:1148 +0x350
  github.com/spf13/cobra.(*Command).Execute(...)
  	github.com/spf13/cobra@v1.9.1/command.go:1071
  github.com/layer5io/meshery/mesheryctl/internal/cli/root.Execute()
  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/root.go:86 +0x58
  main.main()
  	github.com/layer5io/meshery/mesheryctl/cmd/mesheryctl/main.go:26 +0x1c
```

might relates to https://github.com/meshery/meshery/pull/13734

https://github.com/Homebrew/homebrew-core/pull/218763

### PR DESCRIPTION
**Pull request by riyaa14**
**Notes for Reviewers**

- This PR fixes #14334 

One potential solution is to move the `setupMeshkitLogger()` call to the `PersistentPreRun` of the specific command (`registry` command) where it's actually needed, instead of initialising it globally during the CLI setup. This would ensure that this function doesn't affect the whole CLI functionality.

## Tests
1. mesheryctl regsitry generate works as expected after this change.
2. Other commands apart from registry like - mesheryctl version work as expected.

### Before: Registry Logger setup on CLI initialization

Screenshot 2025-04-09 at 3 46 22 AM

### After: Registry Logger setup only when registry or its subcommands are invoked

Screenshot 2025-04-09 at 3 41 48 AM

----

Screenshot 2025-04-09 at 3 48 54 AM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [*] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/internal/cli/root/registry/registry.go [hunk 1]
```diff
@@ -43,6 +43,11 @@ var RegistryCmd = &cobra.Command{
 	Long:    `Manage the state and contents of Meshery’s internal registry of capabilities.`,
 	Example: `mesheryctl registry [subcommand]`,
 
+	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
+		setupRegistryLogger()
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/registry/registry.go:47]: Did not remember why we are not using the same logger used by other commands ?

**Comment by stefanb** [comment]
Applied the patch for testing to
* https://github.com/Homebrew/homebrew-core/pull/218763

File: mesheryctl/internal/cli/root/registry/registry.go (hunk 1 above)
Comment (riyaa14) [reply mesheryctl/internal/cli/root/registry/registry.go:47]: Before moving the registry utility functions to meshkit, I saw that a different Logger was being used which setup logging in some files as well as the terminal.

When utility functions were moved to meshkit, this Logger was shifted too to meshkit as it was being used in functions.

Now here, we can't use `utils.Log` that is used by other commands because
1. The Logger is needed in meshkit registry utility functions, and we can't directly use a Logger declared here in mesheryctl utils inside meshkit
2. `utils.Log` doesn't write to specific files that we setup in the RegistryLogger.

Comment (lekaf974) [reply mesheryctl/internal/cli/root/registry/registry.go:47]: Gotcha I remebmber we talk about it now

**Review by lekaf974 — APPROVED** [review]
LGTM

**Comment by vishalvivekm** [comment]
@riyaa14 
Thank you for your contributions! Let's discuss this today, during Meshery Development call at 9:00 AM CT | 7:30 PM IST. Add it as an agenda item to the 📝 [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1&tab=t.0#), if you would.
https://meet.meshery.io/dev
