### PR TITLE
[mesheryctl] Revert interactive prompt to classic y/n

### LINKED ISSUE #2099: [mesheryctl] revert interactive y/n `mesheryctl version` question
**Description**
```
➜  ~ mesheryctl version
Client Version: v0.4.15 	  GitSHA: 51ca056186a824ad1c2b1bf979b95bdc46978d34
Server Version: unavailable 	  GitSHA: unavailable

Unable to communicate with Meshery: Get http://localhost:9081/api/server/version: dial tcp [::1]:9081: connect: connection refused
Ensure that Meshery is available, see Meshery Documentation (https://docs.meshery.io) for more help.

Checking for latest version of Meshery....

v0.4.15 is not the latest Meshery release. Update to v0.4.27. Run `mesheryctl system update`
Use the arrow keys to navigate: ↓ ↑ → ←
? Would you like to upgrade to v0.4.27 now?(y/n):
  ▸ y
    n
```

**Expected Behavior**
The interactive y / n question is unexpected and not a universal user experience (not consistent with how users are prompted with y/n in other commands). User prompts should be consistent in style. Please update `mesheryctl version` to prompt with:

```
Would you like to upgrade to v0.4.27 now (y/n)? 
```

### PR DESCRIPTION
**Pull request by uds5501**
Signed-off-by: Uddeshya Singh <singhuddeshyaofficial@gmail.com>

**Description**
Reverts the interactive prompt to classic y/n form

This PR fixes #2099

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: handlers/server_spec_handler.go [hunk 1]
```diff
@@ -4,10 +4,10 @@ import (
 	"encoding/json"
 	"fmt"
 	"net/http"
+	"strings"
 
 	"github.com/layer5io/meshery/mesheryctl/pkg/utils"
 
-	"github.com/manifoldco/promptui"
```
Comment (kushthedude) [inline handlers/server_spec_handler.go:10]: We don't need this library, please run `go mod tidy` after the change to remove it from deps.

Comment (leecalcote) [reply handlers/server_spec_handler.go:10]: @uds5501 I went ahead and removed this unused package.

**Review by leecalcote — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]
