### PR TITLE
fix: migrate resource-table from datafetch wrapper function to rtk-query

### LINKED ISSUE #14696: [UI] Migrate ResourceTable component to rtk query from datafetch
### Current Behavior

Currently ResourceTable uses datafetch wrapper to show data instead of that we want to use rtk query  to fetch data.
### Desired Behavior

- Fetching data should be done using rtk query
### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by LibenHailu**
**Notes for Reviewers**
This change aims to migrate resource-table component to rtk query 
- This PR fixes #14696

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@LibenHailu 
Thank you for your contributions! Let's discuss this today, during Meshery Development call at 9:00 AM CT. Add it as an agenda item to the 📝 [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1&tab=t.0#), if you would. https://meet.meshery.io/dev

File: ui/components/DashboardComponent/resources/resources-table.js [hunk 1]
```diff
@@ -115,32 +116,39 @@ const ResourcesTable = (props) => {
...
-        if (query.resourceCategory && query.resourceName && res?.resources.length === 1) {
-          switchView(SINGLE_VIEW, res?.resources[0]);
-        }
-      },
-      handleError(ACTION_TYPES.FETCH_MESHSYNC_RESOURCES),
-    );
+    try {
+      const result = await dispatch(
+        api.endpoints.getMeshSyncResources.initiate(queryParams),
+      ).unwrap();
```
Comment (amitamrutiya) [inline ui/components/DashboardComponent/resources/resources-table.js:138]: there is one `initiateQuery` function here 

https://github.com/amitamrutiya/meshery/blob/master/ui/rtk-query/utils.js

use that.

**Review by amitamrutiya — CHANGES_REQUESTED** [review]

**Review by amitamrutiya — APPROVED** [review]
