### PR TITLE
fix: Workspace modal not rendering below 900px && Not able to open workspace in kanvas below 900px

### LINKED ISSUE #15317: [UI] Workspace modal not rendering below 900px && Not able to open workspace in kanvas below 900px
### Current Behavior

Bug-1:(not opeing in kanvas below 900px)

https://github.com/user-attachments/assets/5f6c5cdc-dac5-4eb3-b7d9-5014b01335a5

Bug-2:(not able to open-org switcher && flickering of workspace happens)

https://github.com/user-attachments/assets/10822306-b170-4010-8f51-aab0c8fe143e

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by FaheemOnHub**
- This PR fixes #15317 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/SpacesSwitcher/SpaceSwitcher.js [hunk 1]
```diff
@@ -30,6 +30,8 @@ import {
   useUpdateSelectedOrganizationMutation,
 } from '@/rtk-query/user';
 import { MobileOrgWksSwither } from './MobileViewSwitcher';
+import WorkspaceModal from './WorkspaceModal';
+import { WorkspaceModalContext } from '@/utils/context/WorkspaceModalContextProvider';
```
Comment (sudhanshutech) [inline ui/components/SpacesSwitcher/SpaceSwitcher.js:34]: @FaheemOnHub what does this context provider do , is it being use somewhere else too?

Comment (FaheemOnHub) [reply ui/components/SpacesSwitcher/SpaceSwitcher.js:34]: the workspace is used across the meshery ui , thats why it is a context.
