### PR TITLE
Fix Data Fetch and Logic from the server causing problems with pattern deployment

### LINKED ISSUE #3774: [UI] Pattern Deploy provides wrong progress output
#### Current Behavior

Pattern Deploy shows successful network result with status `200`, but UI is providing false errors. like this
image

The successful deploy can be checked by running: `kubectl get all -n test` or `kubectl get rolouts -n test`.

suggested by  @utkarsh-pro 

#### Desired Behavior

The wrong error output from UI should be fixed, and it should show successful response in UI

#### Environment

- Browser: Firefox
- Host OS: Linux
- Meshery Server Version: stable-5.23
- Meshery Client Version: stable-5.23
- Platform: Docker

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
**Description**

Earlier the data fetch was written like:
```js
 try {
          result = res.json();
 } catch(e){
          result = res.text();
  }
```

The `res.json()` returns promise which no way could the catch block runs until the promise is resolved thus creating other subsequent error mentioned in #3774 due to resolution in wrong `then...catch` block

2. Added a success snackbar for successful deployment

This PR fixes #3774

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/lib/data-fetch.js [hunk 1]
```diff
@@ -7,21 +7,25 @@ const dataFetch = (url, options = {}, successFn, errorFn) => {
   // setTimeout(() => controller.abort(), 10000); // nice to have but will mess with the load test
   fetch(url, options)
     .then(res => {
-      if (res.status === 401 || res.redirected){
-        if (window.location.host.endsWith('3000')){
+      if (res.status === 401 || res.redirected) {
+        if (window.location.host.endsWith('3000')) {
```
Comment (leecalcote) [inline ui/lib/data-fetch.js:11]: I recognize this isn't part of your changes, but can you confirm this logic is dealing with whether or not Meshery UI is running in development mode? If so, let's open an issue to track this mode globally. // @dhruv0000 @sudo-NithishKarthik

**Review by leecalcote — DISMISSED** [review]

**Review by leecalcote — APPROVED** [review]

File: ui/lib/data-fetch.js (hunk 1 above)
Comment (Abhishek-kumar09) [reply ui/lib/data-fetch.js:11]: Just checked it, UI dev server is loading gracefully. Refreshed UI lot of times on chrome browser seems to be loading efficiently. But still not sure that the issue with dev server is fully fixed.
