### PR TITLE
fix(ui): whitespace in context switcher

### LINKED ISSUE #5828: [UI] K8s Context Switcher: eliminate whitespace in context chip
#### Current Behavior
Unnecessary whitespace exists between the K8s logo and the context name.

#### Screenshot
Screen Shot 2022-07-15 at 3 07 07 PM

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by nishantwrp**
Signed-off-by: Nishant Mittal <mittalnishant14@outlook.com>

**Description**

This PR fixes #5828 

**Notes for Reviewers**
Here are the screenshots. 

**Before**
When meshsync is inactive
Screenshot 2022-07-17 at 1 15 09 AM

When meshsync is active
Screenshot 2022-07-17 at 1 15 45 AM

**After**
When meshsync is inactive
Screenshot 2022-07-17 at 1 09 30 AM

When meshsync is active
Screenshot 2022-07-17 at 1 09 59 AM

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/Header.js [hunk 1]
```diff
@@ -378,7 +378,7 @@ function K8sContextMenu({
                                 />
                               </BadgeAvatars> :
                               <Avatar src="/static/img/kubernetes.svg" className={classes.icon}
-                                style={operStatus ? { margin : 8 } : { opacity : 0.2, margin : 8 }}
```
Comment (nishantwrp) [inline ui/components/Header.js:381]: cc: @Abhishek-kumar09 since you added this margin. Wanted to make sure I didn't break the UI in any other case when this margin is needed.

**Review by Abhishek-kumar09 — APPROVED** [review]
LGTM

**Comment by Abhishek-kumar09** [comment]
Thanks @nishantwrp

**Comment by leecalcote** [comment]
Questionable work as always from @nishantwrp. 

_just kidding 😉 _

**Comment by nishantwrp** [comment]
@leecalcote sorry, didn't get you.

**Comment by leecalcote** [comment]
Not so subtle sarcasm.
