### PR TITLE
Fix prometheus and grafana discovery

### LINKED ISSUE #5967: [Server] Prometheus and Grafana Discovery
#### Current Behavior
Grafana and Prometheus being discovered and shown in Dashboard report, but not in Settings Metrics page.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by MUzairS15**
Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>

**Description**

This PR fixes #5967 
1.  Prometheus and Grafana discovery,
2. Missing hostname in connectivity test

https://user-images.githubusercontent.com/79860504/183157007-a5e860cb-b606-4bf1-8ff4-ed9393936bdb.mov

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Yay! They're back!

File: ui/components/DashboardComponent.js [hunk 1]
```diff
@@ -561,7 +561,7 @@ class DashboardComponent extends React.Component {
   handleGrafanaClick = () => {
     this.props.updateProgress({ showProgress : true });
     const self = this;
-    const { grafanaUrl } = this.state;
+    const { grafanaURL } = this.state.grafana;
```
Comment (leecalcote) [inline ui/components/DashboardComponent.js:564]: @MUzairS15 do you know the genesis of this bug?
