### PR TITLE
fix : Local Provider: Designs fail to load

### LINKED ISSUE #10626: [UI] Local Provider: Designs fail to load
### Current Behavior
On the Designs page, the following error occurs on load:

Screenshot 2024-03-27 at 8 51 50 AM

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Adarsh-jaiss**
**Notes for Reviewers**

This PR fixes #10626 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/MesheryPatterns.js [hunk 1]
```diff
@@ -336,7 +336,7 @@ function MesheryPatterns({
   const [search, setSearch] = useState('');
   const [sortOrder, setSortOrder] = useState('');
   const [count, setCount] = useState(0);
-  const [pageSize, setPageSize] = useState();
+  const [pageSize, setPageSize] = useState(0);
```
Comment (Yashsharma1911) [inline ui/components/MesheryPatterns.js:339]: Thankyou @Adarsh-jaiss this should fix issue with undefined, I think we should have 10 as a default pagesize
```suggestion
  const [pageSize, setPageSize] = useState(10);
```

**Review by Yashsharma1911 — CHANGES_REQUESTED** [review]
LGTM thankyou @Adarsh-jaiss

**Review by Yashsharma1911 — APPROVED** [review]
