### PR TITLE
[Server] Reject invalid performance test endpoint URLs

### LINKED ISSUE #18290: [Server] SMP performance test validator accepts invalid endpoint URLs
### Current Behavior
`SMPPerformanceTestConfigValidator` uses `url.Parse` to validate performance test endpoints, but `url.Parse` accepts many non-URL strings as relative paths without returning an error.

As a result, malformed endpoint values can pass validation and only fail later during execution.

### Expected Behavior
Performance test validation should reject endpoint values that are not valid absolute HTTP or HTTPS URLs.

Invalid endpoint configuration should fail fast during validation instead of surfacing later as runtime request errors.

### Screenshots/Logs
Relevant validator logic:

```go
// server/models/validators.go
for _, URL := range testClient.EndpointUrls {
	if _, err := url.Parse(URL); err != nil {
		return ErrValidURL
	}
}
```

`url.Parse` is too permissive for endpoint validation because strings like `not-a-url` parse successfully as relative references.

The validator already treats these values as concrete test endpoints:

```go
// server/models/validators.go
if len(testClient.EndpointUrls) < 1 {
	return ErrTestEndpoint
}
```

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
- 📺 [Self-paced Contributor Trainings](https://meshery.io/talks-and-trainings#trainings)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Manishnemade12**
**Notes for Reviewers**

- This PR fixes the SMP performance test validator so invalid endpoint strings like `not-a-url` are rejected during validation instead of slipping through to runtime.
- Scope is intentionally limited to `server/models/validators.go` and `server/models/validators_test.go`.
- This PR fixes #18290

**What changed**

- Replaced permissive endpoint parsing with stricter URL validation in `SMPPerformanceTestConfigValidator`.
- Added regression coverage for:
  - rejecting relative / malformed endpoint strings
  - accepting valid absolute endpoints

**Validation**

- Ran:
  `go test ./server/models -run '^TestSMPPerformanceTestConfigValidator' -count=1`

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Manishnemade12** [comment]
@lekaf974 can you please review this pr.

**Comment by Manishnemade12** [comment]
> The switch from `url.Parse` (which accepts almost anything) to `url.ParseRequestURI` + explicit scheme/host checks is exactly right. Tests cover both the reject and accept paths well. Consider converting to table-driven tests in the future for easier expansion, but the coverage is solid as-is.

Thanks for the detailed review and kind words! Glad the switch to `url.ParseRequestURI` with explicit scheme/host checks landed well.

Fully agree on the table-driven tests suggestion ,  it's a cleaner pattern and makes future expansion much easier. I'll go ahead and refactor the tests to that structure.

Thanks for feedback

File: server/models/validators_test.go [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+
+import (
+	"testing"
+
+	SMP "github.com/layer5io/service-mesh-performance/spec"
+)
+
+func TestSMPPerformanceTestConfigValidatorRejectsRelativeEndpoints(t *testing.T) {
+	perfTest := &SMP.PerformanceTestConfig{
+		Name:     "invalid-endpoint-test",
```
Comment (lekaf974) [inline server/models/validators_test.go]:
```suggestion
		Name:     "given invalid endpoint when SMPPerformanceTestConfigValidator then throw ErrValidURL",
```

File: server/models/validators_test.go [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+			{
+				LoadGenerator: FortioLG.Name(),
+				Protocol:      SMP.PerformanceTestConfig_Client_PROTOCOL_HTTP,
+				EndpointUrls:  []string{"not-a-url"},
+			},
+		},
+	}
+
+	err := SMPPerformanceTestConfigValidator(perfTest)
+	if err != ErrValidURL {
```
Comment (lekaf974) [inline server/models/validators_test.go]: use assert instead

File: server/models/validators_test.go [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+		t.Fatalf("expected ErrValidURL, got %v", err)
+	}
+}
+
+func TestSMPPerformanceTestConfigValidatorAcceptsAbsoluteEndpoints(t *testing.T) {
+	perfTest := &SMP.PerformanceTestConfig{
+		Name:     "valid-endpoint-test",
```
Comment (lekaf974) [inline server/models/validators_test.go]:
```suggestion
		Name:     "given valid endpoint when SMPPerformanceTestConfigValidator then assert err nil",
```

File: server/models/validators_test.go [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+			},
+			{
+				LoadGenerator: Wrk2LG.Name(),
+				Protocol:      SMP.PerformanceTestConfig_Client_PROTOCOL_TCP,
+				EndpointUrls:  []string{"tcp://127.0.0.1:8080"},
+			},
+		},
+	}
+
+	if err := SMPPerformanceTestConfigValidator(perfTest); err != nil {
```
Comment (lekaf974) [inline server/models/validators_test.go]: use assert

**Comment by Manishnemade12** [comment]
@lekaf974 done i addressed all comments and 
Refactored to a table-driven test for maintainability and easier extensibility.
Now covers absolute, relative, and empty endpoint cases for robust validation.

you can take review once

File: server/models/validators_test.go (hunk 2 above)
Comment (Manishnemade12) [reply server/models/validators_test.go]: done

File: server/models/validators_test.go (hunk 4 above)
Comment (Manishnemade12) [reply server/models/validators_test.go]: done, i used assert

File: server/models/validators_test.go [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+import (
+	"testing"
+
+	SMP "github.com/layer5io/service-mesh-performance/spec"
+)
+
+func TestSMPPerformanceTestConfigValidatorRejectsRelativeEndpoints(t *testing.T) {
+	perfTest := &SMP.PerformanceTestConfig{
+		Name:     "given invalid endpoint when SMPPerformanceTestConfigValidator then throw ErrValidURL",		Duration: "30s",
+		Clients: []*SMP.PerformanceTestConfig_Client{
```
[the remark this answers is not in the document]
Comment (lekaf974) [reply server/models/validators_test.go]: please address this comment

File: server/models/validators_test.go [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+			{
+				LoadGenerator: FortioLG.Name(),
+				Protocol:      SMP.PerformanceTestConfig_Client_PROTOCOL_HTTP,
+				EndpointUrls:  []string{"not-a-url", "/health", "health"},
+			},
+		},
+	}
+
+	       err := SMPPerformanceTestConfigValidator(perfTest)
+	       if err != ErrValidURL {
```
Comment (lekaf974) [inline server/models/validators_test.go]: use assert please

**Comment by Manishnemade12** [comment]
@lekaf974 I merged the two endpoint validator tests into a single table-driven test and removed the old functions.

File: server/models/validators_test.go (hunk 6 above)
Comment (Manishnemade12) [reply server/models/validators_test.go]: done , i did that

File: server/models/validators_test.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (Manishnemade12) [reply server/models/validators_test.go]: The file was not gofmt-formatted, so I ran gofmt to ensure it meets Meshery’s code style standards. The file is now properly formatted.

File: server/models/validators_test.go [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+)
+
+func TestSMPPerformanceTestConfigValidator(t *testing.T) {
+	cases := []struct {
+		name      string
+		config    *SMP.PerformanceTestConfig
+		wantError error
+	}{
+		{
+			name: "rejects invalid/relative endpoints",
```
Comment (lekaf974) [inline server/models/validators_test.go]: please keep naming given, when, then standard

This is helpful when it fails to quickly know what the test expected as input, what we are testing and the expected output without the need to read all inputs and outputs

**Comment by Manishnemade12** [comment]
@lekaf974 i changed test case names in TestSMPPerformanceTestConfigValidator to follow the "given, when, then" naming convention.

File: server/models/validators_test.go [hunk 8]
```diff
@@ -0,0 +1,67 @@
...
+		},
+	}
+
+	       for _, tc := range cases {
+		       t.Run(tc.name, func(t *testing.T) {
+			       err := SMPPerformanceTestConfigValidator(tc.config)
+			       if tc.wantError != nil {
+				       if !errors.Is(err, tc.wantError) {
+					       t.Errorf("expected error %v, got %v", tc.wantError, err)
+				       }
```
Comment (lekaf974) [inline server/models/validators_test.go]: we have a AsserErrorEqual method in utls package, please reuse it

Comment (Manishnemade12) [reply server/models/validators_test.go]: I first used AssertMeshkitErrorsEqual, but that imported utils, which creates an import cycle because utils already imports models.
To avoid this, I switched to local errors.Is(...) in the test.
This keeps the test simple and removes the dependency cycle.

**Comment by Manishnemade12** [comment]
@PragalvaXFREZ This PR has been approved by @lekaf974 , with small improvement -> reuse of the AssertErrorEqual method.
so I first used [AssertMeshkitErrorsEqual](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html), but that imported [utils](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html), which creates an import cycle because [utils](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) already imports [models](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html).  as result Golang Unit and Integration Tests started failing.
To avoid this, I switched to local [errors.Is(...)](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) in the test.
This keeps the test simple and removes the dependency cycle.

 Could you please review it at your convenience and proceed with merging if everything looks good

File: server/models/validators_test.go [hunk 9]
```diff
@@ -50,18 +50,17 @@ func TestSMPPerformanceTestConfigValidator(t *testing.T) {
...
-					       t.Errorf("expected no error, got %v", err)
-				       }
-			       }
-		       })
-	       }
+		for _, tc := range cases {
+			t.Run(tc.name, func(t *testing.T) {
+				err := SMPPerformanceTestConfigValidator(tc.config)
+				if tc.wantError != nil {
+					utils.AssertMeshkitErrorsEqual(t, err, tc.wantError)
```
Comment (lekaf974) [inline server/models/validators_test.go]: we must not add dependency from cli to server

PS: we have hard time to remove this dependency from cli to server already

Comment (lekaf974) [reply server/models/validators_test.go]: the best will be to move this test assertion in meshkit to reuse it in both components

Comment (Manishnemade12) [reply server/models/validators_test.go]: Thanks @lekaf974 for the feedback. I have addressed both concerns:
1. Removed the CLI utils dependency , now using only standard library errors.Is() for error comparison
2. Agree on moving AssertMeshkitErrorsEqual to meshkit for proper reuse across all components - that would be a great improvement for future maintainability.

**Comment by Manishnemade12** [comment]
@lekaf974 i Removed the CLI utils dependency , now using only standard library errors.Is() for error comparison .
 and also Agree on moving AssertMeshkitErrorsEqual to meshkit for proper reuse across all components - that would be a great improvement for future maintainability.
 
 so can you please review it now .

File: mesheryctl/pkg/utils/testing.go [hunk 10]
```diff
@@ -346,7 +346,7 @@ func formatToTabs(data string) string {
 	return s
 }
 
-// AssertMeshkitErrorsEqual compares  relevant fields of two meshkit errors
+// AssertMeshkitErrorsEqual compares relevant fields of two meshkit errors
 func AssertMeshkitErrorsEqual(t *testing.T, got, expected error) {
```
[the remark this answers is not in the document]
Comment (Manishnemade12) [reply mesheryctl/pkg/utils/testing.go:350]: @copilot apply changes based on [this feedback](https://github.com/meshery/meshery/pull/18291#discussion_r3054826698)
