### PR TITLE
fix: Update component and workspace command tests to get rid of golden files

### LINKED ISSUE #16735: [Server] Upgrade from meshkit v0.8.53 to v0.8.54 causes all mesheryctl golden file tests to fail
### Current Behavior

The upgrade from meshkit v0.8.53 to v0.8.54 causes all mesheryctl golden file tests to fail. The `Error()` method in meshkit v0.8.54 now appends metadata to error strings:

```
message | Short Description: X | Probable Cause: Y | Suggested Remediation: Z
```

This causes mismatches between the golden files (which expect plain messages) and the actual error output.

**Example failure:**
```
exp: "Please provide a model name. Usage: mesheryctl model search [query-text]"
got: "Please provide a model name. Usage: mesheryctl model search [query-text] | Short Description: Invalid Argument | Probable Cause: Invalid Argument | Suggested Remediation: Please check the arguments passed"
```

### Expected Behavior

Tests should pass. Either:
1. Golden files should be updated to match the new meshkit error format

### Screenshots/Logs

```bash

=== RUN   TestModelInit/model_init_no_model_name
Error: must provide only one argument: model name | Short Description: Error model init | Probable Cause: Error during run of model init command | Suggested Remediation: Ensure passing all params according to the command description
init_test.go:274:

        exp: "must provide only one argument: model name"

        got: "must provide only one argument: model name | Short Description: Error model init | Probable Cause: Error during run of model init command | Suggested Remediation: Ensure passing all params according to the command description"
```

### Environment

- **Host OS:** Linux
- **Platform:** N/A (unit tests)
- **Meshery Server Version:** N/A
- **Meshery Client Version:** N/A
- **meshkit version:** v0.8.56

### To Reproduce

1. Ensure `go.mod` has `github.com/meshery/meshkit v0.8.56`
2. Run `go test ./mesheryctl/internal/cli/root/model/... -v`

### Affected Tests

- `mesheryctl/internal/cli/root/model/build_test.go`
- `mesheryctl/internal/cli/root/model/init_test.go`
- `mesheryctl/internal/cli/root/model/search_test.go`
- Other tests comparing `err.Error()` against golden files

### Proposed Fix

Update all error golden files to include the new meshkit metadata format, or modify test utilities to normalize error strings before comparison.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
- 📺 [Self-paced Contributor Trainings](https://meshery.io/talks-and-trainings#trainings)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by lekaf974**
Signed-off-by: lekaf974 <matthieu.evrin@gmail.com>

**Notes for Reviewers**

- This PR **partially** fixes #16735

```
ok  	github.com/meshery/meshery/mesheryctl/internal/cli/root/workspaces	0.036s
```

```
ok      github.com/meshery/meshery/mesheryctl/internal/cli/root/components      0.057s
```

I also took time to remove no more required golden files and added some missing unit tests

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/pkg/utils/testing.go [hunk 1]
```diff
@@ -391,18 +395,29 @@ func InvokeMesheryctlTestListCommand(t *testing.T, updateGoldenFile *bool, cmd *
...
-					return
+					t.Fatal(err)
 				}
-				t.Fatal(err)
+				assert.Equal(t, reflect.TypeOf(err), reflect.TypeOf(tt.ExpectedError))
+				assert.Equal(t, errors.GetCode(err), errors.GetCode(tt.ExpectedError))
+				assert.Equal(t, errors.GetCause(err), errors.GetCause(tt.ExpectedError))
+				assert.Equal(t, errors.GetSDescription(err), errors.GetSDescription(tt.ExpectedError))
+				assert.Equal(t, errors.GetLDescription(err), errors.GetLDescription(tt.ExpectedError))
+				assert.Equal(t, errors.GetRemedy(err), errors.GetRemedy(tt.ExpectedError))
```
Comment (shri771) [inline mesheryctl/pkg/utils/testing.go:418]: Comparing just the error code and Long description should be sufficient here. As only the Long description varies between different error scenarios of same err code.

Comment (lekaf974) [reply mesheryctl/pkg/utils/testing.go:418]: We could review it later, I just wanted to validate this is working as expected.
