### PR TITLE
Fix Environment options update and undefined bug in connections

### LINKED ISSUE #9828: Environment not get updated asynchronously when a new env is created
### Current Behavior

We support of create a new environment when there is no particular env in options through autocomplete but the env doesn't get updated asynchronously and it gets notified as undefined

image

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Notes for Reviewers**

This PR fixes #9828 

Since due to rtk we fetch environments only once so when a new environment is created it was not updating in the options but getting assigned so it is fixed using updating the environments parallelly when a new environment created and also fix the `undefined environment get saved` bug due to wrong value passed

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/connections/index.js [hunk 1]
```diff
@@ -263,9 +276,10 @@ function Connections(props) {
       .unwrap()
       .then((resp) => {
         notify({
-          message: `Environment: ${resp.Name} saved`,
+          message: `Environment: ${resp.name} saved`,
```
Comment (leecalcote) [inline ui/components/connections/index.js:279]:
```suggestion
          message: `Environment "${resp.name}" updated`,
```

**Comment by leecalcote** [comment]
How urgent is this bug?

File: ui/components/connections/index.js (hunk 1 above)
Comment (theBeginner86) [reply ui/components/connections/index.js:279]: This message is for creating the env (reference: https://github.com/meshery/meshery/pull/9831/files#diff-758de2b85e43b78da1cb737ebe181174f2825226d111eff469ded13847a4e062R269), so I believe we should have `saved`. Though we can update to `created` if that sounds more appropriate.

**Review by theBeginner86 — APPROVED** [review]
LGTM

File: ui/components/connections/index.js (hunk 1 above)
Comment (sudhanshutech) [reply ui/components/connections/index.js:279]: yes, created sounds more appropriate i guess
