### PR TITLE
[mesheryctl] Add GET request step in HealthCheck

### LINKED ISSUE #3434: [mesheryctl] Fix `IsMesheryRunning()` for locally running meshery
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Currently many commands fail to execute because the function fails to detect if meshery is running locally or not.

#### Desired Behavior

It should detect, ofcourse!
Send a GET request to http://localhost:9081/api/version ? If the response is 200 then it is running and reachable or else it is not. and that means Meshery is might be running local

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by alphaX86**
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

**Description**
This PR adds a GET request step in process to check if Meshery is running or not

This PR fixes #3434 

**Notes for Reviewers**
Tested on Linux (Ubuntu) no errors caught so far. If any changes needed, report them so that I can fix it

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by alphaX86** [comment]
Oh my bad.... :) fixing lint issues

**Comment by alphaX86** [comment]
@piyushsingariya this works only if port is 9081, so if a user has other port assigned by changing config, then how we can check and change the port?

**Comment by piyushsingariya** [comment]
@alphaX86 `make run-local` and `make run-fast` doesn't fetch the port from config.yaml, in case of these commands it is hardcoded to run meshery on port 9081.

**Comment by alphaX86** [comment]
Agreed, I'm asking in general though actually

File: mesheryctl/pkg/utils/healthcheck.go [hunk 1]
```diff
@@ -114,6 +115,12 @@ func parseKubectlShortVersion(version string) ([3]int, error) {
 
 // IsMesheryRunning checks if the meshery server containers are up and running
 func IsMesheryRunning(currPlatform string) (bool, error) {
+	resp, err := http.Get("http://localhost:9081/api/server/version")
+	// Port number is subject to change depending on user's configuration on config.yaml
+
+	if resp != nil {
```
Comment (piyushsingariya) [inline mesheryctl/pkg/utils/healthcheck.go:121]: Better to check resp.StatusCode==200!!

File: mesheryctl/pkg/utils/healthcheck.go [hunk 2]
```diff
@@ -155,6 +162,10 @@ func IsMesheryRunning(currPlatform string) (bool, error) {
 		}
 	}
 
+	if err != nil {
+		return false, errors.Wrap(err, "Meshery not running locally")
+	}
+
```
Comment (piyushsingariya) [inline mesheryctl/pkg/utils/healthcheck.go:168]: No need to add this thing, we are returning False status in the next line.

**Review by piyushsingariya — CHANGES_REQUESTED** [review]

File: mesheryctl/pkg/utils/healthcheck.go (hunk 2 above)
Comment (alphaX86) [reply mesheryctl/pkg/utils/healthcheck.go:168]: Agreed but that Golang rules... 🙂 Once declared, the variable has to be used right?

File: mesheryctl/pkg/utils/healthcheck.go (hunk 1 above)
Comment (alphaX86) [reply mesheryctl/pkg/utils/healthcheck.go:121]: Got it 👍

File: mesheryctl/pkg/utils/healthcheck.go [hunk 3]
```diff
@@ -114,6 +115,12 @@ func parseKubectlShortVersion(version string) ([3]int, error) {
 
 // IsMesheryRunning checks if the meshery server containers are up and running
 func IsMesheryRunning(currPlatform string) (bool, error) {
+	resp, err := http.Get("http://localhost:9081/api/server/version")
```
Comment (piyushsingariya) [inline mesheryctl/pkg/utils/healthcheck.go:118]:
```suggestion
	resp, _ := http.Get("http://localhost:9081/api/server/version")
```
Mark it like this.

Comment (piyushsingariya) [reply mesheryctl/pkg/utils/healthcheck.go:118]: Also, add a comment above this
// Checking if Meshery is running with "make run-local" or "make run-fast"

**Review by piyushsingariya — CHANGES_REQUESTED** [review]

File: mesheryctl/pkg/utils/healthcheck.go (hunk 3 above)
Comment (piyushsingariya) [reply mesheryctl/pkg/utils/healthcheck.go:118]: add a comment over this,
// checking if meshery is running with "make run-local" or "make run-fast"

Comment (alphaX86) [reply mesheryctl/pkg/utils/healthcheck.go:118]: Hmm alright! That will do 👍

File: mesheryctl/pkg/utils/healthcheck.go [hunk 4]
```diff
@@ -115,10 +115,10 @@ func parseKubectlShortVersion(version string) ([3]int, error) {
 
 // IsMesheryRunning checks if the meshery server containers are up and running
 func IsMesheryRunning(currPlatform string) (bool, error) {
-	resp, err := http.Get("http://localhost:9081/api/server/version")
-	// Port number is subject to change depending on user's configuration on config.yaml
+	resp, _ := http.Get("http://localhost:9081/api/server/version")
+	// Checking if Meshery is running with "make run-local" or "make run-fast"
```
Comment (piyushsingariya) [inline mesheryctl/pkg/utils/healthcheck.go:119]: shift it above http.GET

**Comment by alphaX86** [comment]
This is new! 👀 @piyushsingariya and @navendu-pottekkat the CI action reports as invalid memory reference... Any ideas on how to fix it?

File: mesheryctl/pkg/utils/healthcheck.go (hunk 4 above)
Comment (alphaX86) [reply mesheryctl/pkg/utils/healthcheck.go:118]: Done

**Comment by alphaX86** [comment]
Totally weird 👀 even after changes... seems I need to test it again

File: mesheryctl/pkg/utils/healthcheck.go [hunk 5]
```diff
@@ -114,6 +115,12 @@ func parseKubectlShortVersion(version string) ([3]int, error) {
 
 // IsMesheryRunning checks if the meshery server containers are up and running
 func IsMesheryRunning(currPlatform string) (bool, error) {
+	// Checking if Meshery is running with "make run-local" or "make run-fast"
+	resp, _ := http.Get("http://localhost:9081/api/server/version")
+
+	if resp.StatusCode == 200 {
```
Comment (piyushsingariya) [inline mesheryctl/pkg/utils/healthcheck.go:121]:
```suggestion
	if resp != nil && resp.StatusCode == 200 {
```
This is the nil reference thing.

File: mesheryctl/pkg/utils/healthcheck.go [hunk 6]
```diff
@@ -114,6 +115,12 @@ func parseKubectlShortVersion(version string) ([3]int, error) {
 
 // IsMesheryRunning checks if the meshery server containers are up and running
 func IsMesheryRunning(currPlatform string) (bool, error) {
+	// Checking if Meshery is running with "make run-local" or "make run-fast"
+	resp, _ := http.Get("http://localhost:9081/api/server/version")
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/healthcheck.go:119]: The hostname and port cannot be hardcoded, but must use a central reference for these values.

**Review by leecalcote — CHANGES_REQUESTED** [review]

File: mesheryctl/pkg/utils/healthcheck.go (hunk 6 above)
Comment (piyushsingariya) [reply mesheryctl/pkg/utils/healthcheck.go:119]: @leecalcote Check here https://github.com/meshery/meshery/blob/master/Makefile#L66

Comment (alphaX86) [reply mesheryctl/pkg/utils/healthcheck.go:119]: @leecalcote that's what I felt when I saw this, on public version, the port number may tend to change depending on user config. But here we check locally using `make run-local` or `make run-fast` (which works only on port 9081 or desired port)

IDK if it's ok for now

Comment (leecalcote) [reply mesheryctl/pkg/utils/healthcheck.go:119]: Users don't deploy using the Makefile. The hostname and port cannot be hardcoded, but must use a central reference for these values.

Comment (alphaX86) [reply mesheryctl/pkg/utils/healthcheck.go:119]: Agreed, so à placeholder variable then in this case?

Comment (piyushsingariya) [reply mesheryctl/pkg/utils/healthcheck.go:119]: @leecalcote this is being added for a specific case i.e. Development Mode of Meshery Server.

If some developer made some changes in server-side and is testing out a mesheryctl command (e.g. `mesheryctl system login`) which needs some confirmation that IsMesheryRunning(), which will eventually fail because of the only platform based checking and it won't possible to test the command with new changes in server. that is why the hardcoded part.

Comment (alphaX86) [reply mesheryctl/pkg/utils/healthcheck.go:119]: So..... are we good to go or still needs to be looked on this?

**Comment by alphaX86** [comment]
It's been a week... Can anyone say if this PR is good or still has a conflict?

**Comment by piyushsingariya** [comment]
> It's been a week... Can anyone say if this PR is good or still has a conflict?

@leecalcote @navendu-pottekkat

**Comment by alphaX86** [comment]
Rebasing is really a problem kind :/

File: mesheryctl/pkg/utils/healthcheck.go (hunk 6 above)
Comment (leecalcote) [reply mesheryctl/pkg/utils/healthcheck.go:119]: Unless the hardcoded value used in this check only applies to developers who are compiling `mesheryctl` and is not enforced for users who are running Meshery at an unknown endpoint (a dynamically defined endpoint), no, we cannot proceed until hardcoded `localhost` is removed.

Comment (alphaX86) [reply mesheryctl/pkg/utils/healthcheck.go:119]: OK........... Makes sense at first look at the problem. So the dynamic way then :)

**Comment by alphaX86** [comment]
I have added the variables which will extract the URL endpoint from config file and tested it. Worked pretty much

**Comment by alphaX86** [comment]
Is this PR good to go? Or still needs some changes?

**Review by piyushsingariya — APPROVED** [review]

File: mesheryctl/pkg/utils/healthcheck.go [hunk 7]
```diff
@@ -114,6 +118,23 @@ func parseKubectlShortVersion(version string) ([3]int, error) {
...
 // IsMesheryRunning checks if the meshery server containers are up and running
 func IsMesheryRunning(currPlatform string) (bool, error) {
+	// Get viper instance used for context to extract the endpoint from config file
+	mctlCfg, _ := config.GetMesheryCtl(viper.GetViper())
+
+	currCtx, _ := mctlCfg.GetCurrentContext()
+
+	urlEndpoint := currCtx.GetEndpoint()
+
+	urlTest := urlEndpoint + "/api/server/version"
```
Comment (piyushsingariya) [inline mesheryctl/pkg/utils/healthcheck.go:128]:
```suggestion
	urlTest := urlEndpoint + "/api/system/version"
```
Switch it to system, we are switching the URL in another PR.

**Review by piyushsingariya — CHANGES_REQUESTED** [review]

File: mesheryctl/pkg/utils/healthcheck.go (hunk 7 above)
Comment (alphaX86) [reply mesheryctl/pkg/utils/healthcheck.go:128]: Oh ok then! 👍

Comment (alphaX86) [reply mesheryctl/pkg/utils/healthcheck.go]: It's resolved

**Review by piyushsingariya — APPROVED** [review]

File: mesheryctl/pkg/utils/healthcheck.go [hunk 8]
```diff
@@ -114,6 +118,23 @@ func parseKubectlShortVersion(version string) ([3]int, error) {
...
 // IsMesheryRunning checks if the meshery server containers are up and running
 func IsMesheryRunning(currPlatform string) (bool, error) {
+	// Get viper instance used for context to extract the endpoint from config file
+	mctlCfg, _ := config.GetMesheryCtl(viper.GetViper())
+
+	currCtx, _ := mctlCfg.GetCurrentContext()
+
+	urlEndpoint := currCtx.GetEndpoint()
+
+	urlTest := urlEndpoint + "/api/system/version"
```
Comment (leecalcote) [inline mesheryctl/pkg/utils/healthcheck.go:128]: Looking real good, @alphaX86!

**Review by leecalcote — APPROVED** [review]
