### PR TITLE
Import using url - Patterns and Filters

### LINKED ISSUE #4208: [UI] Import using URL in Patterns and Filters is not working as expected
#### Current Behavior
Import by URL feature in patterns and filters in working uploading the data in the URL. 

#### Desired Behavior
Should display the contents of the URL 

#### Environment

- Browser: Chrome 
- Host OS: Mac 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by meghanacosmos**
Signed-off-by: Meghana-12 <meghana.cosmos@gmail.com>

**Description**

This PR fixes #4208

**Notes for Reviewers**
Tested with samples: 
**Patterns:** https://raw.githubusercontent.com/service-mesh-patterns/service-mesh-patterns/master/samples/IstioFilterPattern 
**Filters:** https://github.com/layer5io/image-hub/raw/master/rate-limit-filter/pkg/rate_limit_filter_bg.wasm

It's uploading the contents of the Patterns sample but it's not working with the Filters sample. The sample filter URL triggers file download and I'm not sure how to handle that.  

I was getting errors while committing so I had to fix the formatting issue in `Accordion.js` file.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/Filters.js [hunk 1]
```diff
@@ -233,12 +233,13 @@ function MesheryFilters({
...
 
-    if (type === "upload") {
+    if (type === "upload" || type === 'urlupload') {
+      const body = type==="upload" ? JSON.stringify({ filter_data : { filter_data : data }, save : true }) : JSON.stringify({ url : data, save : true });
       dataFetch(
         `/api/filter`,
         { credentials : "include",
           method : "POST",
-          body : JSON.stringify({ filter_data : { filter_file : data }, save : true }), },
+          body : body, },
```
Comment (bariqhibat) [inline ui/components/Filters.js:242]: nitpick: this can be shortened to `body` only

File: ui/components/Filters.js [hunk 2]
```diff
@@ -233,12 +233,13 @@ function MesheryFilters({
       );
     }
 
-    if (type === "upload") {
+    if (type === "upload" || type === 'urlupload') {
+      const body = type==="upload" ? JSON.stringify({ filter_data : { filter_data : data }, save : true }) : JSON.stringify({ url : data, save : true });
```
Comment (bariqhibat) [inline ui/components/Filters.js:237]: This is good but I think it'd be better if we can implement it with the Builder design pattern in mind, like
```javascript
let body = { save: true }

if (type === "upload") {
  body = { ...body, filter_data: {filter_data: data}}
}
if (type === "urlupload") {
  body = { ...body, url: data }
}
```
What do you think? It might be an overkill

**Review by bariqhibat — COMMENTED** [review]
Good work Meghana! Just made a few comments

File: ui/components/Filters.js (hunk 2 above)
Comment (Meghana-12) [reply ui/components/Filters.js:237]: Haha, this looks better tbh! Will update the PR.

**Comment by Meghana-12** [comment]
Thanks for the review @bariqhibat :D

File: ui/components/Filters.js (hunk 2 above)
Comment (Meghana-12) [reply ui/components/Filters.js:237]: This looks better tbh, will update the PR!

**Comment by leecalcote** [comment]
@Meghana-12 how far away are you from a final update on this PR?

**Comment by Meghana-12** [comment]
Will update the PR by tonight!

**Comment by leecalcote** [comment]
Merge conflict!

**Comment by Meghana-12** [comment]
Ahhhh! Will fix it tonight!

**Review by leecalcote — APPROVED** [review]
I think that we're good to go here....
