### PR TITLE
Changed output status for system context

### LINKED ISSUE #17201: [mesheryctl] e2e add tests for context subcommand
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

Some tests are failing

### Desired Behavior

Fix the failing tests

### Mockups

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- ⌨️ [Meshkit errors guide](https://docs.meshery.io/project/contributing/contributing-error)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)
- 📺 [Self-paced Contributor Trainings](https://meshery.io/talks-and-trainings#trainings)

### PR DESCRIPTION
**Pull request by DharunMR**
This PR fix #17201 

**Notes for Reviewers**

```bash
mesheryctl system context view --context <invalid-context>
```

this command should fail but it is not
Screenshot_2026-01-28_14 30 30

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: mesheryctl/internal/cli/root/system/context_test.go [hunk 1]
```diff
@@ -53,6 +53,15 @@ func TestViewContextCmd(t *testing.T) {
 			SystemCmd.SetOut(b)
 			SystemCmd.SetArgs(tt.Args)
 			err := SystemCmd.Execute()
+			if tt.Name == "Error for viewing a non-existing context" {
+				if err == nil {
+					t.Fatalf("expected error, got nil")
+				}
+
+				assert.Contains(t, err.Error(), `context "local3" does not exist`)
+				assert.Contains(t, err.Error(), `mesheryctl system context create local3`)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context_test.go]: this is not manageable, you need to introduce a field for errors.

ex: https://github.com/meshery/meshery/blob/4cc42469f036cbb2251053fe5248a5fc2b779057/mesheryctl/internal/cli/root/model/search_test.go#L33

File: mesheryctl/internal/cli/root/system/context.go [hunk 2]
```diff
@@ -323,8 +323,10 @@ mesheryctl system context view --all
 
 		contextData, ok := configuration.Contexts[currContext]
 		if !ok {
-			log.Printf("context \"%s\" doesn't exists, run the following to create:\n\nmesheryctl system context create %s", currContext, currContext)
-			return nil
+			return fmt.Errorf(
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context.go]: This needs to be a meshkit error

**Comment by lekaf974** [comment]
@DharunMR please can you ensure to have an issue before create a PR and thank you to start working on this.

**Comment by DharunMR** [comment]
@lekaf974  I'm bit confused whether this is the right approach or not.

File: mesheryctl/internal/cli/root/system/context_test.go [hunk 3]
```diff
@@ -51,10 +52,18 @@ func TestViewContextCmd(t *testing.T) {
...
-				t.Error(err)
+
+			if tt.ExpectError {
+				if err == nil {
+					t.Fatalf("expected error, got nil")
+				}
+			} else {
+				if err != nil {
+					t.Fatal(err)
+				}
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context_test.go]:
```suggestion
			if tt.ExpectError {
				if err == nil {
					t.Fatalf("expected error, got nil")
				}
				// Error needs to be validated
			}
			
			if err != nil {
				t.Fatal(err)
```

File: mesheryctl/internal/cli/root/system/context_test.go [hunk 4]
```diff
@@ -35,6 +35,7 @@ func TestViewContextCmd(t *testing.T) {
 			Name:             "Error for viewing a non-existing context",
 			Args:             []string{"context", "view", "local3"},
 			ExpectedResponse: "view.notexist.golden",
+			ExpectError:      true,
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context_test.go:40]: we want to validate return error type as well, please check other existing example of implementation

File: mesheryctl/internal/cli/root/system/context.go [hunk 5]
```diff
@@ -323,8 +323,14 @@ mesheryctl system context view --all
 
 		contextData, ok := configuration.Contexts[currContext]
 		if !ok {
-			log.Printf("context \"%s\" doesn't exists, run the following to create:\n\nmesheryctl system context create %s", currContext, currContext)
-			return nil
+			return utils.ErrInvalidArgument(
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context.go]: ErrInvalidArgument looks not to be appropriate here but it needs a ErrContextNotExists instead

**Review by lekaf974 — COMMENTED** [review]
Added some feedback

File: mesheryctl/internal/cli/root/system/testdata/context/view.nonexist.golden [hunk 6]
```diff
@@ -1,3 +1,3 @@
 context "local3" doesn't exists, run the following to create:
```
Comment (DharunMR) [inline mesheryctl/internal/cli/root/system/testdata/context/view.nonexist.golden]: since we use AssertMeshkitErrorsEqual, view.nonexist.golden file is not required

**Comment by DharunMR** [comment]
@lekaf974 made the changes

File: mesheryctl/internal/cli/root/system/context_test.go
Comment (lekaf974) [inline mesheryctl/internal/cli/root/system/context_test.go:1]: Now you don't test cases wihtout Error, any reason why ?

**Comment by lekaf974** [comment]
what is the output of e2e tests now ?

**Comment by DharunMR** [comment]
@lekaf974

i've changed the output according to this pr , e2e test will break now but after this pr got merged it will succeed

**Comment by lekaf974** [comment]
> @lekaf974
> 
> i've changed the output according to this pr , e2e test will break now but after this pr got merged it will succeed

Can you copy paste the output of the e2e from your branch please ?

**Comment by DharunMR** [comment]
@lekaf974 

01-system-context.bats
 ✓ given a valid context-name is provided as an argument when running mesheryctl system context create then the context will be created
 ✓ given a already existing context-name is provided as an argument when running mesheryctl system context create then the duplication error message displays
 ✓ given no context-name as an argument when running mesheryctl system context create then the error message displays
 ✓ given no url as an argument when running mesheryctl system context create --url then the error message displays
 ✓ given a valid url as an argument when running mesheryctl system context create --url then the context will be created
 ✓ given a invalid url as an argument when running mesheryctl system context create --url then the error message displays
 ✓ given all required arguments with --set flag when running mesheryctl system context create --url --set then the new context will be created and set it as current context
 ✓ given an --all flag to view when running mesheryctl system context view displays all the context with it's details
 ✓ running mesheryctl system context view displays the current context
 ✓ given no context-name as an argument when running mesheryctl system context view --context then the error message displays
 ✗ given an invalid context-name as an argument when running mesheryctl system context view --context then the error message displays
   (from function `assert_failure' in file helpers/bats-libs/bats-assert/src/assert_failure.bash, line 71,
    in test file 001-system/01-system-context.bats, line 131)
     `assert_failure' failed
   
   -- command succeeded, but it was expected to fail --
   output (5 lines):
     Missing Meshery config file.
     Default config file created at /tmp/tmp.KxM6yJF86Z/.meshery/config.yaml
     context "foo" doesn't exists, run the following to create:
   
     mesheryctl system context create foo
   --
   
 ✓ given a valid context-name as an argument when running mesheryctl system context view --context then it displays the detailed context
 ✓ running mesheryctl system context list displays all the available context
 ✓ given invalid context-name as an argument when running mesheryctl system context switch then the error message displays
 ✓ given no context-name as an argument when running mesheryctl system context switch then the error message displays
 ✓ given a valid context-name as an argument when running mesheryctl system context switch then the current context will switch to specified context
 ✓ given no context-name as an argument when running mesheryctl system context delete then the error message displays
 ✓ given an invalid context-name as an argument when running mesheryctl system context delete then the error message displays
 ✗ given a valid context-name as an argument when running mesheryctl system context delete then the specified context will be deleted
   (from function `assert_failure' in file helpers/bats-libs/bats-assert/src/assert_failure.bash, line 71,
    in test file 001-system/01-system-context.bats, line 215)
     `assert_failure' failed
   
   -- command succeeded, but it was expected to fail --
   output (3 lines):
     context "example-context" doesn't exists, run the following to create:
   
     mesheryctl system context create example-context
   --
   

19 tests, 2 failures

**Comment by lekaf974** [comment]
please fix the failing tests

**Comment by DharunMR** [comment]
done 👍🏻
