### PR TITLE
[UI] fix continuous subscription initialization

### LINKED ISSUE #4025: [UI] Dashboard Crashes in v0.5.50
#### Current Behavior
Screen Shot 2021-08-29 at 9 43 17 AM
Screen Shot 2021-08-29 at 9 44 43 AM

#### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: stable-v0.5.50
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by bariqhibat**
Signed-off-by: Bariq <bariqhibat@gmail.com>

**Description**

This PR fixes #4025

**Notes for Reviewers**
Previously, subscription initialization is called everytime new data is coming. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/graphql/subscriptions/ServiceMeshSubscription.js [hunk 1]
```diff
@@ -4,23 +4,34 @@ import { requestSubscription } from "react-relay";
...
+    subscription : dataPlaneSubscription,
+    variables : {
+      filter : variables,
+    },
+    onNext : (dataRes) => {
+      if (controlRes) dataCB(controlRes, dataRes)
+    },
+    onError : (error) => {
+      if (controlRes) dataCB(controlRes, null)
+      console.log(`An error occured:`, error)
```
Comment (leecalcote) [inline ui/components/graphql/subscriptions/ServiceMeshSubscription.js:33]: Let’s examine what we might want to let the user know in order to have them troubleshoot the situation.

**Review by leecalcote — APPROVED** [review]
