### PR TITLE
[mesheryctl] system context list: improve msg for listing missing contexts

### LINKED ISSUE #2994: [mesheryctl] system context list: presents error, not info when missing contexts
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
```
 $ mesheryctl system context list
Error: no available contexts
```

#### Desired Behavior
```
 $ mesheryctl system context list
No contexts available. Use `mesheryctl system context create <name> to create a new Meshery deployment context.
```

#### Environment
No contexts present.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by leecalcote**
**Description**

This PR fixes #2994

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by metonymic-smokey** [comment]
LGTM @leecalcote !

**Comment by leecalcote** [comment]
Thanks much, @metonymic-smokey

File: mesheryctl/internal/cli/root/system/context/list.go [hunk 1]
```diff
@@ -23,7 +22,9 @@ var listContextCmd = &cobra.Command{
 		}
 		var contexts = configuration.Contexts
 		if contexts == nil {
-			return errors.New("no available contexts")
+			// return errors.New("no available contexts")
+			log.Print("No contexts available. Use `mesheryctl system context create <name>` to create a new Meshery deployment context.\n")
```
Comment (navendu-pottekkat) [inline mesheryctl/internal/cli/root/system/context/list.go:26]: `log.Error` ?
