### PR TITLE
[UI] Fixed the code mirror bug of filters page

### LINKED ISSUE #6842: [UI] Back Content of filter card takes large width
#### Current Behavior

On clicking the filter card, When back content appears. It expands and takes very large width.

https://user-images.githubusercontent.com/103871275/211006127-d74c91e1-a9e6-4211-a7d8-ef80e3c80d5c.mp4

#### Desired Behavior

Back content should not expand.

https://user-images.githubusercontent.com/103871275/211006226-e8f75cab-ad70-4147-bed5-2267a2806109.mp4

#### Environment

- Browser: Firefox
- Host OS: Linux
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by partik03**
**Notes for Reviewers**

This PR fixes #6842 
**Before** 

https://user-images.githubusercontent.com/99184676/211163853-21066901-8c50-4879-84c8-db1ea7e7553b.mp4

**After**

https://user-images.githubusercontent.com/99184676/211163859-c922a35d-dff7-4407-ae9d-13f658b32717.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by partik03** [comment]
@Chadha93 please review it

File: ui/components/ConfirmationModal.js [hunk 1]
```diff
@@ -185,6 +185,7 @@ function ConfirmationMsg(props) {
   },[selectedK8sContexts]);
 
   const handleTabValChange = (event, newVal) => {
+    console.log(newVal);
```
Comment (harkiratsm) [inline ui/components/ConfirmationModal.js:188]: Can you remove the log.

**Review by Chadha93 — APPROVED** [review]
LGTM, restarted a check.
