### PR TITLE
[mesheryctl] Fix adapter deploy and validate commands ignoring errors in PreRunE

### LINKED ISSUE #11320: [mesheryctl] `adapter deploy` and `adapter validate` logs
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

When we run `mesheryctl mesh deploy linkered` logs `Adapter for required mesh not found` but it says `deployed successfully`.
### Screenshots/Logs

```
./mesheryctl mesh deploy linkerd
Adapter for required mesh not found
Verifying prerequisites...
Adapter for required mesh not found

LINKERD infrastructure deployed successfully
```
### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by kami922**
## Description

Fixes #11320

`adapter deploy` and `adapter validate` were logging errors in `PreRunE`
but returning `nil`, causing cobra to proceed to `RunE` regardless of
failure. This resulted in misleading output like "deployed successfully"
even when prerequisites failed.

Additionally, `validate` could panic with a nil pointer dereference if
`GetSessionData` failed, as `prefs` would be nil but still accessed.

## Changes

- `adapter/deploy.go`: return errors from `GetMesheryCtl` and `validateAdapter` in `PreRunE`
- `adapter/validate.go`: return errors from `GetMesheryCtl`, `GetSessionData` (also prevents nil pointer crash on `prefs.MeshAdapters`), and `validateAdapter` in `PreRunE`

## References
- https://docs.meshery.io/project/contributing
- https://docs.meshery.io/reference/mesheryctl/adapter

## Signed Commits
- [x] Yes, I signed my commits (`git commit -s`)

### CODE REVIEW

**Comment by kami922** [comment]
the tests are passing I will look into the code requests by gemini
image

File: mesheryctl/internal/cli/root/adapter/deploy.go [hunk 1]
```diff
@@ -55,13 +55,13 @@ mesheryctl adapter deploy linkerd --watch
 			mctlCfg, err := config.GetMesheryCtl(viper.GetViper())
 			if err != nil {
 				utils.Log.Error(err)
-				return nil
+				return err
 			}
 
 			if err = validateAdapter(mctlCfg, meshName); err != nil {
 				// ErrValidatingAdapter
 				utils.Log.Error(err)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/adapter/deploy.go]:
```suggestion
```

File: mesheryctl/internal/cli/root/adapter/validate.go [hunk 2]
```diff
@@ -61,12 +61,13 @@ mesheryctl adapter validate istio --adapter meshery-istio --spec smi
 		mctlCfg, err := config.GetMesheryCtl(viper.GetViper())
 		if err != nil {
 			utils.Log.Error(err)
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/adapter/validate.go]:
```suggestion
```

File: mesheryctl/internal/cli/root/adapter/validate.go [hunk 3]
```diff
@@ -61,12 +61,13 @@ mesheryctl adapter validate istio --adapter meshery-istio --spec smi
...
-			return nil
+			return err
 		}
 
 		prefs, err := utils.GetSessionData(mctlCfg)
 		if err != nil {
 			utils.Log.Error((ErrGettingSessionData(err)))
+			return err
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/adapter/validate.go]:
```suggestion
			return ErrGettingSessionData(err)
```

File: mesheryctl/internal/cli/root/adapter/validate.go [hunk 4]
```diff
@@ -79,6 +80,7 @@ mesheryctl adapter validate istio --adapter meshery-istio --spec smi
 		//sync with available adapters
 		if err = validateAdapter(mctlCfg, meshName); err != nil {
 			utils.Log.Error(ErrValidatingAdapters(errors.Wrap(err, "Unable to sync with available adapters. \n")))
+			return err
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/adapter/validate.go]:
```suggestion
			return ErrValidatingAdapters(errors.Wrap(err, "Unable to sync with available adapters")
```

File: mesheryctl/internal/cli/root/adapter/validate.go [hunk 5]
```diff
@@ -79,6 +80,7 @@ mesheryctl adapter validate istio --adapter meshery-istio --spec smi
...
 		}
 		log.Info("verified prerequisites")
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/adapter/validate.go]:
```suggestion
		utils.Log.Info("verified prerequisites")
```

**Comment by lekaf974** [comment]
@kami922 any update on this ?

File: mesheryctl/internal/cli/root/adapter/deploy.go [hunk 6]
```diff
@@ -53,14 +54,11 @@ mesheryctl adapter deploy linkerd --watch
 			utils.Log.Info("Verifying prerequisites...")
 			mctlCfg, err := config.GetMesheryCtl(viper.GetViper())
 			if err != nil {
-				utils.Log.Error(err)
-				return nil
+				return errors.Wrap(err, "failed to get mesheryctl config")
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/adapter/deploy.go]:
```suggestion
				return utils.ErrLoadConfig(err)
```

File: mesheryctl/internal/cli/root/adapter/deploy.go [hunk 7]
```diff
@@ -53,14 +54,11 @@ mesheryctl adapter deploy linkerd --watch
...
 			}
 
 			if err = validateAdapter(mctlCfg, meshName); err != nil {
-				// ErrValidatingAdapter
-				utils.Log.Error(err)
-				return nil
+				return errors.Wrap(err, "failed to validate adapter")
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/adapter/deploy.go]:
```suggestion
				return err
```

File: mesheryctl/internal/cli/root/adapter/validate.go [hunk 8]
```diff
@@ -59,13 +59,12 @@ mesheryctl adapter validate istio --adapter meshery-istio --spec smi
 
 		mctlCfg, err := config.GetMesheryCtl(viper.GetViper())
 		if err != nil {
-			utils.Log.Error(err)
-			return nil
+			return errors.Wrap(err, "failed to get mesheryctl config")
```
Comment (lekaf974) [inline mesheryctl/internal/cli/root/adapter/validate.go]:
```suggestion
			return err
```

**Comment by DharunMR** [comment]
@lekaf974 Since this pr fix the ignoring errors, it would be nice to also remove `utils.Log.Error` from runE ?

**Review by lekaf974 — APPROVED** [review]
