### PR TITLE
[WIP] Cached manifests for skip update flag in Kubernetes

### LINKED ISSUE #2580: [mesheryctl] Kubernetes deployments require Internet access
#### Description
Users not connected to the Internet, who try to start Meshery on Kubernetes are unable to do so. They can an overly verbose error message instead.

#### Expected Behavior
1. `mesheryctl` should use cached k8s manifests when GitHub.com is not reachable (when remote manifests are not reachable).
1. Error message should be concise and handled gracefully with instructions provided to the user.

#### Screenshots/Logs
```
➜  ~ ➜  ~ mesheryctl system start
Error: failed to start Meshery
See https://docs.meshery.io/guides/mesheryctl/\#meshery-lifecycle-management for usage details
: failed to make GET request: failed to make GET request to https://api.github.com/repos/layer5io/meshery/git/trees/3ba314a0870d5291be6216b4d60d2bc9675a39b2: Get https://api.github.com/repos/layer5io/meshery/git/trees/3ba314a0870d5291be6216b4d60d2bc9675a39b2: dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:63927->[::1]:53: read: connection refused
Usage:
  mesheryctl system start [flags]

Flags:
  -h, --help          help for start
      --reset         (optional) reset Meshery's configuration file to default settings.
      --silent        (optional) silently create Meshery's configuration file with default settings.
      --skip-update   (optional) skip checking for new Meshery's container images.

Global Flags:
      --config string    config file (default location is: /Users/lee/.meshery/config.yaml)
  -c, --context string   (optional) temporarily change the
```

#### Environment:
- Meshery Version: v0.5.0-rc-6
- No network connection in this environment.

### LINKED ISSUE #2961: [mesheryctl] Kubernetes platform does not consider skipUpdate flag
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Adding the `--skip-update` flag on Docker platform will skip updating Meshery containers and does not do anything for platform Kubernetes.

#### Desired Behavior

Kubernetes platform should also take this flag into account and provide a consistent UX for both the platforms.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by metonymic-smokey**
**Description**

This PR fixes #2961 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by metonymic-smokey** [comment]
This is the current status:
image

Here, it has started Meshery without downloading manifests.

File: mesheryctl/internal/cli/root/system/start.go [hunk 1]
```diff
@@ -322,22 +322,41 @@ func start() error {
...
+				return errors.Wrap(err, "cannot start Meshery")
+			}
+			for _, adapter := range currCtx.GetAdapters() {
+				var temp utils.Manifest
+				temp.Path = adapter + "-deployment.yaml"
+				manifests = append(manifests, temp)
+			}
+		} else {
+			// fetch the manifest files corresponding to the version specified
+			manifests, err = utils.FetchManifests(currCtx)
```
Comment (hexxdump) [inline mesheryctl/internal/cli/root/system/start.go:340]: @metonymic-smokey, this would fetch all manifests except operator manifests, right?

File: mesheryctl/pkg/utils/platform.go [hunk 2]
```diff
@@ -225,6 +226,110 @@ func GetChannelAndVersion(currCtx *(config.Context)) (string, string, error) {
 	return channel, version, nil
 }
 
+func GetDeploymentVersion(filePath, fileName string) (string, error) {
```
Comment (hexxdump) [inline mesheryctl/pkg/utils/platform.go:229]: I do not see a reason for passing fileName argument, except for logging, can this be hardcoded in that case?

File: mesheryctl/internal/cli/root/system/start.go (hunk 1 above)
Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/system/start.go:340]: @hexxdump yes
The operator manifests are fetched later.

Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/system/start.go:340]: I have changed the new function and removed the call to check for cached operator manifests, since it's being checked later.

File: mesheryctl/pkg/utils/platform.go (hunk 2 above)
Comment (metonymic-smokey) [reply mesheryctl/pkg/utils/platform.go]: agreed @hexxdump 
Removed it now.

**Comment by leecalcote** [comment]
If reviews are being requested, @metonymic-smokey will you remove the draft status from this PR?

File: mesheryctl/internal/cli/root/system/start.go [hunk 3]
```diff
@@ -449,25 +468,31 @@ func start() error {
...
+		if skipUpdateFlag {
+			err = utils.CanUseCachedOperatorManifests(currCtx)
 			if err != nil {
-				return ErrApplyOperatorManifest(err, true, false)
+				return errors.Wrap(err, "no cached operator manifests")
 			}
-		} else {
+			log.Println("using cached operator manifests...")
 			// skip applying update on operators when the flag is used
 			err = utils.ApplyOperatorManifest(kubeClient, false, false)
```
Comment (hexxdump) [inline mesheryctl/internal/cli/root/system/start.go:479]: @metonymic-smokey, do we still need to call ApplyOperatorManifest with update = delete = false?
We can skip this call itself, right? Its as good as not applying any newer manifests? Is there anything I am missing here?

Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/system/start.go:479]: @hexxdump applying manifests provisions the pods from what I understand. So in order to start Meshery, whether with cached manifests or re-downloaded ones, we need to apply these manifests.

Comment (leecalcote) [reply mesheryctl/internal/cli/root/system/start.go:479]: We also need to switch to using helm templates, not manifests.

Comment (metonymic-smokey) [reply mesheryctl/internal/cli/root/system/start.go:479]: @leecalcote yes agreed
for now though, I've stuck to manifests for the time being. Once we switch to helm charts, this could be changed to suit that.

**Review by hexxdump — DISMISSED** [review]
LGTM

File: mesheryctl/internal/cli/root/system/start.go (hunk 3 above)
Comment (leecalcote) [reply mesheryctl/internal/cli/root/system/start.go:479]: Thank you, @metonymic-smokey. Sounds real good.

**Comment by navendu-pottekkat** [comment]
@metonymic-smokey Could you check the failing tests?

**Comment by metonymic-smokey** [comment]
I'm not sure how to fix integration and unit tests failing. Any idea how I could do it?
Thanks!

**Comment by metonymic-smokey** [comment]
@piyushsingariya the unit and integration tests are still failing :(

**Comment by piyushsingariya** [comment]
> @piyushsingariya the unit and integration tests are still failing :(

I am looking into this, will update soon!

**Review by hexxdump — APPROVED** [review]
LGTM

**Review by navendu-pottekkat — APPROVED** [review]
LGTM. Thank you @metonymic-smokey. 

Let's merge this and iterate on the air-gapped deployment support. Let's use [this spec](https://docs.google.com/document/d/1tepj5g4hT934R17YKzpjgqkoIcLxzl7N8nkhxkqD7ig/edit) to track that. Could you also update the changes made in this PR to the spec?

**Comment by leecalcote** [comment]
My preference and last request on this piece of work is to first have the design spec written and reviewed prior to merge. Please present the design spec for review as soon as possible.

**Comment by metonymic-smokey** [comment]
@leecalcote https://docs.google.com/document/d/1_CKBM6DiTQKfymAB5gF69qSochWrz1jYXaDJb51n5E4/edit?usp=sharing - here is the design spec. 
I had drafted this prior to starting work on this PR. Please let me know if you have any suggestions for the same.
Thanks!

**Comment by leecalcote** [comment]
Thank you, @metonymic-smokey. We'll want to ensure that design specs are reviewed and approved prior to implementation, and @navendu-pottekkat, prior merging of code when we can.

**Comment by leecalcote** [comment]
This [air-gapped document](https://docs.google.com/document/d/1tepj5g4hT934R17YKzpjgqkoIcLxzl7N8nkhxkqD7ig/edit) is a false start and needs to be archived and recreated under the direction that the first goal here is to produce instructions for any considerations users need to take into account when deploying Meshery in disconnected environment. To begin with, these instructions will simply be a list of manual steps (no code change).

Source the initial considerations from this reference Issue - [Docs] Instructions for air-gapped k8s installation (could also include other install methods) #2202 - https://github.com/layer5io/meshery/issues/2202

**Comment by navendu-pottekkat** [comment]
Hmm, this was merged because it preps mesheryctl to consider air-gapped deployments. So we can write instructions to the user to copy the manifests to the .meshery folder etc. This PR makes mesheryctl use the manifests present locally.

So, even if we want to manually write the steps, it would not be possible without this PR.

**Comment by leecalcote** [comment]
Users can deploy w/o using `mesheryctl`. 

My request was specifically that this PR not be merged without a design spec in place (its review and approval being implicit to that request).
