### PR TITLE
[UI] fix: routing  between connections and meshsync

### LINKED ISSUE #13812: [UI] Ensure route between Connections and MeshSync menus
### Current Behavior
Users cannot share a hyperlink directly to either of the two tables on the Connections page - https://playground.meshery.io/management/connections

### Desired Behavior
1. Ensure that users can link to either table.
2. Ensure that users can deeplink to a a specific connection within each table.

Image

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by dev-tnsq**
This PR fixes #13812 

### ✨ Demonstration
<details>
<summary><b>Click to expand demo</b></summary>

https://github.com/user-attachments/assets/6414263c-fbc7-40c7-9401-d15b4964587a

**Before**: 
- 🔴 Deep links to specific connections would cause maximum update depth errors
- 🔴 Row expansion would trigger multiple unnecessary re-renders
- 🔴 URL parameters weren't properly synchronized with the UI state

**After**:
- ✅ Deep links work correctly, expanding the specified connection
- ✅ Row expansion updates URL with minimal re-renders
- ✅ Users can share direct links to specific connections in either table
- ✅ URL format is consistent: `?tab=connections&id=<id>` or `?tab=meshsync&id=<id>`

</details>

### 🧪 Testing
- Verified deep linking works by opening direct links with connection IDs
- Confirmed row expansion properly updates URL parameters
- Tested sharing links between browser tabs
- Ensured no "Maximum update depth exceeded" errors appear during navigation

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/connections/index.js [hunk 1]
```diff
@@ -75,23 +75,140 @@ function Connections(props) {
...
+  const tabParam = query.tab?.toLowerCase();
+  const connectionId = query.connectionId;
+
+  const [tab, setTab] = useState(() => {
+    if (tabParam === 'meshsync') return 1;
+    return 0; // Default to connections tab
+  });
+
+  // Mark component as mounted after first render
+  useEffect(() => {
```
Comment (aabidsofi19) [inline ui/components/connections/index.js:98]: This seems to be a code smell . We should not rely  mount status

File: ui/components/connections/index.js [hunk 2]
```diff
@@ -75,23 +75,140 @@ function Connections(props) {
...
+    isMounted.current = true;
+    return () => {
+      isMounted.current = false;
+    };
+  }, []);
+
+  // Listen to URL changes from outside and prevent re-rendering loops
+  useEffect(() => {
```
Comment (aabidsofi19) [inline ui/components/connections/index.js:106]: Why are we using so many use effects

File: ui/components/connections/index.js [hunk 3]
```diff
@@ -75,23 +75,140 @@ function Connections(props) {
...
+    if (isUpdatingUrl.current) return;
+
+    isExternalUrlChange.current = true;
+
+    const timeout = setTimeout(() => {
```
Comment (aabidsofi19) [inline ui/components/connections/index.js:111]: We certainly don't want timeouts

**Comment by vishalvivekm** [comment]
@Tanishq1604 
Thank you for your contributions! Let's discuss this today, during Meshery Development call at 9:00 AM CT | 7:30 PM IST. Add it as an agenda item to the :memo: [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1&tab=t.0#), if you would.
https://meet.meshery.io/dev

**Comment by Tanishq1604** [comment]
@aabidsofi19 i have removed the timeouts and tried to minimize the usage of useeffects.

File: ui/components/connections/ConnectionTable.js [hunk 4]
```diff
@@ -154,18 +160,29 @@ const ConnectionTable = ({ meshsyncControllerState, connectionMetadataState, sel
...
+    },
+    {
+      onError: (error) => {
+        notify({
+          message: `${ACTION_TYPES.FETCH_CONNECTIONS.error_msg}: ${error?.error}`,
+          event_type: EVENT_TYPES.ERROR,
+        });
+      },
+    },
+  );
```
Comment (amitamrutiya) [inline ui/components/connections/ConnectionTable.js:184]: I don't this there if function like this in rtk query

File: ui/components/connections/ConnectionTable.js [hunk 5]
```diff
@@ -175,26 +192,16 @@ const ConnectionTable = ({ meshsyncControllerState, connectionMetadataState, sel
     { orgId: organization?.id },
     {
       skip: !organization?.id,
+      onError: (error) => {
+        notify({
+          message: `${ACTION_TYPES.FETCH_ENVIRONMENT.error_msg}: ${error?.error}`,
+          event_type: EVENT_TYPES.ERROR,
+        });
+      },
```
Comment (amitamrutiya) [inline ui/components/connections/ConnectionTable.js:200]: Same here rtk don't have this function currently.

File: ui/components/connections/ConnectionTable.js [hunk 6]
```diff
@@ -175,26 +192,16 @@ const ConnectionTable = ({ meshsyncControllerState, connectionMetadataState, sel
...
-      });
-    }
-
-    if (isConnectionError) {
-      notify({
-        message: `${ACTION_TYPES.FETCH_CONNECTIONS.error_msg}: ${connectionError.error}`,
-        event_type: EVENT_TYPES.ERROR,
-      });
-    }
-  }, [environmentsError, connectionError, isEnvironmentsSuccess]);
```
Comment (amitamrutiya) [inline ui/components/connections/ConnectionTable.js:197]: add it without using useEffect

File: ui/components/connections/meshSync/index.js [hunk 7]
```diff
@@ -511,21 +534,41 @@ export default function MeshSyncTable(props) {
...
+        details: meshSyncError.toString(),
+      });
     }
   }, [meshSyncError]);
 
+  useEffect(() => {
+    if (columns && updateCols) {
+      updateCols(columns);
+    }
+  }, []);
```
Comment (amitamrutiya) [inline ui/components/connections/meshSync/index.js:554]: no need of use this useEffect

**Review by amitamrutiya — CHANGES_REQUESTED** [review]

File: ui/components/connections/ConnectionTable.js (hunk 6 above)
Comment (Tanishq1604) [reply ui/components/connections/ConnectionTable.js:197]: I tried it without using use effect but there was minor bugs without it 
But I will try.

File: ui/components/connections/ConnectionTable.js (hunk 5 above)
Comment (amitamrutiya) [reply ui/components/connections/ConnectionTable.js:200]: look at other places how we are handling errors.

File: ui/components/connections/meshSync/index.js (hunk 7 above)
Comment (Tanishq1604) [reply ui/components/connections/meshSync/index.js]: i have removed it

**Review by amitamrutiya — APPROVED** [review]

**Comment by Tanishq1604** [comment]
@amitamrutiya 🚀

**Comment by amitamrutiya** [comment]
@Tanishq1604 there are some regress issue that comes with your PR that I just noticed like -
 1) table row size shrinks down
 2) there is flaky behavior on expand and collapse row.
 
image

please fix this as soon as possible otherwise I have to revert this PR.
