### PR TITLE
Fix and add meaningful notification on toggle of extensions

### LINKED ISSUE #10514: [UI] Better snackbar title on toggle of extensions
### Current Behavior
On toggle for extensions, it says Adapter processing but doesn't show success or failure for enabled extension

### Desired Behavior
Suggest better snackbar title

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Notes for Reviewers**

This PR fixes #10514 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: ui/components/extensions/adapters/adapters.js [hunk 1]
```diff
@@ -91,14 +92,14 @@ const Adapters = ({ updateProgress, classes }) => {
       msg = '';
     if (!selectedAdapter.enabled) {
       payload = {
-        status: 'ENABLED',
+        status: ADAPTER_STATUS.ENABLED,
         adapter: selectedAdapter.label,
         targetPort: selectedAdapter.defaultPort,
       };
       msg = 'Unable to Deploy adapter';
```
Comment (leecalcote) [inline ui/components/extensions/adapters/adapters.js:99]:
```suggestion
      msg = 'Unable to deploy adapter';
```

Comment (leecalcote) [reply ui/components/extensions/adapters/adapters.js:99]: @sudhanshutech Line 106 needs updated, too.

**Comment by Ashparshp** [comment]
@sudhanshutech adding this issue for the Meshery dev meeting call?
