### PR TITLE
[UI] Fix: Remove unwanted dot from select menu carets in Settings.

### LINKED ISSUE #13147: [UI] Unwanted Dot Appears Next to Dropdown Caret in Settings Page Select Menus
### Current Behavior
There is an unwanted dot/point appearing to the left of the dropdown caret (▼) in all select menus throughout the Settings page. This visual glitch occurs in both light and dark themes.

### Desired Behavior
The select menus should only show the clean dropdown caret (▼) without any additional dots or visual artifacts next to it.

### Areas affected:
All select menus in the Settings page, including:
- Mesh Adapter URL dropdown
- Available Adapters dropdown
- Grafana Base URL dropdown
- Other select menus in Settings sections

### Screenshots/Logs
I've marked some of the problematic areas with red circles in the screenshots to highlight the unwanted dot:

Screenshot 2025-01-04 at 12 49 35 AM
Screenshot 2025-01-04 at 12 57 55 AM
Screenshot 2025-01-04 at 12 58 06 AM
Screenshot 2025-01-04 at 12 58 23 AM
Screenshot 2025-01-04 at 12 58 31 AM

The visual bug is consistent across all dropdown menus regardless of the theme being used.

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by augustmood**
**Notes for Reviewers**

- This PR fixes #13147

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

#### Before:
Select menus showing unwanted dot next to caret in both light and dark themes
Screenshot 2025-01-04 at 12 58 23 AM
Screenshot 2025-01-04 at 12 57 55 AM

#### After:
Clean select menus with dot removed in both themes
Screenshot 2025-01-04 at 1 51 50 AM
Screenshot 2025-01-04 at 1 52 27 AM

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Thank you, @augustmood. 

Even in the event that this field contains multiple entries, those entries will be show as chips, I believe, in which case the commas aren't necessary in either the empty state or the state with multiple entries. 👍

File: ui/components/ReactSelectWrapper.js [hunk 1]
```diff
@@ -166,6 +166,13 @@ class ReactSelectWrapper extends React.Component {
         color: theme.palette.text.primary,
         '& input': { font: 'inherit' },
       }),
+      dropdownIndicator: (base) => ({
```
Comment (sudhanshutech) [inline ui/components/ReactSelectWrapper.js:169]: why a extra line of styling required to remove these dots. By default they might not be occurring , due to some other styles overriding might be happening. Please ensure we should pass any extra styling to remove them

**Review by sudhanshutech — CHANGES_REQUESTED** [review]

File: ui/components/ReactSelectWrapper.js (hunk 1 above)
Comment (augustmood) [reply ui/components/ReactSelectWrapper.js:169]: Ah yea - you're right. The dropdownIndicator isn't necessary here, indicatorSeparator alone is enough to handle it!

**Review by sudhanshutech — APPROVED** [review]

**Comment by vishalvivekm** [comment]
@augustmood 
Thank you for your contributions! Let's discuss this today, during Meshery Development call at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1&tab=t.0#) || [meeting link.](https://meet.layer5.io/meshery)
