### PR TITLE
Fixed routing to Lifecycle menu

### LINKED ISSUE #5232: [UI] Add Cilium Service Mesh
#### Current Behavior
The [Meshery Adapter for Cilium Service Mesh](https://github.com/meshery/meshery-cilium) is supported as a generic adapter currently without support for logo and default port reservation.

#### Desired Behavior
- [x] 1. The Adapter should be visible in the navigation menu, dashboard, settings.
- [x] 2. The Adapter's components should show inside of the Designer.
- [ ] 3. The Adapter's operations should show inside of Lifecycle menu.

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by MUzairS15**
Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>

**Description**

This PR fixes #5232 

**Notes for Reviewers**

1. Routing to the lifecycle page was broken for all adapters.
2. For cilium adapter due to mismatched name, lifecycle page was not loading. 
**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 

https://user-images.githubusercontent.com/79860504/160232118-25f08d82-9f62-4393-98d9-ac145f187547.mov

### CODE REVIEW

File: ui/components/Navigator.js [hunk 1]
```diff
@@ -747,10 +747,6 @@ class Navigator extends React.Component {
     category = category.toLowerCase();
     meshAdapters.forEach((adapter) => {
       let aName = adapter.name.toLowerCase();
-      // Manually changing adapter name so that it matches the internal name
-      if (aName === "osm") aName = "open service mesh";
-      if (aName === "cilium") aName = "cilium service mesh";
-      if (aName === "nginx") aName = "nginx service mesh";
```
Comment (MUzairS15) [inline ui/components/Navigator.js:753]: For open and nginx service mesh, adapter name as received in response is `open_service_mesh` and `nginx_service_mesh` so this check is redundant.
For the cilium adapter, `id` above was set as `cilium` which after this check is changed to `cilium service mesh` causing the undesired behaviour. Server response id `cilium_service_mesh`

**Comment by leecalcote** [comment]
Yay!🎈

File: ui/components/MesheryPlayComponent.js [hunk 2]
```diff
@@ -71,13 +71,20 @@ class MesheryPlayComponent extends React.Component {
...
+        return aName ===  meshadapters.name.toLowerCase()
+      });
+    }
     const st = {};
     if (meshAdaptersts > state.mts) {
       st.meshAdapters = meshAdapters;
       st.mts = meshAdaptersts;
       if (meshAdapters && meshAdapters.length > 0) {
-        st.adapter = meshAdapters[0];
+        st.adapter = adapter[0];
```
Comment (MUzairS15) [inline ui/components/MesheryPlayComponent.js:87]: Because of explicitly setting the first adapter in the available adapter list, clicking on navigation doesn't change the lifecycle page.

**Review by leecalcote — DISMISSED** [review]

**Comment by MUzairS15** [comment]
@leecalcote I didn't see your review, so I requested for review.

**Review by warunicorn19 — COMMENTED** [review]
While testing this PR locally, I saw that the in-page service mesh selector isn't working. Could you please take a look at that? It might just be my local system.

**Comment by MUzairS15** [comment]
@warunicorn19 Can you pls check now?

File: ui/components/MesheryPlayComponent.js (hunk 2 above)
Comment (leecalcote) [reply ui/components/MesheryPlayComponent.js:89]: Good work. This has been a pain for some time.

**Review by leecalcote — APPROVED** [review]
Works quite well, @MUzairS15 👍
