### PR TITLE
Fix : Replace FontAwesome icons with Sistent icons

### LINKED ISSUE #13647: [UI] Remove FontAwesome Dependency and Replace it with the sistent icons
### Description
We are currently using the FontAwesome library in several places within the project. To maintain consistency and reduce external dependencies, we need to:

1. Remove the FontAwesome library from the project.
2. Replace all FontAwesome icons with equivalent icons from the Sistent icon set. 
3. If an icon does not exist in the Sistent repository, add the missing icons to Sistent and then use them in the Meshery repository.

Listed FontAwsome libraries that needs to remove
```
    "@fortawesome/fontawesome-svg-core": "^6.4.2",
    "@fortawesome/free-brands-svg-icons": "^6.4.0",
    "@fortawesome/free-solid-svg-icons": "^6.4.0",
    "@fortawesome/react-fontawesome": "^0.2.0",
```

### PR DESCRIPTION
**Pull request by GARY121github**
**Notes for Reviewers**

- This PR fixes #13647

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Karan-Palan — COMMENTED** [review]
Checked with sistent, the icons do match, will test it out locally and give a review

File: ui/components/UserPreferences/index.js [hunk 1]
```diff
@@ -514,7 +513,7 @@ const UserPreference = (props) => {
             </CustomTooltip>
             <CustomTooltip title="Choose Performance Test Defaults" placement="top">
               <Tab
-                icon={<FontAwesomeIcon icon={faTachometerAlt} style={iconMedium} />}
+                icon={<TachometerIcon {...iconMedium} fill="#fff" />}
                 label={<TabLabel>Performance</TabLabel>}
               />
```
Comment (amitamrutiya) [inline ui/components/UserPreferences/index.js:518]: use sistent theme token instend of #fff

File: ui/components/Navigator.js [hunk 2]
```diff
@@ -69,8 +66,8 @@ import CAN from '@/utils/can';
 import { keys } from '@/utils/permission_constants';
 import { CustomTextTooltip } from './MesheryMeshInterface/PatternService/CustomTextTooltip';
 import {
-  ChevronIcon,
-  ExpandMoreIcon,
+  // ChevronIcon,
+  // ExpandMoreIcon,
   HideScrollbar,
```
Comment (amitamrutiya) [inline ui/components/Navigator.js:71]: remove this comments

File: ui/components/Navigator.js [hunk 3]
```diff
@@ -947,13 +942,18 @@ const Navigator_ = (props) => {
...
-                    icon={faCaretDown}
-                    onClick={() => toggleItemCollapse(childId)}
-                    isCollapsed={state.openItems.includes(childId)} // Pass collapsed state
-                    isDrawerCollapsed={props.isDrawerCollapsed} // Pass drawer state
-                    hasChildren={!!children}
-                  />
+                  {children && children.length ? (
+                    <CaretDownIcon
+                      fill={state.openItems.includes(childId) ? '#00B39F' : '#fff'}
+                      style={{
```
Comment (amitamrutiya) [inline ui/components/Navigator.js:948]: don't add color like this use sistent themeing make

File: ui/components/Navigator.js [hunk 4]
```diff
@@ -1086,20 +1086,17 @@ const Navigator_ = (props) => {
...
+          alt="Sidebar collapse toggle"
+          style={{
+            cursor: 'pointer',
+            verticalAlign: 'middle',
+          }}
+          fill="#fff"
+          stroke="#fff"
+          width="1.2rem"
+          height="2.8rem"
+        />
```
Comment (amitamrutiya) [inline ui/components/Navigator.js:1099]: make sure this arrow changes based on the drawer open close; use sistent theming.

**Review by amitamrutiya — CHANGES_REQUESTED** [review]
Use sistent theming that we are using in other places using useTheme hook instead of hard code color string

**Comment by amitamrutiya** [comment]
Also don't include any changes that are present in server/meshmodel library. exclude those changes.

File: ui/components/Navigator.js (hunk 4 above)
Comment (GARY121github) [reply ui/components/Navigator.js:1099]: Done

File: server/meshmodel/aws-cloudfront-controller/v1.0.8/v1.0.0/model.json [hunk 5]
```diff
@@ -22,16 +22,16 @@
...
...01 26.357,11.895 C17.723,14.464 11.568,22.23 11.045,31.196 C11.01,31.625 11,32.062 11,32.5 C11,40.444 15.352,47.707 22.354,51.455 C25.459,53.12 28.968,54 32.5,54 C34.892,54 37.229,53.61 39.437,52.843 C41.684,52.086 43.773,50.963 45.646,49.507 C50.955,45.399 54,39.2 54,32.5 C54,24.732 49.787,17.546 43.008,13.749 L43.008,13.749 Z M38.384,37.411 L37.003,38.858 C34.022,36.015 31.047,34.146 27.637,32.975 L28.287,31.083 C31.979,32.351 35.188,34.362 38.384,37.411 L38.384,37.411 Z M38.444,22.364 C41.282,26.692 42.88,31.444 43.193,36.488 L41.197,36.612 C40.905,31.919 39.417,27.495 36.772,23.46 L38.444,22.364 Z M26.451,26.797 L24.773,25.708 C26.316,23.332 27.639,21.758 29.336,20.278 L30.65,21.786 C29.103,23.135 27.886,24.587 26.451,26.797 L26.451,26.797 Z M34.5,16.5 C35.603,16.5 36.5,17.397 36.5,18.5 C36.5,19.603 35.603,20.5 34.5,20.5 C33.397,20.5 32.5,19.603 32.5,18.5 C32.5,17.397 33.397,16.5 34.5,16.5 L34.5,16.5 Z M34.5,22.5 C36.706,22.5 38.5,20.706 38.5,18.5 C38.5,16.294 36.706,14.5 34.5,14.5 C32.294,14.5 30.5,16.294 30.5,18.5 C30.5,20.706 32.294,22.5 34.5,22.5 L34.5,22.5 Z\" id=\"Amazon-CloudFront_Icon_48_Squid\" fill=\"#FFFFFF\"\u003e\u003c/path\u003e\n\u003c/g\u003e\n\u003c/svg\u003e",
```
Comment (amitamrutiya) [inline server/meshmodel/aws-cloudfront-controller/v1.0.8/v1.0.0/model.json:32]: Why this file

**Review by amitamrutiya — CHANGES_REQUESTED** [review]

File: server/meshmodel/aws-cloudfront-controller/v1.0.8/v1.0.0/model.json (hunk 5 above)
Comment (GARY121github) [reply server/meshmodel/aws-cloudfront-controller/v1.0.8/v1.0.0/model.json:32]: I had not made those changes.

Comment (amitamrutiya) [reply server/meshmodel/aws-cloudfront-controller/v1.0.8/v1.0.0/model.json]: then also revert that changes.

**Comment by GARY121github** [comment]
@amitamrutiya I have undone those changes kindly merge this branch

**Comment by amitamrutiya** [comment]
still i am able to see this file in file changes -> server/meshmodel/aws-cloudfront-controller/v1.0.8/v1.0.0/model.json

File: ui/components/MesherySettings.js [hunk 6]
```diff
@@ -265,7 +276,7 @@ const MesherySettings = (props) => {
                   value={ADAPTERS}
                 >
                   <Tab
-                    icon={<FontAwesomeIcon icon={faMendeley} style={iconMedium} />}
+                    icon={<MendeleyIcon {...iconMedium} fill="#fff" />}
```
Comment (amitamrutiya) [inline ui/components/MesherySettings.js:279]: dont use #fff use sistent theme token like theme.pallete.common.white

**Review by amitamrutiya — CHANGES_REQUESTED** [review]

File: ui/components/MesherySettings.js (hunk 6 above)
Comment (amitamrutiya) [reply ui/components/MesherySettings.js:279]: change this in all of the places

Comment (GARY121github) [reply ui/components/MesherySettings.js]: Done

**Comment by GARY121github** [comment]
https://github.com/user-attachments/assets/91e4bd58-2b1c-42dd-86a4-a55ab3fae8fa

@amitamrutiya, I’ve made some changes to improve user interactivity and enhance ease of use in the UI

**Comment by amitamrutiya** [comment]
Resolve merge conflict

**Comment by GARY121github** [comment]
Done @amitamrutiya

**Review by amitamrutiya — CHANGES_REQUESTED** [review]

**Comment by vishalvivekm** [comment]
@GARY121github 
Thank you for your contributions! Let's discuss this today, during Meshery Development call at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1&tab=t.0#) || [meeting link.](https://meet.layer5.io/meshery)

File: ui/components/Navigator.js [hunk 7]
```diff
@@ -243,9 +239,7 @@ const getNavigatorComponents = (/** @type {CapabilitiesRegistry} */ capabilityRe
     children: [
       {
         id: PROFILES,
-        icon: (
-          <FontAwesomeIcon icon={faDigitalTachograph} style={{ fontSize: 24, color: 'white' }} />
-        ),
+        icon: <TachographDigitalIcon fill="#fff" />,
         href: '/performance/profiles',
```
[the remark this answers is not in the document]
Comment (GARY121github) [reply ui/components/Navigator.js]: Done

File: ui/components/General/style.js [hunk 8]
```diff
@@ -109,6 +108,44 @@ export const MainLogoText = styled('img')(({ theme }) => ({
...
+    isCollapsed={isCollapsed}
+    hasChildren={hasChildren}
+    {...props}
+  >
+    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512">
+      <path d="M137.4 374.6c12.5 12.5 32.8 12.5 45.3 0l128-128c9.2-9.2 11.9-22.9 6.9-34.9s-16.6-19.8-29.6-19.8L32 192c-12.9 0-24.6 7.8-29.6 19.8s-2.2 25.7 6.9 34.9l128 128z" />
+    </svg>
+  </ExpandMoreIcon>
+);
+
```
Comment (amitamrutiya) [inline ui/components/General/style.js:148]: This logic is good but not recommended. Do one thing: import the icon from sistent and apply all conditional animation and hover effect for that icon directly. You can do it that way so you don't have to define the icon like this.

**Review by amitamrutiya — CHANGES_REQUESTED** [review]

File: ui/components/General/style.js (hunk 8 above)
Comment (GARY121github) [reply ui/components/General/style.js:148]: I tried it but is was not working

Comment (GARY121github) [reply ui/components/General/style.js]: Can you kindly review it now ?

**Review by amitamrutiya — APPROVED** [review]
